### ISSUE TITLE
Box2d in polygon cliping

### ISSUE THREAD

**Issue by benzkuai** [libgdx/libgdx#1715]
I want a new polygon named C, and C = A - B.
If I have polygon A and B, and now I want a new polygon C = A - B. But I don't find any method in libgdx. Is there a class or method in it or what can I do ?

**Comment by wuao** [comment]
https://github.com/miho/JCSG

**Comment by tommyettinger** [comment]
@wuao I know you're not a bot because you're on the Discord, but please don't post comments on 7-year-old issues. It pings the people who were involved a very long time ago, and is annoying. Also, the link you gave doesn't answer the question; polygons are 2D, and JCSG provides something roughly similar for 3D.
