### ISSUE TITLE
No way to know if a Sound has finished loading.

### ISSUE THREAD

**Issue by Steveice10** [libgdx/libgdx#1775]
On Android, if a Sound is not fully loaded and you try to play it, it will tell you "Sample not ready" in the log and not do anything. This causes problems as in some cases, like the one I have, I need to be able to load sounds, wait for them to finish loading, and play them, and I can't load them ahead of time. It would be helpful if a method like "isReady" was added to Sound.

**Comment by Shuriken255** [comment]
I personally think newSound method should block returning Sound object, because sometimes user will have to use it at once after load. Loading something in gaming process is really bad practice. Before calling game logic you should load every resources you will need in your game logic. Creating a loader and then calling game process is much better than load everything during game process, but it is possible only with blocking returning object until it really loads it...

**Comment by badlogic** [comment]
I'm happy to accept PRs for this. My favorite is the blocking version, as it doesn't introduce new methods and is the least surprising. However, it'd need to be tested and seen how long loading the audio actually takes.

**Comment by centy** [comment]
Are you going to merge this fix to libgdx? It would be really useful.

**Comment by SomeTroglodyte** [comment]
Five years later and still bugged. One either loads sounds ahead of time and more or less violates newSound's documentation "has to be disposed if unused" - and incurs _loads_ of CloseGuard warnings (`W/System: A resource failed to call end.`). Or the android version plays any sound only if it's a a second attempt shortly after another, while desktop is fine. Or one stalls the sound thread while waiting for it to succeed, which shouldn't be responsibility of a client but of the library - and still incurs a logcat full of `W/SoundPool:   sample X not READY`...

I know that sounds annoyed - sorry - it's just I can't believe there's no clean solution to this (and I blame it on convoluted Android design).

**Comment by obigu** [comment]
Yep, `SoundPool` is a mess and our implementation is a bit limited to keep cross-backend consistent behavior and API. 

For most cases I think the best approach is to to load sounds beforehand, which is more or less what `SoundPool` docs indicate:

>This should typically be done early in the process to allow time for decompressing the audio to raw PCM format before they are needed for playback.

The "has to be disposed if unused" on `Audio` may be interpreted that it must be disposed, at least, when closing the app as, in most cases, it's not an issue to keep them loaded while it's running.

I'm not a fan of blocking until all sounds are loaded because it would very probably impact the app loading times (needs testing to confirm though). There's usually enough time between when Sounds are loaded and when they have to be played and the situation in which this is critical are exceptional cases. Maybe a possible approach in this direction would be to allow passing a flag parameter to the asset loader that would then pass it to `newSound()` if you require blocking for a specific Sound (being `false` the default). Afaik the flag would only matter on Android backend though.

Alternatively, as discussed early, an easier to implement approach would be to add an `isLoaded()` method to `Sound`. Even if it would also only be meaningful on Android it wouldn't be the an exception of a method in the API having been added just for one backend.

**Comment by SomeTroglodyte** [comment]
Thanks for the info. Summary: Gdx hasn't adopted a workaround due to architectural constraints. Workarounds from a Gdx client without circumventing Gdx Sound cannot avoid catlog warnings.

And while I understand and wouldn't push the Gdx team (imagine outraged demanding tone here) to 'fix this ASAP'! - I'd suggest 'fixing' the documentation, not forgetting the Jdoc Android Studio offers as tooltips. Short hints that `Gdx.audio.newSound(file).play()` will never succeed because the system needs a little time (subtly hinting it's not libGdx's fault) might go a loooong way. :+1:
