### ISSUE TITLE
Color markup language does not work for Scene2D Labels

### ISSUE THREAD

**Issue by JesseTG** [libgdx/libgdx#1934]
Apparently it's because `Label` wipes out the color specified in the markup language with its own `Color` property.  The text _does_ get parsed (i.e. `[RED]velvet` turns into `velvet`), but not recolored.

**Comment by kalexmills** [comment]
I can't seem to tell how this change is meant to be used in a label to draw multiple colors. From what I understand of the commit, the only merged change from that class was to use .font instead of .color

It seems that the intent was to give Label a way to append text, rather than resetting the entire text. Should we add an appendText method, to allow users to add some text to a Label, change the color, then add more text (which will use the new Color))?

**Comment by NathanSweet** [comment]
@kalexmills Probably makes sense to comment on PR #2387 instead of commenting here and linking the PR. :)

If BitmapFontData `markupEnabled` is true, GlyphLayout parses colors. Label just uses a font, so just give it a font with color markup enabled.
