### ISSUE TITLE
AssetManager: better progress indication for TextureAtlasLoader and probably others as well

### ISSUE THREAD

**Issue by klaus7** [libgdx/libgdx#2714]
Wouldn't it be better to add to the count of `com.badlogic.gdx.assets.AssetManager#toLoad` all dependencies from the assets and change this line at https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/assets/AssetManager.java#L470 from `if (tasks.size() == 1) loaded++;` to simply `loaded++;`?

I'm only loading one big TextureAtlas, hence the progress indication is of little use right now for me.

I changed the classes as described and it works as expected. 

What do you think?

**Comment by klaus7** [comment]
Sorry, I guess I didn't describe my concern well enough.

When using the `AssetManager` and loading a big `TextureAtlas` (mine has 22 pages) the whole atlas counts as one asset. The individual pages are seen as dependencies and do not increase the `toLoad` count. My proposal is to change this behaviour, so dependencies (in case of the `TextureAtlas` this would be its pages) also increase the `toLoad` count, while at the same time the `loaded` must also be increased for every asset it loads. 

This would lead to a more granular progress.

As it seems other developers also stumbled upon this issue. (http://badlogicgames.com/forum/viewtopic.php?f=11&t=11298 and http://badlogicgames.com/forum/viewtopic.php?t=11122)

**Comment by NathanSweet** [comment]
`​​
​loaded
​`​
/
​`​
toLoad
​`​
are used to determine progress percentage. Doing as you suggest would mean
the percentage would go backward. Eg 10%, 20%, then dependencies are added,
15%, etc.
​The dependencies are added by `AssetLoadingTask` only when the asset needs
to load, because even knowing what the dependencies are can require some
loading. Eg, for `TextureAtlas`, to parse the atlas file. I'm all for
improving it, but I'm not sure how.

M
​y​
​​
​ suggestion t​
​o queue y​
​our dependencies is what the guy in the second thread you linked is doing.
Call load on your 22 images so they are reflected by `loaded`/`toLoad`
rather than relying on the dependency mechanism where they won't.

**Comment by badlogic** [comment]
An atlas with 22 pages is kinda exactly oposite of what you want to achieve
with the atlas. Unless you sorted all images so that when drawing a scene
you only reference one of those pages.

**Comment by klaus7** [comment]
@NathanSweet Ok I see, that's the pitfall. Maybe I can think of another solution, otherwise I will do it like the guy in that thread.

@badlogic The graphic assets are not optimized currently. I expect the number to drop when the images are resized to the actual required in-game size, but still there will be more than 4 atlas images for sure. (depending on the atlas size)

If I don't switch back and forth between the atlas textures in one batch of drawing TextureRegions all should be okay I think. I do use more than one atlas file in one batch, but only switch to an particular atlas texture once during one batch. The expensive task is to constantly switch between those atlas textures I thought. Please correct me if I'm wrong. Haven't had the time to try it on mobile yet, but the desktop build runs very smoothly even with a whole lot of sprites drawn.

**Comment by badlogic** [comment]
Example: Atlas 1 has 22 pages. Image A is on page 1, image B on page 2,
image C on page 3. You render a frame using A, B, C. You now have 3 texture
switches. That's bad. And it will be worse with 22 pages. Split up your
atlas into multiple smaller ones, where an atlas contains images that
belong together (e.g. one for UI elements, one for foreground objects, one
for background objects, etc.). Not only will this improve your performance,
it will also fix your issue with AssetManager :) I strongly recommend
testing on mobile early and often. Otherwise you may have to reorganize
deep in your dev cycle.

I stop derailing this issue now.

**Comment by klaus7** [comment]
I see, thanks for your input!

**Comment by badlogic** [comment]
Closing this out.
