### ISSUE TITLE
Lighting doesn't work on gwt

### ISSUE THREAD

**Issue by xoppa** [libgdx/libgdx#2758]
See http://i.imgur.com/4Vorrp7.png & http://i.imgur.com/2992Rg9.png.
![lights](https://cloud.githubusercontent.com/assets/2349087/5825034/cfa2361a-a0e8-11e4-8ff5-2030b65b0361.png)
![invaders](https://cloud.githubusercontent.com/assets/2349087/5825038/d85be42c-a0e8-11e4-8832-e4f122f68ee7.png)

**Comment by MobiDevelop** [comment]
Weird. Lighting works correctly for me on Firefox (35.0.1), IE (11), and Chrome for Android... Chrome on desktop, not so much. Also weird, for Invaders, the explosions are correct on Chrome but the transparency shows as white on Firefox and IE.

**Comment by vbousquet** [comment]
Just to add a few tests ; 
- Firefox 36.0.4 => lighting is right for me
- Chrome 41.0.2272.101 m => no lighting (only ambient)
All on a windows 8 setup

**Comment by vbousquet** [comment]
After going for some investigation, it is due to the fact that the light direction uniform is not passed correctly to the shader.

Looking at the code, the way the vector are passed to the shader do not seem to conform to [the spec](https://www.opengl.org/wiki/Uniform_%28GLSL%29#Uniform_management), since we assume that the uniform are linearly arranged and the spec states:
> However, for structs, if the locations were not explicitly specified then the location of any particular element will have no relation to any other element. So you cannot count on the next element being one location index higher than the previous. This is true even for arrays of structs.

Therefore I changed it to conform, and it did not work either. I finally found that there is a known bug on current Chrome version on windows, [reported here](https://code.google.com/p/chromium/issues/detail?id=462968)

This bug is windows only, so it would be nice **if someone could check that it is ok on other GWT platform (Mac / Linux someone ?), this would be great**.

For the more (sort of) correct code for setting the uniform, I simply use array of uniforms instead of the current implementation which compute the stride and use it directly. If you think it would be better, I can provide a PR for this to review. The general idea for the code is given below:

```java
	protected final int[] u_dirLightsColor;
	protected final int[] u_dirLightsDirection;
	protected final int[] u_pointLightsColor;
	protected final int[] u_pointLightsPosition;
	protected final int[] u_pointLightsIntensity;
	...
	protected int[] dirLightsColorLoc;
	protected int[] dirLightsDirectionLoc;
	protected int[] pointLightsColorLoc;
	protected int[] pointLightsPositionLoc;
	protected int[] pointLightsIntensityLoc;

	In constructor : 

		u_dirLightsColor = new int[config.numDirectionalLights];
		u_dirLightsDirection = new int[config.numDirectionalLights];
		for (int i = 0; i < config.numDirectionalLights; i++) {
			String light = i == 0 ? "u_dirLights" : ("u_dirLights[" + i + "]"); 
			u_dirLightsColor[i] = register(new Uniform(light + ".color"));
			u_dirLightsDirection[i] = register(new Uniform(light + ".direction"));
		}

		u_pointLightsColor = new int[config.numPointLights];
		u_pointLightsPosition = new int[config.numPointLights];
		u_pointLightsIntensity = new int[config.numPointLights];
		for (int i = 0; i < config.numPointLights; i++) {
			String light = i == 0 ? "u_pointLights" : "u_pointLights[" + i + "]"; 
			u_pointLightsColor[i] = register(new Uniform(light + ".color"));
			u_pointLightsPosition[i] = register(new Uniform(light + ".position"));
			u_pointLightsIntensity[i] = register(new Uniform(light + ".intensity"));
		}

	In init : 

		dirLightsColorLoc = new int[config.numDirectionalLights];
		dirLightsDirectionLoc = new int[config.numDirectionalLights];
		for (int i = 0; i < config.numDirectionalLights; i++) {
			dirLightsColorLoc[i] = loc(u_dirLightsColor[i]);
			dirLightsDirectionLoc[i] = loc(u_dirLightsDirection[i]);
		}

		pointLightsColorLoc = new int[config.numPointLights];
		pointLightsPositionLoc = new int[config.numPointLights];
		pointLightsIntensityLoc = new int[config.numPointLights];
		for (int i = 0; i < config.numPointLights; i++) {
			pointLightsColorLoc[i] = loc(u_pointLightsColor[i]);
			pointLightsPositionLoc[i] = loc(u_pointLightsPosition[i]);
			pointLightsIntensityLoc[i] = loc(u_pointLightsIntensity[i]);
		}

```

**Comment by xoppa** [comment]
Thanks! I can confirm that using vec4 instead of vec3 seems to solve it.

**Comment by xoppa** [comment]
Looks like it is solved now.
