### ISSUE TITLE
TextureWrap.Repeat works only for power of two textures

### ISSUE THREAD

**Issue by R0tek** [libgdx/libgdx#2850]
On desktop it works on NPOT textures, but on android it doesn't.
I don't know how it works on other platforms.
I think that it should be put somewhere in documentation, because it's confusing (it is kind of hard to work that out).

**Comment by xoppa** [comment]
So the issue you're reporting is that the documentation doesn't say that [repeating texture wrap isn't supported for non power of two sized textures](https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameter.xml)? If so, then please consider modifying the documentation so that it does say what you think it should say. If you want to change the javadocs then you can send a pull request for that. If you want to change the wiki then you should be able to do so directly.
