### ISSUE TITLE
allow freeing Cell's without recreating the whole Table

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#2851]
Currently, the following code for updating the layout of an actor in a table:
```java
//while(true) {
 actor.remove();
 table.add( actor );
//} // uncomment to get a "WTF"
```
causes a memory leak (and/or a CPU leak on `layout()` calls if the outer loop is timed by `create()`) due to fact that adding an Actor to the Table obtain()s a new Cell, but removing that Actor keeps the Cell in layout. While this is probably intentional, there still ain't any way short of subclassing for removing the no-longer-needed Cells from the Table.

I am aware the Cell's can be reused - yet in some cases (changing the amount of actually used Cell etc) this is quite tedious to keep track of the objects & manage the pool by yourself, when it should have probably be the responsibility of the Table object.

As to the idea that the Table and it's layout is inherently static/immutable after creation: it ain't. Calling `layout()` easily allows to update the layout of the mutated Table - OTOH, it currently can't be used due to aforementioned memory leak.

A possible solution would be, e.g., to add a following (or similar) method to the Table.java,
```java
    public boolean removeActorCell( Actor actor ) {
        if ( !super.removeActor( actor ) ) {
            return false;
        }
        TableExCell cell = getCell( actor );
        if ( cell != null ) {
            cellPool.free( cell );
        }
        return true;
    }
```
and the valid code would be then, simply
```java
//while(true) {
 table.removeActorCell( actor );
 table.add( actor );
//} // no leak here
```

Note that implementing that behaviour that is currently impossible by normal subclassing due to cellPool being package-private etc.

**Comment by NathanSweet** [comment]
By design, removing an actor doesn't remove the cell, it only sets the cell's actor to null. Removing a single cell is not supported (neither is inserting a cell anywhere except the end of the table). 

Table already pools cells.

If you are making a feature request to support removing a single cell, it is more complex than just calling layout. Table does bookkeeping that would need to be adjusted. Same if you wanted to insert a cell anywhere except the end of the table.

You can use `clearChildren` and then add all the actors back. Or, you can use Horizontal/VerticalGroup.
