### ISSUE TITLE
Different versions of Hiero

### ISSUE THREAD

**Issue by nooone** [libgdx/libgdx#2864]
Currently there are two different versions of Hiero. [Hiero](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java) and [Hiero4](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero4.java).

Even though Hiero4 has a higher version number, it still seems to lack some features that Hiero (Hiero v3) offers, e. g. the possibility to add effects.

@NathanSweet What's the purpose of Hiero4? Could it be removed?

**Comment by NathanSweet** [comment]
Hiero3 uses Java's font rendering. Hiero4 uses FreeType (via some code from
MatthiasM's TWL), but lacks some features. The goal was to use FreeType
with supersampling to improve output, because often Java's font rendering
is suboptimal, especially at smaller sizes. BMFont does a good job and I'd
like Hiero to be able to do the same:
https://github.com/libgdx/libgdx/wiki/Hiero#bmfont
I believe Hiero4 is usable as is, though it's unfinished. I don't think it
needs to be removed. Ideally Hiero4 would support everything Hiero3 does,
plus FreeType. Likely when using FreeType some feature would not be
available.


On Fri, Feb 20, 2015 at 2:48 PM, Daniel Holderbaum <notifications@github.com

**Comment by MobiDevelop** [comment]
To be fair, it has been like four years since it has been touched. If it
will never be improved upon (finished), it might as well be removed.

**Comment by NathanSweet** [comment]
As I said, it is usable as is.

**Comment by MobiDevelop** [comment]
Usable and complete are different things. But if Nate wants it for some
reason who are we to argue.

**Comment by NathanSweet** [comment]
Eh? This is a collaborative project, not a dictatorship.

If it were unfinished and not useful for anything, then sure remove it
since it isn't being worked on. I'm just saying that last I remember it was
working and can be used for something Hiero3 can't -- to render using
FreeType. Why remove it?
