### ISSUE TITLE
Button Listener

### ISSUE THREAD

**Issue by mario109** [libgdx/libgdx#2870]
When a Button's listener is set to ClickListener ,overrides clicked and button.setDisabled(true)
the event will still fire.

**Comment by NathanSweet** [comment]
What's an overrides clicked?

**Comment by mario109** [comment]
http://prntscr.com/680ape
When I disable the slot/button the event still fires.

**Comment by NathanSweet** [comment]
Ah, yeah that's correct. An actor being clicked is separate from the actor being disabled. Use `ChangeListener` to detect when a button's checked state changes. This happens when it is clicked, `toggle` or `setChecked` is called, and in the future could happen if enter is pressed when the button is focused, etc.

**Comment by mario109** [comment]
How do I detect if I pressed Left click or Right click when using ChangeListener

**Comment by NathanSweet** [comment]
You can use Gdx.input to detect the current mouse state. A button's change
event doesn't have to be triggered by a mouse or touch. Use a click
listener if you want and check if the button is disabled.

Please don't post any more questions here. This is an issue tracker, not a
help desk. Use IRC, forums, etc.
https://github.com/libgdx/libgdx/wiki/Getting-help
