### ISSUE TITLE
Interface Shape2D does not provide contains() method

### ISSUE THREAD

**Issue by haimat** [libgdx/libgdx#2880]
All classes implementing the `Shape2D` interace (like `Circle` or `Rectangle`) provide a method `contains()`, but the interface itself does not. However that would be really useful.

Would it be possible to add this method to the interface as well?

**Comment by misterdustinface** [comment]
Dependency inversion.  Contains would have a subclass of Shape2D as a
parameter, so Shape2D would then be coupled to it's subclasses.

**Comment by misterdustinface** [comment]
*its subclasses.  It is also possible to make the parameter a Shape2D, but
then within the contains methods you have to branch over the instanceof
keyword (if the implementation is in java).  This is generally considered
to be bad style, but it could work for this situation.

**Comment by xoppa** [comment]
`Shape2D` is only a tagging interface, see #2178. There are many methods that it could have, but it doesn't. Everything is possible though. What exactly is the issue you're reporting? Please provide enough information to reproduce the issue. For example include the practical use-case for a feature you're requesting or preferable submit a [pull request](https://github.com/libgdx/libgdx/wiki/Contributing).

**Comment by misterdustinface** [comment]
Oh yeah definitely a tagging interface.  This issue should be closed.

**Comment by nooone** [comment]
> Dependency inversion. Contains would have a subclass of Shape2D as a parameter, so Shape2D would then be coupled to it's subclasses.

@misterdustinface The `contains(...)` methods actually take either `float x, float y` or `Vector2`. "Dependency inversion" is no problem here.

If all classes implementing `Shape2D` have this method, it would probably not be a bad idea to add it to the interface. IMO it makes sense that a 2D shape can test for a point.

However, there is one problem: `Polyline`. Polyline is the only one which does not have this method. IMO it is however questionable, whether a "polyline" should be a `Shape2D` at all. In my understanding a shape is "closed", has an area and can contain a point. An arbitrary line however does not satisfy this definition.

**Comment by nooone** [comment]
I made a PR with the proposed changes. I think the additional methods fit.

**Comment by misterdustinface** [comment]
But is there a reason that these subclasses of Shape2D are using Ad-Hoc polymorphism?  The parameters associated with the contains method are more variable than you have expressed (some include additional vectors OR shapes)

Most importantly, these "shapes" (I agree that a polyline is not necessarily a shape) have been designed to only be representable within a plane.  They are tagged as Shape2D because that is the manner in which they can be best described (something in 2D).  The interface Shape2D is being utilized for communicative purposes over polymorphic use, because polymorphism in the realm of shape definitions tends to get either very overcrowded (with too many methods which have too much knowledge), or underdescriptive (with too few functions which have much too generic of parameters to be self descriptive).

Yes, there should be a method to check for a point within a Shape2D, but we may get out of hand by trying to expand Shape2D again (and end up repeating the history that Shape2D has already gone through!).

No, this Polyline is definitely represented in 2D, and the Shape2D tag is being utilized to describe THINGS which lie within 2D space.  It is not exactly a shape, but it is definitely 2D.

I think that Shape2D may just need another rename.  Then we can make a NEW Shape2D, or just a Shape, that deals with containment in the way that makes sense to us all.

As for Ad-Hoc polymorphism with the contains method: Point, vector, plane, and volume containment could be added in a much more descriptive and organized manner, but that is an issue for another day.

**Comment by haimat** [comment]
Sorry for my delayed reply. So in my game I load different shapes from a (tiled) map - Circles, Rectangles, and Polygons. Now for collision detection and other reasons I need to test whether a point x/y is within that shape or not.

I have a Collection with all my shapes, with Shape2D as type. So I thought since all implementing classes have that `contains()` method I could simply call that on each member of the Collection. But that is not possible as of now (because the interface doesn't have the method). So currently I would need to cast each member to its real type and then call `contains()`. That feels quite cumbersome to me.

**Comment by NathanSweet** [comment]
See Xoppa's comment above and the linked discussion.

**Comment by haimat** [comment]
I am afraid I don't really get the point of that linked discussion. Or to put it in other words: In the case that I have described, do I really need to manually cast every element of the Collection to its real type in order to call `contains()`, or is there a better approach?

**Comment by badlogic** [comment]
I'd be OK with another interface, say CanContainPoint, with two methods
(x/y,vec2l. Every Shape2D that has a contains method implements it. Then
you can have a list<CanContainPoint>.

Well, that just sounds meh as well. Shapes are hard :p

**Comment by NathanSweet** [comment]
I think the basic issue is that methods for the Shape2D interface don't
make sense for all shapes. Eg, PolyLine can't contain a point, so PolyLine
needing a contains method doesn't make sense. Honestly I've never used the
shape API and don't really have a strong opinion here.

The "shape" interface is commonly used when teaching interfaces, but do
people actually find the need for it in real life? It seems like you would
usually know what shape you have, since most apps probably have an API
above the Shape2D interface. Maybe that is the real issue, that people have
application specific needs and should build a layer on top of what libgdx
provides?

**Comment by haimat** [comment]
Well, your example with PolyLine makes sense. However, in my case (example above) I would really like the idea of having one common interface to all shapes, which provides (maybe amongst others) the `contains()` method. In my case I don't need to know which type of shape it is, just whether or not it would contain the point.

And yes, of course I could write a layer on top of all shapes. But then, why not use the common interface libGDX already provides?

**Comment by NathanSweet** [comment]
You probably already need a layer on top of all shapes, in which case it's
pretty trivial to adds some contains methods or whatever else you need. I'm
not saying this is the only right answer, just an option.

**Comment by haimat** [comment]
Well, sure, if I would have such a custom layer, then of course I could wrap the shape's `contains()` method in that layer. However, in my case there is no such extra layer, I am happy with just having all these the shapes directly in the Collection...

Anyway, it's not a big deal really. I am using Grooy, so I can just call the method anyway. I was just curious why the interface does not include the `contains()` method in the first place, as that seemed logical to me. But if you disagree with me, then please feel free to close this issue :-)

**Comment by xoppa** [comment]
Imo a shape should not contain any functionality. It is simply a container for whatever properties it has that defines the shape. It should not even contain a position or rotation or alike (two shapes can be same regardless their location in space).

Ofcourse you could add as many functionality to the shape as you need. Why stop at contains? You could add a check if it is visible in the frustum or whether it is hit by a ray or get its bounding box, etc. The possibilities are endless and imo it is not the responsibility of the shape to be aware of these algorithms. A shape is passive.

An option (e.g. how bullet does it) could be to move the algorithms out to a separate class. This way you can go nuts on whatever you want to implement and share/reuse code for multiple shapes. Of course this depends on the use-case. For example each shape could have a unique zero-based index which can be used to quickly find the correct algorithm for whatever functionality you need.

**Comment by nooone** [comment]
Guys, besides that lengthy past discussion about which methods Shape2D should have and which ones it should not have, he asked solely for the `contains(point)` method, which every `Shape2D`, besides `Polyline` had anyway. This is a pretty strong indicator that:

- That method is a very good candidate to be added to the interface
- That Polyline might not really be a Shape2D

The question that this discussion can be reduced to is: Should `Polyline` be a `Shape2D`. In my "natural" definition of a shape, a Polyline is not a shape. If there is no specific reason, or application where someone really needs Polyline to be a Shape2D, which I can't think of right now, we might simply remove that interface from Polyline. If that's done, it would be just plain stupid to not add contains to the common interface and force people to do downcasts.

**Comment by obigu** [comment]
I agree with @noone, Polyline may not be a Shape2D, things get much easier/coherent if it doesn't.

I'm using shapes extensively in my game and what I've done is basically add a layer on top of to be able to provide a common API to my shapes. It contains basic methods suchs as getX(), getY(), getRotation(), etc...
With the current Shape2D shapes, simple stuff such as position is not consistent, for instance, Rectangle coordinates are bottom left point based whilst Polygon or Circle are center based. This makes adding all common methods to the current Shape2D harder/not possible.

Having a consistent implementation would also allow to add utility methods. Intersector could then have an overlaps(Shape2D, Shape2D) to allow intersection checks that are not currently possible such as between Circle and Polygon.

So, if we decide to go for a full and nice Shape API solution, I think it would wise to make specific Shape2D implementations such as Rectangle consistent (or probably just create new ones not to break backwards compatibility) and not make a halfway dodgy interface with just a couple more methods.

**Comment by xoppa** [comment]
See #2885
