### ISSUE TITLE
ParticleEffect.scaleEffect(float scaleFactor) causes pooled FX to not reset() correctly

### ISSUE THREAD

**Issue by just4phil** [libgdx/libgdx#2893]
Hi.
i have constant issues with pooled particleEffects / emitters.

after some investigation i found out that ParticleEffect.scaleEffect(float scaleFactor) causes pooled FX to not reset() correctly.

here is a libgdx-barebone-desktop-app to test it:
http://pastebin.com/wmMBiiTv

here are the .png and .p files. put them in assets into a subdirectory "particleFX" 
https://www.dropbox.com/sh/o014eeg53y6cymn/AACJFE-wwFhQ_hgiowqNsrtea?dl=0
(not sure if this works)

alternative:
this is the .p file. (name it "test_explosion.p" and put it into assets/particleFX/
http://pastebin.com/826YZQnm

put the standard particleImage "particleExhaust.png" there, too.

app:
press SPACE
and activate / deactivate the line with setScale...

bye
phil

**Comment by Darkyenus** [comment]
This looks difficult to resolve. Basically the problem is, that changes done by scaleEffect change "type" of the effect - ParticleEffectPool does not expect that, because those properties are not set back on reset. Easiest solution would be to reload all ParticleEmitters in the effect on reset(), similarly to what ParticleEffectPool does on creating a new pooled Effect. That could have some performance impact (probably not much) and -could- break existing code, so adding a flag (reloadOnReset) into the Pool would solve it.

**Comment by yjukaku** [comment]
:+1: I have the same issue.  I'm surprised that calling effect.reset() doesn't reset the scale.  Is it not possible because of the children particle emitters not keeping track of their initial values?

If so I think loading it back from file would probably be the easiest fix.

**Comment by Darkyenus** [comment]
Loading it from the file on each time would be terribly slow. It would have to be saved alongside ParticleEffect or nearby.

**Comment by cypherdare** [comment]
I took a stab at this. PooledEffects have the benefit of having their prototype easily on hand for copying their original values from, so I fixed it there. This unfortunately leaves `reset()` still broken in the superclass, but there is no clean solution for that.

I don't think breaking existing code is of concern in my solution. I can't think of a possible use case for allowing your pooled effects to arrive with various unpredictable scales, and since the super class is unchanged, people relying on this behavior (i.e. not using ParticleEffectPool) should be unaffected. 

In the case of a PooledEffect, this is nothing but a bug. If anyone was burned by this, they may have a work-around in place, but the possible workarounds that I'm thinking of wouldn't be broken by the fix.
