### ISSUE TITLE
OutOfMemoryError in ObjectSet<String>

### ISSUE THREAD

**Issue by nikialeksey** [libgdx/libgdx#2903]
```
public class Test extends ApplicationAdapter {
	
	final static int cntWord = 2 * 100 * 100;
	final static int lenWord = 2;
	final static int cntDistinctLetter = 100;
	Random random = new Random();
	
	ObjectSet<String> objSet = new ObjectSet<String>();
	
	String generateRandomString(int lenWord, int cntDistinctLetter) {
		StringBuilder stringBuilder = new StringBuilder();
		for (int i = 0; i < lenWord; i++)
			stringBuilder.append((char)(random.nextInt() % cntDistinctLetter + 32));
		return stringBuilder.toString();
	}
	
	double tms(Consumer<String[]> consumer, String[] items) {
		long start = System.nanoTime();
		
		consumer.accept(items);
		
		return (System.nanoTime() - start) / 1000000.0;
	}
	
	void objectSetAdd(String[] items) {
		for (int i = 0; i < cntWord; i++)
			objSet.add(items[i]);
	}
	
	@Override
	public void create () {
		
		String[] items = new String[cntWord];
		for (int i = 0; i < cntWord; i++)
			items[i] = generateRandomString(lenWord, cntDistinctLetter);
		
		double t = tms(this::objectSetAdd, items);
		
		System.err.println("=========Testing========");
		
		System.err.println("ObjectSet: Adding: " + String.format("%.2f", t));
		
		System.err.println("=========Testing========");
	}

	@Override
	public void render () {
	}
}
```

After run this code i got OutOfMemoryError.

**Comment by NathanSweet** [comment]
Please post code that is runnable.
https://github.com/libgdx/libgdx/wiki/Getting-help#executable-example-code

**Comment by nikialeksey** [comment]
Is this right?
```
package testObjectSet;

import java.util.Random;
import java.util.function.Consumer;

import com.badlogic.gdx.utils.ObjectSet;

public class Example {
	
	final static int cntWord = 2 * 100 * 100;
	final static int lenWord = 2;
	final static int cntDistinctLetter = 100;
	Random random = new Random();
	
	ObjectSet<String> objSet = new ObjectSet<String>();
	
	String generateRandomString(int lenWord, int cntDistinctLetter) {
		StringBuilder stringBuilder = new StringBuilder();
		for (int i = 0; i < lenWord; i++)
			stringBuilder.append((char)(random.nextInt() % cntDistinctLetter + 32));
		return stringBuilder.toString();
	}
	
	/**
	 * return time in milliseconds of consumer.accept()
	 * @param consumer any function
	 * @param items special parameters, in our case it's a array of string
	 * @return time in milliseconds of consumer.accept()
	 */
	double tms(Consumer<String[]> consumer, String[] items) {
		long start = System.nanoTime();
		
		consumer.accept(items);
		
		return (System.nanoTime() - start) / 1000000.0;
	}
	
	/**
	 * Testing function for add operation in ObjectSet
	 * @param items
	 */
	void objectSetAdd(String[] items) {
		for (int i = 0; i < cntWord; i++)
			objSet.add(items[i]);
	}
	
	public void run() {
		//create array of string
		String[] items = new String[cntWord];
		for (int i = 0; i < cntWord; i++)
			items[i] = generateRandomString(lenWord, cntDistinctLetter);
		
		//test operation
		double t = tms(this::objectSetAdd, items);
		
		System.err.println("=========Testing========");
		
		System.err.println("ObjectSet: Adding: " + String.format("%.2f", t));
		
		System.err.println("=========Testing========");
	}
	
	public static void main(String[] args) {
		new Example().run();
	}
}
```

**Comment by NathanSweet** [comment]
No, because you don't include the Consumer class and `this::objectSetAdd`
is invalid. If I delete that stuff, it runs without an OOM error.

**Comment by nikialeksey** [comment]
Do you think i forgot include the Consumer? I imported Consumer class on line 2. You should run this code on Java 8.

**Comment by NathanSweet** [comment]
Ah, I didn't notice Java 8. There is no need to require Java 8.
http://pastebin.com/GZV2wueh

The objects you are inserting have poor hash codes. Out of the 20k objects,
5690 have duplicate hash codes (using `new Random(1234)`). ObjectSet is
using 3 hash functions so the number of objects that cannot be hashed to
their own bucket is less: 897. This is much more common than ObjectSet
expects.

When an object cannot be hashed to its own bucket, ObjectSet puts the
objects into a small "stash", which a list at the end of keyTable. When the
stash is full, ObjectSet doubles it's backing array and reinserts all
objects. The stash is used to reduce the number of times the backing array
needs to be doubled.

The stash capacity is using `Math.max(3, (int)Math.ceil(Math.log(newSize))
* 2)`. Eg, for a backing array size of 16,777,216 the stash capacity is 34.
The idea is that the stash does not get too large, because looking in the
stash is O(n). Your objects have so many collisions (897) that the stash
capacity doesn't grow large enough to contain them all before the JVM runs
out of memory.

Your options are to not use ObjectSet, to use objects with better
hashcodes, or to modify ObjectSet to use a larger stashCapacity.

**Comment by nikialeksey** [comment]
Yes, I read about ObjectSet's algorithm and understood it. Sorry for any function with unclear name (like tms). It was need to measure a time of operation with Set and compare ObjectSet with HashSet (java.util). After compare on random strings HashSet was better then ObjectSet. Look at:
```
package testObjectSet;

import java.util.HashSet;
import java.util.Random;
import java.util.function.Consumer;

import com.badlogic.gdx.utils.ObjectSet;

public class Example {
	
	final static int cntWord = 1000 * 1000;
	final static int lenWord = 20;
	final static int cntDistinctLetter = 100;
	Random random = new Random();
	
	ObjectSet<String> objSet = new ObjectSet<String>();
	HashSet<String> hashSet = new HashSet<String>();
	
	String generateRandomString(int lenWord, int cntDistinctLetter) {
		StringBuilder stringBuilder = new StringBuilder();
		for (int i = 0; i < lenWord; i++)
			stringBuilder.append((char)(random.nextInt() % cntDistinctLetter + 32));
		return stringBuilder.toString();
	}
	
	double tms(Consumer<String[]> consumer, String[] items) {
		long start = System.nanoTime();
		
		consumer.accept(items);
		
		return (System.nanoTime() - start) / 1000000.0;
	}
	
	void objectSetAdd(String[] items) {
		for (int i = 0; i < items.length; i++)
			objSet.add(items[i]);
	}
	
	void hashSetAdd(String[] items) {
		for (int i = 0; i < items.length; i++)
			hashSet.add(items[i]);
	}
	
	public void run() {
		//create array of string
		String[] items = new String[cntWord];
		for (int i = 0; i < cntWord; i++)
			items[i] = generateRandomString(lenWord, cntDistinctLetter);
		
		//test operation
		double tObj = tms(this::objectSetAdd, items);
		double tHash = tms(this::hashSetAdd, items);
		
		System.err.println("=========Testing========");
		
		System.err.println("ObjectSet: Adding: " + String.format("%.2f", tObj));
		System.err.println("  HashSet: Adding: " + String.format("%.2f", tHash));
		
		System.err.println("=========Testing========");
	}
	
	public static void main(String[] args) {
		new Example().run();
	}
}
```
But i don't know is this issue or no. You may compare for another operation (like remove, contains) and HashSet will be better. Why use ObjectSet?

**Comment by NathanSweet** [comment]
You cannot write a microbenchmark like that in Java:
http://stackoverflow.com/a/513259/187883

ObjectSet is often faster for gets. Adds are expensive, specifically
growing the backing array is expensive for ObjectSet, so set the initial
size in the constructor high enough. You may see different performance with
different sized maps. ObjectSet can be faster for iteration also, since it
is traversing a single array it has good cache locality. HashMap uses a
linked list of "nodes" for each bucket. HashMap may allocate a "node" on
add, ObjectSet does not allocate except when the backing array must grow.

**Comment by nikialeksey** [comment]
HashMap in java 8 use a binary tree for collision nodes http://java.dzone.com/articles/hashmap-performance . May be you should write to ObjectSet doc about ALL advantages and disadvantages, it may be useful.

**Comment by NathanSweet** [comment]
Interesting what they did for Java 8 with HashMap.

The javadocs could definitely be improved with more general info, though
it's hard to write about all the comparisons of Java versions, Android,
GWT, etc especially when it varies based on size, number of add/contains
calls, etc.

It's unfortunate ObjectSet falls on it's face when there are many
collisions. FWIW, I've never encountered the problem in a real app.
