### ISSUE TITLE
[Enhancement] BitmapFont issues

### ISSUE THREAD

**Issue by bachtrong43** [libgdx/libgdx#2959]
1) Can set the TextureFilter for BitmapFont which has separated TextureRegions in Skin.
2) Unable to load BitmapFont which has multiple TextureRegions that were put on TextureAtlas. The reason in code of Skin: method getJsonLoader
 ```javascript
json.setSerializer(BitmapFont.class, new ReadOnlySerializer<BitmapFont>() {
			public BitmapFont read (Json json, JsonValue jsonData, Class type) {
				String path = json.readValue("file", String.class, jsonData);
				int scaledSize = json.readValue("scaledSize", int.class, -1, jsonData);
				Boolean flip = json.readValue("flip", Boolean.class, false, jsonData);
				Boolean markupEnabled = json.readValue("markupEnabled", Boolean.class, false, jsonData);

				FileHandle fontFile = skinFile.parent().child(path);
				if (!fontFile.exists()) fontFile = Gdx.files.internal(path);
				if (!fontFile.exists()) throw new SerializationException("Font file not found: " + fontFile);

				// Use a region with the same name as the font, else use a PNG file in the same directory as the FNT file.
				String regionName = fontFile.nameWithoutExtension();
				try {
					BitmapFont font;
					TextureRegion region = skin.optional(regionName, TextureRegion.class);
					if (region != null)
						font = new BitmapFont(fontFile, region, flip);
					else {
						FileHandle imageFile = fontFile.parent().child(regionName + ".png");
						if (imageFile.exists())
							font = new BitmapFont(fontFile, imageFile, flip);
						else
							font = new BitmapFont(fontFile, flip);
					}
					font.setMarkupEnabled(markupEnabled);
					// Scaled size is the desired cap height to scale the font to.
					if (scaledSize != -1) font.setScale(scaledSize / font.getCapHeight());
					return font;
				} catch (RuntimeException ex) {
					throw new SerializationException("Error loading bitmap font: " + fontFile, ex);
				}
			}
		});
```
If the BitmapFont font.fnt contains two images(with the name font1.png,font2,png), the above code will search the region or the image file with name "font".

**Comment by Bazylot** [comment]
Hi, i also faced this problem and after few hours of debugging found that serializer for BitmapFont (code above) takes .fnt file name as regionName instead of look into .fnt file and read list of .png files that actually represents the font. Now i can't use font with more than one png file or even font that png's name is other than fnt name.
Looking forward this enchancement but i think it's a bug ;(

**Comment by NathanSweet** [comment]
When Skin loads a BitmapFont it needs to look up the region by name, which may come from the skin/atlas. I suggest naming your fonts something you won't name other files. This problem is part of the magic that needs to happen to load things from JSON. If you want more control, feel free to create an empty Skin, populate it with fonts, atlases, etc, then load the JSON into it. This is what I usually do in non-trivial apps.

If you have a suggestion for how this might be fixed, post it and we can reopen the issue. If you found the problem confusing, please consider updating the wiki.
