### ISSUE TITLE
NullPointerException if FreeTypeFontParameter.packer set

### ISSUE THREAD

**Issue by RobRendell** [libgdx/libgdx#2980]
While you're making changes to the font code: trying to call `FreeTypeFontGenerator.generateFont(FreeTypeFontParameter parameter, FreeTypeBitmapFontData data)` with the `FreeTypeFontParameter.packer` parameter assigned to your own packer throws a NullPointerException, because the generated FreeTypeBitmapFontData has regions == null.  The generator only assigns regions if the code decides that it owns the atlas, so the BitmapFont constructor is passed a null value for the array of regions.

To better support packing font glyphs using our own packers, generateData should assign regions on the resulting FreeTypeBitmapFontData object whether the data owns the atlas or it was supplied by the user.  As far as I can see, simply making the block at the end of generateData() that generates the texture regions unconditional, rather than testing if ownsAtlas is true, would be the correct behaviour whether the packer was created by FreeTypeFontGenerator or passed in via the FreeTypeFontParameter.

**Comment by nooone** [comment]
Is this the same as described in https://github.com/libgdx/libgdx/issues/2882 ?

**Comment by RobRendell** [comment]
It's the same NullPointerException as was mentioned in that issue, yes.

I've actually confirmed locally that my suggested change (making that final block unconditional) appears to fix the problem and results in the font rendering and the generated font sharing the atlas/packer with everything else.

**Comment by RobRendell** [comment]
It's pretty trivial to reproduce, but for completeness, the following code:
```
        generator = new FreeTypeFontGenerator(Gdx.files.internal("tubular.ttf"));
        FreeTypeFontGenerator.FreeTypeFontParameter parameter = new FreeTypeFontGenerator.FreeTypeFontParameter();
        parameter.size = 20;
        parameter.packer = new PixmapPacker(1024, 1024, Pixmap.Format.RGBA8888, 1, false);
        BitmapFont font = generator.generateFont(parameter);
```

Will produce this stack trace in 1.5.6-SNAPSHOT
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.graphics.g2d.BitmapFont.<init>(BitmapFont.java:153)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:173)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:164)
	at com.mygdx.game.FontNPE.create(FontNPE.java:28)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

**Comment by NathanSweet** [comment]
AFAIK, [it still works like it always has](https://github.com/libgdx/libgdx/blob/729929ec2685014a56fe486f97ee8952dedfed54/extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java#L496). That link is from before the recent refactoring.

Textures are not created automatically when a PixmapPacker is specified because it is expected that more regions will be added to the packer. See FreeTypePackTest.

**Comment by RobRendell** [comment]
Yes, this isn't a new issue.  I was saying that it looked to me like there was an easy fix, while you were making api-breaking changes to the font code anyway.

Why would it be a problem for the font if more regions are added to the packer after it stores references to the textures?  PixmapPacker-s support incremental updates of their atlas via updateTextureAtlas, and pixmaps packed after glyphs of a font are added won't change the position of those glyphs in the atlas.  As I suggested, making the final block of generateData unconditional, like this:
```
	/** Generates a new {@link BitmapFontData} instance, expert usage only. Throws a GdxRuntimeException if something went wrong.
	 * @param parameter configures how the font is generated */
	public FreeTypeBitmapFontData generateData (FreeTypeFontParameter parameter, FreeTypeBitmapFontData data) {

...
		// Generate texture regions.
		Array<Page> pages = packer.getPages();
		data.regions = new Array(pages.size);
		for (int i = 0; i < pages.size; i++)
			data.regions.add(createRegion(pages.get(i), parameter));

		return data;
	}
```
seems to work just fine when I supply my own packer, even if I pack subsequent pixmaps to the packer and update the atlas.  Are there implications for disposing of resources, or do you end up with two textures for the same atlas page, or something else that I don't understand?

**Comment by NathanSweet** [comment]
FreeTypeFontGenerator `createRegion` creates a new texture for each packer page. With your change, this means every font you generate gets its own texture. You'd have many textures with the exact same data.

Even if only one texture was created per packer page, uploading to a texture is expensive, especially on mobile. PixmapPacker `updateTextureAtlas` reuploads the entire texture if a region was added to an existing page. Eg, if you're packing 4 fonts and some images to a 1024x1024 texture, that would be 4+ 1024x1024 texture uploads when 1 would have been sufficient. 

It does make the API a bit odd when you specify a packer to have `generateFont` crash (unacceptable) and `generateData` return a FreeTypeBitmapFontData that hasn't yet been populated with texture regions (guessing packing multiple fonts into a single packer was tacked on last).

I'd say `generateFont` should throw an exception if a packer is set. This makes the user be explicit about when packing is complete and textures should be created. If only specifying the packer to specify padding or similar, this is only a slight inconvenience.

Next maybe we could have convenience methods to lessen the pain when packing is complete. Maybe a method on FreeTypeFontGenerator takes a packer, creates textures, and returns `Array<TextureRegion>`. That is then used to construct each BitmapFont.

I haven't personally used FreeTypeFontGenerator with my own packer, so I don't have a vested interest in making this super awesome. I'd be happy with someone stepping up and owning that functionality and this issue.

**Comment by RobRendell** [comment]
I can give it a try, if you can verify that I'm not doing anything bone -headed like creating duplicate textures.  I'll try to get you a pull request some time after the weekend.

**Comment by RobRendell** [comment]
(I'm not sure if in this issue is the best place to have a discussion about the proposed changes, so apologies if there's somewhere better).

Reading through the PixmapPacker and the FreeTypeFontGenerator code, there seems to be some duplication here - they both create texture regions using almost identical code, for example.  Also, I see that the incremental font code uses `Gdx.gl.glTexSubImage2D()` to add the glyphs to the existing texture, presumably on the GPU and therefore more efficiently than PixmapPacker using `page.image.drawPixmap()` to add pixmaps to the page's big pixmap and then `page.texture.load(page.texture.getTextureData())` to refresh it.

Taken all together, the approach I'm thinking is to remove `createRegion()` from FreeTypeFontGenerator and have it delegate such work to the PixmapPacker (whether the packer is created locally or supplied by the user) via a new `getRegions()` method which returns the packer's page textures as an Array<TextureRegion>, creating them if necessary.  Also, modify PixmapPacker so it uses `Gdx.gl.glTexSubImage2D()` when adding to existing textures.  Finally, modify `FreeTypeFontGenerator.generateFont`, which after generating the FreeTypeBitmapFontData will check if parameter.packer is set, and if so call the new `packer.getRegions()` method to get the regions to pass to the BitmapFont constructor.

For maximum efficiency, users who want to pack multiple fonts into the same texture could call `FreeTypeFontGenerator.generateData` for each font, then updateTextureAtlas or generateTextureAtlas to pack it all, and then call the new packer.getRegions method to get the parameter to pass in to the BitmapFonts.  A less efficient but more convenient method would be to simply call `FreeTypeFontGenerator.generateFont` with the packer parameter set.

How does all that sound to you?

**Comment by NathanSweet** [comment]
Incremental fonts use glTexSubImage2D because they are likely to update a
small portion of the texture (though I wonder at how many new glyphs at
once would updating the whole texture be faster). If there are many new
regions, it wouldn't be good to make many glTexSubImage2D calls. I think it
makes sense for PixmapPacker to be able to do it both ways. I'm not sure we
can come up with a heuristic to automatically choose which to use.

Currently the packer only cares about its pixmaps. It is sort of nice that
it doesn't need to worry about creating textures and the settings
associated with that, but at the same time I can see it would be convenient
for FreeType font generation. Currently the FreeType font parameter has
these settings, which are ignore if a packer is specified since you need to
create the texture yourself. If we did let the packer create the textures,
we could then remove the texture creation settings from the FreeType font
parameter. To customize these, you'd need to provide a packer.

Maybe @badlogic has input since I believe the FreeType stuff is his baby?

(I'm not sure if in this issue is the best place to have a discussion about
the proposed changes, so apologies if there's somewhere better).

Reading through the PixmapPacker and the FreeTypeFontGenerator code, there
seems to be some duplication here - they both create texture regions using
almost identical code, for example. Also, I see that the incremental font
code uses Gdx.gl.glTexSubImage2D() to add the glyphs to the existing
texture, presumably on the GPU and therefore more efficiently than
PixmapPacker using page.image.drawPixmap() to add pixmaps to the page's big
pixmap and then page.texture.load(page.texture.getTextureData()) to refresh
it.

Taken all together, the approach I'm thinking is to remove createRegion()
from FreeTypeFontGenerator and have it delegate such work to the
PixmapPacker (whether the packer is created locally or supplied by the
user) via a new getRegions() method which returns the packer's page
textures as an Array, creating them if necessary. Also, modify PixmapPacker
so it uses Gdx.gl.glTexSubImage2D() when adding to existing textures.
Finally, modify FreeTypeFontGenerator.generateFont, which after generating
the FreeTypeBitmapFontData will check if parameter.packer is set, and if so
call the new packer.getRegions() method to get the regions to pass to the
BitmapFont constructor.

For maximum efficiency, users who want to pack multiple fonts into the same
texture could call FreeTypeFontGenerator.generateData for each font, then
updateTextureAtlas or generateTextureAtlas to pack it all, and then call
the new packer.getRegions method to get the parameter to pass in to the
BitmapFonts. A less efficient but more convenient method would be to simply
call FreeTypeFontGenerator.generateFont with the packer parameter set.

How does all that sound to you?

—
Reply to this email directly or view it on GitHub
<https://github.com/libgdx/libgdx/issues/2980#issuecomment-87163280>.

**Comment by RobRendell** [comment]
Re: glTexSubImage2D: ok, that makes sense.

Re: the packer only caring about its pixmpas: actually, PixmapPacker also creates textures, when it generates or updates textureAtlasses.
```
	public synchronized TextureAtlas generateTextureAtlas (TextureFilter minFilter, TextureFilter magFilter, boolean useMipMaps) {
		TextureAtlas atlas = new TextureAtlas();
		for (Page page : pages) {
			if (page.rects.size != 0) {
				Texture texture = new Texture(new PixmapTextureData(page.image, page.image.getFormat(), useMipMaps, false, true)) {
					@Override
					public void dispose () {
						super.dispose();
						getTextureData().consumePixmap().dispose();
					}
				};
				texture.setFilter(minFilter, magFilter);
<snip>
```
... and similar in updateTextureAtlas.  It's pretty much the same code as appears in FreeTypeFontGenerator's createRegion method:
```
	private TextureRegion createRegion (Page p, FreeTypeFontParameter parameter) {
		Texture tex = new Texture(
			new PixmapTextureData(p.getPixmap(), p.getPixmap().getFormat(), parameter.genMipMaps, false, true)) {
			@Override
			public void dispose () {
				super.dispose();
				getTextureData().consumePixmap().dispose();
			}
		};
		tex.setFilter(parameter.minFilter, parameter.magFilter);
		return new TextureRegion(tex);
	}
```
... aside from createRegion also wrapping the texture in a TextureRegion.  I thought it would be cleaner to have that texture-creating code in only one place, in PixmapPacker, as well as being more convenient if you're manually creating the BitmapFonts and need the array of TextureRegions.

In any case, you don't appear to feel that what I suggested was inherently broken, so I'll get together a pull request or two and we can converse about the specific changes I'm offering on that pull request.

**Comment by NathanSweet** [comment]
That's what I get for posting from a phone without reviewing PixmapPacker. It would be nice to have the texture creation code in one place, but then it's also not much code so hopefully we don't need to strain too much to do that. The goal is a sane way for FreeTypeFontGenerator to work when a packer is specified, and when one isn't. If I understand correctly, your approach sounds reasonable.

FreeTypeFontParameter has `minFilter` and other settings for when not specifying a packer. Do we leave those and note they aren't used if a packer is specified?

Note that the incremental texture updates done using glTexSubImage2D don't generate mipmaps. That should be documented somewhere (or remedied).

**Comment by MobiDevelop** [comment]
Assumed to be fixed by merged PR, if not reopen.

**Comment by RobRendell** [comment]
Yes, the PR fixed this.  I should have closed this issue - apologies.
