### ISSUE TITLE
Wrong size of Actor's debug bounds rectangle

### ISSUE THREAD

**Issue by patwork** [libgdx/libgdx#2989]
Hi,

I've found small problem in Actor's drawDebugBounds method. My app has viewport working in virtual world dimensions 16 units x 9 units. drawDebugBounds is using its coordinates instead of pixel screen resolution and because of this and "width - 1, height - 1", every rectangle is one unit short in width (1/16 of viewport) and height (1/9 of viewport). Fullscreen background with 16x9 unit size has 15x8 debug rectangle, sprites with 1x1 unit size has 0x0 debug rectangle, etc.

*my code*
```java
		camera = new OrthographicCamera();
		viewport = new FitViewport(16f, 9f, camera);
		viewport.apply();
		stage = new Stage(viewport);
```

*libgdx/gdx/src/com/badlogic/gdx/scenes/scene2d/Actor.java*
```java
	/** Draws a rectange for the bounds of this actor if {@link #getDebug()} is true. */
	protected void drawDebugBounds (ShapeRenderer shapes) {
		if (!debug) return;
		shapes.set(ShapeType.Line);
		shapes.setColor(stage.getDebugColor());
		shapes.rect(x, y, originX, originY, width - 1, height - 1, scaleX, scaleY, rotation);
	}
```

**Comment by NathanSweet** [comment]
Do you have an executable example?

**Comment by Darkyenus** [comment]
Right, the problem is that drawDebugBounds assumes that 1 unit is small (pixel), so it draws debug rectangles smaller by one unit, presumably so they don't overlap.

Solution would be to remove this adjustment, making it less clear in pixel-perfect situations. But we could overwrite that back to current behaviour in Widget and WidgetGroup, so it would stay the same for scene2d UI (where the pixel-perfect assumption will be usually correct).
