### ISSUE TITLE
Scene2D elements (like Table and Ninepatch) only work with pixel cameras

### ISSUE THREAD

**Issue by StrongJoshua** [libgdx/libgdx#3023]
Like the title says, if I attempt to use a Table, Ninepatch, Label etc. in a Stage where the camera measures in world units, they will draw ridiculously large. This could be caused by the elements internally measuring everything in pixels and not converting back to world units when being drawn (i.e. I tell a Ninepatch to be 0.8x0.8 world units in size, when being drawn it knows that means 51.2x51.2 pixels if each world unit is 64x64 pixels, and then draws at that size instead of the 0.8x0.8), but it could be something else entirely. Besides having a separate stage for these elements I do not know any ways to fix this without going into the libraries code.

Is a fix for this feasible or will I have to live with the workaround?

**Comment by Darkyenus** [comment]
I'd argue that UI should stay as it is - assuming that everything is pixels. It makes pixel-perfect alignment way easier, which is useful for thin lines and text. Also, this assumption is rooted deeply in scene2d.ui and removing it (while keeping the features it brings) would be too complex.

**Comment by NathanSweet** [comment]
scene2d.ui is most commonly used with a 1:1 ratio of world units to screen pixels. This allows the UI to stay crisp, which is especially important for fonts. When using Table and other auto adjusting layouts, you can swap your entire UI atlas for one of a higher or lower resolution and all your layouts will continue to work while still using pixel sizes. For these reasons most apps use a stage for the UI using pixels sizes, then draw that on top of their game's rendering (which could be a second stage, but scene2d is maybe not the best fit if model/view separation is important).

AFAIK, there is not actually a problem with rendering using different world units. Eg, NinePatch has top/left/bottom/right and middle width/height sizes that are set to pixels by default (because what else would they default to?), but nothing stops you from setting different sizes or (more likely) using NinePatch's `scale` method. Similarly, TextureRegionDrawable defaults to the region size in pixels. Table and other layouts use floats and should not care about pixels.

I'm guessing you were thrown off by the default sizes. Can you provide concrete examples of where you are actually forced to use pixels? Since scene2d.ui is mostly used with pixels this has not seen as much testing as other areas, but it isn't designed specifically for pixels.

There may be some central place (eg Skin) we could scale the resources (NinePatches, etc) that make up a UI, but since it's uncommon I haven't really looked at doing it.

**Comment by StrongJoshua** [comment]
For example, my game uses Tiled maps, so having the world in units of tiles makes things much cleaner, but as I said, when I tried putting a Table filled with Labels I did not get the clean result I expected. Instead I had some huge blurry rectangle in the corner of my map. Then I asked on the forums ([link](http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=18807)) and the only suggestion I got was to use a separate Stage, which I ended up doing.

**Comment by NathanSweet** [comment]
This is an issue tracker. What is the issue you are reporting?

**Comment by StrongJoshua** [comment]
The issue is this:
I create a NinePatch like so:
```java
ninePatchTest = new NinePatch(new Texture(Gdx.files.classpath("tests/highlighter.png")), 8, 8, 8, 8);
```
with "highlighter.png" being a 64x64 pixel image with the specified edge offsets (or whatever they're called).
I am drawing it in a world that uses world units instead of pixels. The app window is 960 x 960 pixels in size. The world is 50x50 units (so each unit is 19.2x19.2 pixels).
I then try to draw the NinePatch at 0, 0 with a size of 2x2 (the batch is using world units), which should be 38.4x38.4 pixels, but instead of a nice NinePatch that has a center of 22.4x22.4 pixels I get this mess (in the lower left corner): ![Messy NinePatch](http://i.imgur.com/5nDbcj4.png)
I understand that this is because of the conflict of me giving it pixels for the edge offsets but the batch drawing in world units, or something like that. But there is currently no workaround, at least that I am aware of (besides making a second Stage).

**Comment by MobiDevelop** [comment]
Why don't you scale the NinePatch?

**Comment by StrongJoshua** [comment]
I tried scaling with 1/worldWidth and 1/worldHeight, but then I wasn't able to see the NinePatch anymore.

**Comment by NathanSweet** [comment]
Please provide an [executable example](https://github.com/libgdx/libgdx/wiki/Getting-help#executable-example-code) that shows the NinePatch not drawing correctly.

**Comment by StrongJoshua** [comment]
I'm working on that right now.

**Comment by StrongJoshua** [comment]
This [zip file](http://www.mediafire.com/download/yzjv4yotv7ybxh4/NinePatchTest.zip) contains both the executable and the image. You just need to put them in the source folder of a project that has the libgdx and the lwjgl backends as dependencies. What should be happening (if I did everything correctly) is that the ninepatch (which is 5x5 units) should be drawn in the center of the application window (which is 400x400 pixles and 20x20 units), so the NinePatch should be 100x100 pixels, but as you will see, it's not.

**Comment by NathanSweet** [comment]
1. If you are going to use such small world coordinates, don't use integer math.
2. Use the camera combined matrix.
3. Update the camera if you change it.
4. Scale the NinePatch.

```java
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.badlogic.gdx.graphics.Camera;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.Batch;
import com.badlogic.gdx.graphics.g2d.NinePatch;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;

public class NinePatchTest extends ApplicationAdapter {
	Camera cam;
	Batch batch;
	float worldWidth = 20, worldHeight = 20, ninePatchWidth = 5, ninePatchHeight = 5;
	NinePatch ninePatch;

	@Override
	public void create () {
		Gdx.graphics.setDisplayMode(400, 400, false);

		cam = new OrthographicCamera(worldWidth, worldHeight);
		cam.position.set(worldWidth / 2, worldHeight / 2, 0);
		cam.update();

		batch = new SpriteBatch();
		batch.setProjectionMatrix(cam.combined);

		ninePatch = new NinePatch(new Texture(Gdx.files.classpath("highlighter.png")), 8, 8, 8, 8);
		ninePatch.scale(1 / worldWidth, 1 / worldHeight);
	}

	@Override
	public void render () {
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

		batch.begin();
		ninePatch.draw(batch, worldWidth / 2 - ninePatchWidth / 2, worldHeight / 2 - ninePatchHeight / 2, ninePatchWidth,
			ninePatchHeight);
		batch.end();
	}

	public static void main (String[] arg) {
		LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
		new LwjglApplication(new NinePatchTest(), config);
	}
}
```

**Comment by StrongJoshua** [comment]
Wow... So many mistakes are often so simple... Thanks!
