### ISSUE TITLE
Issue With VertexBufferObjectWithVAO

### ISSUE THREAD

**Issue by realitix** [libgdx/libgdx#3050]
Hello everyone, this bug is completely strange and it takes me several hours to find the source.

You can see two pictures, on the second, some object are just black.
I have a Framebuffer that renders the scene from another point of view, if I don't enable the framebuffer, the objects are OK, if I use my Framebuffer, the objects are KO.

So I deep into libgdx (very deep!) and I found that in the `VertexBufferObjectWithVAO`:

```
	

    VertexBufferObjectWithVAO
     
    @Override
            public void bind(ShaderProgram shader, int[] locations) {
     
                    GL30 gl = Gdx.gl30;
                    if (vaoDirty || !gl.glIsVertexArray(vaoHandle)) {
     
                            tmpHandle.clear();
                            gl.glGenVertexArrays(1, tmpHandle);
                            vaoHandle = tmpHandle.get(0);
                            gl.glBindVertexArray(vaoHandle);
     
                            //initialize the VAO with our vertex attributes and buffer:
                            bindAttributes(shader, locations);
     
                            // HERE IS THE BUG
                            vaoDirty = false;
     
                    } else {
                            //else simply bind the VAO.
                            gl.glBindVertexArray(vaoHandle);
                    }
                    //if our data has changed upload it:
                    bindData(gl);
     
                    isBound = true;
     
            }
```

If I disable `vaoDirty = false` only for the rendering in the framebuffer, it works.

It's very difficult for me to understand because there is a lot of mecanisms involved.

Xoppa, can you take a look?

Thank you.

![capture_ok](https://cloud.githubusercontent.com/assets/6367936/7316186/27e99018-ea75-11e4-8699-948eb65bfaf9.png)

![capture_ko](https://cloud.githubusercontent.com/assets/6367936/7316188/309ffc42-ea75-11e4-825c-dfd0fd482ef3.png)

**Comment by realitix** [comment]
If I add `bindAttributes(shader, locations);` in the `else` it works.

Maybe this is the problem ?

**Comment by tommyettinger** [comment]
Can you post some small sample of code that demonstrates the problem? (As in, what generates those images?) It's always possible that the bug is in libGDX, but if it hasn't surfaced until now (this appears to be issue number 3,050) it seems more likely that it's in your code, a library you're using, or (since this is deep in OpenGL code) the way you're programming in this case might not be typical usage of libGDX.  If it's the last one, it could be a real bug that has never been encountered because the code that causes it is problematic in some other way, and there may be a simple way to fix your game without changing the library.

**Comment by xoppa** [comment]
@realitix Thanks for reporting. Looking at the code, it looks indeed indeed like the bindAttributes always has to be called (moved to after the branch). Could you send a PR for that? Otherwise I can have a look at it this weekend (along with the cubemap fbo :)).

@tommyettinger VertexBufferObjectWithVAO is recently added and only used for gles3.

**Comment by realitix** [comment]
Ok I will send you a PR.

**Comment by realitix** [comment]
I created the Pull Request https://github.com/libgdx/libgdx/pull/3051
