### ISSUE TITLE
TextButton is not resized to viewport

### ISSUE THREAD

**Issue by david-mccann** [libgdx/libgdx#3060]
Varying the value of the variable "scale" in the following example should not have any visible effect since all coordinates are viewport coordinates and the scale factor is applied to all coordinates. The Image is correctly resized to viewport coordinates and stays invariant when changing the scale factor. The TextButton however isn't. The text seems to be in device coordinates and the button is pixelated. The screenshots show the output for scale=1 and scale=4.
I observed the problem on desktop and android, using gdxVersion 1.5.5 and 1.5.7-SNAPSHOT.

```
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Image;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.TextButton;
import com.badlogic.gdx.utils.viewport.ExtendViewport;

public class GdxGame extends ApplicationAdapter {

	private Skin skin;
	private Stage stage;

	public void create () {
		float scale = 4f;

		skin = new Skin(Gdx.files.internal("skin.json"));
		stage = new Stage(new ExtendViewport(600f / scale, 300f / scale));

		TextButton button = new TextButton("Click", skin, "default");
		button.setWidth(200f / scale);
		button.setHeight(35f / scale);
		button.setPosition(0, 0);
		stage.addActor(button);

		Image image = new Image(new Texture(Gdx.files.internal("blue.png")));
		image.setWidth(80f / scale);
		image.setHeight(80f / scale);
		image.setPosition(100f / scale, 100f / scale);
		stage.addActor(image);
	}

	public void render() {
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		stage.draw();
	}

	public void resize(int width, int height) {
		stage.getViewport().update(width, height, true);
	}
}
```
![scale_1](https://cloud.githubusercontent.com/assets/12129212/7340331/8a0f7178-ec8b-11e4-8776-f7256193b676.png)
![scale_4](https://cloud.githubusercontent.com/assets/12129212/7340330/8a0cb848-ec8b-11e4-81ce-5564cec72d2f.png)

**Comment by NathanSweet** [comment]
You want the text size to change because you've sized the button differently?

**Comment by david-mccann** [comment]
No, I expected that the button and text size should be independent of the absolute coordinate values (sorry, maybe my title is misleading). Shouldn't only the relative values (the values in relation to the world dimensions) matter? It shouldn't make a difference whether the world has a size of (100, 100) and the button a size of (20, 10) or whether the world has a size of (50, 50) and the button a size of (10, 5), should it? In case of the Image this is true, in case of the TextButton it isn't. Am I missing something?

**Comment by NathanSweet** [comment]
If you draw everything without resizing it, everything will be 4 times larger. You size the button and image so they stay the same size on screen. Unlike the image, the button is made up of multiple actors. It has a label and the label renders using a font. Sizing the button or label does not change the size that the font renders at, so your text is 4 times larger.

You could scale the font, but I'm not sure what you are doing. The whole point of using a viewport is so you don't have to manually size each actor. Maybe use a ScreenViewport for your UI and whatever viewport you want for your game.

**Comment by david-mccann** [comment]
Nathan, thanks for your explanation. If I use a ScreenViewport everything looks fine if I set the size of the TextButton in accordance with the actual screen dimensions. But as I understand it, I want to use one of the other viewport types precisely because I want to be indepenent of actual screen dimensions. If I use a FitViewport, for example, and set the width and height in such a way that they match the aspect ratio of standard devices, then I expect the UI to look the same on all devices with that aspect ratio (on other devices the viewport fills in black bars). The coordinates should only be logical coordinates. To put it differently: if I presuppose, for example, a square screen (just an example) and I want a TextButton that fills half the screen in width and 1/10 of the screen in height, I might use a viewport of size (1000, 1000) and a button of size (100, 500) or a viewport of size (100, 100) and a button of size (10, 50). How would I achieve it that the TextButton, including the label which it contains, have the same relative size and positioning on all square screens if not in the way indicated by my example?

**Comment by NathanSweet** [comment]
There are many ways to handle this.

Generally you don't want a UI to be scaled because the bitmap fonts will look bad and the images blurry. Especially small font sizes become unreadable. What I do is design my UIs using Table and other layout groups, without using absolute screen or world sizes or positions. I use ScreenViewport, but I change the atlas that is used based on the screen resolution. I design my UI images at the largest size, then also include 1-2 scaled down atlas sizes with the game. The fonts can be generated for each smaller size rather than just scaling down the large atlas font images. Because my layouts don't have hardcoded sizes or positions, changing the atlas means all the buttons, fonts, etc get bigger or smaller based on which atlas is used, and the entire UI is always drawn without scaling.

You can do as your example code, but you need to scale the font. See BitmapFont `setScale`. You could also use gdx-freetype to generate a font at the exact size you want using a TTF file. Your font will be crisp, but your UI images may be scaled. FreeType adds some size to your app.

You can use a fixed world size that corresponds to the pixel sizes of your UI images, eg 800x480, and then design your UI using hardcoded sizes. Once your UI looks correct at that screen resolution, a viewport (like FitViewport) can scale your UI to fit the screen. The important part is that you don't have to do math every time you size or position something.

**Comment by david-mccann** [comment]
Thanks a lot for your clarifications, Nathan! They were very helpful.
