### ISSUE TITLE
new Label(text,style); produces different result than new Label(null,style);setText(text);

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#3072]
I believe those two should produce the same result, yet the current implementation makes the two situations quite different:
1) executes
```
this.text.append(text);
setStyle(style); //calls invalidateHierarchy();
setSize(getPrefWidth(), getPrefHeight());
```
2) executes
```
setStyle(style); //calls invalidateHierarchy();
this.text.append(text);
invalidateHierarchy();
```
This wouldn't be a problem, because behaviourally those two are quite similar - if not for the fact that the two resulting `Label`-s can (and quite often will) have different resulting placements, mainly due to the `setSize()` call on the former and lack of it on the latter.

I honestly don't know which behaviour is the "correct" one, but I reckon that both cases shouldn't generate different Label-s.

As a side note, we could probably use
``` 
       if ( text != null ) {
            if ( text instanceof StringBuilder ) {
                this.text.append( (StringBuilder) text );
            } else {
                this.text.append( text );
            }
        }
```
on https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java#L70 for minor performance optimization (AFAIR libGDX's StringBuilder has some fast `append(StringBuilder)` method).

**Comment by MobiDevelop** [comment]
I don't think setting the text should inherently set the size.

**Comment by NathanSweet** [comment]
I agree with @MobiDevelop. Just setting the text shouldn't necessarily change the label size. The label size is set in the constructor to provide a default size, otherwise you would have to call `pack` or `setSize`, etc. This is normally only used when using the label outside of Table or other groups that do layout.

To get the same behavior, call `pack` after `setText` (well, mostly the same but `pack` calls `layout`). The constructor doesn't call pack [because reasons](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/utils/Layout.java#L46).

It's not clear where you suggest making the optimization. FWIW, libgdx's StringBuilder is mainly used for direct access to the char[] without a copy, I'm not sure the methods are actually faster.

**Comment by FyiurAmron** [comment]
As to the main issue: if setting the text shouldn't set the size, and the constructor has to set the size, we're stuck with having those two with different behaviours then?

As to the optimization:
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/StringBuilder.java#L919 shows that simple `this.text.append(charSequence)` always calls `toString()` on the `charSequence`, which, in case the https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java#L70 constructor is supplied with `StringBuilder` as the `CharSequence` object, will needlessly create a new String (including copying the data from the StringBuilder's array etc, wasting both CPU & mem). This makes using `this.text.append( (StringBuilder) text );` faster, since it calls append on the underlying char array directly.

My suggestion is to replace the line `this.text.append( (StringBuilder) text );` (https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java#L70) with the
```
       if ( text != null ) {
            if ( text instanceof StringBuilder ) {
                this.text.append( (StringBuilder) text );
            } else {
                this.text.append( text );
            }
        }
```
code, directly copied from `setText()` below it.

**Comment by NathanSweet** [comment]
Yes, I think it's ok for the constructor to set the size but `setText` doesn't. The constructor is the only place within any widget where the the widget sets its own size. The reason for that is to help keep layout sane. Widgets provide a min/pref/max size but don't size themselves. Their size is either set either by code you write, or by a parent group doing layout.

There are many actions that can change a widget's preferred size: setting a label's text, adding an item to a select box, etc. Instead of resizing itself, the widget calls `invalidateHierarchy`. When using a layout group, the parent will then size the widget using its new pref size (or whatever rules the parent wants to use). When not using a layout group, the `invalidateHierarchy` doesn't do anything since the parent doesn't care about layout. In that case it's up to you to know about and respond to the widget having a new pref size, eg by calling `pack`, ignoring it, reading the pref size and doing some computation, etc.

As mentioned, setting the size in the constructor is done for convenience when not using a Table or other layout group. Eg without it, you'd create a label and `getWidth` would be zero until you call `pack` or set it yourself. It was this way for a long time, but confused people. It's really better to use a layout group anyway.

Re optimization, gotcha, thanks. I committed a change to StringBuilder to do the instanceof there. I think it's ok for `append(CharSequence)` to try to avoid the allocation, and then we don't need instanceof everywhere `append` is called.

**Comment by FyiurAmron** [comment]
Glad to be of help; I'm closing the issue then.
