### ISSUE TITLE
LWJGL and JGLFW behave differently

### ISSUE THREAD

**Issue by AlchemicTempest** [libgdx/libgdx#3133]
I would like to refer you to this bug I posted on the box2dlights bug tracker:
https://github.com/libgdx/box2dlights/issues/57
(box2dlights gives a black screen with libgdx 1.3 and up and and error with 1.5.5 and up. LWJGL ONLY) [OpenGLException: Cannot use Buffers when Array Buffer Object is enabled]

Since this behavior only appears on LWJGL, I would assume that either the box2dlights guys do something slightly wrong or that LWJGL and JGLFW simply don't behave the same way.

(Using windows 7)

**Comment by xoppa** [comment]
This should be fixed in latest release.

**Comment by AlchemicTempest** [comment]
I suppose you mean upcoming release, since the aforementioned error does occur in 1.6.0 and the nightly right now.

**Comment by xoppa** [comment]
No in latest release (or nightly). If you still encounter the issue then you probably have useGL30 set to true. Otherwise make sure to include [enough information](https://github.com/libgdx/libgdx/wiki/Getting-Help#executable-example-code) to reproduce the issue you're reporting. See https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#using-the-issue-tracker.

**Comment by AlchemicTempest** [comment]
Ah yes, my apologies for not mentioning useGL30. I wasn't aware that it is still experimental.
Indeed I usually use useGL30 = true, which does result in this error. Setting it to false makes it behave as intended without any errors .

**Comment by xoppa** [comment]
box2dlight uses vertex array which are not supported in gles3.
