### ISSUE TITLE
Circle.contains() does not work as intended.

### ISSUE THREAD

**Issue by piotr-j** [libgdx/libgdx#3202]
Perhaps I'm dumb, but Circle.overlaps() doesn't seem to work properly. 
Simple test and working implementation:
https://gist.github.com/piotr-j/6bbc4ae03f7753ce6b6f

**Comment by FyiurAmron** [comment]
AFAIK the error is precisely on https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/math/Circle.java#L175 & L176 and because the squaring is done wrong.

The algo for circle containing is to check if `dist(c1.center, c2.center) <= big.radius - small.radius`; squaring this will make radius order unimportant, thus, those two lines should be
```
		float distCenterSq = dx * dx + dy * dy, radiusDiff = c.radius - radius;
		return distCenterSq <= radiusDiff * radiusDiff;
```
The current code fails because it assumes that `(c.radius - radius)^2 = c.radius^2 - radius^2`, which is obviously not the case. Changing those two lines should fix it.

**Comment by piotr-j** [comment]
Yeah, I couldn't really brain at that point. The overlaps code was adapted from some other stack question without due diligence.

**Comment by xoppa** [comment]
Thanks, looks good. Would you mind sending a PR for it?

**Comment by xoppa** [comment]
Nvm, I applied your fix, thanks!

**Comment by FyiurAmron** [comment]
@xoppa as far as I know, there's no need to check `dst < radiusSum * radiusSum` - since the condition is
```
return (!(radiusDiff * radiusDiff < dst) && (dst < radiusSum * radiusSum));
```
you can easily see it's equal to
```
return radiusDiff * radiusDiff >= dst && radiusSum * radiusSum > dst;
```
now, since radiusDiff^2 is always <= radiusSum^2, there's no need to check the 2nd condition - if dst is <= radiusDiff^2, it's also < radiusSum^2

as such, L175 should be just (using your var names)
```
return radiusDiff * radiusDiff >= dst;
```
