### ISSUE TITLE
Scene2D - Stage calling Batch.begin() & Batch.end() on an instance it doesn't own.

### ISSUE THREAD

**Issue by MonsterOfCookie** [libgdx/libgdx#3317]
Hey!

I was passing in a Batch object into the Stage as I wanted to reduce my draw calls, but I found that if the Stage doesn't own the Batch instance it will still call begin() and end() on it. 

In the draw() method.

```
if (batch != null) {
    batch.setProjectionMatrix(camera.combined);
    batch.begin();
    root.draw(batch, 1);
    batch.end();
}
```

It would be awesome if the Stage instance didn't own the Batch it just assumed that the Batch was ready to render.

```
if (batch != null) {
    if (!ownsBatch) batch.setProjectionMatrix(camera.combined);
    if (!ownsBatch) batch.begin();
    root.draw(batch, 1);
    if (!ownsBatch) batch.end();
}
```

Is this by design or an oversight? I could well be doing something really wrong here and there maybe a better way for me to do this?

**Comment by xoppa** [comment]
I think that would be nice to have. But changing it now might break quite some existing code and I doubt it would really be a noticeable gain in a typical game (unless you have more than one stage (which you shouldn't)). I guess it would be possible to make it configurable and disable it by default, but personally I don't think it's worth to make spritebatch more complicated for this.

Either way, I arguable don't think that not owning a batch should imply that it is properly setup using the correct projection matrix. Although not owning the batch implies not owning the viewport, there is no obvious relationship between the two other than the stage itself. Of course, not assuming the correct projection matrix required to flush the batch and thus defeats the whole purpose of this feature request.

So, while I think it might be useful, personally I'm not in favor for adding this. Especially because you could easily work around this, e.g. something like:
```java
batch = new SpriteBatch() {
    int nestCount;
    void begin() { if (nestCount++ == 0) super.begin(); }
    void end() { if (--nestCount == 0) super.end(); }
    void setProjectionMatrix(Matrix4 v) { if (nextCount == 0) super.setProjectionMatrix(v); }
};
```

**Comment by xoppa** [comment]
sorry, hit the wrong button

**Comment by MonsterOfCookie** [comment]
You are completely right. 

I went down a rabbit hole last night that I shouldn't have gone down. 

Sorry!
