### ISSUE TITLE
Feature request - Vulkan (after released)

### ISSUE THREAD

**Issue by mars3142** [libgdx/libgdx#3344]
It would be nice, if **libgdx** could use **Vulkan** on **Android**, after the release. More about it on http://android-developers.blogspot.de/2015/08/low-overhead-rendering-with-vulkan.html

More background information: http://blog.imgtec.com/powervr/gnomes-per-second-in-vulkan-and-opengl-es

**Comment by badlogic** [comment]
It would indeed be nice, but that would mean the Android backend would no
longer be compatible with the libGDX interfaces that directly expose OpenGL
ES.

**Comment by GreenLightning** [comment]
Maybe it's time for LibGDX 2.0?

**Comment by nooone** [comment]
^

**Comment by xoppa** [comment]
I'm very curious to play around with vulkan. But currently we probably should first make opengl es 3.0 support more robust.

**Comment by JesseTG** [comment]
Vulkan isn't really intended to replace OpenGL anyway, is it?  In that case, why not both?

**Comment by badlogic** [comment]
Are you going to maintain it? :D

**Comment by intrigus** [comment]
You'll get access to Vulkan on the desktop via LWJGL3.
I'm not exactly sure why everyone wants Vulkan, because it's very explicit and verbose ^^

**Comment by SaeedMasoumi** [comment]
With Android N release (preview 2), They made Vulkan a part of the platform.
http://developer.android.com/intl/zh-cn/preview/api-overview.html?#vulkan

**Comment by kerberjg** [comment]
I agree with @SaeedMasoumi; also Google has already started writing docs for the Vulkan API in Android (http://developer.android.com/ndk/guides/graphics/index.html), which already gives us a base to work on.
With LWJGL3 supporting Vulkan as well, all the conditions should be clear. We can at most keep backwards compatibility for OpenGLES for iOS until they make the transition too

Also bigger companies like Unreal Games, Valve and similar are already making the transition to Vulkan. Since Google is starting to support it as well, I think it's our chance to get ahead of the curve and start implementing it in LibGDX.

Also, @xoppa, given how things are going I don't think it's worth to evolve the support for OpenGLES (3.0) as it's already getting obsolete

**Comment by intrigus** [comment]
Vulkan is absolutely **NOT** going to replace OpenGL nor OpenGLES.

I don't unterstand why everybody want's Vulkan. Just because it's 'new'?
Using Vulkan means that a simple rotating triangle demo has [2k loc](https://github.com/glfw/glfw/blob/master/tests/vulkan.c).
If you really need Vulkan for speed, you have to know how Vulkan works. (Why else would you use it)
When you know how Vulkan works, you should also be able to build a cross-platform Vulkan wrapper yourself. (Because Vulkan is extremely verbose and explicit and for advanced programmers)

If you absolutely want Vulkan in libGDX, you are free to fork libGDX and create a PR **AND** to maintain the Vulkan code.

You also have to remember that Vulkan does **NOT** automatically make your game faster. It can even make it slower!

**Comment by cyraid** [comment]
People want Vulkan so they can be in control of the threading themselves, and so it can be a more predictable fps. P.S. how's the progress on this?

**Comment by badlogic** [comment]
Vulkan will never happen in libGDX.

**Comment by cyraid** [comment]
Well I was gonna offer to put in vulkan support myself, and actually make a game editor with libgdx.. but guess with that attitude, I'm out. Enjoy guys.

**Comment by badlogic** [comment]
All rendering code in libGDX is based on the GLES API. Adding Vuokan would
require a complete rewrite of all rendering code, which would essentially
mean an almost rewrite of libGDX.

This is not an attitude problem, but a matter of practicality.


On Jul 4, 2017 5:42 PM, "cyraid" <notifications@github.com> wrote:

Well I was gonna offer to put in vulkan support myself, and actually make a
game editor with libgdx.. but guess with that attitude, I'm out. Enjoy guys.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/libgdx/libgdx/issues/3344#issuecomment-312907537>, or mute
the thread

**Comment by terefang** [comment]
you might watch https://github.com/Think-Silicon/GLOVE as GL/ES over Vulkan
