### ISSUE TITLE
[GWT] FileHandle.readBytes() doesn't work for internal

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#3359]
ver 1.6.4
The method reads and returns only 1 byte of data:
```
FileHandle tfile = Gdx.files.internal(("badlogic.jpg"));
L.d("tfile", tfile + " : " + tfile.exists());

byte[] byts = tfile.readBytes();
L.d("byts", byts.length + " " + tfile.length());
			
Texture img = new Texture(tfile);
L.d("img1", img);
```

**Comment by MobiDevelop** [comment]
For images and audio this is behaving as intended. For files declared as text and binary, the file can be read as bytes.

Will have to defer to @badlogic for the specifics on why this was done this way.

**Comment by JFixby** [comment]
How does the back-end reads textures then?

**Comment by MobiDevelop** [comment]
It loads them into image/canvas elements.

**Comment by JFixby** [comment]
OK, but I assume it needs to read data-bytes for that, right?

**Comment by MobiDevelop** [comment]
No.

**Comment by JFixby** [comment]
So how can I declare a file as binary?

**Comment by Zarandor** [comment]
You have to change the extension to .bin.
I wanted to add an issue "inconsistent behaviours with FileHandle" when I found this one.

Duplicate badlogic.jpg and rename it badlogic.bin.
tfile.readBytes()
tfile.length()
will then work as expected BUT you won't be able to load the bin file as a texture.

On gwt, it seems that everything depends on the file extension.
On Android it doesn't care. It can recognize an image even if the extension has been changed.

For me this issue shouldn' be closed.
FileHandle should work the same on all platforms (internal files case), and if not possible, at least this trick should be mentioned in the Handling file documentation.

I used to have binary files (not images) in my android projects with no extension and obviously FileHandle fails to treat them correctly.

Same goes for UTF-8 encoding text files without the .bin extension. In this case the data loaded are corrupted. "\r\n" -> "\n" and length files differ from Desktop to Gwt. So searching for "\r\n" obviously fails.

It can save days of debugging knowing those !

**Comment by MobiDevelop** [comment]
You can supply your own AssetFilter that will be called for every asset, which allows you to specify whether it should be included as well as the type to apply to it. You don't have to change the extension.

**Comment by JFixby** [comment]
I have custom atlas loader. It works fine on all backends except the GWT, because GWT doesn't support readBytes().

**Comment by MobiDevelop** [comment]
Unfortunately, there are things that just aren't supported with the GWT backend. Sometimes you have to get creative with workarounds.

**Comment by Zarandor** [comment]
I have nothing against being creative to find workarounds, the thing is I chose libGDX, I don't expect it to be perfect I just want to know that issues exists regarding some functions and if there are, workarounds have been found.

The first thing I did when I discovered (I shouldn't have discover it in fact) that readBytes doesn't work on gwt is to look into the java doc of the class to see what I missed, and: no clue, not even a mention to a different behaviour with gwt in the wiki explaining File Handling.

And when I found this issue here, it's marked as closed, meaning that there is no problem or it has been solved. What is not the case.

The main problem here for me is a lack of centralization of the information.

At minimum, known issues or different behaviours on platforms should be indicated in the documentation of the function. 

But the best would be to do something like php Manual which enables to separate the code from the documentation and above all enables users to enlight specific behaviours observed, good practices in the using of the function, issues, workarounds and so on.

How can we help ?

**Comment by Zarandor** [comment]
I would like to have information about AssetFilter, where can I find them ?

**Comment by JFixby** [comment]
http://nexsoftware.net/wp/2013/07/07/libgdx-deferred-asset-loading-with-gwt/

**Comment by Zarandor** [comment]
Ok thanks, my first try to use it didn't work. I'll try harder later.

Here's a suggestion about assets to the libGDX team:
Common assets to all platforms should be by default in core\assets directory and specific ones in each targeted platform. 

Think about the different icons needed for iPhone with their specific names for instance. They should be placed in the ios\assets dir and the resource manager when building a platform should collect the resources in core and add to them the ones of ios. Same thing for all other platforms in fact.

I know I can change the assets dir but what I suggest is to have common + specific assets dirs and in this case, as for interfacing platform dependent code, assets should obviously be in core dir.

I can understand that for historical reason assets are in Android, but currently it makes less sense.

**Comment by MobiDevelop** [comment]
The Android Development Tools for Eclipse still require the current structure.

**Comment by JFixby** [comment]
One byte of data is not a valid output. Should throw some exception about that.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://click4bookings.com/security.php?reqyf>

 

loogie@basicelementdesign.com
