### ISSUE TITLE
Stage keeps propagating handled touch events

### ISSUE THREAD

**Issue by mttkay** [libgdx/libgdx#3368]
I just stumbled over this issue:
http://gamedev.stackexchange.com/questions/106120/stopping-actor-tap-click-event-from-propagating

I believe this might be a bug in `Stage`. Looking at its `touchUp` handler (or any of the other handlers), it doesn't appear to stop events from propagating when listeners handle it, since it makes no attempt to break out of the loop if `Event#isHandled()` is true:
https://github.com/libgdx/libgdx/blob/2bd1557bc293cb8c2348374771aad832befbe26f/gdx/src/com/badlogic/gdx/scenes/scene2d/Stage.java#L348

This means that it's impossible to receive click events in actors and swallow them in order to prevent them from triggering other game behavior in response to taps on the stage.

**Comment by mttkay** [comment]
PS: unless I'm missing something about the intended API contract here I'd happily throw a fix together if that helps?

**Comment by Darkyenus** [comment]
This is intended behavior, read the [javadoc](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/Event.java):
> An Event may be marked as "handled" which will end its propagation **outside** of the Stage (see {@link #handle()}).

To stop the propagation, call `stop()`.

**Comment by mttkay** [comment]
> To stop the propagation, call stop().

That doesn't work either--see my SO post for more details. Just looking at the sources, the loop continues without checking any of `handled/stopped/cancelled` so how would `stop` have any effect?

**Comment by mttkay** [comment]
Actually, I'm also not sure I understand this bit:

> An Event may be marked as "handled" which will end its propagation outside of the Stage (see {@link #handle()}).

Events are never propagated between stages, so what is "outside the stage"?

**Comment by mttkay** [comment]
Also:

> An actor's capture listeners can {@link #stop()} an event to prevent child actors from seeing it.

I don't want to stop the event from propagating to child actors; as said above, I want the event to stop from propagating anywhere. I want to handle it, thus stop its propagation. I think that's what the canonical definition of handling an event is based on previous experience with other event systems.

**Comment by Darkyenus** [comment]
From Stage#touchUp:
> Only {@link InputListener listeners} that returned true for touchDown will receive this event.

It would be a mistake to NOT propagate touchUp to listeners that returned true for touchDown. Your problem is returning true in touchDown when you don't actually want to handle the touchUp.

This is because, if you look carefully, touchUp (among with touchDragged) is a special case - it does not propagate normally but _always_ gets to the listeners which indicated their interest in these events by returning true in touchDown.

**Comment by mttkay** [comment]
Both `touchDown` and `touchUp` in `ActorGestureListener` are void methods. The only thing I have any control over is the event that was fired. Similarly, the actor click handler that I would like to handle the event doesn't get `touchDown`, it gets `clicked`, which is equally void.

Could you clarify where it is I should be returning/handling `touchDown`?

**Comment by Darkyenus** [comment]
Ah, I assumed InputListener. The returning is done in `handle(Event)` method of `EventListener`. `InputListener` returns whatever its (usually overriden) `touchDown/Up/whatever` returned. For `ActorGestureListener` this is slightly more complicated, because it does not support "not detecting gesture" and always returns true. Therefore, you will have to override the [`handle()`](https://github.com/libgdx/libgdx/blob/2bd1557bc293cb8c2348374771aad832befbe26f/gdx/src/com/badlogic/gdx/scenes/scene2d/utils/ActorGestureListener.java#L88) method and add custom gesture-filtering logic.

**Comment by NathanSweet** [comment]
Explanations by @Darkyenus are correct.
