### ISSUE TITLE
AssetManager refcount issue

### ISSUE THREAD

**Issue by VinceAngel** [libgdx/libgdx#3373]
Hi,

I found an issue in the AssetManager refCount management : https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/assets/AssetManager.java#L396

Here, if the asset is duplicated, the refcount should be incremented

I did not make a PR because I'm not 100% sure of my analysis, but I'm sure a Gdx master could confirm or not the issue here quickly.

Thanks.

**Comment by xoppa** [comment]
I don't see why duplicate dependencies should be refcounted more than once, that would be making it more complicated at no gain. What exactly is the issue you're having? Can you provide a sscce for it?

**Comment by VinceAngel** [comment]
The issue is about loading failure : when a file referencing more than one time the same dependency failed to load (whatever is the reason) the assets are unloaded according to the refcount.
So, the dependency is referenced with count of 1 (2 or 3 in reality) so the dependency is unloaded. When the loop continue, the same dependecy appears again, but is not referenced this time in the dependency map, so an exception is raised here https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/assets/AssetManager.java#L182

**Comment by xoppa** [comment]
Would you mind to include a [sscce](https://github.com/libgdx/libgdx/wiki/Getting-Help#executable-example-code) so we can see the actual issue.

**Comment by VinceAngel** [comment]
Here is a sample : https://github.com/VinceAngel/GDXTests/tree/master/Issue_3373

The g3dj file will not load because node's material ID do not match in order to fail loading and make assets beeing unloaded.

**Comment by xoppa** [comment]
Thanks, I see what you mean. I don't think that an asset should depend more than once on another asset though. So I'd say that this is an issue of the model loader. However, the `getDependencies` method does return an `Array`, so perhaps other (custom) loaders have the same problem. That could be fixed by changing it to `ObjectSet`, but that's probably going to break quite some code. Therefor I guess that removing any duplicate dependencies in the `AssetLoadingTask` class might be a good and simple way to fix this. Not sure if that's the best way to deal with this though.

**Comment by VinceAngel** [comment]
It's a start, I do not have a good overview of the loader and AssetsManager to be relevant but I think we should avoid the exception to be raised for a simple reason : the error listener is not called due to that "shortcut" in the `unload`.
