### ISSUE TITLE
Character following "[]" in scene2d labels has wrong width

### ISSUE THREAD

**Issue by ghost** [libgdx/libgdx#3378]
I wrote a [small reproduction class](https://gist.github.com/horse-mans/ebbb6739b2234460d07e) for this. Tested in libgdx 1.6.5 on OS X 10.10.5.

The basic idea is that when using color markup in scene2d labels, the character immediately following the "pop color" control code, `[]`, either doesn't have its width set correctly, or is not offset the correct amount from the character before the control code. The problem isn't confined to fonts with fixed width glyphs specified, but it does help illustrate it better.

The above code run with the call to `font.setFixedWidthGlyphs` commented out: Small but noticeable difference. This difference is more pronounced on monospace fonts (even with no fixed width glyphs specified).

<img width="512" src="https://cloud.githubusercontent.com/assets/6292811/9505635/d7a791a0-4c43-11e5-8a89-7370ac17af11.png">

With the call uncommented:
<img width="512" src="https://cloud.githubusercontent.com/assets/6292811/9505672/132425a4-4c44-11e5-8e87-616fde909d74.png">

Note:
1. How more pronounced the effect is the more `[]` controls are in the string, and
2. The amount of space between the last 't' and the first period on each line.

This may or may not be related to #3239, but my hunch is it's a different subtle bug somewhere else in the glyph width calculation :-)

**Comment by NathanSweet** [comment]
GlyphLayout parses text into a number of GlyphRuns. A glyph run is a list of Glyphs and their positions. Each glyph run has the same y coordinate and color. GlyphLayout uses BitmapFont#getGlyphs to convert characters from the text into glyphs to store in the GlyphRun. `getGlyphs` provides a place to "shape" the run. By default this lays out the characters using kerning, but BitmapFont can be subclassed to choose which glyphs are displayed based on surrounding characters (eg, for [Punjabi](https://en.wikipedia.org/wiki/Punjabi_language)). Rendering a glyph layout means drawing each of the glyph runs.

Because a color change starts a new glyph run, `getGlyphs` doesn't apply kerning between the characters. This issue and #3166 are the downsides to how GlyphLayout works. Unfortunately this is not easy to fix.

**Comment by NathanSweet** [comment]
Latest libgdx does kerning between color runs on the same line.
