### ISSUE TITLE
Suggestion: add setAlpha() for Actor

### ISSUE THREAD

**Issue by rotter** [libgdx/libgdx#3380]
Quick/simple suggestion, as I end up doing this manually all the time:

Add the following method around line 631 of Actor.java.

File/line: https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/Actor.java#L630

Method:
public void setAlpha (float a) {
	color.set(color.r, color.g, color.b, a);
}

**Comment by FyiurAmron** [comment]
a) why not simply

    public void setAlpha (float a) {
        color.a = a;
    }

?

b) why don't you use `actor.getColor().a = newAlpha` ?

**Comment by rotter** [comment]
Hey.

Yeah, your solution mentioned on a) seems great.

Regarding b), yeah, its possible, but:
- not intuitive, as I shouldnt need to know internally how it's implemented
- since theres a setColor, why not a setAlpha?
- Sprite for example has both a setColor and a setAlpha

**Comment by FyiurAmron** [comment]
1. since the alpha is set as a `Color` component anyway, you *should* know how it's implemented before using it; otherwise how you may know that using your proposed `setAlpha` may be muted by a following call to `setColor`?
2. because of Single Responsibility Principle? If alpha is set in `Color` anyway, there shouldn't be two API methods allowing to set it.
3. Sprite is a *completely* different animal here; it doesn't store it's color information in Color variable, using a packed format instead - see https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/Sprite.java#L565 for details.

Once again - no. If you want to create a utility method for it - nobody's going to stop you. Bloating the API with redundant method ain't a good idea.

**Comment by rotter** [comment]
Ok, no problem, not my call, it was just a suggestion. You can close it if you want (I won't close it, I still think it's a valid suggestion, but it's not my call).

But as a user of the interface, I find it weird to not have a setAlpha, since it's a very VERY common need for my games at least (I probably need the setAlpha more than setColor to be honest). I can work around it, I have always worked around it, I just think a direct method would make it much clearer.

And regarding Sprite being different internally - again, I dont care about the inner implementation. I simply use the library/interface. And that interface has setAlpha, while Actor doesnt. It doesnt make sense.

**Comment by xoppa** [comment]
From a user (at first glance) perspective I can see that having a `setAlpha` method would indeed be useful.

However, as @FyiurAmron correctly pointed out, alpha is indeed part of the color (technically it doesn't matter how you specify it, but eventually the color will be packed including the alpha into the color vertex attribute). In this particular case `Actor` provides direct access to its `Color` instance (which might not be the best way to expose such member, but that's not the issue here). Technically there is no direct need for a `setAlpha` method.

From an API view, you haven't convinced me that having such shortcut method is a good idea. In fact it might even cause confusion: e.g. someone might set alpha to 0.5 and then color to white and find the alpha to be unexpected overwritten.

`Sprite` has indeed a `setAlpha` method which is indeed arguable, but that's not the issue here. That doesn't mean that we should add `setAlpha` methods to every other class.

**Comment by rotter** [comment]
I have now probably wasted more time here than what I would have saved in my lifetime if there was a direct setAlpha method... but discussion is always fun :)

Anyway, it's hard to convince that such as method is *needed*, because it isn't needed - it would be a convenience method, or a method to make the interface more clear/complete: as if all entities that deal with colors would implement an imaginary ColoredThing interface which has methods such setColor, getColor, setAlpha, getAlpha, etc, no matter the inner workings of that class, such as having a Color entity or using vertexes or whatever.

But talking about the inner workings of the class, if setAlpha makes no sense on Actor, then:
- setColor(newColor) also doesnt make sense as one can always do getColor().set(newColor)
- and setColor(r,g,b,a) also doesnt make sense as one can do getColor().set(r,g,b,a)

Those 2 methods are there for either convenience (which applies to setAlpha also), or to hide the inner implementation (which also applies to setAlpha).

**Comment by xoppa** [comment]
I already noticed that is arguable, that's not a reason to add a `setAlpha` method to `Actor` though. Btw, I never said it doesn't make sense.

Please send a pull request if you have a method to provide this convenience method without adding potential confusion. So we can have a look at it and review it. Other than that I don't expect anyone is going to implement it for above reasons.

Either way, can we close this issue? Please open a PR if you like.

**Comment by rotter** [comment]
Yeah, sorry for not making it clear, that comment regarding the inner workings of setColor was mostly to Fyuir.

I can do the pull request, but I would do it with the mentioned implementation by Fyuir. I have to be honest that I dont see clearly the potential confusion mentioned. If it's regarding the example you mentioned of setAlpha(0.5f) and then setColor(1,1,1,1) clearing the alpha, well it may happen, but it's definitely a very basic fault (since to call setColor one *MUST* pass an alpha value as parameter, what would the person expect to happen?), and it would probably happen anyway (the person would find a way to set the alpha through getColor().a).

Yes, we can close this np, but Im still far from convinced that not having Actor.setAlpha is better for the API than having it.

**Comment by FyiurAmron** [comment]
@rotter a final comment on this matter:

`setColor()` is intended to complement `getColor()` as a proper getter/setter pair. As such, both `setColor()` methods ain't "convenience" methods per se - the `setColor(r,g,b,a)` is there for *speed and heap/GC reasons* (when you don't want/can't create a new object instance on each call and/or it makes no sense, because you have the values by themselves), and `setColor(color)` is there to create a valid getter/setter pair with `getColor()`.

Your basing your point on the fact that they are there to either "hide implementation" or "for convenience"; that premise is not valid by itself, and the point based on it ain't valid either.

Also, `setAlpha()` would require `getAlpha()` to conform to getter/setter idiom properly. Further, why not add `setColor(r,g,b)` to just allow keeping old alpha value intact? etc.

*prefer composition over inheritance*, that's why. `Color` object already handles it, conforming to https://en.wikipedia.org/wiki/Single_responsibility_principle .
