### ISSUE TITLE
Mesh with Integer Indices

### ISSUE THREAD

**Issue by wsrdzg** [libgdx/libgdx#3386]
At the moment Mesh uses short for indices. Because Java has no unsigned short this means you can only use 2^15 vertices. Therefore you can't render a big world at once even if it all uses the same Material. I could render my complete game world in one render call, but instead I have to use over 100. That is really bad for the frame rate.

An Mesh with Integer Indices would solve this problem?

**Comment by xoppa** [comment]
Currently, `Mesh` can contain 32k vertices (actually it is 64k, because signed indices are simply cast to unsigned, but that's not very practical). On a 800x480 screen, that is ~12 pixels per vertex (around 120 pixels on 2500x1500). If you need more detail than that, then it is no problem to have a few draw calls.

We could go through some hoops to support integer indices (which surely shouldnt be the default). I doubt that there is a good use-case where using integer indices is a good solution. Saying that you need over 3,276,800 vertices (which around the number of pixels a 2500x1500 screen has) is a good indication that you're doing something wrong.

Keep in mind that the vertex shader is always executed for every vertex (even if it turns out to be not visible). Make sure to implement proper (frustum) culling, so you dont render meshes of which you know that they aren't going to be visible. And if you really need that much detail, then use a normal map instead.

Will reopen if you add a valid use-case for this [feature request](https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#feature-requests).
