### ISSUE TITLE
Stuttering when not running in fullscreen

### ISSUE THREAD

**Issue by tobloef** [libgdx/libgdx#3405]
**Background**
For some time I have been facing a problem where my game would stutter once per second or so. I searched far and wide for a solution, as I thought I was doing something wrong, until I came upon [this thread](http://badlogicgames.com/forum/viewtopic.php?f=11&t=8909) on the forums. It was here someone suggested that I put my game in fullscreen, which completely fixed the problem. Problem is, some people might want to play in windowed mode.

**Steps to reproduce**
I have a very simple project to demonstrate the bug. Run this on desktop and you should see the stuttering. Note: It might not occur on all computers, but I know I'm not the only one having this problem.

``` java
public class LagTest extends ApplicationAdapter {
    SpriteBatch batch;
    Texture dot;
    float x;
    float y;
    int speed;
    float dotWidth;
    int screenWidth;

    @Override
    public void create () {
        batch = new SpriteBatch();
        dot = new Texture("dot.png");
        x = 100f;
        y = Gdx.graphics.getHeight()/2f - dot.getHeight()/2f;
        speed = 500;
        dotWidth = dot.getWidth();
        screenWidth = Gdx.graphics.getWidth();
    }

    @Override
    public void render () {
        Gdx.gl.glClearColor(0.2f, 0.4f, 0.8f, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.begin();
        batch.draw(dot, x, y);
        batch.end();
        if (x < 0) {
            speed = 500;
        } else if (x > screenWidth - dotWidth) {
            speed = -500;
        }
        x += speed * Gdx.graphics.getDeltaTime();
    }

        public static void main (String[] arg) throws Exception {
        LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
        config.width = 1920;
        config.height = 1080;
        new LwjglApplication(new LagTest(), config);
    }
}
```

I can only assume this is a bug in libGDX, as the "game" will run fine in fullscreen, but not in windowed mode. Please let me know if I'm wrong.

**Comment by MobiDevelop** [comment]
As far as I am aware, this is an LWJGL problem.

**Comment by TobLoef** [comment]
Ah. Should I remove this issue then?

**Comment by xoppa** [comment]
Don't use `int` for world coordinates. In fact, don't use `int` at all (except for indices etc.). I'm surprised this works at all on desktop (which is probably because you have v-sync enabled and have a huge speed value). This is an issue tracker, please use the forum or irc if you need help.

If you still think there's an issue with libgdx then please provide the required information and the steps you took to verify that it is indeed an issue with libgdx. Will reopen in that case.

**Comment by TobLoef** [comment]
I'm sorry, but a fair bunch of people have said that this was probably a bug. Me accidently using integers in my example has nothing to do with it. I have a hard time proven that it is indeed a bug, but I have tried to make a simple project as possible to demonstrate.

**Comment by xoppa** [comment]
Ok, will reopen. Your initial issue report was clearly an issue with your code, which is why I closed the issue. Please make sure that you actually verify the code that you post.

Also, please include the main method, especially because the config might be important in this case. See: https://github.com/libgdx/libgdx/wiki/Getting-Help#executable-example-code.

However, as @MobiDevelop said, it is possible/likely that this is a lwjgl issue and that we can't do anything about it.

**Comment by TobLoef** [comment]
Great. Thanks a bunch. I just wanted to let you know of this problem in case you hadn't already heard about it.

**Comment by Voltasalt** [comment]
I'm seeing some tiny stuttering in pretty much all my gdx games too, this is definitely a problem.

**Comment by badlogic** [comment]
Jupp, it's a problem with the way LWJGL has to do synching in windowed mode. It's essentially using a timer, not synching to the refresh rate. I hope the switch to LWJGL 3 (soon) will fix this issue.

**Comment by NathanSweet** [comment]
I doubt a windowed app can use vsync even with LWJGL 3.

**Comment by badlogic** [comment]
LWJGL3 backend has been out for a while. Closing as LWJGL2 won't get any further updates.
