### ISSUE TITLE
[feature request]Does libgdx need a scripting language? Ideas and possible contributors as well as possible problems.

### ISSUE THREAD

**Issue by jacksondus** [libgdx/libgdx#3444]
Libgdx has a JSON parser and a XML parser. It is my opinion that it should also feature a wrapper that supports the creation of basic scripts, either using a unique language or a language that already exists. I would be willing to write some of the code for this, but before I commit to thousands of lines of coding I would like to get an idea of how many people would use this.

Many great game engines and frameworks use scripting languages to avoid the need to recompile games when making changes. It is, as a matter of fact, [recommended to use a scripting language](http://gamedev.stackexchange.com/questions/2913/why-do-we-use-scripts-in-development/2914#2914) for large projects. While most libgdx projects are small, some can be pretty big. For example, I was compiling my game to test it and it took fifteen minutes to complete. This is annoying, and I toyed around with the concept of creating my own scripting language, but the idea of debugging 2000+ more lines of code by myself was daunting.  It seems better and more efficient to break the work up between multiple devs than to try and accomplish such a task alone.

I want to keep with the reusable and extendable tradition of libgdx and have drafted the following (rough) graph of how the engine could work;

![image](https://cloud.githubusercontent.com/assets/10172349/10140923/7483b158-65cf-11e5-9cbd-802deb7aa736.jpg)

The Parser would be an interface to handle the syntax of the script while the Interpreter (an abstract class and the real meat) would handle expressions and logic. The java implementation would, of course, be custom implementations of the interfaces which tie together into a controlling class which can be instantiated in your create method and implemented in your render method.

Would this fit well with the main project? Should I add it to the main project?  Any ideas on how to implement it?

**Comment by FyiurAmron** [comment]
Reinventing the wheel yet again? What's wrong with any of: Lua, Scala/Groovy, JavaScript, Python, Ruby, Lisp etc, via either direct Gradle inclusion/preprecession or e.g. `javax.script` (http://docs.oracle.com/javase/7/docs/technotes/guides/scripting/programmer_guide/) or any other standard-compliant solution?

**Comment by Tom-Ski** [comment]
Pretty much. If you really wanted to create some more LibGDX specific language then go for it, it would stay as a third party extension though.

**Comment by nooone** [comment]
I've recently used Javascript (Rhino) with libgdx. Worked pretty well also on android, because with the proprietary mozilla API (not javax.script), it's possible to turn off optimizations and set language levels.

**Comment by xGnoSiSx** [comment]
What's wrong with java? The entire modding community for minecraft adds to the game with extra classes, why introduce another language?

Is it the steep curve for the people to build a jar? or the fact that you can't distribute the java compiler with the game? I'd love to hear your thoughts.

**Comment by xoppa** [comment]
I think that you should use whatever is available. Implementing (and maintaining!) an own scripting engine is in most use cases unneeded.

That said. A time ago [I looked into adding scripting](https://gist.github.com/xoppa/95dbc55a0b4c27818b0e) support, because we still have a problem with managing the shaders. Adding a small (graphical/programmable) layer might make it easier to manage and extend uber shaders. Preferable while keeping it possible for users to copy paste glsl code (the language should be similar to glsl). Ofcourse that adds some specific requirements and it doesn't necessarily have to actually compile/execute, just generate the final shader. Fixing this shader problem is still on my todo list, but lack of time...

So, if anyone is going to make a custom scripting engine, then keep this in mind ;)

**Comment by xGnoSiSx** [comment]
xoppa, you kicked it up another notch by talking about scripted glsl shaders... XD

**Comment by jacksondus** [comment]
@xoppa I am actually currently working on the language. I have basic if/then and (semi-working) functional syntax working with regular expressions. I will keep that in mind when I post the code on GitHub and add it if I can. I will have to read up on glsl shaders, though first. Before that though I will have to fix my functions (weird bugs occur when calling functions from within the script that are not predefined in Java classes), add support for math operations (gonna be difficult I think, especially without causing the script to slow performance down), and touch up on many minor bugs that make it impractical to use. As it is it is not the fastest possible implementation, but I do intend on releasing it as open source after I play around with it in my game.

I don't feel comfortable with releasing my code yet, as I want to fix some things first, though, such as add an "Object" system to my script to make better abilities for it. I am up to my head in things I need to do before I release it as open source (because I just want to get an open source extension started and then open source it for people to do with as they please). It turns out that this is a fun challenge.

@FyiurAmron I looked at your repo and studied the code but (honestly, no offense intended) I had trouble reading your naming scheme. I am dyslexic and the lower cases combined with the "_" were killing my eyes. I do have one question though, why did you use chars? I am using Strings and the standard libgdx file system. Are chars faster? Do they create less clutter? I am using `java.utils.regex.*` to parse the scripts and they seem (mostly) fine after I debug.

@xGnoSiSx I want to add a scripting language to stop from having to recompile my project every time I fix a few bugs. I could probably figure out how to include a java compiler if I wanted to, but the purpose is not explicitly modding support.

**Comment by davebaol** [comment]
Regular expressions? It sounds pretty weird to parse a scripting language. Unless it has a very basic syntax and you don't mind performance.
Regular expression are good for the lexical part (identifiers, numbers and so on). Usually for the syntax you use grammars.  
I'd suggest using Ragel.

**Comment by FyiurAmron** [comment]
@jacksondus the code has a severe C legacy, so it's naming convention is mostly C. `String` is just an immutable wrapper for `char[]` - you won't see `String` used as a base type anywhere in any serious tokenizer/lexer, since the most basic data struct appearing there is a single `char`. To be able to do any real tokenization/parsing/lexing, you'll need a properly constructed state machine. https://en.wikipedia.org/wiki/Ragel (suggested by @davebaol) is indeed a very stable and quite standard solution, easy to implement and maintain. Alternatively, you can use https://en.wikipedia.org/wiki/JavaCC , http://www.antlr.org/ or any other tool. If you're using regexes, both the extend of your lexical analysis and the performance will suffer.

Creating and maintaining own lexical/syntactical analysis framework is IMO just asking for development hell and Yet Another Abandoned Project, unless you have a couple of good developers willing to works a couple of years for free.

**Comment by jacksondus** [comment]
@FyiurAmron I apologize for the closes and reopens. I feel the need to say that tokenizing with regex and then building lexeme's and compiling them into a parse tree (which is what is actually executed as it is traversed and actually what I meant by regex parsing). And referring to your dyslexic joke - following that logic don't you see the possible risk of a dyslexic writing code in general?

**Comment by MobiDevelop** [comment]
You don't need to reopen to comment. Also, it feels like this conversation is no longer relevant for libgdx so should probably be moved elsewhere.
