### ISSUE TITLE
Issues requiring a major release that won't be fixed anytime soon

### ISSUE THREAD

**Issue by davebaol** [libgdx/libgdx#3494]
What is this? Simply said, this is:
- an invitation not to open new issues implying wide API breakage
- a single collection point for such issues
- a gentle way to let the dev team absorb the idea that sooner or later a major release will be needed :relaxed: 

This is what I collected so far:
- [Immutable Color and Vector](https://github.com/libgdx/libgdx/issues/3424)
- [gdx-utils](https://github.com/libgdx/libgdx/issues/2793)
- [Logging](https://github.com/libgdx/libgdx/issues/1311) (BTW I think that a logging system separated from `Gdx.app`, for instance `Gdx.logger`, would be much easier to customize)
- [Vulkan](https://github.com/libgdx/libgdx/issues/3344)
- [For consistency's sake use Array in place of ArrayList](https://github.com/libgdx/libgdx/pull/347)

**Comment by nooone** [comment]
How to add new ideas/suggestions to this, without opening new issues? Via comments?

I have two suggestions:

#### Switch the relationship between `Camera` and `Viewport`
A camera naturally has a viewport, not the other way around. This would make for a more natural API. The current implementation was done the way it is to keep the API backwards compatible.

#### Exchange `LifecycleListener` with `ApplicationListener`
Extensions or other 3rd party additions would be able to hook into the lifecycle directly, which would add new possibilities.

**Comment by davebaol** [comment]
@nooone 
Your suggestions sound interesting to me

**Comment by JesseTG** [comment]
Why not just make a new label called `libgdx-2.0` or something?

**Comment by davebaol** [comment]
We've already discussed this on irc and decided not to create such a label to avoid useless flooding and hype, since a major release is not planned at all.

**Comment by JesseTG** [comment]
Not even a less misleading tag like `major-change`?

**Comment by cypherdare** [comment]
Suggestion: SequenceAction and ParallelAction `.addAction` should call `setTarget(this.target)` on the action that is added. When constructing a complicated sequence involving multiple actors, it would be nice not to have to manually call `setTarget` on each and every action within all the sub-sequences, etc. It results in about three times as many lines of code.

**Comment by nooone** [comment]
Something else I just stumbled over in the API...

`AssetManager` can currently only work with a certain type of FileHandles. This by itself is a quite annoying fact, because if I have internal assets and external assets, I will now need to have two different managers to load/store them.

By default an AssetManager has an InternalFileHandleResolver. I can create `AssetDescriptors` with any kind of FileHandle though. If I create one with an external FileHandle and supply that to a default AssetManager, it is "internally transformed" into an internal FileHandle. This is totally unexpected API-wise and should be changed.

    AssetManager assetManager = new AssetManager();
    FileHandle external = Gdx.files.external("path/to/pic.png");
    external.exists(); // true
    assetManager.load(new AssetDescriptor(external, Texture.class));
    assetManager.finishLoading(); // Crashes with GdxRuntimeException: File not found: path/to/pic.png (Internal)

**Comment by kerberjg** [comment]
Speaking of Vulkan, it's getting official support starting in Android N. Already in Google's Android dev docs

http://developer.android.com/ndk/guides/graphics/index.html
http://www.theinquirer.net/inquirer/news/2454575/android-n-developer-preview-2-arrives-with-vulkan-support-and-new-emoji
https://developer.nvidia.com/vulkan-android

**Comment by nhydock** [comment]
Something to bring up: LWJGL3 has switched over to requiring at least Java8 to build and run.  Since libgdx has the LWJGL3 backend, I was wondering if is this going to impact libgdx's build process significantly.  Android has already switched over to using OpenJDK8 on newer versions of android, but with KitKat still has a large market share of android.  At this point in time I feel LibGDX should require at least Java8/9 to build and run already with how old Java 8 already is, with people who wish to support older platforms having to use old libgdx.  For those who need a Java8 JRE to package with their games, they can use something like Zulu on desktop.

**Comment by sjosegarcia** [comment]
I also want to be like all then other cool kids on the block and use
lambdas.

**Comment by MobiDevelop** [comment]
> Android has already switched over to using OpenJDK8 on newer versions of android, but KitKat still has a large market share of android

These newer versions are Android N - which is still in developer preview.

**Comment by intrigus** [comment]
You are free do to what ever you want.
If you want Java 8 features, use them.
Libgdx doesn't force you to not use Java 8 features, you just won't be able to use Java 8 on all platforms :)

**Comment by sreich** [comment]
not to spam, but if you do not know this and you are restricted to < java 8 (*cough* android), you may be interested in kotlin to alleviate such complaints. does a lot of things better than even java 8 does, but still seamlessly runs on java6 onward. actually even though i can target the newest java, i still much prefer kotlin, albeit its smaller community is a big disadvantage. works well with libgdx :)

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://kmrlure.com/artist.php?fi3b3>

 

loogie@basicelementdesign.com

**Comment by nhydock** [comment]
in the same vein as extracting out gdx-utils into a reusable submodule, I feel libgdx should also look into the idea of separating out Scene2D and its GUI system into its own submodule, largely because people might want to use their own or an alternative GUI framework a top libgdx, and the redundancy would just add bloat to their apps.

**Comment by kerberjg** [comment]
@nhydock Would make sense. There aren't so many cases where it's used, given the total number of games/apps made with libGDX

**Comment by obigu** [comment]
Not sure if this applies here as it's not an API breaking issue but a project folder structure/organization change.

###  **Default Android module to Idea/Android Studio folder structure**

My understanding is that the current Android module folder structure for libGDX projects is based on the pre-Gradle Eclipse based folder structure to be able to support both Eclipse and IntelliJ.

These are the main differences:
http://codebin.co.uk/blog/android-studio-vs-eclipse-folder-structure/ 

Since Android development decided to drop support for ADT Eclipse plugin some time ago and most people should have already migrated to IntelliJ, I wonder if it's the time to adopt their standards on the Android module.

**Benefits**
- **Multi Flavour builds**: With the current folder structure taking advantage ok the awesome Build Variants and specially Build Flavours (https://developer.android.com/studio/build/build-variants.html) is not possible (at least not easy without workarounds, I've personally been unsuccessul trying to set up flavoured builds for building separate APK with different classes, manifest and resources for both Google Play and Amazon. Switching to recommended folder structure and it worked straightforward).

- **Convention over configuration**: Using defaults helps making configuration less verbose and easier to find relevant (that works as it is) documentation/examples online

**Implications**
- Changes are minimal for new projects (just need to change the project template and build.gradle) to use the new folders (src/main/java instead of src/ for java resources, etc...).

- Breaks Eclipse support (which the Android team has already decided anyway)

**I'm able to provide support for this as well as creating a PR if you think it would be an improvement.**

**Comment by Tom-Ski** [comment]
ADT is still being maintained, and there still a lot of developers that rely on eclipse as their IDE, and it is still a viable option for android development. (Not that I would personally recommend it). There isn't much point in the huge breaking change just to make things slightly more convenient for flavours, it also is already possible at the moment with the current structure with not too much adjustment required.

**Comment by obigu** [comment]
Well, I don't know how many people are still developing Android apps using Eclipse but the ADT plugin is not maintained by Google anymore and the Open Source Andmore community that has taken over is not very active on it (https://projects.eclipse.org/projects/tools.andmore), in my opinion it's just a matter of time.

In any case that's why I was suggesting libGDX 2.0 for the change, if people are developing Android apps with Eclipse they can still be using 1.9.X, otherwise if they want to use 2.X it would be a good time to migrate.

Regarding breaking compatibility, existing project wouldn't notice when upgrading to 2.0 from 1.9 as the build.gradle is generated on project creation as it currently happens any time a change is applied to the project template.

It's indeed possible to set up simple flavors with the current structure but when increasing in complexity problems arise. When you say it's currently possible to have flavored build with the current project structure "with not too much adjustment required" are we talking about complex flavors with for instance hierarchical java resources, resources, manifest, etc...? Can you be more specific or provide an example? In my experience it's not been the case, I can provide the details if needed.

**Comment by Tom-Ski** [comment]
If the entirety of the developers that are still using eclipse move over to an alternative by the time 2.0 ever happened, then sure, but there are still a lot of people that use it for development and I don't see that changing any time soon. You only have to visit the forums or sit in the irc to see them.  It would mean that people wanting to update their project, if any of the scripts change for any reason, they would have to do it manually instead of generating a new project and copying source.  People aren't too familiar with Gradle in general, and nor should they need to be.

The default application has a very basic structure in terms of the gradle build, and it doesn't take much effort to change this, If you are having a specific issue with something you are trying to achieve make a forum post and I can take a look.

**Comment by ThomasWrobel** [comment]
*cough*
I'm developing crossplatform libGDX projects with eclipse - which import
two other cross platform Java projects of mine.
Not sure I fancy having to switch between multiple IDEs to develop
something. (and if we go down this road, where does it stop? Will
eventually there be specific IDEs for each target platform?) :-/

--
http://lostagain.nl <-- our company site.
http://fanficmaker.com <-- our, really,really, bad story generator.

**Comment by ThomasWrobel** [comment]
(for what its worth I dont use Scene2D though)


--
http://lostagain.nl <-- our company site.
http://fanficmaker.com <-- our, really,really, bad story generator.

**Comment by cypherdare** [comment]
@obigu I've been using build flavors with LibGDX for almost two years. [Example project](https://github.com/CypherCove/DoubleHelix/blob/master/android/build.gradle).

Look at the `sourceSets` enclosure for how I'm doing hierarchical resource files for the free version of the app.

**Comment by obigu** [comment]
@Tom-Ski Makes sense. If 2.0 takes long though I think it's worth considering, as you say people should not need to know Gradle so using defaults and simplifying configuration files will make their lives easier.

@cypherdare Thank you for the example, it's really helpful. I think you are right that defining the `sourceSets` relevant folders for each flavor pointing outside the `src` folder it's possible to have complex build cases. It's config heavy and less organized (that's may be subjective) but it should work.

On another note I've seen in your particular build.gradle you can simplify the product flavours definitions by defining any shared configuration inside the `defaultConfig` section (like `applicationId` or default values to the build properties). If a flavour needs a different value it can just override it.

**Comment by ForsakenHarmony** [comment]
@ThomasWrobel you can use IDEA for everything though, android developers didn't stop eclipse support without a reason, just saying

**Comment by ThomasWrobel** [comment]
@Ashley You can develop GWT web apps in it? Does it support super dev mode?
(live previewing/updating in a browser)

--
http://lostagain.nl <-- our company site.
http://fanficmaker.com <-- our, really,really, bad story generator.

**Comment by ForsakenHarmony** [comment]
@ThomasWrobel have you even looked it up? 
https://blog.jetbrains.com/idea/2014/09/intellij-idea-14-brings-better-gwts-super-dev-mode-support/

**Comment by ThomasWrobel** [comment]
True. I am a idiot.
That said , gwt is a pro feature, so Id need to be quite serious about
switching before making a investment.

--
http://lostagain.nl <-- our company site.
http://fanficmaker.com <-- our, really,really, bad story generator.

**Comment by cypherdare** [comment]
I've have a minor one... PerspectiveCamera only uses `Camera.viewportWidth` and `viewportHeight` for calculating aspect ratio, so there's no reason to hang onto the parameters. OrthographicCamera uses them for the size of the viewable area, so the variable names are confusing. So they should be renamed to just `width` and `height`, and they should only be available in OrthographicCamera. PerspectiveCamera can store an `aspect` parameter instead.

Regarding Vulkan, I think some hooks could be added to LibGDX 1.x and an extension created so we don't have to wait for the (never coming) 2.0. 

Regarding immutable Color and Vector--that would make for very verbose code. Perhaps the existing static final Colors could be made into color integers instead to avoid the issue entirely. I don't think the static final Vectors are used much, so they could simply be removed.

**Comment by badlogic** [comment]
I'm not sure what people expect from Vulkan. It's an extremely fickle API and the gains for what 99% of libGDX users do (2D) will most likely be nil.

**Comment by kerberjg** [comment]
Speaking of Java 8 though, things have changed since the release of Android 7.0 (previously N), namely **most Java 8 features are now supported on older Android versions** thanks to Google's new "Jack" toolchain, specifically:

**Features requiring Android 6.0 *and lower*:**

* Lambda expressions
* Method references
* Type annotations

**Features requiring Android 7.0 *and newer*:**

* Default and static interface methods
* Repeatable annotations

All we need to do is to update our `build.gradle` files to allow source compatibility with JDK 1.8 and to tell the Android SDK to build with Jack (details in the link below) and we're ready to go.

I don't see why we shouldn't take advantage of new features of Java 8 (specifically the new Stream utlities, which could be very useful on modern multi-core mobile devices) instead of still using a 10-year old Java version. I'm ready to take care of the necessary PR myself, as long as we all agree on this.

source: https://developer.android.com/guide/platform/j8-jack.html

**Comment by badlogic** [comment]
Jack is broken in all kinds of funny ways. RetroLambda does the same thing,
I'm OK with (optionally) supporting that in gdx-setup.

**Comment by Br0lici0us** [comment]
> Replace LifecycleListener with ApplicationListener

> Extensions or other 3rd party additions would be able to hook into the lifecycle better (mostly via the 
> additional render callback), which would add new possibilities.

Would it be hard to implement this in the core code? Since there is already something similar (LifecycleListener).

**Comment by shatterblast** [comment]
Android is dropping support for JACK.  Can we close this, please?

**Comment by shatterblast** [comment]
Android recently dropped support for JACK.  Older versions of Android just should not put it into use.

LWJGL offers support for Vulkan over roughly the last two years.

**Comment by shatterblast** [comment]
Can we close this, please?

**Comment by intrigus** [comment]
LWJGL2 does not and will never support Vulkan 
Color and Vector are still mutable.

**Comment by shatterblast** [comment]
Have you even tried?  LWJGL2 supports Vulkan.  You have to satisfy what Vulkan wants in the data to make it work, and LWJGL2 certainly does.  Just because it does not work for you does not mean it does not work for me.  Have you tried an Nvidia RTX Series hardware?  It works fine.  It's because of the OpenGL 1.1 backwards compatibility, which some people don't like for some reason.  Newer versions of Vulkan support LWJGL2.  If you have not tried a newer version, then that is your problem.

**Comment by shatterblast** [comment]
Close this, please.

**Comment by noblemaster** [comment]
It's now closed.
