### ISSUE TITLE
[Feature Request?] get asset with same path but different param?

### ISSUE THREAD

**Issue by wonson** [libgdx/libgdx#3549]
As I know, AssetManager got a method called
    public synchronized <T> T get (AssetDescriptor<T> assetDescriptor)
and AssetDescriptor contains a AssetLoaderParameters<T> params
but  get (AssetDescriptor<T> assetDescriptor) ignores that params. 

Is it possible to make it also get it by determining params? 

As I made a extended AssetLoader to return a Texture, but there are possibility that using the same file but with different params can return different Textures

or maybe we can make it capable to set our own custom key instead of filename when AssetManager.load()?

**Comment by wonson** [comment]
Now my way to accomplish the task is input my filename as filename#myparamid at load(). 

Then in my custom AssetLoader check if filename contains "#" and do a filename.split("#")[0], so that I can access the asset by "filename#myparamid"

**Comment by intrigus** [comment]
This would also allow to load I18NBundles with the same name but a different different locale.
+1

**Comment by junkdog** [comment]
This would be pretty useful for BitmapFonts, as they're loaded as a single instance per  font; makes it a bit tricky when you need to manage multiple instances of each font.

**Comment by badlogic** [comment]
It's a problem for dependency resolution, as that's based on the key only. The locale scenario can be fixed with a custom loader. The font scenario is a bit harder to resolve i guess. The way i did it previously was to append the style info to the key name and have a custom file handle resolver set for fonts. Not ideal.

But introducing match on key AND params seems like a disaster to happen to me. AssetManager is already to complex for my taste. This proposed change will likely make it more surprising.
