### ISSUE TITLE
[Improvement] Move ShaderLoader from gdx-tests to gdx

### ISSUE THREAD

**Issue by realitix** [libgdx/libgdx#3557]
Currently, when we create shader, we have to copy/paste from default shader all needed property.
We should at least support #include notation.
Fortunately, ShaderLoader in tests supports this feature. It would be great to move it inside gdx and split default shader into small pieces.
What do you think about it ( @xoppa ) ?

**Comment by xoppa** [comment]
We're aware of this and have had some attempts to fix it. Ranging from generating a shader using a node graph to implementing a (pre)compiler / scripting. The ShaderLoader class in the tests is a left-over of one of those attempts, where I tried to find out whether it is possible to split shaders into small independent snippets.

This issue is getting more significant e.g. with GLES3 support where we at least need to generate shaders based on the supported platform while keeping backwards compatible with gles2 (think `#version`). And, as you said, to prevent code duplication. As well as to keep the shaders maintainable and extendable.

The main reason we still dont have a good solution for this is probably mostly because it takes quite some time to explore, implement, and compare the various options and then to put it in a good api we can build on. It is on my todo list, but I'm afraid that it is not likely that i find the time to do this anytime soon. So perhaps, indeed, it is a good idea to split this up into smaller, more easier to implement, parts.

Supporting the `#include` macro could indeed be a good start. But unfortunately this is not as simple as it might look and we certainly cannot move ShaderLoader to the core for that. Basically there are two things to consider:

*what to include*: we would need something like a FileHandleResolver but context aware, e.g. either relative to the current file or to one or more other locations specified.

*when to include*: simply replacing every `#include` directive with the content of that file is not really an option API wise. E.g. think about the common `#ifndef xxx` `#define xxx` code `#endif //xxx` structure to prevent nested includes. To support that we would need to add a precompiler.

**Comment by realitix** [comment]
Hi Xoppa, using a node graph would be the best solution but indeed it's very long to do.
For the second solution (only include), here solution we could use:

### 1 - What to include
We could add a preprocessor directive like 
`#include-set-directory [classpath | internal] [directory]` .
This directive would configure the context to all the next `#include` call.
Moreover we could add `#include [classpath | internal] [filepath]`

First example:
```
#include-set-directory internal com/badlogic/gdx/graphics/g3d/shaders/parts
#include directional.glsl
#include spot.glsl
#include point.glsl 
```

Same example:
```
#include internal com/badlogic/gdx/graphics/g3d/shaders/parts/directional.glsl
#include internal com/badlogic/gdx/graphics/g3d/shaders/parts/spot.glsl
#include internal com/badlogic/gdx/graphics/g3d/shaders/parts/point.glsl 
```

### 2 - When to include
The ShaderLoader should reference all included files and prevent nested includes so we don't need to add `#ifndef #define #endif` to preprocessor.

What do you think about it ?

**Comment by Darkyenus** [comment]
I personally would be in favor of just `#include filepath`, no resolving in shader files. The filename resolution would have to be in the loader. Because when somebody decides to move all shaders to different resolution path (internal -> local or whatever), all shaders would have to be changed as well to reflect this. It is also not very likely that one shader will include files from more than one place and if it does, it can be explicitly dealt with in the resolver.

However, there is still a few problems with this.
**1.** Using `#include` next to other preprocessor directives will be confusing. For example:
```c
#ifdef POINT_LIGHTS
#include point_light_support.glsl
#endif
```
This code would always import `point_light_support.glsl`, which would be confusing and not very flexible. Adding support for basic preprocessor directives would not be that hard though. But:

**2.** It has to work nicely with GLSL's own preprocessor system, if we use `#include` directive, it will look like there is one unified preprocessor system, but in fact there will be two, layered on each other. I suspect that this will lead to some confusion in all but simplest cases. I have two ideas how to resolve this:
- custom preprocessor system - simplified preprocessor system with well defined rules. It would look differently from the GLSL's system, so the confusion should be smaller.
- Use the GLSL system with added directives, but keep all directives in place after parsing (except for `#include`, which would get expanded, if it should be there according to the standard preprocessor system).  For example:
```c
#define POINT_LIGHTS
//...
#ifdef POINT_LIGHTS
#include point_light_support.glsl
// ... light code
#else
#include light_support_stubs.glsl
// ... stub code
#endif
```
would get expanded into:
```c
#define POINT_LIGHTS
//...
#ifdef POINT_LIGHTS
// ... point_light_support.glsl content
// ... light code
#else
// ... stub code (only #include is resolved, nothing else is changed to prevent errors)
#endif
```
This system would be more flexible, but slightly harder to implement, because we would have to emulate whole C preprocessor.
But maybe there is easier way and I am overthinking it.

**3.** It should play well with errors in GLSL code, particularly line numbers from GLSL compiler error messages. This could be solved by emitting #line directives. LibGDX should probably also support something like "save libgdx-processed sources, for debugging #include statements (and everything that goes into the GLSL compiler)".

**Comment by realitix** [comment]
Hi Darkyenus,
You're write about file resolving. It would be better to let the ShaderLoader handle file resolving. Moreover, Gdx.file.internal falls back to classpath if not found.

You're first exemple seems good to me.
I don't agree about preprocessor, indeed if you let glsl handle `ifdef ifndef`, it should work well.

```
#ifdef something
#include point.glsl
#endif
```

If you replace all the `#include` by the file content although `something` is not defined, it's not a problem because during compile time, glsl would not enter in `ifdef`.

@xoppa What do you think about it!

**Comment by xoppa** [comment]
If we would add support for the `#include` directive then I don't think we should deviate from the [include syntax](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html). The logic for resolving the file name would require a (customizable) class for that. Note that in that case it is likely to have at least a default set of "code" the user could include, for which we could use the `<filename>` variant. That "code" doesn't necessarily have to be an actual file, it might as well be stringified.

Simply replacing `#include` occurrences with the content is going to have issues. Modifying it to be like [include_once](http://php.net/manual/en/function.include-once.php) behavior would fix the nested include issue, but would introduce other issues as well. E.g.:

```c
#if X
  #if Y
  #include A
  #else
  #include B
  #endif
#else
  #if Y
  #include B
  #else
  #include A
#endif
```

What I mean is that if we would add support for the `#include` directive then it should behave as users would expect it to behave (e.g. as a reference precompiler would do). Otherwise it would cause confusion and hard to find bugs.

**Comment by realitix** [comment]
Good example @xoppa , I didn't think about this use case.
Indeed, we need to support all preprocessors directives in this situation.
Such a mess to do....

**Comment by realitix** [comment]
Maybe we could add a first version which might lead to the bug you mentionned @xoppa.
If the issue is well explained in the ShaderLoader javadoc, I think it's not so big. 
Later we would update the ShaderLoader to resolve this bug. What do you think @xoppa? 
A Little bugged version now or a version in an undefined time?

**Comment by Darkyenus** [comment]
Why rush it? ShaderLoader can be already used, one just has to copy it to project's sources. If we are to add it, let's do it properly and don't risk breaking somebody's code by doing it in phases.

**Comment by realitix** [comment]
Ok

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://blackburnhamletmassagetherapy.ca/climb.php?zi6ab>

 

loogie@basicelementdesign.com
