### ISSUE TITLE
Gdx.input.justTouched() not working correctly on iOS

### ISSUE THREAD

**Issue by brisma** [libgdx/libgdx#3568]
Hi, using Gdx.input.justTouched() on iOS will recognize only the first touch, all other touchs (second finger & co.) will not be recognized.

An example:

```
for(int i = 0; i < 5; i++) {
    if(Gdx.input.isTouched(i)) {
        // This is recognized correctly for all the fingers
        if(Gdx.input.justTouched()) {
            // This is true only with the first finger, if i am keep touching the screen with the first finger and i touch antoher point of the screen with another finger is not recognized
        }
    }
}
```

On Android is working correctly for all the touch/fingers.

**Comment by Tom-Ski** [comment]
https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSInput.java#L616 looks like the culprit but I can't test on IOS at the moment, someone else will have to!

**Comment by brisma** [comment]
Any news?

**Comment by soylomass** [comment]
@Tom-Ski Would it be out of place to ask how to test that change? As I also need to solve this issue.

**Comment by Tom-Ski** [comment]
Downloading libgdx source, making the change to the line linked (should be >= 1), testing brismas code.

**Comment by badlogic** [comment]
Fixed.

**Comment by Peter-Warlock** [comment]
I've got a bug with Gdx.input.justTouched in iOS version of my game. See the video here:
https://www.youtube.com/watch?v=RdAs05TIw1U

Android and Desktop versions works fine. iOS version works on some devices. But not on my device. Sometimes it's triggered sometime not. The touchscreen is good I've checked it by other app. No problem with it.
Gdx.input.getX(), Gdx.input.getY() always return correct values, But Gdx.input.justTouched() don't triggered and wherefore I miss the touches. 

Seems like IF statement in this line : https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSInput.java#L621 is absolutely wrong. justTouched flag must be set to ON on every BEGAN event phase. There is no reason to check numTouched. numTouched seems like a completely superfluous in this place. Android version set justTouched to true at touchDown event. iOS must to do the same. Without additional rule.

I fixed this bug by re-writing the code to use my custom InputProcessor and just set my local m_justTouched variable to true in touchDown() method. At the end of Game.render() I set m_justTouched to false. And now instead of using Gdx.input.justTouched() I use my m_justTouched check.  Now all works fine. 
So, I think it will be useful to inform you about this problem so that you remove this unnecessary IF check.
