### ISSUE TITLE
Can't get JsonValue from String returned by JsonValue.toString()

### ISSUE THREAD

**Issue by nikoliazekter** [libgdx/libgdx#3608]
I need to parse JsonValue to String and then parse this String back to JsonValue. JsonReader fails to parse String returned by JsonValue.toString() because of appended name. One way I found so far is to use awkward String manipulations but there clearly should be an easier way.

**Comment by JFixby** [comment]
Example code?

**Comment by nikoliazekter** [comment]
Something like this:
```java
            Json json = new Json();
            json.setUsePrototypes(false);
            JsonValue jsonValue = new JsonReader().parse(json.toJson(new BodyInfo()));
            String jsonString = jsonValue.get("linearVelocity").toString();
            JsonValue anotherValue = new JsonReader().parse(jsonString);
```
`jsonString` looks so:
```java
linearVelocity: {
x: 0
y: 0
}
```
Error occurs on thelast line:
```java
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.SerializationException: Error parsing JSON on line 2 near: x: 0
y: 0
}
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:548)
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:38)
```

**Comment by JFixby** [comment]
How about ```JsonValue anotherValue = jsonValue.get("linearVelocity");```?

**Comment by nikoliazekter** [comment]
But I need to parse it to String because I use libGDX clipboard for storing information. What I'm actually doing is copying object by parsing it to JSON string, saving this string to clipboard and then pasting this object. I need to know JsonValue name to get a correct class for Json.fromJson(). In my case JsonValue name is the name of the object class.

**Comment by JFixby** [comment]
Try ```jsonValue.prettyPrint(OutputType.json, 0);``` instead of ```toString()```

**Comment by nikoliazekter** [comment]
JsonValue.prettyPrint() erases the name but I need to keep it. What is the point of toString() anyway if I can't parse it back to JsonValue?

**Comment by JFixby** [comment]
```Object.toString()``` in Java is generally intended for debug.

Regarding the subject I recommend you to write detailed explanation of your problem including:
1) What you did
2) What you expected to happen
3) What actually happened

Otherwise it looks like you are doing something unintended and receive garbage as a result.

**Comment by Darkyenus** [comment]
In addition:
```
linearVelocity: {
x: 0
y: 0
}
```
is not a valid [json object](http://json.org), that is why you have this problem.

**Comment by NathanSweet** [comment]
JsonValue `toString` does not return JSON. Like most Java `toString` methods it returns *something* that tells you about the object. The name and the value or children of the JsonValue object make up most of what the object stores. If you want JSON, you can use `prettyPrint` as has been mentioned. It is odd that there is no way to get the JsonValue as non-pretty printed JSON, so I will add a `toJson` method. However, it won't do what you want because it is not possible to emit the name of the object in the JSON. Store it separately or do the string parsing you are doing.
