### ISSUE TITLE
Run test suite in IntelliJ.

### ISSUE THREAD

**Issue by AldousP** [libgdx/libgdx#3636]
To the best of my knowledge it is still difficult, if not impossible to run the desktop test suite in IntelliJ. While IntelliJ is currently fantastic for building LibGDX projects on all platforms, the fact that it can't run tests when working with source makes it inconvenient to need to use two IDE's to contribute.

**Comment by Tom-Ski** [comment]
Are you talking about the unit tests? Or the gdx-tests-lwjgl/gdx-tests-jglfw tests? Either way I have no issues with running either from within Intellij IDEA.

**Comment by AldousP** [comment]
The lwjgl and jglfw tests. It appeared that IntelliJ was struggling with the multi project layout of the source project, in addition to the snippet at the top of [this article](https://github.com/libgdx/libgdx/wiki/Running-demos-%26-tests) stating that tests were currently limited to Eclipse only. If they are currently considered functional in IntelliJ, it might be worth updating the documentation on how to set them up properly.

**Comment by Tom-Ski** [comment]
That article is outdated now IDEA has good eclipse integration and now we have a gradle model for LibGDX source also.  If you import via the Gradle model then you should be just fine. Otherwise you should manually set up the tests.  You shouldn't have an issue doing either of these.

**Comment by Tom-Ski** [comment]
I'll do both methods from a clean project, and update the guide for working from source for both methods.

**Comment by AldousP** [comment]
Great. I'll give it a shot. Thanks.

**Comment by AldousP** [comment]
@Tom-Ski Until you update the documentation, would you mind to point towards how I would run the tests after importing via the Gradle model? I'm currently getting a ClassNotFoundException when attempting to run the LwjglCanvasTest. I suspect this is a classpath issue with my run config in IntelliJ.

**Comment by Tom-Ski** [comment]
I suspect you are using Intellij 15.0.1? In which case you need to mess around a bit to get things to compile due to a bug with Intellij.  (which should be fixed in 15.0.2 iirc)

You'll need to remove all Gradle facets from the project. On Windows, `Ctrl + Shift + Alt + S` to bring up project structure, select facets and just remove everything. 

After this you will then need to manually compile the projects, this should only be required once.
Begin with `gdx`, select the folder in project explorer and hit `Ctrl + Shift + F9`  to compile the module.  Then do this for the backends, either the whole backends folder, or just the `gdx-backends-lwjgl`, and finally for `gdx-tests` and `gdx-tests-lwjgl`.  Then you should be able to run.  As I said, this is due to a bug, which should be resolved in the next minor patch, and you should only need to do this once, unless you clean out your build files.

If you have problems with other modules the solutions are a little more involved, I can give you a hand on the irc channel, the forum or over email; I just want to avoid any spam on this issue tracker due to problems out of our hands.

**Comment by AldousP** [comment]
Ah. Thanks for the explanation. Given the nature of the issue and the succinct explanation, this issue can be closed. Thank you.
