### ISSUE TITLE
ScalingViewport ignores screenX and screenY position

### ISSUE THREAD

**Issue by CrazyDude1994** [libgdx/libgdx#3681]
ScalingViewport ignores screenX and screenY position. Because of this, while using two FitViewports with different position on screen, it would not move it there. I've fixed it by adding current screenX and screenY position into update() method of the ScalingViewport. I could create pull request, but I should know if this is a bug, or intended.

```
setScreenBounds(getScreenX() + ((screenWidth - viewportWidth) / 2), getScreenY() + ((screenHeight - viewportHeight) / 2), viewportWidth, viewportHeight);
```

**Comment by nooone** [comment]
This is the intented behaviour currently, because all Viewports are centered on the screen by default, when updated.

If you want to move the Viewport, you will have to first update it, then set the screenX/Y and then use `apply()`.

**Comment by xoppa** [comment]
@nooone do you think it is desired to change this behavior or should we close this?

**Comment by NathanSweet** [comment]
Unfortunately I don't seem to remember how this viewport stuff works!

**Comment by rafcolson** [comment]
@xoppa 

Currently I'm working on [Viewports for BDX](https://github.com/GoranM/bdx/issues/701). The behavior of LibGDX viewports as being described in this issue is causing some inconveniences. First there's the necessity to set `screenX` and `screenY` and call `apply()` after calling `update()` and secondly some of the Viewport types, such as FitViewport, won't update correctly so `screenX`, `screenY`, `screenWidth` and `screenHeight` had to be recalculated. These issues made me consider not to utilize LibGDX Viewports, but maybe that wouldn't be necessary.

@nooone mentioned that the current behavior of LibGDX Viewports is intended because they ought to be positioned at the center of the screen, when updated. I would like to suggest to change this behavior so Viewports, such us ExtendViewport, StretchViewport and FitViewport (ScalingViewports) are centered relatively to their position and size. The old behavior then would still apply if the position would be (0, 0) and the size would be the same as the size of the screen.

**Comment by badlogic** [comment]
See other issue linoed here.
