### ISSUE TITLE
TMX map loader: wrong "y" property on Tile objects with flipped Y.

### ISSUE THREAD

**Issue by clebs** [libgdx/libgdx#3698]
The Tmx Map loader places objects wrong in the Y axis coordinate when the flipY flag is true.

How to reproduce:

1.- Create a TMX map in tiled.
2.- Create an object layer.
3.- Add a tile object to the layer in any position and remember the position.
4.- Retrieve the layer, and afterwards the object, through TmxMapLoader.
5.- Check "y" property after retrieval.

LibGDX version: 1.7.2
Tiled version: 0.14.2

**Comment by jojorabbit** [comment]
I got the same issue with LibGDX version 1.9.2 and Tiled version 0.16.0

Seems that problem is in BaseTmxMapLoader.java
around line 270
object.getProperties().put("y", (flipY ? y - height : y) * scaleY);

in older version of libgdx there was no flipY and y property was set to y - height. (LibGDX 1.5.5)

looks to me like it should be (flipY ? y : y - height) * scaleY

hope it helps.

**Comment by clebs** [comment]
yes, I already made a Pull request to fix that:
https://github.com/libgdx/libgdx/pull/3699
