### ISSUE TITLE
Graphics class needs more configuration options for windowed mode

### ISSUE THREAD

**Issue by bgroenks96** [libgdx/libgdx#3773]
This is a fairly easy change, so I will go ahead and submit a PR shortly.

Windowed mode needs additional configuration options: most importantly, setting the window to be resizable and decorated.

The overloaded method could look something like:
`public boolean setWindowedMode(int width, int height, boolean resizable, boolean decorated)`

Assuming we keep the old method that takes width and height and assumes false for both other params, this won't break any client code.

It seriously sucks right now that for dynamically changing these values you have to resort to interfacing directly with the backend, or in the case of LWJGL use hacky system properties.

*Additional note:*
I realize this is only relevant for desktop GDX, but the Android/iOS implementations can do the same thing that they do for the existing windowed mode method, immediately return false.

**Comment by Darkyenus** [comment]
Wouldn't be better to add setters for these two values? e.g. `setResizable(boolean), setDecorated(boolean)`? Then maybe the `decorated` property may be (mis?)used in iOS backend (maybe in Android as well) to toggle status bar visibility.

**Comment by bgroenks96** [comment]
That's fine with me too. I just think the functionality needs to be provided.

**Comment by bgroenks96** [comment]
@Darkyenus The only issue that comes to mind with that approach is that the Graphics object isn't describing a "window" specifically... per se. It does in desktop environments in certain cases.

It might be more consistent API wise to keep configuration options for the window in the `setWindowedMode` method.

What would be even better is if we could also have a an enum, maybe `WindowProperty` that could be passed in as a varargs:

`setWindowedMode(int, int, WindowProperty...)`

so a call might be:

`setWindowedMode(width, height, WIndowProperty.RESIZABLE, WindowProperty.DECORATED);`

What do you think?

**Comment by Darkyenus** [comment]
Yeah, the original idea wasn't very clean. I am not sure if the `WindowProperty` isn't overengineering though. I don't like bundling it with `setWindowedMode` because when I, for example, decide that I want to make the window non-resizable during the game (there is probably a better example, but bear with me), I'll have to retrieve window's dimensions to supply with the `setWindowedMode` call. Which in turn will do a bunch more work because it resizes the window to the same size it already has.

So I'd prefer separate setters for all properties. I have been thinking: how many  properties are there and to which backends to they apply? Most of the properties are backend specific:
- fullscreen - desktop and GWT only
- window dimensions, title, resizability and decorated - desktop only
- title bar/"immersion mode" - iOS/Android only

maybe there is more (does cursor count?), but I can't think of them. Some of these are currently as setters in `Application` (`setTitle`), some only in their backend subclasses (`AndroidApplication.useImmersiveMode`) and some can't be specified at all (what was mentioned, title bar on iOS).

Just a thought: Would it be worth it to somehow unify these properties and give them their own setters in `Application`/`Graphics`? That way, they won't do anything on platforms which don't support that property, but working with them in platform agnostic way will be easy. Or we can go in the opposite way and add them only where they are implemented. I like the previous option more though.

**Comment by bgroenks96** [comment]
Do you think it would be viable to combine them into unified API methods, kind of like you mentioned before?

i.e. setting a window decorated (or undecorated) and enabling/disabling the status bar on mobile could be one method that behaves differently on different backends.

That might be too confusing, though.

**Comment by 3xp0n3nt** [comment]
I think changing the status bar is analogous to changing the window decoration; I would just add javadoc explaining what it does. The multiplatform abstraction is always a little leaky; I don't think it can be completely avoided one way or the other. It's leaky to cast to the concrete backend to access functionality, but I consider it slightly less leaky to provide a polymorphic api that plugs the leaks by doing nothing on certain platforms, or performing an analogous function (such as changing the title bar). As long as the changes are additive, I think it's reasonable to provide javadoc detailing the situation because no one will already be using that code yet; i.e., there are no previous expectations for behavior.

**Comment by 3xp0n3nt** [comment]
That's what I did when adding custom cursor support to LibGDX anyway.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://antojitospampam.com.mx/hit.php?uaqkd>

 

loogie@basicelementdesign.com
