### ISSUE TITLE
Cell width with Value.percentWidth broken in debug mode

### ISSUE THREAD

**Issue by lukz** [libgdx/libgdx#3778]
When Value.percentWidth is used in debug mode Cell is scaled two times. For example if I set cell width to Value.percentWidth(0.5f); it would work nice but in debug mode actual size will be 0.25f.

Example code:
```java
public class ValueBug extends ApplicationAdapter {

	private Image normalSize;
	private Image halfSize;

	private Stage stage;

	@Override
	public void create () {
		stage = new Stage();

		Table table = new Table();
		table.setFillParent(true);

		normalSize = new Image(new Texture("badlogic.jpg"));
		halfSize = new Image(new Texture("badlogic.jpg"));

		halfSize.setPosition(normalSize.getX() + normalSize.getWidth(), normalSize.getY());

		table.add(normalSize);
		table.add(halfSize).align(Align.bottom).size(Value.percentWidth(0.5f));

		stage.addActor(table);
		stage.setDebugAll(true);
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

		stage.act();
		stage.draw();
	}
}
```

Result:
![image](https://cloud.githubusercontent.com/assets/4088173/12551941/a114e8ca-c36e-11e5-92d9-e2046529cf9a.png)

**Comment by NathanSweet** [comment]
```
table.add(halfSize).size(Value.percentWidth(0.5f));
```
This says that the size of `halfSize` will be half the size of `halfSize`. This means every time the table's layout is done, the size will be reduced. This would only make sense if you were setting the size of `halfSize` and then wanted the table to scale that. If you add `table.invalidate();` to the render method you'll see it scale down to nothing. I admit it is maybe pretty strange behavior, but it's actually working correctly and doing what you've told it.

`percentWidth` makes more sense when you pass in a different actor than the one you are sizing. In your case though, you may not need a dependency on another actor's size just to have the table size your actor half as large:

```
table.add(halfSize).size(halfSize.getWidth() / 2);
```

Just so you know where the size is coming from, when the `halfSize` Image was created, the Image constructor set the width and height to the pref size, which is the size in pixels of the region. Instead of relying on the current size of `halfSize`, it's probably better to just specify the pref size:

```
table.add(halfSize).size(halfSize.getPrefWidth() / 2);
```
