### ISSUE TITLE
hiero do not create some glyphs

### ISSUE THREAD

**Issue by serpent7776** [libgdx/libgdx#3800]
Sometimes hiero do not create glyphs on the generated texture, but there is entry in *.fnt file. For example in attached fnt file there is entry for char `id=21457`, but glyph for this character does not exist on generated texture. In fact glyph's coordinates exceed texture size. For mentioned character coordinates in *.fnt file are
`x=0    y=945  width=164  height=153`
Texture size is set to 1024x1024 and 945+153 exceedes this size.
I noticed this only when used with big font sizes and only when multiple pages are created.
I attach generated *.fnt file and *.hiero settings file. I could also attach generated textures if that helps.

[test.fnt.txt](https://github.com/libgdx/libgdx/files/110512/test.fnt.txt)
[test.hiero.txt](https://github.com/libgdx/libgdx/files/110514/test.hiero.txt)

**Comment by mjoyner-vbservices-net** [comment]
I am also having this issue, settings file, font file, and example .fnt/.png attached.
[_fonts-128.zip](https://github.com/libgdx/libgdx/files/227112/_fonts-128.zip)

**Comment by Mateiaru** [comment]
Issue still occurs, example is attached. Can confirm it only happens when multiple pages are created.
[font.zip](https://github.com/libgdx/libgdx/files/1243174/font.zip)

**Comment by ttencate** [comment]
Ugh, also running into this. This is the umpteenth bug I've personally encountered in Hiero. I'm of half a mind just to rewrite the whole thing from scratch some day, but for now, I'm just going to see if I can fix this one issue.

For reference, I'm also attaching my own test case:
[libgdx-issue-3800.zip](https://github.com/libgdx/libgdx/files/1362935/libgdx-issue-3800.zip)
The m character is among those that have gone  issing in action.

**Comment by ttencate** [comment]
Found the issue: [GlyphPage.java:107](https://github.com/libgdx/libgdx/blob/83e55a491b0a4656a240e7889d470ec4e91dea07/extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/unicodefont/GlyphPage.java#L107).

The algorithm adds glyphs to pages incrementally, putting them in rows:

* First, try to add it to each existing row except the last.
* If that didn't work, try to add it to the last row, increasing its height if possible.
* Otherwise, add a new row and add it to that. Even if that new row would fall off the page partly or completely...

The fix is straightforward and works well for me. PR incoming.
