### ISSUE TITLE
Wrong viewport size on Windows - good on Ubuntu

### ISSUE THREAD

**Issue by Magnesus** [libgdx/libgdx#3813]
When I run my game on Windows it looks as if the viewport is about 1.25x the size of the screen (photo attached) while on Ubuntu it is just fine (the same screen, the same laptop).

Here is how I turn on full screen:
DisplayMode mode = LwjglApplicationConfiguration.getDesktopDisplayMode();
                config.fullscreen = true;
                config.vSyncEnabled = true;
                config.resizable = true;

Here is how I create stage:
stage = new Stage(new ExtendViewport(1280, 800), new SpriteBatch());

Here is how I react to resize:
screen.stage.getViewport().update(width, height, true);
screen.stage.getCamera().translate(MaApp.px, MaApp.py, 0); 
// although centering doesn't seem to work, I have to manually translate the camera by gutter sizes (px, py are just negative gutter size).

How it looks on Ubuntu: https://www.dropbox.com/s/yns8va8t4rro9x8/20160201_144202.jpg?dl=0
How it looks on Windows: https://www.dropbox.com/s/udk09gvwnh3epbu/2016-02-01%2014.41.33.jpg?dl=0

PS. The laptop screen I am testing on is 1920x1080, the resulting screen is about 2400x1300, when started in window mode the window is also larger than I specify as size (by the same margin).

**Comment by Magnesus** [comment]
I have found the reason - scaling of elements in Windows was by default set to a larger value to compensate for the screen size. Is there a way to detect such setting and compensate?

**Comment by Magnesus** [comment]
PS. Adding:

width = width/(width/Gdx.graphics.getBackBufferWidth());
height = height/(height/Gdx.graphics.getBackBufferHeight());

to resize seems to have solved the problem...

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by BenMcLean** [comment]
I am having the same issue.

On Windows 10, there is a feature called UI Scaling described in this article: https://www.thurrott.com/windows/windows-10/4597/windows-10-feature-focus-display-scaling

When this feature is enabled, two very bad things happen for libGDX:

1. In full screen mode, we only see the upper left portion of the screen according to the degree of the UI scaling.

2. Nearest Neighbor pixel rendering screws up and shows blurry pixels instead of sharp edges.

I have confirmed this by running my program with UI scaling turned off (it works perfect) then turning UI scaling on. (these bad effects happen)

If you'd like to see my code, here is the commit I tested this effect on: https://github.com/BenMcLean/badroguelike/commit/31afc8fdba22180d9b9d47b5a9fd8aaf2417a516

**Comment by BenMcLean** [comment]
Discussion on IRC has revealed that this is probably a LWJGL issue. Their wiki (may be out of date) says they only have a high DPI mode implemented for OSX. http://wiki.lwjgl.org/wiki/Using_High_DPI_Mode.html

**Comment by voxelv** [comment]
I'm seeing this issue on my high dpi laptop.
There's a "barebones" example at https://github.com/voxelv/bitcorfab/blob/master/core/src/com/derelictech/bitcorfab/Screen1.java

The following post tries to meet most of the "More Information Needed" criteria.
http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=26659&p=105000#p105000

**Comment by NathanSweet** [comment]
It appears there is nothing we can do on our end. LWJGL2 is getting old and no longer maintained. Consider using LWJGL3, if possible.
