### ISSUE TITLE
Error in copy constructor for ObjectSet

### ISSUE THREAD

**Issue by JP314** [libgdx/libgdx#3843]
The item in the ObjectSet is not removed every time.

```java
package com.mygdx.game;

import com.badlogic.gdx.*;
import com.badlogic.gdx.utils.*;

public class Test extends ApplicationAdapter {

	@Override
	public void create() {

		ObjectSet<Object> set = new ObjectSet<>();
		Object o = new Object();
		set.add(o);

		ObjectSet<Object> set2 = new ObjectSet<>(set);
		// ObjectSet<Object> set2 = new ObjectSet<>();
		// set2.addAll(set);

		System.out.println(set2);
		set2.remove(o);
		System.out.println(set2);

	}

}
```

Expected output:
```
{java.lang.Object@8bcab4}
{}
```

But somtimes I get this:
```
{java.lang.Object@1b9c41}
{java.lang.Object@1b9c41}
```

**Comment by code-disaster** [comment]
This is an interesting one. We should summon @NathanSweet for consulting. ;)

I believe the culprit is at https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/ObjectSet.java#L64. In case of the copy constructor, this leads to a capacity different to the source set, and to slightly different behaviour.

Adjusting this line made the test pass, but I don't know this hashing method well enough to be sure. Also, if I'm right, it affects other libGDX container types, too.
