### ISSUE TITLE
ModelParameters specified to G3dModelLoader is totally ignored !

### ISSUE THREAD

**Issue by aboudaladdin** [libgdx/libgdx#3845]
no mipmaping generation nor texture filtering setting can be set 
` G3dModelLoader g3dModelLoader = new G3dModelLoader(jsonReader);

        Gdx.gl.glEnable(GL20.GL_GENERATE_MIPMAP);

        ModelLoader.ModelParameters modelParameters = new ModelLoader.ModelParameters();
        modelParameters.textureParameter.genMipMaps = true;
        modelParameters.textureParameter.minFilter = Texture.TextureFilter.MipMap;
        modelParameters.textureParameter.magFilter = Texture.TextureFilter.Linear;

   SkyboxModel = g3dModelLoader.loadModel(Gdx.files.getFileHandle("skydomeg10x.g3db", Files.FileType.Internal ),modelParameters);

TextureAttribute myTex = (TextureAttribute)GroundInstance.materials.get(0).get(TextureAttribute.Diffuse);
        Texture groundTexture = myTex.textureDescription.texture;
        System.out.println(groundTexture.getTextureData().useMipMaps());
        System.out.println(groundTexture.getMinFilter());
        System.out.println(groundTexture.getMagFilter());

`
and the output is 
useMipMaps = false 
minFilter = Linear
magFilter = Linear

**Comment by aboudaladdin** [comment]
guys dont ignore this its totally important , directly related to the quality of my scene graphics 
and without mipmaping it looks very weird (optical illusions)

**Comment by realitix** [comment]
Indeed, the parameter is not used, see https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g3d/loader/G3dModelLoader.java#L61

**Comment by realitix** [comment]
I will do it as soon as I have time

**Comment by realitix** [comment]
What I want to do to resolve this issue:

1 - Update [FileTextureProvider](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g3d/utils/TextureProvider.java#L31) like that:


```
public static class FileTextureProvider implements TextureProvider {
    private Texture.TextureFilter minFilter, magFilter;
    private Texture.TextureWrap u, v;
    private boolean useMipMaps;

    public FileTextureProvider() {
        minFilter = magFilter = Texture.TextureFilter.Linear;
        u = v = Texture.TextureWrap.Repeat;
        useMipMaps = false;
    }

     
     public FileTextureProvider(TextureLoader.TextureParameter p) {
        if(p == null) return this();
        this.minFilter = p.minFilter;
        ....
    }

    @Override
    public Texture load (String fileName) {
        Texture result = new Texture(Gdx.files.internal(fileName), useMipMaps);
        result.setFilter(minFilter, magFilter);
        result.setWrap(u, v);
        return result;
    }
}
```


2 - Here [ModelLoader](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/assets/loaders/ModelLoader.java#L59) I will just update like that:

```
public Model loadModel (final FileHandle fileHandle, P parameters) {
     return loadModel(fileHandle, new TextureProvider.FileTextureProvider(parameters.textureParameters), parameters);
}
```

@xoppa What do you think about it ?
I could have use the ModelTexture but the mipmaps parameter can only be set in the constructor of texture. By the way, what is the purpose of TextureDescriptor since wrap and filter are in GLTexture ?

**Comment by xoppa** [comment]
Just to make sure: everything works fine when you use AssetManager, the parameters are only ignored when using the loader directly?

If so then I would say lets keep things consistent and remove the `loadModel` method which takes the `parameters` argument, otherwise it might have contradicting arguments. If you don't want to use AssetManager then you should not use the parameters. Instead you can specify your own TextureProvider if you want to modify how the textures are loaded. Indeed it might be a good idea to add the members for generating the mipmaps and setting the initial values to the `FileTextureProvider` class. They don't necessarily have to be constructor arguments though and let's not use TextureParameter for that.

As for TextureDescriptor: https://github.com/libgdx/libgdx/wiki/ModelBatch#texturedescriptor

**Comment by realitix** [comment]
@aboudaladdin 
I created the pull request. If it's merged before next release, you could use this like that:
```

SkyboxModel = g3dModelLoader.loadModel(
     Gdx.files.internal("skydomeg10x.g3db"),
     new TextureProvider.FileTextureProvider(minFilter, magFilter, uWrap, vWrap, mipmaps)
);
```

**Comment by aboudaladdin** [comment]
wow amazing job .... thanks realitix & thanks xoppa 
for your efforts to fix that issue 
waiting to test it ! (Y)
