### ISSUE TITLE
Linux and Xbox controller mappings are all -1 in controller Mapping class.

### ISSUE THREAD

**Issue by AldousP** [libgdx/libgdx#3879]
#### Issue details

The source code for the class Xbox.java only has correct mappings for the Mac environment. All other platforms have all button mappings listed as -1.
#### Reproduction steps/code

Attempt to poll a controller for input on Windows using the constants defined in Xbox.java.
#### Version of LibGDX and/or relevant dependencies

1.9.2
#### Platforms
- Windows
- Linux
#### Relevant Code

```
 if (SharedLibraryLoader.isWindows) {
            A = -1;
            B = -1;
            X = -1;
            Y = -1;
            GUIDE = -1;
            L_BUMPER = -1;
            R_BUMPER = -1;
            BACK = -1;
            START = -1;
            DPAD_UP = -1;
            DPAD_DOWN = -1;
            DPAD_LEFT = -1;
            DPAD_RIGHT = -1;
            L_TRIGGER = -1;
            R_TRIGGER = -1;
            L_STICK_VERTICAL_AXIS = -1;
            L_STICK_HORIZONTAL_AXIS = -1;
            R_STICK_VERTICAL_AXIS = -1;
            R_STICK_HORIZONTAL_AXIS = -1;
        } else if (SharedLibraryLoader.isLinux) {
            A = -1;
            B = -1;
            X = -1;
            Y = -1;
            GUIDE = -1;
            L_BUMPER = -1;
            R_BUMPER = -1;
            BACK = -1;
            START = -1;
            DPAD_UP = -1;
            DPAD_DOWN = -1;
            DPAD_LEFT = -1;
            DPAD_RIGHT = -1;
            L_TRIGGER = -1;
            R_TRIGGER = -1;
            L_STICK_VERTICAL_AXIS = -1;
            L_STICK_HORIZONTAL_AXIS = -1;
            R_STICK_VERTICAL_AXIS = -1;
            R_STICK_HORIZONTAL_AXIS = -1;
}
```

**Comment by Tom-Ski** [comment]
Bit of a tricky one.  I think @badlogic may have pushed that xbox binding for mac for the lwjgl3 controllers, which will probably give different results to the desktop controllers backend.  Not sure though, and I don't have a mac to test with.  

I've had a quick look at the binding for windows, and the dpad is reported as PovDirections, so that wouldn't be compatible with the current state in the bindings.  The lwjgl3 controllers extension behaves a bit better, and each direction has its own int, however not all buttons work, left axis push in doesn't seem to register.  Also interestingly, with desktop controllers the native windows game controller doo-da kicks in with the 360 home button, but doesn't with lwjgl3. 

Anyway, not sure of the direction we'd want to take with this.  We could have introduce a "is lwjgl3" into the binding, or just add a new binding for the desktop version of controllers (rather than the lwjgl3), but that still leaves us with the issue of PovDirection not being compatible with the current state of bindings.  Also on desktop controllers on windows you would have to query Pov rather than query button for dpad, on mac/linux this may even be different.

**Comment by AldousP** [comment]
Would it make more sense for the controller mapping class to be in the controllers-lwjgl3 package?

**Comment by Tom-Ski** [comment]
That would solve one of the issues, there is still the issue with the Pov vs individual buttons.  Perhaps bindings could be a little more involved, but I guess this is only an issue with the desktop controllers so I'm not sure if it's even worth it. I'd be happy with just pushing lwjgl3 going forwards, in which case please feel free to create a PR for the bindings for windows/linux for the xbox controller!

**Comment by WickedShell** [comment]
LWJGL3 specific mappings for this were already accepted ( #5090 ), and the current workflow can be summarized as if your dpad mappings come in as -1 then use POV instead, which while not terribly convenient is how the controller is presented across different platforms. Given that I think this issue can probably be closed, unless I've missed something.

**Comment by MrStahlfelge** [comment]
Hi, please take a look at [gdx-controllers v2 prerelease snapshot](https://github.com/libgdx/gdx-controllers). It should solve your issue.
