### ISSUE TITLE
Framerate drops with gdx-controllers-lwjgl3 and NO connected controllers

### ISSUE THREAD

**Issue by saibotd** [libgdx/libgdx#3886]
#### Issue details

My game encounters extreme performance issues whenever I launch it without having any controllers attached. The framerate drops exactly from the point on where I call Controllers.getControllers() the first time.  
Game runs fine if at least one controller is attached or Controllers.getControllers()  never gets called.
#### Reproduction steps/code
- Enable LWJGL3
- Remove all gamepads from PC
- Call Controllers.getControllers() within you Application
#### Version of LibGDX and/or relevant dependencies

LibGDX 1.9.2 on Windows 10. Using a MS wireless receiver and Xbox 360 controller. It doesn't matter if the receiver is connected btw.
#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows 10
- [ ] Linux
- [ ] MacOS

**Comment by intrigus** [comment]
Could you please define 'extreme performance issues'?

I don't have a controller so I can't test it.
The problem is probably that https://github.com/libgdx/libgdx/blob/master/extensions/gdx-controllers/gdx-controllers-lwjgl3/src/com/badlogic/gdx/controllers/lwjgl3/Lwjgl3ControllerManager.java#L33 takes a long time for enumerating all possible controllers (It's possible to have 16 controllers, iirc).
Since pollState() is called every frame we spend a long time enumerating all possible controllers.

GLFW is going to add connect and disconnect events, so we don't have to enumerate all possible controllers.

A possible fix would be to only check every second for new controllers, just like https://github.com/libgdx/libgdx/blob/master/extensions/gdx-controllers/gdx-controllers-desktop/src/com/badlogic/gdx/controllers/desktop/OisControllers.java#L61-L89 does for a lost window handle.

**Comment by saibotd** [comment]
Thanks for taking the time. It goes from 60 fps to, I guess, 10-15 fps - I can measure it if you want to. I see no polling, etc. in the logs, but it sounds like that could be the problem. I checked with VisualVM (it helped me in the past with performance issues) and it shows an increased CPU usage (2% to 20%) when no controller is plugged in.

**Comment by intrigus** [comment]
Could you profile how long calls to https://github.com/libgdx/libgdx/blob/master/extensions/gdx-controllers/gdx-controllers-lwjgl3/src/com/badlogic/gdx/controllers/lwjgl3/Lwjgl3ControllerManager.java#L32 take when you use zero/one controller?

This issue is a little bit strange because it shouldn't really matter if there are zero/more controllers, because Libgdx iterates overall possible controllers anyway.

**Comment by saibotd** [comment]
I think you got it :+1: [Check this out](http://imgur.com/a/iOwiC), gflwJoystickPresent is slow all the time, just like you said, but it gets super-slow when no joystick is present.

**Comment by saibotd** [comment]
I've just noticed that the game crashes when a controller gets unplugged. should I open a new issue for that?

**Comment by code-disaster** [comment]
Interesting issue.

I think it's questionable how often games actually need to get notified about connected devices immediately, all the time. It may be a good idea to make the poll for newly connected devices optional, and/or spread it out a few frames (e.g. only poll 1 out of N each frame). Also, for registered (connected) joysticks glfwJoystickPresent() is called twice per frame, once in the manager, and again in Lwjgl3Controller.pollState().

Btw it looks like this isn't a new issue at all:
http://blackhole12.blogspot.de/2012/06/how-joysticks-ruined-my-graphics-engine.html
http://en.sfml-dev.org/forums/index.php?topic=5600.0

@saibotd please report the crash too. I've seen some random crashes on my coworker's Windows notebook already, which is strange because he had no controllers attached. I'm curious to see if the crash looks similar.

**Comment by saibotd** [comment]
@code-disaster sounds reasonable, for example in my game I have a lobby screen where all of the players for a local multiplayer session "log in". I need polling here and at the start of the game, but not anywhere else. Methods like

    Controllers.setPolling(bool)
    Controllers.setPollingRate(ms)
    Controllers.poll()

would be great to let devs chose when and where to poll for new controllers.

I'll open a new issue for the crash on disconnection.

**Comment by saibotd** [comment]
Is anyone working on this? If not, I could give it a try.  
I would implement a rate limit for the polling of new controllers and add a function to ControllerManager to set how often it happens. Cool?

**Comment by intrigus** [comment]
Feel free to work on it :)

**Comment by lukz** [comment]
Is there any progress on that? I have same issue with my game. Lwjgl3 backend is unusable due to that issue.

**Comment by saibotd** [comment]
I have to admit that I gave up on Lwjgl3 (and Lwjgl2) for controller support. There are just far to many issues generally with desktop controller support in libGDX (missing mappings, different mappings for different OSes, broken hot-plugging, triggers share one axis, etc.)

For now I switched to [JXInput](https://github.com/StrikerX3/JXInput). If you are developing for Windows only, where the Xbox 360/One controllers are pretty much standard, I would suggest doing the same.

**Comment by code-disaster** [comment]
Reopened because GitHub is too smart. #4104 is not a fix, just the prerequisite.

**Comment by intrigus** [comment]
@saibotd Could you please retry?
Just change `compile "com.badlogicgames.gdx:gdx-controllers-lwjgl3:$gdxVersion"` to
`compile "com.github.intrigus.gdx:gdx-controllers-lwjgl3:$gdxVersion"`.
and `$gdxVersion` to `1.9.4-SNAPSHOT`.

> There are just far to many issues generally with desktop controller support in libGDX (missing mappings, different mappings for different OSes, broken hot-plugging, triggers share one axis, etc.)

Missing mappings could be improved. It should be possible to use the controller database from SDL, which would also solve the problem of different mappings.
Not sure, but what do you mean with 'broken hot-plugging'?
Re: Triggers sharing one axis. GLFW used DirectInput for joysticks, which has the nice "feature" that Xbox controllers share one axis. (See https://msdn.microsoft.com/de-de/library/windows/desktop/ee417014(v=vs.85).aspx and the comments on it)
Since GLFW3.2 Xinput is used for Xbox controllers, so this should work.

**Comment by lukz** [comment]
@intrigus is it possible to have gamepad vibrations in LibGDX controllers?

**Comment by intrigus** [comment]
It's currently not possible.

**Comment by code-disaster** [comment]
@intrigus this updates your branch so that disconnect events are handled correctly:
https://github.com/code-disaster/libgdx/commit/6bb2c17acc283be265df4afeb39bd1381138dcbe

tested on my PC with XB1 controller and a flightstick/throttle combo.

**Comment by MrStahlfelge** [comment]
Hi, please take a look at [gdx-controllers v2 prerelease snapshot](https://github.com/libgdx/gdx-controllers). It should solve your issue.
