### ISSUE TITLE
LWJGL3 Swallowed Exceptions

### ISSUE THREAD

**Issue by piotr-j** [libgdx/libgdx#3921]
#### Issue details
Exceptions thrown in ```ApplicationAdapter#dispose()``` swallows other exceptions. Additionally when exception is throw after new window is created, ```dispose()``` is called on it, but ```create()``` never was. 

#### Reproduction steps/code
See the gist for SSCEE.
https://gist.github.com/piotr-j/42e6f1caf3ed4b0ca899

#### Version of LibGDX and/or relevant dependencies
1.9.3-SNAPSHOT

#### Stacktrace
```java
Exception in thread "main" java.lang.AssertionError: Hides them all
	at com.mygdx.game.desktop.ExceptionSwallowTest.dispose(ExceptionSwallowTest.java:31)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.dispose(Lwjgl3Window.java:281)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.cleanup(Lwjgl3Application.java:152)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:103)
	at com.mygdx.game.desktop.ExceptionSwallowTest.main(ExceptionSwallowTest.java:37)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by JFixby** [comment]
https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html

> An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch. Most such errors are abnormal conditions. The ThreadDeath error, though a "normal" condition, is also a subclass of Error because most applications should not try to catch it.
A method is not required to declare in its throws clause any subclasses of Error that might be thrown during the execution of the method but not caught, since these errors are abnormal conditions that should never occur. That is, Error and its subclasses are regarded as unchecked exceptions for the purposes of compile-time checking of exceptions.

**Comment by xoppa** [comment]
Thanks! Can you confirm it works fine on LWJGL? Can you suggest a fix?
