### ISSUE TITLE
Music getPosition returns always 0.0 after played at least one time (on Android)

### ISSUE THREAD

**Issue by kutoman** [libgdx/libgdx#3935]
this happens when I first **play()** a music instance, **stop()** afterwards and **play()** again. In this case **getPosition()** returns always 0.0 even though the music is being played. This does not happen in the desktop application.
#### Version of LibGDX and/or relevant dependencies

gdxVersion = 1.9.2
tested on Android 5.1.1
#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment]
I created this PR some time ago in an attempt to fix it https://github.com/libgdx/libgdx/pull/3585. I tried the fix on a life app and it worked on most devices but there were some exceptions so I dropped it.

I never opened it as an issue again due to the lack of interest but there are definitely some issues with music on NuPlayer devices, this is just one of them, happy to see I'm not the only one experiencing them.

**Comment by radiocold** [comment]
I used libgdx 1.9.2 and have the same error, please any solution or how to incluide that fix??

**Comment by chandujr** [comment]
I encountered this bug too. Loaded music by `Gdx.audio.newMusic()` from external storage. After calling `play()`, `getPosition()` returns 0 even though music is playing. I tested in Desktop app and gdx version 1.9.5.

**Comment by CeuxDruman** [comment]
It is 2021 and I just faced the same issue. First time the Music is played you can get the position (even if it already looped some times). But once stopped and played again, it always returns 0.0...

I deeply tested this issue and **setPosition()** is also affected. You cannot either get or set the position of a previously stopped music.

FYI: As a workaround, every time you need to stop the music you can:
music.dispose();
music = new Music(...);
music.set... (setLooping, setVolume...)

so next time you want to play it again, it will be already "reseted". But of course this is a really dirty solution.

Any other workaround or estimated date of resolution?

**Version of LibGDX and/or relevant dependencies**
gdxVersion = 1.9.6
tested on:
- Android 6.0.1
- Android 10

(So I can confirm it is not failing on Desktop, but it is failing in all Android devices with several years and Android versions in between. I don't have an iPhone to test it)

**Comment by obigu** [comment]
I attempted to fix this at some point https://github.com/libgdx/libgdx/pull/3585. The fix worked but when I released an app with it, a small percentage of devices were failing (I think they had no sound). I didn't investigate any further because it was not something I needed on my projects and audio on Android is very fragile. If you want to work on it, it may be a good starting point.
