### ISSUE TITLE
Add basic VR support using the LWJGL3 OpenVR bindings

### ISSUE THREAD

**Issue by me4502** [libgdx/libgdx#3986]
With VR technologies such as the HTC Vive, and the Oculus Rift becoming mainstream, the ability to hook a LibGDX camera to a VR HMD, or track a controller, would allow for LibGDX to be used to create VR games.

Usage of the OpenVR (SteamVR) bindings is most sensible, as it works on multiple HMDs, rather than Oculus' LibOVR, which is limited to Oculus HMDs at this stage. Also, OpenVR supports room-scale and touch controls, unlike LibOVR.

The following are stages that I feel would make sense
- [ ] A VR Camera. LibGDX 3D camera that is tracked to a HMD, and renders to the VR Compositor. (Possibly even a VR Camera Wrapper to wrap other cameras)
- [ ] VR Touch Controller Input Types
- [ ] Access to room-scale boundaries

**Comment by Tom-Ski** [comment]
What do you mean by a LibGDX camera? 

Would be cool, just depends on time and access to devices I guess.  Do you have devices to recommend developing with for this?  Perhaps we can get an official extension rolling.

**Comment by me4502** [comment]
I have an HTC Vive Pre.

By camera, I mean like a PerspectiveCamera, as in the class. Basically the position would automatically move with the HMD. As would the rotation.

I'm willing to do this, it's really a matter of lack of time - I have Uni assessment right now.

I should be able to do the camera at least within the next few days

**Comment by nooone** [comment]
I think one `VRCamera` which is connected to the "head" transform would not help much, as you will need two cameras, for the left and right eye.

OpenVR seems to have an easy API that could be easily used with libgdx, but "LWJGL3 OpenVR bindings"... where did you find these? I have only found a few ([this](https://github.com/phr00t/jMonkeyVR/tree/master/src/jopenvr) and [this](https://github.com/jherico/JOpenVR/tree/master/src/main/java/com/valvesoftware/vr)) selfmade java wrappers.

Having OpenVR java bindings and adding few utilities to convert objects to the libgdx equivalents (Matrix4, Quaternion, Vector3, PerspectiveCamera, ...) might already be enough to write a VR-enabled application using libgdx. Maybe it would even make sense to create our own wrapper with optimizations (like bullet), because performance and latency is crucial in VR.

**Comment by me4502** [comment]
The camera would contain two matrices that act as transforms, that the camera would render from.

**Comment by xeoshow** [comment]
Can google cardboard be supported with this new feature?

**Comment by wangcan26** [comment]
Is google cardboard being to be integrated into libgdx in the future?

**Comment by xeoshow** [comment]
Here is a 3rd party google cardboard extension for libgdx, hopefully it could be useful for the offcial libgdx VR extension:
https://github.com/yangweigbh/Libgdx-CardBoard-Extension

**Comment by kerberjg** [comment]
A `VRCamera` might as well just be an abstraction/container for two `PerspectiveCamera`s, with proper adjustments like distance between eyes, position, rotation etc

**Comment by me4502** [comment]
All it really needs is a location, and then two matrices that transforms the position for each eye, not two seperate cameras.

**Comment by kerberjg** [comment]
Yeah, it'd be actually a more optimized approach, at least it'll generate less memory overhead.

**Comment by Brummi** [comment]
I implemented a `VRCamera` for LibGDX that uses two `PerspectiveCamera` s and `FrameBuffer` s. It can be transformed and rotated and comes with a head tracker.
It doesn´t use any external libraries, only LibGDX.

Check out the **GitHub repository** **<a href="https://github.com/Brummi/VRCamera">here</a>**.
An **usage example** can be found **<a href="https://github.com/Brummi/VRDemo">here</a>** (Android Studio Project).

You pass the `VRCamera` an interface which contains a method to render the 3D scene with the specific `PerspectiveCamera` (left or right). The `VRCamera` then renders both images side by side on a given `Batch.`

The headtracker (`VRCameraInputAdapter`)reads the gyroscope and accelerometer values and rotates the camera accordingly. However, you can also easily implement mouse controls since you would only have to set two rotation angles.

It is really simple to use and does not require any knowledge of VR technology.

I designed the VRCamera mainly for mobile devices with Google Cardboard or similar "VR Glasses". Even though i don´t have any experience with Oculus Rift or HTC Vive programming, i don´t hink it would be a real problem to use the VRCamera for these kind of VR glasses

I will try to create a tutorial on how to use it soon, hope you like it.

**Comment by avatar21** [comment]
@Brummi Ah nice and easy way to start

**Comment by ThomasWrobel** [comment]
As someone very interested in AR/VR, and also code-aly invested in LibGDX this is very appreciated!

**Comment by badlogic** [comment]
@Brummi sweet! I'm closing this out and modifying the top post to link to your Github repository.
