### ISSUE TITLE
3D Perspective Camera Gimbal Lock

### ISSUE THREAD

**Issue by mttprvst13** [libgdx/libgdx#4023]
Please ensure you have given all the following requested information in your report.

#### Issue details
I am working on a new project, and I have come across an issue when using a similar version of FirstPersonCameraController. When the player looks directly up, or down, the screen has a sort of spasm. I think it is rotating, trying to make sure the player does not look down too far, but in my game, I don't want it to rotate the camera.

#### Reproduction steps/code
Copy FirstPersonCameraController to project, and set it up. Import a model. Look directly up, or down.

#### Version of LibGDX and/or relevant dependencies
LibGDX version 1.9.2

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by ThatGamerBlue** [comment]
Can confirm

**Comment by mttprvst13** [comment]
I have found out that this is a Gimbal Lock. I am looking up how to fix this.

**Comment by jsjolund** [comment]
I am not completely sure this is a bug, since it has to do with how your game handles the camera up vector. This is only a problem if you set the camera up vector to something constant, like ```Vector3.Y``` on each camera update. If you rotate the up vector along with the direction vector (outside of ```FirstPersonCameraController```) this problem should disappear.

This behaviour occurs when the camera direction vector aligns with, or rotates past, the camera up vector (or its inverse, down). If they align, this problem comes from the fact that their cross product has an infinite number of orthonormal bases. If the direction vector rotates past up/down, their cross product will point in the opposite direction from before the rotation occurred, which makes the camera flip direction.

This could be prevented by changing ```FirstPersonCameraController#touchDragged``` to check for this situation, and prevent rotation if it would cause the "spasm".
```
	@Override
	public boolean touchDragged (int screenX, int screenY, int pointer) {
		float deltaX = -Gdx.input.getDeltaX() * degreesPerPixel;
		float deltaY = -Gdx.input.getDeltaY() * degreesPerPixel;
		camera.direction.rotate(camera.up, deltaX);
		Vector3 oldPitchAxis = tmp.set(camera.direction).crs(camera.up).nor();
		Vector3 newDirection = tmp2.set(camera.direction).rotate(tmp, deltaY);
		Vector3 newPitchAxis = tmp3.set(tmp2).crs(camera.up);
		if (!newPitchAxis.hasOppositeDirection(oldPitchAxis))
			camera.direction.set(newDirection);
		return true;
	}
```
But I am not sure if current behaviour is intended or not. If it is not, I could make a PR for this change.

**Comment by mttprvst13** [comment]
That worked, thank you very much!
