### ISSUE TITLE
Template Project for Cloud9/Displayless Environment

### ISSUE THREAD

**Issue by ashes999** [libgdx/libgdx#4064]
Hi,

I'm trying to use `Cloud9` for my IDE. I can't use `gdx-setup.jar`, because there's no display attached to my environment. (Cloud9 offers Ubuntu VMs, configured via Docker, I think).

When I try to invoke `gdx-setup.jar` with the command-line arguments, I get an error about not having a display.

Okay, so I need to create a project template; I found [this repository](https://github.com/libgdx/libgdx-gradle-template), which was deprecated circa 2015.

Is there a more current repository or template I can download/clone to get this set up?

Is it possible to update `gdx-setup.jar` so that it can run completely from the command-line, without a GUI?

**Comment by MobiDevelop** [comment]
As far as I can tell, you should be able to run the setup cli without having a display. What parameters did you pass?

**Comment by np511** [comment]
I've used cloud9 and it is possible.

However, you need to pass in all of the following args for it to work 
without needing a display:

name, dir, mainClass, package

You probably also want to put in --excludeModules "ios"

If you want to use android you need to set up the android sdk within 
cloud9 - the easiest way to do this is to use the cloud9-vnc scripts. 
<https://github.com/fjakobs/cloud9-vnc>

Otherwise, add android to the excluded modules list.

Example:

java -jar gdx-setup.jar --name App --dir AppDir --mainClass 
MainApplicationClass --package com.example.package --excludeModules 
"ios;android"

**Comment by ashes999** [comment]
I'm pretty sure I passed all the parameters in (at least, the ones mentioned on the wiki). I'll try adding exclusions for the android module.

I don't think Cloud9 comes with the Android SDK installed anyway.

I'll try this again and report back.

**Comment by np511** [comment]
It doesn't come with the SDK, you'd have to go the download page, copy 
the URL, and wget it.
