### ISSUE TITLE
Add RGB 255 support for Color API

### ISSUE THREAD

**Issue by briceambrosiak** [libgdx/libgdx#4071]
Currently, Color class can only be used with float values and if working with RGB, one must always use (value / 255) to convert to float value. It would be nice to have the Color class API directly working with RGB 255 integer values.

**Comment by xoppa** [comment]
Color already has methods to supply RGBA integer values, see `Color(int rgba)` and `Color#set(int rgba)`. https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#feature-requests

**Comment by briceambrosiak** [comment]
Yes, but I actually expected more a signature like Color(int r, int g, int b, int a). I must do those conversion in my game, although it could be factorized in the framework.

**Comment by xoppa** [comment]
You probably mean `byte` then, so you can provide 4 separate values (bytes) in the range of 0 to 255. That would be kinda restricted to a specific implementation (what if you use 16 bits per pixel or floating point textures?).

Some libs use that indeed, usually those are targeted to canvas graphics, but it's not something that you should prefer for a game. Normalized values are a lot easier to work with.

However, as said, the `Color` class already allows specifying an `int` (4 bytes) as well (e.g. `0xff00ffff`), just like most applications (and html) do. If you prefer to specify each component separately then you might as well add the `/255f` also. You haven't convinced me of the added value of such method signature to justify the confusion of having two near identical method signatures with very different meanings.

Simply using 4 ints would cause a lot of issues btw, e.g. imagine how existing code like `color.set(1, 0, 0, 1)` or `new Color(1, 0, 0, 1)` would break because of that.

**Comment by briceambrosiak** [comment]
You're right, I didn't thought about 16 bits and possible retro-compatibility of the new signature. Thanks for the explanation!

**Comment by BenMcLean** [comment]
Just add a 16bit on the end of the function name for functions that accept 16 bit color values
