### ISSUE TITLE
FR: local file support for html 

### ISSUE THREAD

**Issue by stefanhaustein** [libgdx/libgdx#4128]
I don't think there is a technical reason preventing this -- it should be able to live parallel to internal files in localstorage, using different path prefixes?

Version: 1.9.3
#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [X] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MobiDevelop** [comment]
The problem with local files is that the amount of local storage available by default is fairly small, not standardized, and there no (good) way to accurately query the quota. I'm not terribly opposed to the idea, and I guess some amount of local storage is better than nothing (although we do provide preferences on html, backed by local storage).

Since local storage is essentially a string/string map - we'd have to write everything to it as strings. Knowing that we have to do that, you might as well just use the preferences api to do the same.

Just as a not, internal files don't live in local storage - they are initially served by the server and potentially cached by the browser using its caching mechanism.

Have an idea for how this would be implemented transparently (and efficiently)? Like I said, I am not opposed to the idea if it makes sense and can be made to work well within the constraints imposed by the web environment.

**Comment by stefanhaustein** [comment]
I had assumed the internal FS uses localstorage because localstorage is mentioned in the javascript file platform documentation: https://github.com/libgdx/libgdx/wiki/File-handling#platform-filesystems
Also, it's synchronous  and I saw something called "Preloader" when I took a quick glance at the source -- didn't expect you to pre-load everything to RAM to address the web platform synchronous access problem O:)

I agree that a LocalStorage FS might not make much sense when you don't have the infrastructure implemented for a similar purpose already.

I have added some information from your answer to the wiki.

Thanks for the quick response!

**Comment by stefanhaustein** [comment]
While looking into [data storage with web support](https://github.com/stefanhaustein/quake2-libgdx-port/blob/master/html/src/com/googlecode/gdxquake2/emul/com/googlecode/gdxquake2/gdxext/AsyncLocalStorage.java) some more, I have noticed some strange things about FileHandle and File:

My old local storage-based (incomplete) File implementation seems to be included in your JRE emulation, but FileHandle is completely stubbed out, and then GwtFileHandle implements some of it.... Do you have any background why it's this way? 

- Stubbing out FileHandle seems to makes it harder to implement a subclass (based on indexedb and / or typed arrays) that would work on web. 
- If a localstorage-based FIle implementation is included anyway, why not support it properly, even if it is limited to small files?

**Comment by MobiDevelop** [comment]
Will have to defer to @badlogic on the specifics as I am not totally familiar.

**Comment by stefanhaustein** [comment]
Have looked into this some more:

- The original FileHandle java source [compiles](https://github.com/stefanhaustein/quake2-libgdx-port/blob/master/html/src/com/googlecode/gdxquake2/emul/com/badlogic/gdx/files/FileHandle.java) with GWT when adding a few small missing java.io classes and moving hasResource and getResourceAsStream to a platform helper.
- Your GWT [File](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/java/io/File.java) emulation already has localStorage support, so it seems reasonable to extend this to full support by adding FileInput/OutputStream. Doing so would improve consistency between platforms, even if local storage space is limited.

I have made some of these changes in my own project for now, should be able to contribute them when I have made some more progress with my primary work.

**Comment by badlogic** [comment]
You're probably not working on this anymore. If you are, please send a PR :)

**Comment by stefanhaustein** [comment]
I still plan to have this ready for 20 years of Quake II at the end of 2017 O:) 
I am happy to create a PR for this particular aspect (better GWT file support) if you agree with the general approach.

**Comment by badlogic** [comment]
FileHandle is used by a few apps without a full backend, and I don't want
to break this (and I think Nate'd kill us :D). I think it's OK to subclass
FileHandle for GWT, and override the handful of methods that need to call
into a PlatformHelper. Could be HtmlFiles that the subclassed Filehandle
delegates to.

On Dec 4, 2016 11:40 PM, "Stefan Haustein" <notifications@github.com> wrote:

I still plan to have this ready for 20 years of Quake II at the end of 2017
O:)
I am happy to create a PR for this particular aspect (better GWT file
support) if you agree with the general approach.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/libgdx/libgdx/issues/4128#issuecomment-264737546>, or mute
the thread

**Comment by stefanhaustein** [comment]
I think people could keep this working locally by keeping the existing FileHandle super-source.
Extending the differences will also extend the maintenance burden, which may or may not be the right path for libgdx, but certainly won't be for me.

**Comment by badlogic** [comment]
Keepng the super source works for me.
