### ISSUE TITLE
Using OrthographicCamera.combined as the projection matrix results in text rendering problems 

### ISSUE THREAD

**Issue by SasLuca** [libgdx/libgdx#4185]
#### Issue details
I use an Orthographic Camera in my project with the width equal to 720 pixels and the height 1280 pixels, I then use the OrthographicCamera.combined matrix as the projection matrix in my SpriteBatch. All textures scale fine but the fonts look weird. After hours of testing I manage to figure out that it is because of the combined matrix because when I comment the line SpriteBatch.setProjectionMatrix(Camera.combined) the text renders fine, but it does not scale my app to different screen sizes.  I tested it on Android too though and the text looked better on my phone (except for one italic font which also looked weird), I thought this was because the phone is of a resolution higher than 720p but that does not seem to be the case since running the Desktop version of my app in 720p does not help the text render any better.

![5bd2d13daa705f214c2dda965e852921](https://cloud.githubusercontent.com/assets/15983269/16713971/cf3f30f6-46be-11e6-9992-7db121aafc72.png)
Text rendering with problems when using combined matrix.

![dab1f148f91b1ffc8a51d9a82d15eab0](https://cloud.githubusercontent.com/assets/15983269/16713967/b7eb4b74-46be-11e6-8db5-fc191d06396f.png)
Text rendering fine without combined matrix.

#### Reproduction steps/code
Create a font using the FreeTypeFontGenerator with Linear min and mag filters.
Create a Sprite Batch and a OrthographicCamera.
Set the Sprite Batch projection matrix to Camera.combined.
Render the text.

#### Version of LibGDX and/or relevant dependencies
_Lib Gdx version 1.9.2_

#### Please select the affected platforms
- [X] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by xoppa** [comment]
Please include the required information to reproduce the issue that you are reporting. That includes the actual code.
Other than that it looks like expected behavior to me. If you really want to scale texels then you have to take into consideration the texture filtering. And if you set that to linear filtering then that will result in what you showed in your screenshots. So, either use a pixel perfect projection or use a different texture filter. Either way, I don't see how this is an issue of libgdx.
