### ISSUE TITLE
Possible BUG: Rectangle.contains does not work as expected

### ISSUE THREAD

**Issue by sasadangelo** [libgdx/libgdx#4236]
Hi,

Analyzing source code of Rectangle.contains(int, int) it seems there is a problem when width and height are equal to 1. Here the code:

public boolean contains (float x, float y) {
		return this.x <= x && this.x + this.width >= x && this.y <= y && this.y + this.height >= y;
	}

Let me do an example.
Suppose I have a rectangle with x=5, y=5, width=1 and height=1. If it would be a rectangle on a screen it could be a single pixel.

Then I have the point x=5,y=6 (like a pixel at ccoordinate 5,). 
Obviously it is not contained into the rectangle. The problem is that according to the code it is, because all conditions are true, in fact:
5<=5 is true
5+1>=5 is true
5<=6 is true
5+1>=6

Am I right?

**Comment by xoppa** [comment]
The Rectangle coordinates have nothing to do with pixels. Perhaps try your example with fractional numbers to better understand why this is not an issue.

**Comment by sasadangelo** [comment]
Hi
I know rectangle  is not relative to a pixel. It was just an example. If my understanding is correct Rectangle should work with integer numbers. I Hoped to do a favor but I only receiver a non answered.  Can you exploit why You think this code should work. If I use Point in a space whee rectangle start in x, y and end in width-1 height-1 as in whatever frame work this code cannot work. I am 100% sure. Probable there is an assumption that I do not know and I would like to understand.

**Comment by xoppa** [comment]
This is an issue tracker, please use the forum or IRC if you need help or have a question. 
See also: https://github.com/libgdx/libgdx/wiki/Issue-Tracker.

**Comment by MobiDevelop** [comment]
For what it is worth, all other frameworks (that I've used) do require that the tested point be less than the extents of the rectangle to be _contained_. The same parameters to standard Java, .NET, and Android rectangle contains methods all return `false` while we return `true`. I agree that this result is _unexpected_, when considering how other frameworks work in similar scenarios.

**Comment by xoppa** [comment]
Afaik the [java](https://docs.oracle.com/javase/7/docs/api/java/awt/Rectangle.html), [.NET](https://msdn.microsoft.com/en-us/library/system.drawing.rectangle(v=vs.110).aspx) and [Android](https://developer.android.com/reference/android/graphics/Rect.html) rectangle classes all target canvas graphics and have integer coordinates. Or do you mean that there's a comparable class that also uses floating point coordinates and doesnt include the top/right edges in its `contains` method? In my experience with (collision) shapes you'd rather have a false positive than a false negative due to floating point errors. E.g. Bullet uses a margin to make the shape slightly bigger to compensate for possible floating point errors.

**Comment by MobiDevelop** [comment]
Yes, they all have float variants which do not include the bottom/right edges (since they are y-down). I don't necessarily think that we need to change anything (other than maybe documenting it) - but I can see how it would be unexpected.
