### ISSUE TITLE
WIKI free edit

### ISSUE THREAD

**Issue by andrkhar** [libgdx/libgdx#4272]
I can make any changes to wiki without being in libgdx group. Is it correct behavior? Someone bad guy can delete all wiki of the awesome libGDX or change links for advertisement. Please be aware!

I discovered this after I followed link in JSON page today. The link was bad. So I edit and write !BAD LINK!

Please keep wiki safe!

**Comment by MobiDevelop** [comment]
Would have been more helpful to just remove the link and surrounding text (which I've just done).

The wiki is editable by anyone with a github account so that people can contribute. Yes, there is a certain level of trust that goes along with that, but in general the benefits outweigh the risks.

Thanks for letting us know of the bad link.

**Comment by andrkhar** [comment]
Thank you for your quick detailed explanation. I hope people are not evil enough to spoil it. I will use your advice in future.
