### ISSUE TITLE
BitmapFont Scale doesn't work properly

### ISSUE THREAD

**Issue by little-dgek** [libgdx/libgdx#4278]
Please ensure you have given all the following requested information in your report.

#### Issue details
After update 1.9.4 bitmapFont.getData().setScale(x,y) doesn't work for widgets in widgetgroup. 

#### Reproduction steps/code
Create the font using BitmapFontGenerator, set scale and use this font for TextButton/Label/etc

<img width="700" alt="2016-08-29 0 56 41" src="https://cloud.githubusercontent.com/assets/9482740/18037044/7d7e44f0-6d83-11e6-847e-bc42df15be69.png">

Left image - 1.9.3, Right - 1.9.4

#### Version of LibGDX and/or relevant dependencies
1.9.4

#### Please select the affected platforms
- [*] Android
- [*] iOS (robovm)
- [*] iOS (MOE)
- [*] HTML/GWT
- [*] Windows
- [*] Linux
- [*] MacOS

**Comment by psiegel** [comment]
I was just logging in to report this bug myself.  Since upgrading to 1.9.4, all my fonts are enormous.  I believe the culprit is this change:

https://github.com/libgdx/libgdx/commit/6602a80d39212c935956506823657524f3a3a3da

In my case, I have values set in my uiskin.json file for the scaledSize value of my fonts.  This sets all font scales to a value other than 1 when initially loaded in the skin.  I do not set my label scale values at all, so they remain at their initialized value of 1, which is different from the value in the underlying font, so the Label code here always forces them back to 1.

**Comment by psiegel** [comment]
Ah, I see there's further discussion and an open pull request around this:

https://github.com/libgdx/libgdx/issues/4232
https://github.com/libgdx/libgdx/pull/4270

**Comment by Tom-Ski** [comment]
This should be resolved by https://github.com/libgdx/libgdx/pull/4270
