### ISSUE TITLE
ButtonGroup throws ClassCastException when accessing through getAllChecked()

### ISSUE THREAD

**Issue by seudein** [libgdx/libgdx#4294]
Adding buttons to button group:

``` java
ButtonGroup<TextButton> btnGrp = new ButtonGroup<TextButton>();
TextButton btn = new TextButton("body", menu.buttonStyle);
btnGrp.add(btn);
```

Accessing clicked buttons:

``` java
Array<TextButton> btns = btnGrp.getAllChecked();
System.out.println(btns);
System.out.println(btns.toArray());
System.out.println(btns.items[0]);
```

Log:

```
[TextButton
|  Label: Body]
[Ljava.lang.Object;@16b9a615
Exception in thread "LWJGL Application" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lcom.badlogic.gdx.scenes.scene2d.ui.TextButton;
    Stacktrace to last 'accessing clicked buttons' line
```

---

Also has same exception here:

``` java
btns.toArray()[0]
```

affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

libgdx v: 1.9.4

**Comment by CyborgGecko** [comment]
Do you by chance have an example file where this occurs?

**Comment by Darkyenus** [comment]
This happens because generic `Array` storing checked (and all) buttons is [created without `Class<>` argument](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ButtonGroup.java#L28), so the array you ultimately get in `btns.items[0]` is not really of type `TextButton[]` but of type `Object[]`. However when indexing, Java expect it to be the former (for some technical reason) and thus complains.

I'm afraid this is a won't fix, as the `ButtonGroup` has no good way of knowing what `Class` corresponds to its generic parameter and thus can't pass it to the `Array`s.

This is the reason you shouldn't directly access/use `Array#items` field - use `Array#get(int)` instead, which does not suffer from this problem.

**Comment by NathanSweet** [comment]
Yep, as @Darkyenus explained, this is a gotcha with libgdx Arrays. If the item type was not specified in the array constructor (or you don't know) then treat the `items` field as `Object[]` or just use the `get` method.
