### ISSUE TITLE
MOE Link third party framework error!

### ISSUE THREAD

**Issue by tianqiujie** [libgdx/libgdx#4355]
I use the moe actions to link framework.

![image](https://cloud.githubusercontent.com/assets/2835129/19235735/22c69b92-8f26-11e6-8f47-25165b7337dc.png)

And the moe plugin will rebuild the xcode file and add some dependencies into the .xcconfig file. For example the admob framework, should add `AdSupport,AudioToolbox,AVFoundation,CoreBluetooth,CoreGraphics,CoreMedia,CoreMotion,CoreTelephony,CoreVideo,EventKit,EventKitUI,Foundation,GLKit,MediaPlayer,MessageUI,OpenGLES,SafariServices,StoreKit,SystemConfiguration,UIKit`to the xcconfig file.

But the setup.jar set the generateProject false,  so I have to add dependencies manually. Can you please make the 'generateProject true' so that the moe plugin can automatically add dependencies by rebuild the xcode project file.
#### Version of LibGDX and/or relevant dependencies

libgdx 1.9.5-SNAPSHOT
moe-gradle:1.2.0
#### Please select the affected platforms
- [ ] iOS (MOE)

**Comment by vbousquet** [comment]
The generateProject is discouraged as of MOE 1.2 (see [here](https://multi-os-engine.org/blog/2016-09-30-removed-features/)) and will be deprecated in MOE 1.3. So I don't think this would be the solution.

From my humble point of view, this seems as an issue for MOE and not LibGdx since this is not linked to LibGdx. Therefore, I would suggest pushing the question to the MOE forum [here](https://discuss.multi-os-engine.org/).

**Comment by Tom-Ski** [comment]
generateProject was incompatible with our build so we sticked with it off. 

Thanks @vbousquet for digging into this, looking forward to see the solution the MOE team work towards.  In the mean time you'll have to manually adjust your xcode project, I suggest you do this through xcode itself when you import the libgdx project there.
