### ISSUE TITLE
Bullet wrapper - Some upcast static methods are missing

### ISSUE THREAD

**Issue by parnold-x** [libgdx/libgdx#4407]
Hello, it seems like some static upcast methods are not wrapped.
For example the btRidgidBody has no upcast method that it should have according to 
https://github.com/libgdx/libgdx/wiki/Bullet%20Wrapper%20-%20Using%20the%20wrapper#extending-classes

**Comment by xoppa** [comment]
Thanks for reporting. It [was removed](https://github.com/libgdx/libgdx/pull/462/commits/224b0a377a2df7bb56b925330f81bc42399e0b6e) because of [this issue](https://code.google.com/archive/p/libgdx/issues/1453). Because bodies are always created in java they don't need an upcast and can directly be casted. Would you mind to contribute an update to the wiki to fix this in the wiki, it's publicly editable.

**Comment by parnold-x** [comment]
Thanks for the answer. Tried to update the documentation.
