### ISSUE TITLE
[Feature request] setDefaultHideAction() and setDefaultShowAction() for Dialog

### ISSUE THREAD

**Issue by Betalord** [libgdx/libgdx#4503]
Currently, the Dialog class does not provide a way to set actions that happen on hide() and show(). The source code uses some default hardcoded actions that cannot be changed (if not by manually calling show() and hide() methods, which is a problem, especially with hide() because it gets called automatically and you have no control over it):

```
	public void hide () {
		hide(sequence(fadeOut(0.4f, Interpolation.fade), Actions.removeListener(ignoreTouchDown, true), Actions.removeActor()));
	}

	public Dialog show (Stage stage) {
		show(stage, sequence(Actions.alpha(0), Actions.fadeIn(0.4f, Interpolation.fade)));
		setPosition(Math.round((stage.getWidth() - getWidth()) / 2), Math.round((stage.getHeight() - getHeight()) / 2));
		return this;
	}
```

So I think it would be very useful to have the following methods:

```
private Action showAction, hideAction;

public void setDefaultShowAction(Action showAction) {
	this.showAction = showAction;
}

public void setDefaultHideAction(Action hideAction) {
	this.hideAction = hideAction;
}
```

That would then be used as following:

```
	public void hide () {
		hide(hideAction);
	}

	public Dialog show (Stage stage) {
		show(stage, showAction);
		setPosition(Math.round((stage.getWidth() - getWidth()) / 2), Math.round((stage.getHeight() - getHeight()) / 2));
		return this;
	}
```

**Comment by MrStahlfelge** [comment]
This is something I often wanted. For next it would be enough to have overridable (protected) methods returning the Action used.

**Comment by NathanSweet** [comment]
Storing actions in a field is a bit odd, as they may be needed multiple times. Depending on the action you want to use and what state it needs, you may want to create the action when it is needed. Maybe fields could be made to work, but we don't do that anywhere else.

You could override `show(Stage)` and/or `hide()` and use your own actions instead of the default implementation, which is what I do in my apps. I see `show(Stage)` calls `setPosition`, which makes overriding the method slightly more cumbersome. Would have to investigate the ramifications of removing or moving that `setPosition` call so it doesn't need to be in the overridden method.

**Comment by MrStahlfelge** [comment]
I agree storing the actions in a field is not the way to go.
It is not only setPosition that is a problem. It's also a problem that part of the Actions is for animation (`fadeOut(0.4f, Interpolation.fade)`), another part is needed for correct behaviour of the Dialog (`Actions.removeListener(ignoreTouchDown, true), Actions.removeActor()`).

I suggest using a protected (thus overridable) method to create the Actions, not a field: 

	public void hide () {
		hide(sequence(getHideAction(), Actions.removeListener(ignoreTouchDown, true), Actions.removeActor()));
	}

	protected Action getHideAction() {
		return fadeOut(0.4f, Interpolation.fade);
	}

The `setPosition` needs to stay in the `show` method, because sometimes it is also needed to overide it. I have games moving the dialogs from outscreen to center for showing them.

**Comment by MrStahlfelge** [comment]
Wow, we already have this since 1.9.7! Introduced with 67f445aede75ec4ecefc24cbf1ca26364d85b420 - so we can close this.
