### ISSUE TITLE
Why does Timer thread sometimes not get started when starting an app in Libgdx?

### ISSUE THREAD

**Issue by vminc** [libgdx/libgdx#4549]
Please ensure you have given all the following requested information in your report.

#### Issue details
_Please provide the details of your issue_

Sometimes when my Activity gets started, the Libgdx's Timer thread is not started at all (I figured this out by attaching a breakpoint) and all the timer functionalities don't work (https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/utils/Timer.html). This doesn't happen consistently. Is this a known bug?

#### Reproduction steps/code
Not consistently reproducible.

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by hardik124** [comment]
Can you please provide steps for reproduction?

**Comment by javaddict** [comment]
Yes! I have been running into the same situation recently.
It is very unpredictable and hard to reproduce. I finally nail it at its last appearance.

The cause is that the execution of method 'dispose()' in class
'com.badlogic.gdx.utils.Timer.TimerThread' should have set 'instance' to null but
somehow it is not. I don't know how could this happened. It is just what the debugger told.
So next time when 'Timer.schedule(...)' is called, the constructor of 'TimerThread'
is not executed. 'Timer.instance()' just keep returning a dead instance which won't
trigger any task on it.

Currently my workaround is to have the line
`instance = null;`
executed before
`Gdx.app.removeLifecycleListener(this);`
But I don't know if it works or just luck not running into this bug.
