### ISSUE TITLE
SVG support for libgdx

### ISSUE THREAD

**Issue by bitbrain** [libgdx/libgdx#4567]
Are there future plans to integrate SVGs into libgdx? The font rendering already allows the rendering of fonts to a `Texture`, however I could not find any information about rendering .svg files to a texture, including scaling and resizing.

**Comment by Darkyenus** [comment]
Font rendering is IIRC done entirely in freetype library, which is unsuitable for general purpose svg rendering. For my projects, I have created a [tool](https://github.com/Darkyenus/ResourcePacker) which rasterizes svg's and packs it all into texture atlases, but the code is unsuitable for use at runtime.

It would be interesting to create a libGDX extension for general purpose, runtime svg rendering though.

**Comment by Tom-Ski** [comment]
This topic has come up before on here, in the irc and on the forums. The short answer is no, there is no plan right now to support it in the future. 

I think there have been efforts to make cross platform extensions, but afaik (from others), all the libraries out there that would be suitable for cross platform use suck.  I don't use SVGs so that might be wrong, but that was the last I heard.  I don't think any of the core contributors would be working towards this, they can pipe up if they want to volunteer, so it would have to come in the form of a PR.  As we would not be maintaining this ourselves it would be better suited as a third party extension.

**Comment by bitbrain** [comment]
Thanks for the info!
