### ISSUE TITLE
[GWT] error in gdx.gwt.xml

### ISSUE THREAD

**Issue by SergeyLabutin** [libgdx/libgdx#4579]
I cat not compile gwt project. I add next lines for compile without errors

exclude name="utils/DataBuffer.java"
Reason: change name for overrided member

exclude name="utils/PauseableThread.java"
Reason: wait() and notifyAll() is undefined

exclude name="graphics/g3d/environment/SphericalHarmonics.java"
Reason: use Array.clone()

#### Version of LibGDX and/or relevant dependencies
1.9.5

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by tommyettinger** [comment]
1.9.5 had all sorts of nasty GWT issues, if I remember it right, including BitmapFont never working. Updating to GWT 2.8.0 and libGDX 1.9.8 fixes them.

**Comment by SteveSmith16384** [comment]
I'm on Gradle v 4.6 and LibGDX 1.9.9 and have exactly the same errors?

**Comment by tommyettinger** [comment]
Well, oddly, `PausableThread` is added to be included in the reflection cache, but the class is actually called `PauseableThread` with an `e`. So I don't know if an exclude is strictly necessary for that one, but it shouldn't be included in `gdx.gwt.xml` because it does call `Thread.notifyAll()` and `wait()`. Unless Thread is super-sourced and implements those somehow, including PauseableThread would be bad.

@SteveSmith16384 you have exactly the same errors as... the ones Sergey described how to fix? You can add these lines to your own project's `gwt.xml` files and they'll be used as if they were in libGDX's `gwt.xml` file, by the way; all of those files get merged.

**Comment by SteveSmith16384** [comment]
Thanks for the reply; I misread Sergey's original post and didn't realise it was actually the solution as well as the problem.  This does indeed fix it.  Thanks.

**Comment by MrStahlfelge** [comment]
Closing, problem is fixed.
