### ISSUE TITLE
Run desktop version

### ISSUE THREAD

**Issue by DarkDrim** [libgdx/libgdx#4585]
#### Issue details
When I run desktop version - app do not compile and run

#### Reproduction steps/code
I use last version of libGDX.
This is empty project (I use gdx-setup.jar).
But after I run desktop config - I get message "Process finished with exit code -1073740791 (0xC0000409)".
In folder \desktop\build\libs size of file desktop-1.0.jar 2 kb!!!

But if I run gradle desktop dist - size of desktop-1.0.jar ~6 mb and it can be run.

Desktop configuration:
![2017-01-31 23 03 56](https://cloud.githubusercontent.com/assets/3989836/22484433/13b6f682-e80a-11e6-867a-14c017501bce.png)

Please, help me! I do not understand, why not start a desktop project..
PS sorry for my English.

**Comment by agmcleod** [comment]
Yeah the .jar file won't be populated until you run the distribution task, as you discovered. Running the desktop configuration doesn't use that JAR, but compiles the class files via gradle, and runs things that way. Not sure what your issue is, but you can always try running the `desktop:run` task and see if that helps.

Note that github issues are reserved for actual issues with libgdx, where as this is more of a support request. The libgdx folks have a forum here: http://www.badlogicgames.com/forum/. There's also an IRC channel as well. If you're still having problems, please ask on one of those channels.

**Comment by badlogic** [comment]
NVIDIA botched their latest driver update. They are working on a fix. In
the meantime you can downgrade your NVIDIA driver to the previous version
from December 2016.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
