### ISSUE TITLE
Add topics to Github repo

### ISSUE THREAD

**Issue by beatgammit** [libgdx/libgdx#4587]
Github [recently added topics](https://github.com/blog/2309-introducing-topics) and it would be nice to add these to the github repo to help people find `libgdx`. Some ideas:

- game-engine
- multi-platform
- opensource

**Comment by davebaol** [comment]
I agree.
Yesterday I've added topics to gdx-ai.
But I've no rights to do it on the libgdx repo.

**Comment by mgsx-dev** [comment]
It would be nice to agree on topics for libgdx extensions as well (libgdx-extension) across libgdx related repo, It would be helpful to quickly find non official libgdx third party extensions and new coming ones.

@beatgammit for libgdx repo :
* "game-engine" may not be the right topic, it's more a "game-framework" than "game-engine" see ["Libgdx aims to be a framework rather than an engine"](https://github.com/libgdx/libgdx/wiki/Introduction)
* IMO "cross-platform" would be better than "multi-platform" 
* I think "opensource" is not really helpful for public github repository, Apache licence is enough to describe how opened it is (free for comercial use, no patent ...).

Maybe too many topics would kill topics.

**Comment by davebaol** [comment]
About libgdx topics I'd say something like
`java` `game-framework` `cross-platform` `2D` `3D`
and maybe you could mention supported platforms too
`android` `iOS` `html5`  `windows` `linux` `Mac OS X`

**Comment by davebaol** [comment]
@Tom-Ski 
Sweet!
