### ISSUE TITLE
Bump libGDX project files to default to Java 1.7

### ISSUE THREAD

**Issue by wiverson** [libgdx/libgdx#4619]
Please ensure you have given all the following requested information in your report.

#### Issue details
As described at 

(http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=25857&sid=35f8facdf61ae0641f629dc612fb0a68)

https://github.com/libgdx/libgdx/wiki/Setting-up-your-Development-Environment-%28Eclipse%2C-Intellij-IDEA%2C-NetBeans%29

The default instructions for libGDX install indicate Java 1.7 is required, but the default Gradle files reference 1.6, which causes noise in builds and confusion.

I would be happy to take a stab at a PR for this, just leave a comment if you would like me to do that.

#### Reproduction steps/code
Build any project with the standard Setup tool.

#### Version of LibGDX and/or relevant dependencies
1.9.5+

#### Please select the affected platforms

All or N/A, depending on how you look at it.

**Comment by Tom-Ski** [comment]
You need Jdk 1.7, but you can compile with 6 source level for maximum compatibility (which is what is set by default)

**Comment by mgsx-dev** [comment]
Not sure where to continue discussion (badlogic forum thread or this issue).

At the origin of my question, I had issues compiling at source level 6 with jdk 7 because I was using stuff not available in jdk 6 : Integer.compare() was one of these. And eclipse didn't complains about that.

I tried with gdx-ai for instance and they use @SafeVarargs which is available since jdk7. Then gdx-ai wouldn't run on jre6. Eclipse show compilation errors when using jdk6 but not when using jdk7.  

So using  a jdk that doesn't strictly match source level can lead to some issues.

**Comment by MobiDevelop** [comment]
Using Java 7 APIs prevents running on Android versions lower than 19 because they aren't supported there. That said, Java 7 language features are supported (because they are backwards compatible at the bytecode level). We aim for maximum compatibility with our supported platforms - would rather it fail at compile time than at runtime.
