### ISSUE TITLE
Json parse to HashMap<ArrayList<>> throwing StackOverflowError

### ISSUE THREAD

**Issue by RubicCube** [libgdx/libgdx#4673]
My Json is:

    {
    "objects":{
        "apple":[
            {"x":3, "y":5},
            {"x":6, "y":9}
        ],
        "car":[
            {"x":7, "y":9},
            {"x":5, "y":8}
        ]
     }
     }

Code:

    import com.badlogic.gdx.utils.Json;
    import java.util.ArrayList;
    import java.util.HashMap;

    public class ClassA{
        public Integer x, y;
    }

    public class ClassB{
       public HashMap<String, ArrayList<ClassA>> objects; 
    }

    public static void main(String[] args) {
    Json json = new Json();

    ClassB classB = json.fromJson(ClassB.class, "{\n" +
            "            \"objects\":{\n" +
            "                \"apple\":[\n" +
            "                    {\"x\":3, \"y\":5},\n" +
            "                    {\"x\":6, \"y\":9}\n" +
            "                ],\n" +
            "                \"car\":[\n" +
            "                    {\"x\":7, \"y\":9},\n" +
            "                    {\"x\":5, \"y\":8}\n" +
            "                ]\n" +
            "            }\n" +
            "        }");

    System.out.println(json.toJson(classB));
    }

#### Issue details
I use "Libgdx", "json.fromJson" is works fine and when i call "json.toJson(classB)" an exception throws:

    Exception in thread "main" java.lang.StackOverflowError
    at com.badlogic.gdx.utils.JsonWriter$OutputType.quoteValue(JsonWriter.java:187)
    at com.badlogic.gdx.utils.JsonWriter.value(JsonWriter.java:88)
    at com.badlogic.gdx.utils.Json.writeValue(Json.java:574)
    at com.badlogic.gdx.utils.Json.writeFields(Json.java:290)
    at com.badlogic.gdx.utils.Json.writeValue(Json.java:580)
    at com.badlogic.gdx.utils.Json.writeFields(Json.java:290)
    at com.badlogic.gdx.utils.Json.writeValue(Json.java:580)
    ...

When i change "ArrayList" to String(etc) on HashMap in ClassB the code works fine.

So why an exception is thowing when i use "ArrayList" and how can i parse my json to ClassB instance?

It is probably a bug
[stackoverflow link](http://stackoverflow.com/questions/43054621/json-parse-to-hashmaparraylist-throwing-stackoverflowerror-in-libgdx)

#### Version of LibGDX and/or relevant dependencies
        gdxVersion = '1.9.6'
        roboVMVersion = '2.3.0'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
When you parse the `HashMap<String, ArrayList<ClassA>>` you get a HashMap where values are ArrayLists, but each ArrayList contains JsonValue objects, not ClassA objects. This is because `Json` doesn't support multiple levels of generics. JsonValue is what you get when the type is not known. Supporting multiple levels of generics has been deemed too complex for `Json`, which is not often used for such complex object graphs. I suggest using Kryo instead, which is also much faster and the output much smaller.

**Comment by RubicCube** [comment]
As far as I understand, there is no solution for now with "libgdx json".
Ok i will use Kryo.
Thank you.

**Comment by NathanSweet** [comment]
You could use `Json` then process the data structures afterward, swapping JsonValue entries in the ArrayList with the appropriate class. Kryo will be better though. Likely you'll want to use TaggedFieldSerializer.

**Comment by terebusk** [comment]
Would Kryo solution work in GWT? I've experienced the same problem with trying to save multiple levels of Object<String, Array<String>> but I'm not sure what to proceed with in case it is limited by GWT.

**Comment by NathanSweet** [comment]
Yes, Kryo can be used with GWT. [Here](http://esotericsoftware.com/gloomhaven-helper-web) is an app that uses Kryo.

**Comment by tommyettinger** [comment]
I just want to point out, since someone found this issue 4 years later, that out-of-the-box Kryo **does not work** with GWT, due to at minimum the lack of a .gwt.xml file and more significantly the presence of several .jar dependencies with no present sources. In addition, not only does `UnsafeUtil` not work on GWT because of the missing `sun.misc.Unsafe` class, the static-block check for whether `Unsafe` can be used in `Util` will fail due to `System.getProperty()` not existing on GWT. `Class.isAssignableFrom()` is used in `Util` as well, and it isn't present on GWT either.

I don't really know how GloomHaven-Helper-Web works internally, but it isn't straightforward to get Kryo working on GWT, to say the least. It would be nice if there were some guide to getting Kryo working on GWT, though, if getting Kryo on GWT is at all feasible.
