### ISSUE TITLE
[Feature request]Multiple textures of the same usage in gdx.graphics.g3d.Model

### ISSUE THREAD

**Issue by Daedronus** [libgdx/libgdx#4732]
It would be nice if we could have more then one texture of a specific usage, something like:
TextureAttribute.Diffuse
TextureAttribute.Diffuse1
TextureAttribute.Diffuse2
...etc....
similar to how UV maps are handled.

It's kinda wird to export a baked light map from blender as things are right now.

**Comment by xoppa** [comment]
What would be a use-case for this and how should this be handled in the shader?

**Comment by Daedronus** [comment]
In blender you can UV map and bake the light maps and the ambient occlusion, on top of this you usually add a diffuse color map, like the bricks on a wall.
It's not feasible to combine the two because the diffuse texture can be tiled and/or have much higher resolution.
The fragment shader does something like ambient color * light map (if present) * diffuse map (if present).

Not sure if there are use cases for the other texture types but I would not mind the flexibility, it would be up to the shaders the users create to sort what texture does what, the default shader could ignore them.

**Comment by xoppa** [comment]
Well, in that case you would still have one diffuse texture and not more than one. So your feature request is to add a new TextureAttribute type, e.g. TextureAttribute.LightMap?

**Comment by Daedronus** [comment]
The problem is blender has no notion of a lightmap texture, you would set it up as another texture that influences the diffuse color.
In fact a lightmap is kinda of a second diffuse texture and having generic support for extra textures would be the more flexible solution imho.

**Comment by xoppa** [comment]
Misusing the Diffuse usage for what actually is a LightMap sounds like a bad idea and defeats the purpose of the material attributes. Either way, regardless of whether you call it "Diffuse2" or "LightMap" doesn't really matter. You would still have to map the texture from the fbx file to the material attribute. My guess is that you can't rely on the second texture to always be the light map.

With that said, I guess a generic approach is possible. But that will make things alot more complicated. I'm not sure whether that (a generic approach instead of specific use-case) is worth it. But if you like, you can give it a try of course. https://github.com/libgdx/libgdx/blob/master/.github/CONTRIBUTING.md

**Comment by slebed** [comment]
A lightmap doesn't have anything to do with a diffusemap.  A lightmap is just luminance information (texture) and should get multiplied on top of the diffusemap.

**Comment by mgsx-dev** [comment]
I think this one could be closed, default libgdx shader provides minimal classic shader features, for advanced features, it has to be implemented by user code or use extension like [https://github.com/mgsx-dev/gdx-gltf](gdx-gltf) which provides a PBR shader with ambiant occlusion maps and such.
