### ISSUE TITLE
[Feature Request] Stop using "private" modifiers

### ISSUE THREAD

**Issue by doit-ceo** [libgdx/libgdx#4883]
#### Issue details
LibGDX is a great OSS, but some class are designed with Java best practice, that may not fit well in OSS model, for example it's recommended in Java to private most internal variables and methods, however this may not be the best solution for OSS. I open this ticket to maybe start a rule to remove all "private" & "default"  modifiers from the source as this greatly limit our ability to customize the classes without the need of manual copy & paste the whole class (in some cases this is not even an option).

A quick example would be HorizontalGroup.computeSize() & HorizontalGroup.layoutWrapped() they both are private and I can't modify them. In this class it's possible to duplicate the whole class (but bad for future compatibility), but Label.computePrefSize() is more problematic example, Label is being used in other components such as Buttons, Tables, etc, so we can't even duplicate the class and modify it. 

I highly recommend marking all internal variables and methods with "protected" modifier. 

I know this may not be an "Issue" but I think this will reduce issues in the future and allow users to fix their issues themselves.

**Comment by mgsx-dev** [comment]
Sounds like anti-pattern and not related to OSS. You may need to read more about OOP design and API meaning, this might enlight you a little : 

* https://stackoverflow.com/questions/8353272/private-vs-protected-visibility-good-practice-concern
* https://stackoverflow.com/questions/2028495/when-do-you-write-a-private-method-versus-protected

I suggest you to continue this discussion in IRC or forum and closing the issue.

**Comment by Darkyenus** [comment]
If everything were private, each change would be breaking, which would be very bad for future compatibility. You are right that some of the classes could be designed to be more extensible, but simply changing the access modifiers is not the way to go. Also, the argument that "encapsulation does not apply because this is OSS" is moot - the encapsulation is not for obfuscation.

You won't get far by being patronizing here.

**Comment by mgsx-dev** [comment]
@doit-ceo I didn't wanted to upset you, sorry. Indeed, make some feature accessible/extendable sounds reasonable but should be stated on a case by case basis and shouldn't be a general rule since it would break encapsulation.

I won't argue further on this subject out of respect for watchers.

**Comment by RUSshy** [comment]
I agree with you, i wish more method where public, sometimes it is hard to extend stuff, so i end up with lot of copy paste

**Comment by Tom-Ski** [comment]
protected methods and fields need to be protected with forethought, not just by default. Subclassing classes is very common, and is done all the time even if the developer does not have extensive knowledge of the parent class. 

We have no problem fixing and changing the scope of certain classes, as you can see from many previous PRs on this repo, but they have to be evaluated on a case by case basis.  

Your specific example may be an example of a case where the scope can be changed, and I'm sure there are many more in the repo. Please feel free to submit a PR, explaining your reasoning for the specific case and if its valid and supported it will no doubt be merged.  Changing everything to protected is not a solution for this.

**Comment by doit-ceo** [comment]
I think my message was not clear, so let me start over 

1. All **fields** should be declared as private and encapsulated, **encapsulation should be respected even within the class** (i.e. getWidth() & setWidth()) and no direct field access. 
2. All **methods** should be **public** or **protected** & **no private methods**. 

I'm calling for more OOP as long it's done right & I'm calling for more respect to encapsulation (currently ignored in LibGDX), for example width, height, x, y, in Actor class were all declared with default modifier and they are being extensively accessed directly in many other classes (bypassing getter & setter), in this case "getWidth()" should be marked as "final" otherwise overriding that is dangerous. If encapsulation is done and being respected, the field should be private. 

For my second point, marking a method with private modifier, and thinking this will protect users is imaginary ! as they do have the power to copy the whole class ! or simply override the public calling method !  it just make them do more work, nothing more, nothing less. 

If the 2 points above accepted, the code will be clean and extendable and removes the guess work.

Thanks

**Comment by NathanSweet** [comment]
> my question why some code / developers in LibGDX explicitly choosing to have some methods modifiers as private, for instance in HorizontalGroup, you have HorizontalGroup.layout() as public, while HorizontalGroup.layoutWrapped() is private ! the developer here didn't even maintain one 'pattern', also what is he trying to hide or protect ?

That would be me. `layout` is public API, it is implementing a `Layout` interface method. `layoutWrapped` performs internal logic and never makes sense to call it from outside the class. If you have the case where you want to customize wrapped layout, you can just override `layout`, since if your group uses wrapping mostly all it does is call `layoutWrapped`.

You say it would reduce support by making everything private, but instead it would mean that any change we make likely breaks users. It takes away our ability to judge how much impact our changes have. Breaking changes frustrate users greatly and increase support, as people complain and need to ask how they fix what was broken.

Also, if everything is public, it exposes all sorts of things that the user shouldn't be calling or modifying. Classes can easy get in unexpected or invalid states. The worst part is that the user is no longer able to tell what is OK for them to manipulate. They will quickly be doing terrible things, then have to ask for support.

Likely some of the direct member access you mentioned comes from the performance impact of method calls on Android. Even if that is no longer true, there is too much code to make it worth the effort to change internal code to use getters/setters. Also, I don't feel it's a great pattern for a subclass to replace a property by overriding the getter/setter, so I don't care to design classes to support that. Subclasses are tightly coupled and there are plenty of ways they can break things. There is only so much we can do to stop people from doing stupid things. Opening everything up so it's even less clear which things are stupid is a terrible idea, it's not going to happen.

There's no magic fix. Exposing everything is extreme and causes far more problems than we have now. Exposing nothing is also extreme, but marginally better. We are somewhere in the middle.

I suggest treating the places where you are stuck because of private access modifiers as feature requests. Or, consider forking libgdx locally, remove the access modifiers as you need so you can move on and be productive. You only need to recompile the Java sources, which is easy, and can use the natives and other stuff from `master`.
