### ISSUE TITLE
Extendability Issues

### ISSUE THREAD

**Issue by Dakror** [libgdx/libgdx#4921]
Hi, I'm using libGDX for quite a while now and I finally decided to "speak up".
I find it very annoying and problematic that the library is hardly extendable / overrideable.

Today I tried to fix Tooltips out of the box crashing on Android (for which I might open another issue).
The easy fix for me would be to extends Tooltip and fix the issues there. But most if not all important Class fields are package private and never protected. So my only option is to fork the library, make my change and use the library from source in my project, which I find rather cumbersome.

Same goes for ScrollPane in my last project. I only wanted to change a little thing and whoop, had to swap out the entire 2k+ lines class to replace some fields access modifiers.

Who made the design choices / lacks the supervision of maintaining an extendable, flexible framework design?

Regards

**Comment by Velocity-** [comment]
Nobody lacks those skills, you lack the skill to work with open source projects. That is your own lack of skill, not the "lack of supervision in extendable, flexible framework design". Instead of complaining about what is broken, create a pull request with a fix and contribute to the open source community? I'm pretty sure that makes us all move forward. Whining on an issue tracker does not.

Next time you decide to speak up, please think about whether you have the right to speak up. Insulting the maintainers of this project only makes you sound incredibly rude and incapable.

**Comment by badlogic** [comment]
I would appreciate if the tone could be less confrontational. I do not feel
insulted, and while I wished Maximilian would have send a PR instead of
letting of steam, I can understand frustration (having used other people's
code myself :)).

Maximilian, we do think about extensibility, but it needs to be balanced
with maintainability. Protected fields and methods are a public contract,
preventing us to change the internals of an API. As such, we are open to
change things, but onoy if there are good reasons.

The preferred way to get changes going is to fork the repository, create a
patch with the wanted changes, then sending a PR with reasons why the
change is better than what's there at the moment. The reasoning should not
onoy include extensibility, but also some thoughts on what this means in
terms increase in API surface and the impact on the changability of the API
implementation.

On Oct 17, 2017 2:48 PM, "Bart Pelle" <notifications@github.com> wrote:

Nobody lacks those skills, you lack the skill to work with open source
projects. That is your own lack of skill, not the "lack of supervision in
extendable, flexible framework design". Instead of complaining about what
is broken, create a pull request with a fix and contribute to the open
source community? I'm pretty sure that makes us all move forward. Whining
on an issue tracker does not.

Next time you decide to speak up, please think about whether you have the
right to speak up. Insulting the maintainers of this project only makes you
sound incredibly rude and incapable.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/libgdx/libgdx/issues/4921#issuecomment-337220499>, or mute
the thread

**Comment by Dakror** [comment]
I understand your point and apologize for my rather rude tone. You may have seen that I've already submitted a proper PR with the one-liner fix for the particular issue.
