### ISSUE TITLE
Android: Bluetooth keyboard is not detected by isPeripheralAvailable

### ISSUE THREAD

**Issue by MrStahlfelge** [libgdx/libgdx#4968]
#### Issue details
Gdx.input.isPeripheralAvailable returns false if a Bluetooth keyboard is connected to the device.

#### Reproduction steps/code
Further investigation revealed: 

`if (config.hardKeyboardHidden == Configuration.HARDKEYBOARDHIDDEN_NO) keyboardAvailable = true;`

This is only correct für devices with a built-in slideable hardware keyboard (that are unfortunately vanished from the world). Besides this, a check like the following must be added:

`if (config.keyboard != KEYBOARD_NOKEYS) keyboardAvailable = true;`

#### Version of LibGDX and/or relevant dependencies
All

#### Please select the affected platforms
- [X] Android

**Comment by Zomby2D** [comment]
After a few tests with the two bluetooth keyboards I have at my disposal, one of them would be detected correclty and the other wasn't. After some testing and a few searches, it turns out that some bluetooth keyboards need to have the `navigation` element added to the `android:configChanges` part of AndroidManifest in order to trigger the `onConfigurationChanged()` method.

**Comment by MrStahlfelge** [comment]
I will check if that helps with my keyboard.

**Comment by MrStahlfelge** [comment]
Can confirm, it works! Thanks.
