### ISSUE TITLE
Android: Controller Extension swallows bluetooth keyboard events

### ISSUE THREAD

**Issue by MrStahlfelge** [libgdx/libgdx#4969]
#### Issue details
If the controller extension is added to a libgdx project and a bluetooth keyboard is used on Android, it cannot be used with the libGDX application.

#### Reproduction steps/code
AndroidControllers registers a keylistener on AndroidInput that swallows all events coming from devices that it recognizes as a game controller.

AndroidInput.java 
```
    public boolean onKey (View v, int keyCode, android.view.KeyEvent e) {
    	for (int i = 0, n = keyListeners.size(); i < n; i++)
    		if (keyListeners.get(i).onKey(v, keyCode, e)) return true;
       ...
```

The check if a device is a controller is the following from 
AndroidControllers.java:
```
     private boolean isController(InputDevice device) {
      	return (device.getSources() & InputDevice.SOURCE_JOYSTICK) != 0;
    }
```

Unfortunately, every keyboard has this bit set because every keyboard has a dpad.

The following check must be added to improve the recognitation:
```
    private boolean isController(InputDevice device) {
    	return ((device.getSources() & InputDevice.SOURCE_JOYSTICK) != 0
                      && device.getKeyboardType() != InputDevice.KEYBOARD_TYPE_ALPHABETIC;
    }
```

#### Version of LibGDX and/or relevant dependencies
All

#### Please select the affected platforms
- [X] Android

**Comment by Zomby2D** [comment]
Unfortunately, the issue seems to be a bit more complex than that. I have 2 controllers reporting KEYBOARD_TYPE_ALPHABETIC (one of them actually has a full QWERTY keyboard on the face of the controller) so these wouldn't work with the added check.

I have compiled a [Google spreadsheet](https://docs.google.com/spreadsheets/d/1oYoYMfCv8QlOgEyPxwcdLifjXVIOveu9aopEXl6UjnE/edit?usp=sharing) with some of the devices I had around the house. This should prove useful to figure out a definitive solution.

**Comment by Zomby2D** [comment]
Turns out, once I've given a good look at the compiled results it wasn't that hard to find a pattern.

This is the code I ended up with:
```javascript
	private boolean isController(InputDevice device) {
		Gdx.app.log("device.getSources", Integer.toString(device.getSources()));
		Gdx.app.log("device.getKeyboardType", Integer.toString(device.getKeyboardType()));
		return ((device.getSources() & InputDevice.SOURCE_CLASS_JOYSTICK) == InputDevice.SOURCE_CLASS_JOYSTICK)
				&& (((device.getSources() & InputDevice.SOURCE_GAMEPAD) == InputDevice.SOURCE_GAMEPAD)
					|| (device.getKeyboardType() != InputDevice.KEYBOARD_TYPE_ALPHABETIC));
	}
```

The only device that still mistakenly reports as a controller is my old Microsoft Internet Keyboard Pro. (The keyboard portion doesn't get detected as a controller actually, only the media buttons portion.) I doubt there's going to be that many people trying to play Android games with an odd keyboard from 2001 anyway.

I'm going to do a few more tests, and if all goes well I'll submit a PR. I would like the keyboard keys on my keyboard gamepad to not register as controller buttons when pressed if possible (although there's something interesting about having a 50-buttons gamepad) and I've also noticed that the trackpad on the Ouya controller gets interpreted as movements in the left stick.

**Comment by MrStahlfelge** [comment]
For getting both to work on a mixed device, a way to go is to not leave the processing in `onKey` if the pressed button is a "normal" keyboard key, media or Android button. That would be very desirable because many controllers have media buttons and the wide-spread Amazon FireTV controller has default Android menu/back buttons which are not working at the moment.

Of course, the difficult part here is the distinguish if the pressed button is such a key or a controller button.

**Comment by MrStahlfelge** [comment]
Besides, perhaps you also want to check for analog Axis: 
`((device.getSources() & InputDevice.SOURCE_GAMEPAD) == InputDevice.SOURCE_GAMEPAD
                || (device.getSources() && InputDevice.SOURCE_JOYSTICK) == InputDevice.SOURCE_JOYSTICK)`

**Comment by Zomby2D** [comment]
If you look at my spreadsheet, you will notice that almost every device is a ``InputDevice.SOURCE_JOYSTICK``, including keyboards and even some mice. The current method uses ``(device.getSources() & InputDevice.SOURCE_JOYSTICK) != 0`` which is the functinal equivalent of ``((device.getSources() & InputDevice.SOURCE_CLASS_JOYSTICK) == InputDevice.SOURCE_CLASS_JOYSTICK)``.

**Comment by MrStahlfelge** [comment]
Are you sure that it is functional equivalent?

Anyway, you are right that I got confused, the current method uses SOURCE_JOYSTICK. Your check now is better than the one before, so we have an improvement.

**Comment by Zomby2D** [comment]
> Are you sure that it is functional equivalent?

Yes, if something is ``SOURCE_CLASS_JOYSTICK`` but not ``SOURCE_JOYSTICK``, the ``&`` check will return 16 which is the constant value for ``SOURCE_CLASS_JOYSTICK``, so comparing it to ``!=0`` gives the same result as the check I made.
