### ISSUE TITLE
A feature request

### ISSUE THREAD

**Issue by ghost** [libgdx/libgdx#5022]
Feature request:

- Support for specular/diffuse/ambient maps without needing to use shaders.

As a refrence for what I am talking about (random link on internett. Though it uses shading.)

http://trederia.blogspot.no/2013/03/further-enhancing-2d-sprites-with-3d.html

**Comment by Darkyenus** [comment]
That is impossible to do without shaders. However, these features are already implemented in the 3D API, so you don't need to write own shaders. [Xoppa has a really nice tutorial on how to get started with 3D API on his blog](https://xoppa.github.io/blog/).

**Comment by kalexmills** [comment]
@Darkyenus I think that the request is to bake in some high-quality "textbook" shaders for specular, diffuse, and ambient maps, and provide some basic API support for them.

@pitara correct me if I am wrong.

**Comment by pitara** [comment]
Thats true, and 2D libgdx may very well beneifit from shadows as shown in video in the link :)

**Comment by cypherdare** [comment]
SpriteBatch doesn't use enough vertex attributes to support 3D lighting, and it's unlikely to be added because it could significantly impact performance. You can try the [FlexBatch](https://github.com/CypherCove/gdx-cclibs/tree/master/flexbatch) library for that. It doesn't include pre-built shaders, but you can [look here](https://github.com/CypherCove/gdx-cclibs/blob/master/examples/core/src/com/cyphercove/gdx/examples/FlexBatchTest.java) for the example that creates the bump-mapping shown in the picture below. 

[Example image](http://cyphercove.com/wp-content/uploads/2017/09/bump-mapping2.gif)

**Comment by MrStahlfelge** [comment]
@mgsx-dev can you take a look at this issue?

**Comment by mgsx-dev** [comment]
I think Cypherdare already answered the issue : 
* current SpriteBatch is simple, efficient and cover most of use cases, we shouldn't change it
* 3D API covers most of 3D lighting use case but would be inefficient for 2D
* for advanced 2D stuff, you need to either : write your own shaders, implement a custom SpriteBatch or use FlexBatch

Note that advanced stuff like 2D normal maps can be implemented with a custom shader without the need to change SpriteBatch

So i think this request can be closed
