### ISSUE TITLE
Missing validate() or super.draw() in TextField.draw()

### ISSUE THREAD

**Issue by Persuer** [libgdx/libgdx#5035]
#### Issue details
Is validate() or super.draw()  in TextField.draw() missing ? 

#### Version of LibGDX and/or relevant dependencies
1.9.5

**Comment by NathanSweet** [comment]
`validate` calls `layout` if the layout has been invalidated. TextField doesn't override `layout` (probably because the original implementation is super old, predating the Layout interface) and the Widget superclass has an empty `layout` implementation, so it isn't important for TextField to call validate.
