### ISSUE TITLE
intersectSegmentCircleDisplace does not work when the segment is partially inside the circle

### ISSUE THREAD

**Issue by FlorentMasson** [libgdx/libgdx#5070]
#### Issue details
The [Intersector.intersectSegmentCircleDisplace()](https://github.com/libgdx/libgdx/blob/9b8f20b2d0e96e53f0f2b98dc8f6131c810aae71/gdx/src/com/badlogic/gdx/math/Intersector.java#L286
) function is wrong when one of the endpoint of the segment is inside the circle.
![bitmap](https://user-images.githubusercontent.com/9975455/35669305-f1b3ea04-0734-11e8-997d-d375ea7e88f1.png)
The current algorithm calcultates the projection of the circle center on the infinite line (start, end), but returns no intersection if the projection point is not within the segment endpoints (as in the diagram above)

Also, the function is supposed to "returns by how much and in what direction the line has to move away from the circle to not intersect." but it returns by how much and in what direction the line has to move to cross the circle center.

Here's my correction: 

```
	public static float intersectSegmentCircleDisplace(Vector2 start, Vector2 end, Vector2 point, float radius, Vector2 displacement) {
		float u = (point.x - start.x) * (end.x - start.x) + (point.y - start.y) * (end.y - start.y);
		float d = start.dst(end);
		u /= d * d;
		if (u < 0)
			tmp2.set(start);
		else if (u > 1)
			tmp2.set(end);
		else {
			tmp.set(end.x, end.y).sub(start.x, start.y);
			tmp2.set(start.x, start.y).add(tmp.scl(u));
		}
		d = tmp2.dst(point.x, point.y);
		if (d < radius) {
			displacement.set(tmp2).sub(point).nor();
			return radius - d;
		} else
			return Float.POSITIVE_INFINITY;
	}
```

#### Reproduction steps/code
`System.out.println(Intersector.intersectSegmentCircleDisplace(new Vector2(0,0), new Vector2(0,1), new Vector2(0,2),1.5f, new Vector2()));
`
returns Infinity instead of 0.5

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by obigu** [comment]
Wow! I guess nobody has ever used this one, it's pretty bad. 
The implementation of _intersectSegmentCircleDisplace_ is wrong but I believe it should be aligned with the _intersectSegmentCircle_ implementation which is correct and more efficient:
1. Operators should also check for equality (<= and >=)
2. Avoid square roots such as Vector2.dst for efficiency

On a more general note I see several things that could be improved:
1. I miss basic important utility mehods such as the orthoghonal projection of a point in a line or the intersection between line and circle (not a segment).
2. Use Circle as argument instead of center and radius. The reason why some of these methods don't accept it is because Circle class was created afterwards (they were there on first commit! :).
3. Reuse code when possible
4. Add some tests

I'll work on a PR see where it goes that includes a fix for this.

**Comment by anigart** [comment]
Hi, thanks for the fix. Just used the method for the first time and promptly ran into the same issue. Is there a timeline for the merge?

**Comment by obigu** [comment]
That's up to the repository mantainers so I can't tell but this is not a high priority issue (and it's not quick to review) so I wouldn't expect it to be merged soon.

It shoud work for all cases. It's a static independent method so you can just copy&paste it to your project from the PR and use it/test it.

**Comment by anigart** [comment]
Tested the code and it seems the issue where the mtv's normal vector is being set to or left at (0,0) when the segment goes right over the circle's center is still present.
depth is now correct though (e.g., not zero, as it was before).

It's understood that this case is special as it offers two possible solutions of the same value. I think the correct solution would be to pick one though, instead of setting/leaving the mtv at (0,0). Alternatively, it could be documented that this is the expected result.

Repro code:

Vector2 v1 = new Vector2(5.577498f, 5.577498f);
Vector2 v2 = new Vector2(6.5f, 6.5f);
Circle circle = new Circle(6.489414f, 6.489414f, 0.390625f);
MinimumTranslationVector mtvec = new MinimumTranslationVector();
boolean does_intersect = intersectSegmentCircle(v1, v2, circle, mtvec);
System.out.println("intersects: " + does_intersect + ", depth: " + mtvec.depth + ", normal: " + mtvec.normal.toString());
>> intersects: true, depth: 0.390625, normal: (0.0,0.0)

**Comment by obigu** [comment]
@anigart Thank you, it's been fixed
