### ISSUE TITLE
AtomicInteger in HTML5 backend

### ISSUE THREAD

**Issue by sonicfran86** [libgdx/libgdx#5111]
Please ensure you have given all the following requested information in your report.

#### Issue details
HTML5/GWT does not have an implementation of AtomicInteger from java.concurrent.

The Guava version can be used to fulfill this.
https://github.com/google/guava/blob/master/guava-gwt/src-super/java/util/super/java/util/concurrent/atomic/AtomicInteger.java

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
We seem to use AtomicInteger in [`AtomicQueue`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/AtomicQueue.java), but that is [not supported on gwt](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx.gwt.xml#L392). So I am not sure what the point of this issue is.

**Comment by badlogic** [comment]
Spine uses AtomicInteger

**Comment by MobiDevelop** [comment]
Looks like Google moved Guava's `concurrent` emulation into GWT 2.8.2. I'll look into updating to that this weekend.

**Comment by MobiDevelop** [comment]
GWT was updated to 2.8.2, AtomicInteger is now available.
