### ISSUE TITLE
Application crashes with LWJGL3 backend: pointer being freed was not allocated

### ISSUE THREAD

**Issue by tyrondis** [libgdx/libgdx#5205]
#### Issue details
When running my application with the LWJGL3 backend, it crashed right upon starting with the error message:
`java(84925,0x7fffb15f6380) malloc: *** error for object 0x11f762180: pointer being freed was not allocated`

This does not occur with the LWJGL backend.

#### Reproduction steps/code
Use LWJGL3, start application.

#### Version of LibGDX and/or relevant dependencies
LibGDX: 1.9.8
Java: 1.8.0_171-b11
OSX: 10.13.4 (17E199)

#### Stacktrace
`java(84925,0x7fffb15f6380) malloc: *** error for object 0x11f762180: pointer being freed was not allocated`

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [X] MacOS

**Comment by Tom-Ski** [comment]
Seen this before with mac. Not sure the what the absolute cause is here as i don't have a device i can reproduce this on, but the gpu is being switched from discrete to integrated. At which point this error happens. This usually happens when transitioning from using an external monitor, or exiting a game, mac seems to put you back on integrated, (probably to save power). You can confirm this by manually switching back to discrete gpu with any application that can manage this on macosx and running again

This is also most likely a lwjgl3 issue, if you can confirm that this is not a problem with a standard lwjgl3 (no libgdx) application, we can try to look into it, but afaik this is not something with libgdx itself.

**Comment by mudlee** [comment]
Regarding [this thread](http://forum.lwjgl.org/index.php?topic=6806.0), it can be solved with a VM parameter:

    -Dorg.lwjgl.system.allocator=system
