### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by yuripourre** [libgdx/libgdx#5239]
Hey guys,

I love libgdx and I think it has a great potential to become a base for a high-standard tool (similar to Unity 3D or Unreal Engine).

There are 74 Pull requests now waiting for some action and we cannot be sure (automatically) if they break something so we have to carefully look into each modification to guess if they are fine and then merge.

I really suggest that we focus our energy to ensure that the future improvements would not break something and speed up the Merge/Close PR process. I think that *unit tests* could be a good first step.

What do you think?

**Comment by NathanSweet** [comment]
Unit tests are fine, but add to the maintenance burden (especially when crazy people start adding tests like "tests if getName returns the name"). Since libgdx development (and library usage) has slowed in recent years, I don't see us adding a significant number of tests.

If you'd like to contribute tests, please submit a PR. Note that tests that are very complex or that test things that are simple enough not to need tests are unlikely to be merged.
