### ISSUE TITLE
Discussion: Approaches to scene2d Layout/Widget measuring

### ISSUE THREAD

**Issue by Darkyenus** [libgdx/libgdx#5244]
*This would probably be a better fit for a forum, but this place seems to be a better fit to reach other contributors*

After seeing cae2342f08a368d15bed2d8d923f4f79f903d6f1 and fighting with similar issues myself:

How about we added Android-style [onMeasure()](https://developer.android.com/reference/android/view/View.html#onMeasure(int,%20int)) instead of `getMin/Pref/MaxSize`?
- Working with wrapped Labels without it is a pain (and probably with some other widgets as well),
- it clearly defines when should a widget measure itself
- and generally, from my experience, it is more predictable to use.

I don't like many Android constructs, but this one is IMO pretty good. iOS [seems to be doing something similar, under the hood of Autolayout](https://developer.apple.com/documentation/uikit/uiview#//apple_ref/occ/instm/UIView/intrinsicContentSize).

It would be a breaking change, but it shouldn't be hard to write some temporary bridges to ease the transition. I know that there are some big applications written in scene2d.ui, so the costs of rewriting could prevent this from happening (maybe libGDX 2.0). But even if that would be the case, I'd like to know what the general opinion is about these two approaches.

Of course this is just about the general idea, it probably wouldn't have the exact Android API. I'd volunteer to write the PR for this, given enough positive feedback. Implementation details could be further discussed there.

**Comment by NathanSweet** [comment]
It's been a while since I looked at it, but from my experience Android layout is completely FUBAR, rivaled only by the madness in UIView. I would not look to either API for inspiration.

I have struggled with many UI toolkits over the years and there are absolutely none which I think get layout correct. scene2d.ui's layout is at the core of the library and it works fabulously, IMHO, especially Table, which has no equal. It is pretty much the simplest solution, easy to understand, handles all the necessary cases, and is easy to customize. I'm happy to discuss alternatives, but it is unlikely I can be convinced a different system is better, even putting aside the conversion effort of all the widgets and apps built with the current system (eg, Spine). It may be more fruitful to discuss your pain points with scene2d.ui's layout.

Keep in mind that scene2d.ui and scene2d are separate, so there is nothing stopping you from writing a different layout system on top of scene2d.

Note that cae2342f08a368d15bed2d8d923f4f79f903d6f1 was done because b9ec77edf9192aac9b0d6c1bd0e5c62ca5266ad7 now ensures the layout is indeed valid after `validate` returns. Otherwise the min/pref/max of scene2d.ui and the way layout works has been solid for a very long time.

A wrapped Label is the only widget which calls `invalidateHeirarchy` from within `layout`. It is really not terribly complex: a wrapped label's preferred height depends on its width. For example, a smaller width means the text wraps more often and so it will have a larger preferred height. A `measure` method is unnecessary. If you want the pref height of a wrapped label for a given width, simply set the label's width, then call `getPrefHeight`.

No other widgets have a dependency between their current size and their pref size and so are even simpler: the pref size is the size the widget would like based on its current state, regardless of its current size.

**Comment by Darkyenus** [comment]
Thanks for the thoughtful response!

I agree with most/all of your points (especially the one about awesomeness of Table).
However, the repeated `layout()` in `validate()` and setting the width of `Label` to influence its preferred width still feel a bit hacky to me. For example, I am not sure if there is a clean way to use the set-width-of-Label-first-trick for Labels inside Table, for situations when you want the Label to be at most 300 wide, but 280px when wrapping at 300px would lead to preferred width of 280px.

My line of thinking is, that this would be easily solved, if `getPrefW/H` was supplied with some constraints about the environment in which it will be placed, for example max width/height or something. Which is basically what Android's `onMeasure` does. And if we had that, the min/max/pref system as it is now would be probably superseded by this new one.

It is true that this currently only really affects one widget, but on the other hand, text handling is, in UI library, pretty important.

I'll probably try to implement a proof of concept to see if it would even solve the problems I think it would, and then I will report back. I'll close the issue so it doesn't get in the way, but the discussion can continue.

**Comment by Darkyenus** [comment]
Interesting, in that case I might need to recalibrate my hackiness detector.

>> for situations when you want the Label to be at most 300 wide, but 280px when wrapping at 300px would lead to preferred width of 280px.

> I don't follow -- a wrapped label doesn't have a preferred width (it is zero). A wrapped label's width must be set based on something external.

It is currently not easily achievable  which is probably why it sounds weird, so I'll try to explain it better:
I have tried to create tooltips with arbitrarily sized text. Without wrapping, the Label in Table got the exact size it needed. However, when the text was too long, it didn't look good (and didn't fit on the screen), so I have decided that I wanted to wrap at 300px. But for this to work, I had to do something like this:
```
label.setText(tooltipText);
if (label.getPrefWidth() > 300) {
    label.setWrap(true);
    table.add(label).prefWidth(300); //or just width()
} else {
    table.add(label);
}
```
This was ugly, had to be done on every text change, but worked. However the tooltip was then always 300px wide, even though it could be smaller, as none of the wrapped lines was exactly 300px wide - all were smaller, sometimes significantly, which created strange extra space in the tooltip.

Setting the width of the `label` before adding it to the `table` just collapsed the label to be 0 width. `pack()`ing the `table` afterwards also didn't help, because I had to force the `Cell`s (pref)width
to already be some size. Also, I have tried to do the set-width-first-trick in custom `Cell.width` `Value`, but that seems to be impossible to implement without getting down to measuring the width of letters myself, because even though [`computePrefSize()`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java#L147) supports it, [`getPrefWidth()`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java#L235) just returns 0f when wrap is enabled, thus there is no way to actually get that value.

So unless I am missing something, it is not easily possible to achieve the "wrap at 300px and shrink" behavior with current API, but it would be natural if the `getPrefWidth()` didn't have special case for wrapped Labels and always sized itself according to the preferences of its container.

---

This whole thing is mostly a corner case, and it could be fixed by implementing custom `Value` for these cases (with appropriate changes to `Label`). But it makes me wonder, if this could all be prevented with a different approach entirely.

**Comment by NathanSweet** [comment]
I do exactly what you describe with wrapped label tooltips in Spine:
![](http://n4te.com/x/4297-Z7s5.png)

It's done like this:
```
Label label = ...
label.setWrap(true);
label.setWidth(maxWidth);
label.validate();
Table table = ...
table.add(label).width(Math.min(maxWidth, label.getGlyphLayout().width));
```

This doesn't consider a background on the label, but my label doesn't have a background. Maybe Label could expose the pref width in a new method, separate from `getPrefWidth`. It doesn't make sense to allow `getPrefWidth` to return the pref width for a wrapped label. Presumably someone is calling `getPrefWidth` so they can set the width, so there is a chicken and egg problem since the pref width has a dependency on the current width. This could result in different pref widths when layout is done multiple times in succession without explicitly setting the width to some value first.

Layout is the thing all other toolkits get horribly wrong, either with a wacky or complicated API and/or with really poor layout managers. There may be something better, but scene2d.ui's system stays out of the way for the most common cases and still handles complex cases just fine. Sorry I don't have much ideas for a new system, I really like the current system!

I find I don't use percentages very often, instead relying on table columns.

Getting a bit off topic, but one thing I would like is for UI animations to be easier. I've found trying to use actions for UI animations works OK at first, but falls apart when there are multiple actions, actions need to be cleared, etc. In a recent project I wrote a class that stores a group's children's positions, validates the layout, stores the "target" position, then puts the children back to the original position. Every frame the children are moved toward their target position. The result is that when I change the UI (eg, add or remove a widget), widgets animate from their old position to their new layout position. You can see it in action in this app:
http://esotericsoftware.com/gloomhaven-helper

The code is sort of general purpose, you can see it here:
http://n4te.com/x/4298-PkCz.txt
Each child needs to implement HasAnimator, then it is used like this:
```
// Parent widget needs to avoid invalidate if animating and call updateChildren.
parent = new HorizontalGroup() {
	public void invalidate () {
		if (!Animator.enabled || !Animator.childrenAnimating(this)) super.invalidate();
	}

	public void draw (Batch batch, float parentAlpha) {
		Animator.updateChildren(this);
		super.draw(batch, parentAlpha);
	}
};
...
// Later, change the UI in ways that change child positions, but don't validate.
parent.addActor(something);
parent.removeActor(somethingElse);
// Then just call this.
Animator.storeChildren(parent, 0);
```
It requires enough wiring up that I'm not sure it belongs in scene2d.ui, but it is neat.

Oh, the missing piece for the above is this gem:
http://n4te.com/x/4299-vs2q.txt
Here is a version that works on a float:
http://n4te.com/x/4300-1DcV.txt
I love this function. It moves from the current value toward the target value, moving faster when farther away, without needing to track start/end times. I use it all over the place to easily animate values, eg:
```
float desaturation; // Animates between 0 and 1 based on isDesaturated().

public void act (float delta) {
	super.act(delta);
	float target = isDesaturated() ? 1 : 0;
	desaturation = animate(desaturation, target, 0.5f, 1, 2, delta);
}
```

**Comment by NathanSweet** [comment]
Looking forward to seeing your prototype! :D

An animation system is maybe tougher than it appears. Sometimes animations can be combined, other times they need to be cancelled, other times they need to be fast forwarded to the end. I have a feeling the most flexible solution is some sort of animation controller that handles just one type of animation, then application code can define what happens as the user takes more actions.

Using HarfBuzz for shaping would be awesome. We don't have RTL support, but we already have on-the-fly glyph generation, enabling typing in CJK or most other LTR languages, even when the glyphs typed are not known beforehand.
![](http://i.imgur.com/TSli2bL.jpg)
