### ISSUE TITLE
Problem running Android tests from sources

### ISSUE THREAD

**Issue by piotr-j** [libgdx/libgdx#5269]
Perhaps its a problem with my dev environment, but i had to change few things to run Android Tests from sources. Other backends work as expected.

- Removed ` "com.android.support:support-v4:${versions.androidSupport}"` from android libs in dependencies.gradle, conflict with one in backend-android/libs
- Set android test source and target compat to 1.8
- enabled multidex
- used jdk8

**Comment by obigu** [comment]
I've ran in the same issues and from the 4 points you mention, I believe the first one is a bit more complex than removing the Android support library from Gradle dependencies.

I do not fully understand how the build config is set up because there's a mnixture of Maven and Gradle configuration files. I guess the reason behind this is to have maximum IDE compatibility but it'd be great to get some details on that.

Anyway, support v4 must be set up to the latest 25 version (it needs to be as high as possible but less than 26 as long as we support minSDK < 14).

There is a support -v4 v19 Jar inside the libs folder of the Android backend that is loaded as a dependency on its pom.xml. I believe the reason it can't be updated to v25 is that its packaging was changed to AAR which is Maven doesn't understand (unless using 3rd party plugin). I donb't know either why this jar must be embedded in the libGDX project and can't be added as remote dependencies on the Pom.

So yep, there are 2 versions of Android support-v4 (v19 loaded via Maven and v25 via Gradle) and it complains when trying to run the tests.

@Tom-Ski Can you give us some insights on this?

**Comment by Tom-Ski** [comment]
Its embedded because we use it to build against. 
For deployment to the repositories and building libgdx _officially_ we use Maven.

We still have the ant build lying around because it has some nice scripts to build natives and fetch. Also some people like the basic binaries built by this. Don't ask me who, I am not allowed to say.

The Gradle build is to make life easier when working from source. Its the easiest to import and get running, and you also don't need to import into an IDE to run any of the tests. It is not used for any building other than some PR tests for this issue tracker, and generation of runnable tools.

As far as this specific issue goes, I could reproduce it but didnt look into it too much. As we are linking the support lib with gradle, we can just make Gradle ignore the binary in the repo. We still will need this for the other build tools that don't support AAR. (And other IDEs). We should make sure the jars are the same version, and also fixed versions.

**Comment by obigu** [comment]
Thank you @Tom-Ski.

1. I understand that we officially build libGDX with Maven and we need to build Android but on the other hand there's no official support for Maven on Android which complicates things.

2. I've checked the contents of the 25.4.0 AAR (latest 25+ available) and it does not contain any resources so in theory we could take the .jar inside and embed it. A bit too hacky for my taste though.

If I've understood this correctly we are on the edge now and this leads inevitably to problems building libGDX in the long run when Google comes up with new stuff that is unsupported by Maven. 

What options are there? Would it be feasible to keep Maven as the build system but delegating to a Gradle task building the Android stuff? Would it make sense to migrate the build to Gradle in the future?

**Comment by obigu** [comment]
@Tom-Ski Great! Android tests now can be run from IDE. Support libraries are still different versions though, until we find a better solution, do you think we should replace the v19 inside /libs from the jar extracted from the v25.4.0 AAR so that they are the same?

**Comment by Tom-Ski** [comment]
Yup!On 8 Aug 2018 18:44, obigu <notifications@github.com> wrote:@Tom-Ski Great! Android tests now can be run from IDE. Support libraries are still different versions though, until we find a better solution, do you think we should replace the v19 inside /libs from the jar extracted from the v25.4.0 AAR so that they are the same?

**Comment by obigu** [comment]
Hahaha, easier said than done. I didn't realize the actual classes are not inside the AAR in the repo. I've tried to get the JAR file using [Maven-Android-Sdk-Deployer](https://github.com/simpligility/maven-android-sdk-deployer) but it's outdated and after patching some issues, in the end, I've decided it's not worth it. I think this is fighting the inevitable. I'm afraid we'll need to build Android (at least) using Gradle sooner or later or we'll get stuck in old versions and hacky solutions.

**Comment by MobiDevelop** [comment]
What do we need to have the support library for? Just the fragment support, right? Maybe we can limit our scope to just that component, rather than the whole v4... that aar has a classes.jar which contains the relevant class files.

**Comment by obigu** [comment]
Not in my repo. Inside the classes.jar of the aar there's just the class BuildConfig.class inside some folders.

**Comment by obigu** [comment]
You're right. It may be that support-fragment depends on another one, but that's easy to  check. For the moment it could be the best way to get everything in sync. I'll try to put up a PR.
