### ISSUE TITLE
F13-F24 keys missing

### ISSUE THREAD

**Issue by EtK2000** [libgdx/libgdx#5389]
These keys are usually not on keyboards, but are often used in custom bindings for multiple input devices or mice with more than 5 buttons (which Windows doesn't natively support).

Here are the backend keycodes I've found:
• Android: https://source.android.com/devices/input/keyboard-devices
• GLFW (LWJGL3): http://www.glfw.org/docs/latest/group__keys.html
• LWJGL 2: https://github.com/LWJGL/lwjgl/blob/master/src/java/org/lwjgl/input/Keyboard.java

I'm sure other keys are missing on LWJGL2 (see https://github.com/libgdx/libgdx/issues/4739 for example).

**Comment by FyiurAmron** [comment]
related: https://github.com/libgdx/libgdx/issues/2524, https://github.com/libgdx/libgdx/pull/2592, https://github.com/libgdx/libgdx/pull/5207 ...

**Comment by EtK2000** [comment]
I might work on a pull request adding in all of these missing keys (including the related issues).
I've never used GWT or any of the iOS backends so those will require me to research.

Are there any other keys that are missing that I should add in?

Also, what should I do about keys that only exist on some backends?

**Comment by FyiurAmron** [comment]
@EtK2000 to know what's still missing, you'd have to research the related issues. Try to begin your work based on https://github.com/libgdx/libgdx/pull/5207 (and probably https://github.com/libgdx/libgdx/pull/2592) instead of doing a entirely new PR.

As to the keys that exist only on some backends - I guess the idea is to implement all of them in the root Input class, and simply leave them unmapped in the backends that miss them.

**Comment by EtK2000** [comment]
None of those pulls seem to actually map the keycodes on other backends, no wonder they weren't accepted.

**Comment by FyiurAmron** [comment]
@EtK2000 firstly, you're wrong; my PR didn't add them to backends on purpose (so that everyone can agree on the exact `Input` changes before implementing them in backends), and yousiftouma actually did add them at least to LWJGL backend.

Secondly, you miss the main issue. Until you have the keys defined in `Input`, you can't use them in backends. It's completely mandatory to do the preliminary work in the `Input` class beforehand. The PRs weren't accepted for multitude of reasons (well, actually, mine got accepted, but got reverted due to a dumb typo), not implementing changes in backends weren't one of them.

**Comment by EtK2000** [comment]
Ok, I'm confused as to why you wouldn't implement them in the backends if you're already adding them.
Yes, his had LWJGL2 backend, but none others.

**Comment by FyiurAmron** [comment]
Frankly? It's probably mostly because covering all the backends is equal to creating a lot of code (that should also be most probably covered by tests due to input handling being crucial to libGdx's stability BTW), and e.g. back in the days I was doing libGdx game development while being paid by the hour. Nobody would pay me to write code that our project wouldn't use; even if I did it for fun (which I didn't), I would probably only cover those backends I would most probably use (Android & LWJGL3, maybe RoboVM or MOE too).

**Comment by wcko87** [comment]
Hello, I would like to request prioritizing adding at least caps lock to the list of keys.
Caps lock is a commonly used keybind in games, and as far as I know libgdx has no way of detecting whether the capslock key is being pressed.

**Comment by FyiurAmron** [comment]
@wcko87 if you want this functionality to be added, write the PR and work for it to be merged :)

**Comment by EtK2000** [comment]
I'll get back to this at sometime, but I still can't implement anything on the iOS backends due to having no way to test.

**Comment by Monarchis** [comment]
Maybe this is also the Reason for #5857?

**Comment by EtK2000** [comment]
I actually have a different fix for the controller issue that seems to work for me on lwjgl2 backend.

I could submit that as a pull sooner than this.

**Comment by MrStahlfelge** [comment]
Short info on how to add new keycodes:

* Add the keycodes to `Input.Keys`. If they exit for Android, use same codes as in Android's `KeyEvent` class. If not existant for Android, define a keycode non-clashing with Android's codes and document it as a comment.
* don't forget to define * Input.Keys.toString()` for the new codes
* Android: Due to Android's code being the same, no change is needed in Android's backend
* GWT: Changes needed in `DefaultGwtInput.keyForCode()`. GWT's KeyCode.java is incomplete. Check with all browsers and OS at hand (might be slightly different) at https://keycode.info/
* RoboVM: `DefaultIOSInput.getGdxKeyCode()` needs change. Check `UIKeyboardHIDUsage` enum (yes, you can do that on any OS)
* Lwgl: Use `Keyboard` constants in `DefaultLwjglInput.getGdxKeyCode()` and `getLwjglKeyCode()`, Lwjgl3 is similar. 
* CHANGES: Document newly added keycodes and if they are completely new (unmapped before) or changing a mapping existing before

If you follow these steps, merge is highly likely.

For any controller issues, take a look at the gdx-controllers repo.

**Comment by yuripourre** [comment]
@MrStahlfelge thank you for providing such useful information. I just created a wiki page with your comment.
