### ISSUE TITLE
Dragging to the left calls Target.reset() when over a target.

### ISSUE THREAD

**Issue by madmenyo** [libgdx/libgdx#5403]
#### Issue details
Using DragAndDrop() Target.reset(...) is called when a draggable Source is dragged to the left while still within bounds of the Target Actor. This results in not being able to make a drop on the target as the target is reset to null. Moving in any other direction above the Target sets the target again for a succesfull drop.

The expected behaviour would be to have it call Target.reset(...) only when it leaves the target.

#### Reproduction steps/code
https://pastebin.com/W13HHUth

#### Version of LibGDX and/or relevant dependencies
Gdx-1.9.8

#### Stacktrace
No exceptions

#### Please select the affected platforms
- [ x] Windows

**Comment by NathanSweet** [comment]
Please provide executable code (with a main method). Eg http://n4te.com/x/5224-ApvZ.txt

The mouse is going over your drag actors. It seems this commit checks non-touchable actors:
https://github.com/libgdx/libgdx/commit/d139e851106b2e094a97443f84638c9864a10212
I assume this is because drag targets may not normally be touchable, but I don't remember (6 years ago!). I'm not sure we want to change the default behavior. We could make a setting so non-touchable actors aren't checked. You could subclass your drag actors so `hit` always returns null. You could offset the drag actors so it's hard/impossible to hit them with the mouse. Thoughts?

**Comment by madmenyo** [comment]
What is wrong with my executable coffee with entry point? Pretty sure it has what your asking. 

I will try to offset the drag actor but I already thought about it and shouldn't this behaviour also happen when dragging down, since drag actor 0,0 is positioned at cursor? But if overriding hit() would fix it I will be using that I think. 

Lastly, I implemented DragAndDrop into a ScrollPane within a Window for my actual app and there it behaves as expected. I'm also using exactly the same label as the drag actor in the code I posted here.

**Comment by NathanSweet** [comment]
[Before](https://pastebin.com/Aa2YtBrw) your edit, your code wasn't executable. No imports are fine.

Moving the actor farther from the mouse cursor makes it less likely to interfere. I have a better fix though: we'll just remove the drag actor before checking what is under the mouse.

**Comment by madmenyo** [comment]
Although a good solution this recreates a new Actor each frame while dragging. Is this really necessary? Could it be send to the back perhaps and pulled to the front instead? If the target actor returns false on a "hover" event the actor at the back should not be handled by input anymore right?

**Comment by NathanSweet** [comment]
The drag actor is removed from the stage, then added back if needed (no allocations).
