### ISSUE TITLE
Tiledmap MapObjects getByType error with GWT

### ISSUE THREAD

**Issue by mgsx-dev** [libgdx/libgdx#5469]
#### Issue details

Call to [MapObjects.getByType(...)](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/maps/MapObjects.java#L95) raise an error for GWT builds.

I could make a PR but i'm not sure what's the best way to solve it : 

* append `<extend-configuration-property name="gdx.reflect.include" value="..." />` for MapObject class and all subclasses in [gdx.gwt.xml](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx.gwt.xml).
* or replace `ClassReflection.isInstance` by `object.class == type` in [MapObjects.getByType(...)](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/maps/MapObjects.java#L95) which change (break) its behavior.

#### Reproduction steps/code
Call `MapObjects.getByType(RectangleMapObject.class)` in a GWT built game.

#### Version of LibGDX and/or relevant dependencies
libgdx 1.9.8 (and probably all versions)

#### Stacktrace
```java
Couldn't find Type for class ...
```
where class can't be any of MapObject class or subclass.

#### Please select the affected platforms

- [ x] HTML/GWT

**Comment by tommyettinger** [comment]
You can insert those `<extend-configuration-property name="gdx.reflect.include" value="RectangleMapObject" />` lines, for whatever MapObject subclasses you need, into your own `.gwt.xml` files. It will act the same as if they were in libGDX's such file; the GWT compiler merges all `.gwt.xml` files. This is likely to be the most reasonable fix since you can do it today without waiting for a new release. Adding subclasses I am fairly sure will also add their parent classes to the reflection cache, but you can do it manually for all classes you know have been mentioned in a `Couldn't find Type for class ...` error. The reflection cache can get too big to compile if there are too many classes added to it (and that's not the same as `extend-configuration-property` lines), so the `gdx.gwt.xml` file is only enlarged if a class is important to most applications on GWT, I think.
