### ISSUE TITLE
 [feature request] Support reading JSON from stream/reader while reading it

### ISSUE THREAD

**Issue by EtK2000** [libgdx/libgdx#5481]
Simply put, loading JSON currently requires reading all the data and processing it.
This required more memory, especially when the length of the data is unknown, so we keep reallocating byte[] until we've finished reading it all.

Quite a few libraries support such loading, and it would be helpful for low-end devices with massive JSON files (for example g3dj files).

**Comment by obigu** [comment]
> Quite a few libraries support such loading, and it would be helpful for low-end devices with massive JSON files (for example g3dj files).

Why not just use those libraries?

**Comment by EtK2000** [comment]
I currently do.
It's just kinda upsetting to me that the parser that LibGDX comes with doesn't support this.

**Comment by NathanSweet** [comment]
FWIW, the libgdx JSON parser's goal is to be convenient. It's probably not the fastest or the lowest memory solution. It's never been benchmarked, though it's mostly Ragel generated code so there's probably little that could be done anyway. While it can be used for callback style parsing by overidding the protected methods, by default it creates JsonValue instances, which are linked lists, and it creates a JsonValue for _every_ value. JsonValue is convenient for navigating the data, but not terribly efficient. If you are parsing so much JSON you need a reader, you might consider using a different parser. If speed or memory is important then JSON may not be the right format at all.

JsonReader.java is generated by Ragel from JsonReader.rl (in the same directory). Ragel can process in chunks, see "5.9 Maintaining Pointers to Input Data" on page 40 of the [Ragel docs](https://www.colm.net/files/ragel/ragel-guide-6.4.pdf). I took a quick crack at it:
http://n4te.com/x/5743-JsonReader.rl
http://n4te.com/x/5745-JsonReader.java
The problem is we have some manual parsing for strings: we set `s` and later create a string from `s` to `p` (which is the current buffer position). We need to be careful that we don't discard the part of the buffer referenced by `s`. To see the problem, use a small buffer size (4 here):
```
System.out.println(new JsonReader(4).parse(new StringReader("{ thisisaname: value12345 }")));;
```
I added code to refill the buffer where we parse manually, but I didn't add code to keep some of the buffer if `s` is set. For that we should "compact" the buffer, moving the data from `s` to the end to 0, then setting `s` to 0, then filling the rest of the buffer. If the buffer is too small to contain a whole string, we can throw an exception or automatically grow the buffer (an exception is simple and probably fine). There may also be other problems.

I likely won't have time to work on this further, but maybe someone else would like to take it up.

**Comment by EtK2000** [comment]
I probably won't have much time in the next few months, but once I get back if no one else has I could try.

**Comment by MrStahlfelge** [comment]
We are happy to accept PRs on it, but based on the feedback here it is not really important. As obigu said, you can use other libs on the JVM-based platforms, and need to go a different approach on GWT anyway if you want more speed or less memory consumption.
