### ISSUE TITLE
AndroidGL20 JNI Removal

### ISSUE THREAD

**Issue by Anuken** [libgdx/libgdx#5485]
While snooping around the libGDX Android backend's source, I noticed something strange.
[AndroidGL20](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGL20.java) uses JNI to access openGL 2.0 methods, while [AndroidGL30](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGL30.java) uses a standard Android library class to do so: [GLES30](https://developer.android.com/reference/android/opengl/GLES30). However, standard Android also has a [GLES20](https://developer.android.com/reference/android/opengl/GLES20) class.

Why does AndroidGL20 use JNI when it could be using standard Android libraries? I've re-implemented AndroidGL20 without any JNI and tested it in one of my games, and there doesn't seem to be any performance difference. After asking around in the Discord, someone suggested that the JNI-based GL20 implementation could have been made before the standard GLES20 implementation was released.

If that is the case, would it be a good idea for me to submit a pull request removing [these C++ files](https://github.com/libgdx/libgdx/tree/master/gdx/jni/android) and replacing the current AndroidGL20 implementation with [my own](https://gist.github.com/Anuken/38e3e6c0db299c7ff22d5cfd500ab070), to reduce the amount of unnecessary C++ code in the repository?

**Comment by MrStahlfelge** [comment]
The problem is, most people don't like to bother with an own build to try things. I had no problem to run my debug and test builds on a new Android backend while keeping 1.9.8 for release builds, but I will not throw in the effort to check if there are changes, then pull, build and publish locally every time I build a new test version.  And I think I am not alone with this.

What libGDX really lacks the last time (the last 18 month), is continous releases. There's an easy schema to implement new, experimental features while constantly having a stable version: Running two versions at a time. The version numbers have three numerals, by intention. They are named major, minor, incremental. All fixes go into a new version where the first two numerals stay the same and just the third one, the incremental is incremented. Experimental features or code-breaking changes go into a version where at least the minor version number is incremented.

Two important points: It must be stated on the release page if a release is experimental, beta or stable. And: A new incremental release for all running versions should be done every time there are enough changes that should go out to the public. For the experimental versions, that means when it should be tested by all devs. For stable versions, it is when there are important fixes.

**Comment by noblemaster** [comment]
This is an older post but probably deserves more consideration. Since targeting the latest SDK (28) and uploading it to Google Play I am getting the following **warning** in the app's pre-launch report. I am targeting OpenGL ES 2.0:

> The following APIs are greylisted and Google can’t guarantee that they will work on existing versions of Android. Some may be already be restricted for your target SDK

The warnings shown all refer to `AndroidGL20` and `java.nio.NIOAccess`/`java.nio.Buffer`. There are 6 warnings, here is 1 example:
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/nio/Buffer;->_elementSizeShift:I
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at com.badlogic.gdx.backends.android.AndroidGL20.init(Native Method)
	at com.badlogic.gdx.backends.android.AndroidGraphics.<init>(SourceFile:117)
	at com.badlogic.gdx.backends.android.AndroidGraphics.<init>(SourceFile:112)
	at com.badlogic.gdx.backends.android.AndroidApplication.init(SourceFile:138)
	at com.badlogic.gdx.backends.android.AndroidApplication.initialize(SourceFile:103)
        ...
```
`AndroidGL20` potentially should be replace with non-native methods? The app in question works fine, but it's possible not on all devices anymore?

@MrStahlfelge: would you mind posting your code as a pull request?

**Comment by noblemaster** [comment]
There appears to be a related pull request already: https://github.com/libgdx/libgdx/pull/5641
