### ISSUE TITLE
BitmapFont useIntegerPosition should default to false

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#5519]
One of the most recurrent issues on libGDX support channels is related to issues with font scaling. Many times the reason is simply not having set `useIntegerPositions` to `false` on the `BitmapFont`.

Afaik `useIntegerPositions` is there as an optimization to avoid filtering. Probably @NathanSweet  can give more information on what's the performance penalty associated to it but I don't think it's currently an issue. ~~If I understand correctly, he agreed several years ago it should be set to `false` by default:~~ He seems to advocate just to remove the parameter from the BitmapFont constructor but keep it true https://github.com/libgdx/libgdx/issues/3495.

@NathanSweet Is there any reason not to do it?

I'll create a PR if agreed safe.

**Comment by Darkyenus** [comment]
I don't think that it is an optimization, but really is to avoid filtering. Bitmap fonts (especially small ones, <30px for example) look good only when rendered "pixel perfect", i.e. 1 pixel of bitmap = 1 pixel of screen, otherwise they look blurry, incosistent or just "off".
When moving such text around (for example as a part of scene2d animation, or in custom code), it will often land on non-whole pixel coordinates, thus making the text look bad, especially if it stops.
`useIntegerPositions` is a "hack" to prevent this. (Hack, because it can't ensure that it always rounds correctly. For example when the text is scaled and already looks weird, this breaks it even more.)

I wouldn't mind changing the default to `false`. It is better to control the pixel alignment in the element which draws the text - and some scene2d.ui widgets already do this. And having bad looking text is better than having no text at all.

**Comment by obigu** [comment]
@Darkyenus Thanks for giving some insight on this.

Just for completion, this issue not only affects when working with very small texts/fonts. If you work with Labels on a Stage with "low number" World units (for example 16 units * 9 units), Labels won't be displayed at all, even if your font is large size.

**Comment by MrStahlfelge** [comment]
And if used with a ScrollPane, setUseIntegerPositions set to true leads to strange flickering effects. I would also vote for setting it to false ny default.

**Comment by NathanSweet** [comment]
The setting is to avoid filtering artifacts, not for performance. In general, bitmap fonts look much better when they are not scaled and are positioned on integer coordinates to avoid filtering. It is common to use 1:1 bitmap pixels to screen pixels. If using other coordinate systems or scaling fonts, then you'd likely want to disable the rounding.

I don't really mind which is the default, though it's just going to move the annoyance from one group of people to the other. The default should be what the larger group of people want to use, though changing it now would cause disruption for little gain, IMHO.

**Comment by MrStahlfelge** [comment]
Thank you for this clarification! I think best is to extend the JavaDoc for setUseIntegerpositions. Stating the default value is true which is better for unscaled Pixel-optic, value false is better for scaled graphics and that there is no performance impact.

**Comment by obigu** [comment]
@NathanSweet Thanks for the answer.
I think @Darkyenus answer is spot on saying that not having a font displayed is worse than having a bad looking font and that it doesn't really fix the issue in many cases.

>  The default should be what the larger group of people want to use, though changing it now would cause disruption for little gain, IMHO.

It may be common to use 1:1 bitmap pixels but I doubt it's the largest group.  Lots of new confused users would benefit from it in exchange for a small disruption. 

So far there seems to be some consensus around the fact it would be better to default to `false`. I'm not sure if you're open to change it, would you consider merging a PR or shall I move on and close the issue?

**Comment by NathanSweet** [comment]
@obigu you may be right that the `false` group is larger, it's hard to say. Most UIs want to use 1:1. At any rate, the default chosen years ago is in use in many places. Even if `false` is a better default, I don't think it's worth the breakage to change it now.

**Comment by obigu** [comment]
Fair enough, thanks @NathanSweet
