### ISSUE TITLE
PooledEffect with non continuous not draw at the first time.

### ISSUE THREAD

**Issue by bachtrong43** [libgdx/libgdx#5571]
Please ensure you have given all the following requested information in your report.

#### Issue details
PooledEffect with non-continuous not draw at the first time after create new instance.

#### Reproduction steps/code
particle-animation.p is taken from test assets.
```
public class ParticleEditorLauncher {
    public static void main(String[] args) {
        new LwjglApplication(new ApplicationAdapter() {
            private ParticleEffectPool pool;
            private Array<ParticleEffectPool.PooledEffect> pooledEffects = new Array<ParticleEffectPool.PooledEffect>();
            private SpriteBatch batch;

            @Override
            public void create() {
                super.create();
                ParticleEffect effect = new ParticleEffect();
                effect.load(Gdx.files.internal("particle-animation.p"), Gdx.files.internal(""));
                effect.setEmittersCleanUpBlendFunction(true);
                pool = new ParticleEffectPool(effect, 0, 100);
                batch = new SpriteBatch();

            }

            @Override
            public void render() {
                super.render();
                if (Gdx.input.justTouched()) {
                    ParticleEffectPool.PooledEffect pe = pool.obtain();
                    pe.setPosition(MathUtils.random(100, 300), MathUtils.random(100, 300));
                    pooledEffects.add(pe);
                }
                Gdx.gl20.glClearColor(0, 0, 0, 1);
                Gdx.gl20.glClear(GL20.GL_COLOR_BUFFER_BIT);
                batch.getProjectionMatrix().setToOrtho2D(0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
                batch.begin();
                for (int i = 0; i < pooledEffects.size; i++) {
                    ParticleEffectPool.PooledEffect effect = pooledEffects.get(i);
                    effect.draw(batch, Gdx.graphics.getDeltaTime());
                    if (effect.isComplete()) {
                        pooledEffects.removeIndex(i);
                        effect.free();
                        i--;
                    }
                }
                batch.end();
            }
        }, new LwjglApplicationConfiguration());
    }
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.8

Result: first touch the particle not draw, second is ok because pooledEffect is reset. The isComplete return true after first draw of new instance of PooledEffect
Expected: new pooledEffect draw as usual.
This bug occurs on non-continuous particles in test assets. If we check continuous on particleeditor it will work ok.
Fix: 
- Call start or reset on new instanceof PooledEffect in ParticleEffectPool or call default restart after constructor on ParticleEmitter.

**Comment by obigu** [comment]
Not really a bug but I agree it's an issue.

According to the docs `start()` must be called before `ParticleEffect` is used. The `ParticleEffectPool` hides the ParticleEffect initialization requiring the user to make ugly solutions to manually call `start()` (I do so in my projects by encapsulating the Pool).

The solution as you suggest is to call `start()` on `newInstance()` in `ParticleEffectPool` (I can't think of a reason where this would not be desired). 

I'll create a PR.

**Comment by mgsx-dev** [comment]
@obigu i'm not sure about your proposal : a pool just abstract object creation, nothing more. Start should be called for non pooled effects in user code and it should be the same for poolled effects.

There is some use cases when you don't want polled effects to be automatically started (same use cases as non pooled effects) : you prepare a bunch of effets, position them and start them with some delay (like fireworks).

IMO wiki pooled effect examples have to be fixed in this way. It's not a "ugly solution", it's  how particle effects have to be used.

**Comment by obigu** [comment]
@mgsx-dev In my opinion for just abstract object creation without ParticleEffect specifics users can just use Pool<ParticleEffect>. What makes ParticleEffectPool useful is that not only takes care of object creation but of appropriate extra stuff that needs be done to work with ParticleEffects.

The described use case (fireworks) can be easily implemented even if the effects are started. A list of the effects in use need to be kept in any case (in order to call `update` on each of them) so instead of calling `start` after the delay they can be added to the "list" (or if it's Scene2D to the Stage/Group).

Which "clean" to the sample provided would you make to the sample code to make it work?

**Comment by mgsx-dev** [comment]
@obigu I looked deeper in the code and you're right :-) I think i was misguided by the meaning of "start", my bad.

Effect should be started before using it, so it make sense to do it in effect pool since user code don't have to know if effect was obtained by creation or by recycling.

Nice catch! :-)
