### ISSUE TITLE
models appear/disappear during change in viewpoint

### ISSUE THREAD

**Issue by robertlight** [libgdx/libgdx#5629]
This app is running on MacOSx.

I have model objects that are inside other model objects (with diffuse sides).   The interior model objects that are inside appear & disappear at random times as the viewpoint changes.  

Both the interior as well as exterior objects are "diffuse" material objects.   The artifact DOES NOT appear if the interior object is made via:   new Material(Color.RED)  ... though I can't get the interior object to be colored red, it doesn't blink in/out as the viewpoint changes.

1) Does libGDx handle model objects that are entirely interior to other model objects?
2) Does libGDx handle the case where model objects intersect one another?

A video showing the behavior & visibility artifact can be found here:  
     https://www.youtube.com/watch?v=zGTTcW44maE

Any help would be much appreciated.

   - Bob

**Comment by Darkyenus** [comment]
1. You have ignored the issue template, so it is impossible for us to diagnose the issue properly
2. This not a bug in libGDX. Since all of your objects are transparent, standard depth test is not sufficient to render everything correctly. Default model batch sorter tries to handle this, but your case is pretty complex. I suggest looking up this topic in general, as it isn't libGDX or even OpenGL specific. If you have trouble implementing your chosen strategy to deal with this in libGDX, check the links (and everything else) [here](https://github.com/libgdx/libgdx/wiki/Getting-Help), we'll be happy to help. But please note that this is an issue tracker and not a general support forum (we have that elsewhere, check the links).

I am kinda impressed by the fact that you had the patience to record and upload a video showing your problem, but not the patience to read any of the support documentation...

**Comment by NathanSweet** [comment]
:) https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by robertlight** [comment]
I was mostly putting out a request for someone to look at the behavior I was seeing and try to put some words around the problem so that I could delve into things a bit deeper - having never built anything in libGDx, sometimes the most difficult task is being able to describe the problem you are seeing.

It turns out that all I needed to do is to alter how I created the little boxes (see the video) which were internal to the transparent boxes.   If I create them using just:
```
new Material( ColorAttribute.createDiffuse(Color.YELLOW))
```
and leave the transparent boxes defined with

```
BlendingAttribute blendingAttribute = new BlendingAttribute();
blendingAttribute.opacity = .05f;
model = modelBuilder.createBox(getWidth(),getLength(), getHeight(),
                                     new Material(blendingAttribute, ColorAttribute.createDiffuse(Color.BLUE))
```

Then I can see my yellow interior boxes just fine and they don't go "blinking" in/out as show in the video.

**Comment by MrStahlfelge** [comment]
> I was mostly putting out a request for someone to look at the behavior I was seeing and try to put some words around the problem so that I could delve into things a bit deeper - having never built anything in libGDx, sometimes the most difficult task is being able to describe the problem you are seeing.

Hi, best was if you join the libGDX discord. :)

**Comment by robertlight** [comment]
> Hi, best was if you join the libGDX discord. :)

What is the "libGDX discord ???

**Comment by MrStahlfelge** [comment]
It is stated on the main page: https://github.com/libgdx/libgdx#news--community

and on the libGDX website's community page: https://libgdx.badlogicgames.com/community.html

Di you have suggestions where to announce it more exposed?
