### ISSUE TITLE
[android] large translation issue with 3d particles

### ISSUE THREAD

**Issue by PlayLight** [libgdx/libgdx#5666]
#### Issue details
I noticed this issue on one of my games which uses a large 3d map (300,000 x 300,000).
When setting a large translation on 3d particles, the particles are no longer rendering on Android (but works fine on Desktop).
eg.
```
Vector3 position = new Vector3(240952, 9, 221895);
particles.translate(position); // Will not render on Android
```

However when using small translations the particles render just fine on Android.
eg.
```
Vector3 position = new Vector3(5000, 9, 5000);
particles.translate(position); // Works fine
```

I have tested this on multiple devices, running Android API 24, 25, 27 & 28, all with the same result.

#### Reproduction project
I have made a sample project which replicates this issue.
It has commenting in the core game class (Main.java) with a starting Vector3 called _spawnPosition_ which is used to create the scene at that position in 3d space.
[Reproduction project](https://github.com/libgdx/libgdx/files/3292582/emmiterposition.zip)

#### LibGDX version
tested on 1.9.8, 1.9.9 and 1.9.10-SNAPSHOT

#### Affected platforms
- [x] Android

**Comment by Darkyenus** [comment]
This is most likely caused by a lower precision used by the device's GPU. [Default particle shader](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g3d/particles/particles.fragment.glsl) uses `mediump` precision by default, which is [probably 16bit float](https://stackoverflow.com/questions/4414041/what-is-the-precision-of-highp-floats-in-glsl-es-2-0-for-iphone-ipod-touch-ipad) which is not enough for maps that big.

Try supplying a custom shader with `highp` position.

**Comment by PlayLight** [comment]
Thanks Darkyenus, Yes that seems to be the problem.
using highp for vertex positions fixes this.
Unfortunately the 3d particle batches do not allow for a custom ShaderProvider, but i can work around this for now by including a modified particles src in my project.

**Comment by Tom-Ski** [comment]
The ParticleShader allows you to configure the shader yourself.

**Comment by PlayLight** [comment]
True, but configuring the default ParticleShader is definitely not a practical approach for mobile platforms with numerous devices, esspecially under the circumstances that this issue outlines.
