### ISSUE TITLE
[1.9.9] Change in DragAndDrop causes NPE

### ISSUE THREAD

**Issue by chancezeus** [libgdx/libgdx#5675]
Please ensure you have given all the following requested information in your report.

#### Issue details
Due to a change between 1.9.8 and 1.9.9 in the DragAndDrop class (actual change is here: https://github.com/libgdx/libgdx/blob/gdx-parent-1.9.9/gdx/src/com/badlogic/gdx/scenes/scene2d/utils/DragAndDrop.java#L75) the updated version causes the `dragStop` to be called while still in `drag`. Using a watch on the payload I was able to trace it through a cascade of `dragActor.remove` -> `parent.removeActor` -> `stage.unfocus` -> `cancelTouchFocus` -> ... some event classes in between ... -> `listener.dragStop` (the one inside `DragAndDrop.addSource`). This sequence of events causes payload to be reset and thus causes an NPE at line 105 (https://github.com/libgdx/libgdx/blob/gdx-parent-1.9.9/gdx/src/com/badlogic/gdx/scenes/scene2d/utils/DragAndDrop.java#L105)

#### Reproduction steps/code
Just implement the DragAndDrop and it should happen as soon as you start dragging.

#### Version of LibGDX and/or relevant dependencies
LibGDX: 1.9.9+ 

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.scenes.scene2d.utils.DragAndDrop$1.drag(DragAndDrop.java:105)
	at com.badlogic.gdx.scenes.scene2d.utils.DragListener.touchDragged(DragListener.java:61)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:62)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchDragged(Stage.java:314)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:345)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by NathanSweet** [comment]
DragAndDropTest works fine, so how to reproduce?

**Comment by Xian767-6424** [comment]
Ok,I have replace the DragAndDrop.java and DragAndDrop.class with 1.9.7 version and it works fine. 
otherwise the game will crush if you started to drag an item.

**Comment by Xian767-6424** [comment]
@Tom-Ski 
I have replace the DragAndDrop.java and DragAndDrop.class with 1.9.7 version and it works fine. 
otherwise the game will crush if you started to drag an item. 
Can you guys replace the files?
http://central.maven.org/maven2/com/badlogicgames/gdx/gdx/1.9.7/

**Comment by NathanSweet** [comment]
If there is a problem, I would love to fix it. Will reopen if more info is provided.

**Comment by Extain** [comment]
I'm getting this same issue, it seems that setting the dragActor to a child actor and trying to drag it is causing a NPE.

**Comment by AbyssOfMisery** [comment]
> I'm getting this same issue, it seems that setting the dragActor to a child actor and trying to drag it is causing a NPE.

you have to change libgdx to 1.9.7. if they aren't going to fix it

**Comment by NathanSweet** [comment]
@Extain You'll need to show what problem you are having before anyone can fix it.

**Comment by kamarad** [comment]
> 
> 
> @Extain You'll need to show what problem you are having before anyone can fix it.

I'm using 1.9.10 encounterd the same issue.

The reason the test works is because in the dragStart method you create a new actor, namely a Label, and set it as the dragActor. The use case here is if the dragActor is set via the getActor() method for example. In these cases the idea is to drag the actual actor that has been picked up, not a derivative. If you change the test on line 68 to use getActor() you should be able to reproduce.

Hope it helps.

**Comment by kdenzel** [comment]
I can verify this issue. I am working with the Book "Mastering LibGDX" by  [Patrick Hoey](https://github.com/patrickhoey/BludBourne). With Version 1.9.8 and before there isn't any issue with the DragAndDrop class, but when i switch to Version 1.9.10 i get the Nullpointer exception too.
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.scenes.scene2d.utils.DragAndDrop$1.drag(DragAndDrop.java:110)
	at com.badlogic.gdx.scenes.scene2d.utils.DragListener.touchDragged(DragListener.java:61)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:62)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchDragged(Stage.java:315)
	at com.badlogic.gdx.InputMultiplexer.touchDragged(InputMultiplexer.java:135)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:363)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:221)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
```

**Comment by NathanSweet** [comment]
@kamarad Thanks for describing a way to reproduce the problem. The DragAndDrop class is not designed for the source actor to be the drag actor. Even if the NPE issue you have is fixed, if Payload `setValidDragActor` or `setInvalidDragActor` is used then drag actor is removed from the stage and those added. Also, the drag actor is removed from the stage when drag stops, which may or may not be what you want to happen to the source actor.

First, the NPE issue occurs because of how #5403 was fixed. We want to allow drop targets with touch disabled, but we need to do something so `event.getStage().hit` doesn't hit the drag actor. Removing from the stage accomplishes this, but if the drag actor is the source actor then it has touch focus (since we touch downed it) and removing it from the stage causes a "cancel touch focus", which simulates a touch up, stopping the drag. So removing it isn't good.

A workaround is for the drag actor to return null from `hit`, but needing to manage this yourself is clunky. Another is to offset the drag actor so it isn't under the touch, though fast movements may still trigger it.

We could move the drag actor really far away when we do the `hit` test. This feels pretty hacky but it may actually be the most elegant solution. Let's go with that and we can do something else if someone has a better idea.

Next, to use a source actor as the drag actor, we could have DragAndDrop only removes actors that were not already in the stage. If it has to add a drag actor, then it will remove it, but if the actor was already in the stage it will only position it, never remove it. This means existing code may need to be adjusted to remove the drag actor that used to be removed automatically, but I think it is better behavior and that should be pretty obvious that it needs to be done.

**Comment by kamarad** [comment]
> 
> 
> @kamarad Thanks for describing a way to reproduce the problem. The DragAndDrop class is not designed for the source actor to be the drag actor. Even if the NPE issue you have is fixed, if Payload `setValidDragActor` or `setInvalidDragActor` is used then drag actor is removed from the stage and those added. Also, the drag actor is removed from the stage when drag stops, which may or may not be what you want to happen to the source actor.
> 
> First, the NPE issue occurs because of how #5403 was fixed. We want to allow drop targets with touch disabled, but we need to do something so `event.getStage().hit` doesn't hit the drag actor. Removing from the stage accomplishes this, but if the drag actor is the source actor then it has touch focus (since we touch downed it) and removing it from the stage causes a "cancel touch focus", which simulates a touch up, stopping the drag. So removing it isn't good.
> 
> A workaround is for the drag actor to return null from `hit`, but needing to manage this yourself is clunky. Another is to offset the drag actor so it isn't under the touch, though fast movements may still trigger it.
> 
> We could move the drag actor really far away when we do the `hit` test. This feels pretty hacky but it may actually be the most elegant solution. Let's go with that and we can do something else if someone has a better idea.
> 
> Next, to use a source actor as the drag actor, we could have DragAndDrop only removes actors that were not already in the stage. If it has to add a drag actor, then it will remove it, but if the actor was already in the stage it will only position it, never remove it. This means existing code may need to be adjusted to remove the drag actor that used to be removed automatically, but I think it is better behavior and that should be pretty obvious that it needs to be done.

Sounds good to me Nathan. I understand the reasoning. I will adjust my code to adopt the architecture.
