### ISSUE TITLE
Unexpected segmentation fault (related to CVE-2017-0700)

### ISSUE THREAD

**Issue by WOOSEUNGHOON** [libgdx/libgdx#5737]
**Version**
Libgdx master version

**Issue description**
Hi,
I found a unpatched CVE-2017-0700 vulnerability in root/gdx/jni/gdx2d/jpgd.cpp.

The vulnerability was reported as an Android vulnerability in NVD, but in fact,
it was identified as a vulnerability in code in Libgdx.

I found the PoC at https://github.com/ele7enxxh/poc-exp/tree/master/CVE-2017-0700
and confirmed that Libgdx was terminated while printing "segmentation fault".

For vulnerability information, please refer to https://nvd.nist.gov/vuln/detail/CVE-2017-0700 and related patch information is found in https://android.googlesource.com/platform/external/libgdx/+/38889ebd9b9c682bd1b64fd251ecd69b504a6155.

Thanks.

**Comment by akien-mga** [comment]
For the reference, I started looking into this as the same library is used in Godot Engine, reported in godotengine/godot#30952.

Google's Gitiles doesn't allow downloading patch files AFAIK, so I had to clone the 800 MB repo to get a Git formatted patch: [0001-Fix-series-of-JPEG-vulnerabilities.patch.txt](https://github.com/libgdx/libgdx/files/3446048/0001-Fix-series-of-JPEG-vulnerabilities.patch.txt) (`.txt` appended because GitHub doesn't like `.patch` ¯\\\_(ツ)\_/¯)

Interestingly, this patch never made it to Google's `master` branch, but it is included in their `nougat-mr2-release` branch and some Android 7.1.2 releases. I'm not familiar with Android's release management so I can't really say why... there's a number of other relevant security fixes done in the `master` branch which might be worth considering to backport to libgdx upstream (you'd wish Google had done that themselves back in 2017, but well...).

The actual upstream library is https://github.com/richgel999/jpeg-compressor, but it seems unlikely to get fixes merged there as it was never updated since importing from Google Code. I might give it a try nevertheless,

**Comment by akien-mga** [comment]
> Interestingly, this patch never made it to Google's `master` branch, but it is included in their `nougat-mr2-release` branch and some Android 7.1.2 releases. I'm not familiar with Android's release management so I can't really say why...

**Comment by akien-mga** [comment]
Peculiar results...
```
$ git branch --contains 38889ebd9b9c682bd1b64fd251ecd69b504a6155
* nougat-mr2-release
$ git tag --contains 38889ebd9b9c682bd1b64fd251ecd69b504a6155
android-7.1.2_r18
android-7.1.2_r19
android-7.1.2_r28
```

In other `android-7.1.2_rXX` tags after `r18` it seems that the commit is included too, but the hash changed and it's not included in any branch, as they seem to have done tags from orphan commits.

**Comment by akien-mga** [comment]
In case it's useful, here's the `nougat-mr2.3-release` patchset from Google Android on top of their libgdx 1.9.3 fork (14 commits): [nougat-mr2.3-release-patchset.zip](https://github.com/libgdx/libgdx/files/3446177/nougat-mr2.3-release-patchset.zip)

First commits are about porting to Android, the rest seems to be security related fixes to some extent, some of which might be worth upstreaming.

**Comment by akien-mga** [comment]
Backporting this PR might be sufficient for `jpgd.cpp`: https://github.com/richgel999/jpeg-compressor/pull/10

Note that the above patchset also has fixes for some actual libgdx code as well as your copy `stb_image.h` (that one is actively maintained, so updating to latest upstream might be better than backporting Google patches).

**Comment by akien-mga** [comment]
Note that the patch for CVE-2017-0700 aims at preventing remote code execution, but it won't prevent aborting the process since it uses asserts. But abort is better than segfault, and for game engines this is pretty corner case anyway.
