### ISSUE TITLE
How to add ImGui to LibGDX?

### ISSUE THREAD

**Issue by ejamshidiasl** [libgdx/libgdx#5748]
Hello
 
i want to add ImGui to LibGDX but there is a lots of problems.

how to do this?

**Comment by Darkyenus** [comment]
You may try one of many [immediate mode libraries/imgui bindings for Java](https://duckduckgo.com/?q=java+imgui&t=ffab&ia=software), but none have direct support from libGDX.

Since this is a question and not an issue with libGDX, please use [IRC/Discord/forums](https://github.com/libgdx/libgdx/wiki/Getting-Help#helping-yourself) for further questions, we'll be happy to help you there. This issue can be closed.
