### ISSUE TITLE
ParticleSystem multiple ParticleEffects with different Textures

### ISSUE THREAD

**Issue by cubesdev** [libgdx/libgdx#5759]
#### Issue details
The 3D ParticleSystem class does not work correctly as soon as multiple billboard ParticleEffects are loaded with different texture resources in their JSON 'assets' tag: All particles will share the same Texture.

Could be fixed if different effects were using their own BillboardParticleBatch type. But this is currently not working properly because you have to add (and construct) ParticleBatch objects manually. The ParticleEffectLoader does not take care of this step. The current `BillboardParticleBatch#setTexture()` method will override the texture for all future drawn effects, ignoring the assigned texture for a specific effect.

#### Reproduction steps/code
For example:

`   assets:[
      {
         filename:particle_type_one.png,
         type:com.badlogic.gdx.graphics.Texture
      }
   ]`

and
`   assets:[
      {
         filename:particle_type_two.png,
         type:com.badlogic.gdx.graphics.Texture
      }
   ]`

in a different billboard ParticleEffect.

I initialized the ParticleSystem using this code:  
`mParticleSystem = new ParticleSystem();`
`mBillboardBatch = new BillboardParticleBatch();`
`mParticleSystem.add(mBillboardBatch);`

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.10

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

Not tested on any other platform except Windows. It should be a general problem and I assume it will fail on all other platforms, too.

**Comment by Timvisser1994** [comment]
When implementing this, there is another aspect coming in: the division that you want, e.q. 50/50 or 30/70. This would mean that `assets` will need to support an array of `{ filename..., type... }`.

I would suggest to append an optional third parameter there: `{ filename..., type..., weight... }` where `weight` is a float ranging from `0.0` to `1.0` and where the sum of all weights is `1.0`. When no `weight` is specified, the remaining weight (`1.0` minus the sum of the specified weights) should be divided evenly across all entries that don't have a `weight` specified.

With this `weight`, one can have multiple particle assets that are... well... weighted. E.q. 30% balloons, 45% sparkles and the remaining 25% confetti. (In that case, the weights are: `0.3`, `0.45` and `0.25`, totaling `1.0`)

When the sum of the weights is more than `1.0`, the weights should be normalized so that _the ratio_ is preserved.

**Comment by cubesdev** [comment]
> When implementing this, there is another aspect coming in: the division that you want, e.q. 50/50 or 30/70. This would mean that `assets` will need to support an array of `{ filename..., type... }`.
> 
> I would suggest to append an optional third parameter there: `{ filename..., type..., weight... }` where `weight` is a float ranging from `0.0` to `1.0` and where the sum of all weights is `1.0`. When no `weight` is specified, the remaining weight (`1.0` minus the sum of the specified weights) should be divided evenly across all entries that don't have a `weight` specified.
> 
> With this `weight`, one can have multiple particle assets that are... well... weighted. E.q. 30% balloons, 45% sparkles and the remaining 25% confetti. (In that case, the weights are: `0.3`, `0.45` and `0.25`, totaling `1.0`)
> 
> When the sum of the weights is more than `1.0`, the weights should be normalized so that _the ratio_ is preserved.

I am not sure whether we are talking about the same issue. The bug described in the issue above refers to the fact that even multiple different billboard ParticleEffects (without any relation to each other) cannot be rendered correctly when their base particle texture differs. This is not a missing extra feature and not related to any weighting. It's simply an annoying BillboardParticleBatch creation bug which makes it very difficult/annoying to use the API when multiple effects are required.

**Comment by tommyettinger** [comment]
@cubesdev It seems like the 3D particle code is not maintained by any one person in particular -- we seem to depend on @mgsx-dev for a lot of 3D-related issues, and rather few other people have experience with it. Since this was reported nearly 2 years ago, no one was been able to even comment on it until today, probably because we need more 3D gurus on the team... Xoppa has his own priorities right now, and I'm glad he's doing well, but we can't expect him to swoop in and fix 3D issues, unfortunately. To me, it feels like the 3D-specific code (G3D files, Flame particles, not sure what else) might belong in an extension, if only because gdx-gltf could be swapped in to let a game avoid G3D entirely. It would also show that it's special-purpose code and should be expected to be harder to get help with. I don't use the 3D code, so I don't know if that's at all reasonable to suggest, and definitely don't expect it to happen, but other libraries built on libGDX like [Arc](https://github.com/Anuken/Arc) and [mini2Dx](https://mini2dx.org/) have discarded 3D support entirely. I believe this is because Arc is primarily meant for a 2D game (Mindustry) and both Arc and mini2Dx are primarily the work of one author for each, and neither author has the time to maintain both 2D and 3D parts of the library.

Anyway, I'm sorry your bug was ignored for 22 months, and I wish I could help.

@Timvisser1994 The weights seem very unrelated to this, but could be their own issue.

**Comment by Timvisser1994** [comment]
> I am not sure whether we are talking about the same issue. The bug described in the issue above refers to the fact that even multiple different billboard ParticleEffects (without any relation to each other) cannot be rendered correctly when their base particle texture differs. This is not a missing extra feature and not related to any weighting. It's simply an annoying BillboardParticleBatch creation bug which makes it very difficult/annoying to use the API when multiple effects are required.

@cubesdev Ahhhh, thank you for your comment! Indeed, I was not talking about the same thing 🙂
@tommyettinger I would love to try and resolve this bug... could you maybe give me some pointers please? Or is it something that solely relies on 3rd party software?

**Comment by tommyettinger** [comment]
@Timvisser1994 the Flame issue affects one of libGDX's extensions, https://github.com/libgdx/libgdx/tree/master/extensions/gdx-tools/src/com/badlogic/gdx/tools/flame . If you want to take a look, great! I have only run some other parts of gdx-tools (Hiero), but I think there's some main class in the `flame` directory that you can run. A PR for weights or especially a PR for this particle texture issue would be welcome, if only to get some more life into Flame. The PR would go to this repo (libgdx/libgdx) as normal.

**Comment by Timvisser1994** [comment]
@tommyettinger @cubesdev Well, I took a look (and opened and closed a PR) and it turns out that I don't know how to go about this... 😶

**Comment by tommyettinger** [comment]
Based on what mgsx-dev said in the PR comments, it's not clear if this even should be resolved, since particle effects should all be on one atlas page to get reasonable performance. (And that's all one texture.) It also seems like none of the current active members of the project (who would review any PR) use Flame, which could make large changes... challenging.

**Comment by mgsx-dev** [comment]
indeed, since you can use texture atlas, and particles are typically small sprites, there is no reason to support multiple textures. In all case Flame and Billboard batch was not designed in this way.
