### ISSUE TITLE
New R8 obfuscator with android

### ISSUE THREAD

**Issue by SimonIT** [libgdx/libgdx#5785]
I tried releasing my game on android with enabled minifying. It did work with proguard, but the new R8 obfuscator did not work. I used the default proguard config file. 
I tried this https://badlogicgames.com/forum/viewtopic.php?t=29056 solution but it didn't work

#### Reproduction steps/code
Set `minifyEnabled true` in android/build.gradle

#### Version of LibGDX and/or relevant dependencies
Android Gradle plugin 3.4.0 and higher, in my case 3.4.2

#### Stacktrace
```
Couldn't construct AndroidInput, this should never happen
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Anuken** [comment]
This is because reflection is used to construct input: [See this file.](https://github.com/libgdx/libgdx/blob/a4805d6a017b80622d6bfdd3a791352257a3c539/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidInputFactory.java)

If you somehow prevent R8 from obfuscating these class names, it should work.

*Side note: The code linked is completely unnecessary now, considering that the API level should/will be raised to 14 soon.*

**Comment by 00-Evan** [comment]
I encountered this issue as well, (see here: https://gitlab.com/fdroid/fdroiddata/issues/1759) but it seems to be fixed when using android gradle plugin 3.5.0 or higher

**Comment by SimonIT** [comment]
@Anuken Yes, I know. But R8 works with the same config like proguard. So I'm wondering why proguard works and R8 not.
https://developer.android.com/studio/build/shrink-code

@00-Evan That's interesting. I will try it

**Comment by Anuken** [comment]
@SimonIT That's because Proguard will automatically recognize cases of reflection usage, while R8 does not. See https://www.guardsquare.com/en/blog/proguard-and-r8

**Comment by SimonIT** [comment]
@Anuken But the page you linked says:

> The good news for developers is that R8 is backward compatible with ProGuard. If you have a working ProGuard configuration (maybe eclectically copied from Stackoverflow), you can carry that over to R8.

**Comment by Anuken** [comment]
Configuration is backwards compatible, but that doesn't imply that it has the same features. The page also mentions:

> R8 doesn't yet automatically recognize and handle simple cases of reflection.

**Comment by MobiDevelop** [comment]
Hasn't it been a long time since you needed to use reflection in these cases anyway?

**Comment by SimonIT** [comment]
I personally never used reflection.
By the way, why is reflection used in `newAndroidInput`?
```java
if (sdkVersion >= 12) {
	return new AndroidInputThreePlus(activity, context, view, config);
} else {
	return new AndroidInput(activity, context, view, config);
}
```
This works also fine, or am I missing something? If not, I'll make a PR

**Comment by jsjeon** [comment]
For those missing reflective cases, could you try adding `-addconfigurationdebugging` into the proguard configuration? It will add logging messages instead of shrinking apps, so it might reveal where a certain type is reflectively created (as well as where R8 is missing). See: https://issuetrackers.google.com/issues/73707846
