### ISSUE TITLE
screen flickering when draw spritebatch in render loop one time

### ISSUE THREAD

**Issue by sadeghpro** [libgdx/libgdx#5788]
#### Issue details
I want to draw one time on screen and until next change not clear screen and render it again then I wrote this code:
```java
public class MyGdxGame extends ApplicationAdapter {
	SpriteBatch batch;
	Texture img;
	int i = 0;
	
	@Override
	public void create () {
		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");
	}

	@Override
	public void render () {
		if (i == 0) {
			Gdx.gl.glClearColor(1, 0, 0, 1);
			Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
			batch.begin();
			batch.draw(img, 0, 0);
			batch.end();
			i++;
		}
	}
}
```
it's work fine on ios but on mac os and android screen flickering like this
![bug](https://user-images.githubusercontent.com/22843329/64476764-32e39f80-d1a8-11e9-9cd1-e2f896ab1e8d.gif)

I add `Thread.sleep(1000);` to see what happened exactly and I see in even time it's work fine but in odd time it's only show back screen
then I set image only in two first frame with different position like this:
```java
@Override
public void render () {
	if (i < 2) {
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		batch.begin();
		batch.draw(img, 100 * i, 0);
		batch.end();
		i++;
	}
	try {
		Thread.sleep(1000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
}
```
and the out put is :
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/22843329/64476898-e6995f00-d1a9-11e9-9e9f-fa0d514d8789.gif)

in android it's worse I test it on `Sony C1305 (Android 4.2.2, API 17)` and 4 first frame is affected like above, I mean if you set image in only 4 first frame with different position android shows image in loop with 4 different position

Is this a bug or it's fine? I want to do this for better performance and only draw screen if needed not in each frame.

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Please select the affected platforms
- [x] Android
- [x] MacOS
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux

**Comment by angns9** [comment]
If you want to render only when needed, you should call Gdx.graphics.setContinuosRendering(false)

See https://github.com/libgdx/libgdx/wiki/Continuous-%26amp%3B-Non-Continuous-Rendering

**Comment by Darkyenus** [comment]
angns9 is correct and libGDX does explicitly support what you want, you just have to use the correct API.

I just want to add, that what you are seeing is the effect of double buffering - [see wikipedia article](https://en.wikipedia.org/wiki/Multiple_buffering) - and even if what you see is reproducible, you should *never* rely on it, because it usually isn't guaranteed (as you can see, some platforms handle even this simple case differently). The backbuffer into which you are drawing can usually contain anything (exact behavior is platform defined), sometimes even garbage leftovers from other programs. Even on iOS, where the behavior seems predictable, the contents of the backbuffer will most likely become corrupted/erased after putting your application into the background and then bringing it back (or quite possibly after receiving a call, notification, etc.).

**Comment by sadeghpro** [comment]
tnx @angns9 it was just what I needed
but I want to know why this happened that @Darkyenus explains it,
really tnx
