### ISSUE TITLE
BitmapFont draws strings starting with spaces at a wrong offset

### ISSUE THREAD

**Issue by guichazan** [libgdx/libgdx#5824]
Hi,

If you draw " a b" and "a  b" (two consecutive spaces), it will draw them with a different width. The reason is at BitmapFont:

if (lastGlyph == null) // First glyph on line, adjust the position so it isn't drawn left of 0.
   xAdvances.add(glyph.fixedWidth ? 0 : -glyph.xoffset * scaleX - padLeft);

the space char has xoffset=0, while all other chars have a positive value.

This is the result of the error:

![image](https://user-images.githubusercontent.com/28924247/67801129-52d86680-fa67-11e9-8abd-c83b5d24bf44.png)

**Comment by tommyettinger** [comment]
If you depend on things being drawn with a fixed width, you can't do what you're doing. Use a fixed-width font; of course this means "not Arial," and if you make a fixed-width font with Hiero then make sure "FreeType" is selected near the upper left. You probably also need to set all glyphs that must be fixed-width (typically numbers, space, '.', etc.) to definitely be fixed-width with `bmpFont.setFixedWidthGlyphs("0123456789 .-+,");` . All font layout that can allow glyphs to have negative x offset will have the potential problem of letters sticking out of their containing widget; the code you pasted from libGDX addresses that, and is not an error.

If you think this is is an error or even unusual, just wait until you deal with width changes from kerning or hinting... In some fonts the expected behavior is for `..ff..` to have a smaller width than `..f..f` due to `ff` fusing into one kerning pair; it could look ugly without that behavior.

**Comment by guichazan** [comment]
Hi, i'm not using fixed width fonts. Actually, the font i created was a MSDF based on  Chlumsky/msdfgen, using a Roboto font. 
The space is a special Glyph, from what i saw. The BitmapFont ignores kerning, so its not a real problem.

**Comment by tommyettinger** [comment]
Yes, you're not using fixed-width fonts. So, you can't expect fixed-width. That's all.

There's potentially other issues with MSDF because most tools that use it don't produce glyphs with the same baseline, so the bottom of each letter wiggles up and down as you read left to right. Even if you are sure you are using an MSDF font with uniform height, the MSDF shader adds and removes pixels based on the current zoom. If it adds pixels at the end of a word, that word will appear wider.

**Comment by guichazan** [comment]
I created a customized version of the shader exactly to remove the python dependency and fix the up/down issue (that also occurs with Hiero).

I'm closing the issue because i found that is a bug in the generated MSDF font that does not occur when Hiero is used.
