### ISSUE TITLE
Atlas region render rotated

### ISSUE THREAD

**Issue by svk2140** [libgdx/libgdx#5851]
Why this method render region by rotate 90°?
Whereas a regular one that accept input position and size renders normally.
![image](https://user-images.githubusercontent.com/12610535/69573580-113bcc80-0fcf-11ea-8430-ad0d29d90a3f.png)

**Comment by MobiDevelop** [comment]
It is unclear what the issue is that you are reporting. If you simply have a questions, please use one of the community support channels (irc, discord, forum, stackoverflow, etc...).

An AtlasRegion may be rotated, depending on the settings when the atlas was packed. Depending on what you want to do, you may use AtlasSprite to automatically account for the rotation and/or whitespace stripping that might occur during packing the atlas, or you can manually account for those.
