### ISSUE TITLE
com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:149)

### ISSUE THREAD

**Issue by leafdjy** [libgdx/libgdx#5872]
Issue details
I use libGdx partical 2D effect. Crashed When ParticleEffect->loadEmitterImages.
I had try-catch all method.

Version of LibGDX and/or relevant dependencies
1.9.8

Stacktrace
`
1 com.badlogic.gdx.utils.GdxRuntimeException:Couldn't load file: /data/user/0/com.xx.xx/files/skins/effect/xxx.png
--
2 com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:149)
3 ......
4 Caused by:
5 android.system.ErrnoException:read failed: EINVAL (Invalid argument)
6 libcore.io.Linux.readBytes(Native Method)
7 libcore.io.Linux.read(Linux.java:184)
8 libcore.io.BlockGuardOs.read(BlockGuardOs.java:254)
9 libcore.io.IoBridge.read(IoBridge.java:501)
10 java.io.FileInputStream.read(FileInputStream.java:307)
11 java.io.FileInputStream.read(FileInputStream.java:276)
12 com.badlogic.gdx.utils.O0O00oO.O000000o(StreamUtils.java:49)
13 com.badlogic.gdx.utils.O0O00oO.O000000o(StreamUtils.java:36)
14 com.badlogic.gdx.utils.O0O00oO.O000000o(StreamUtils.java:91)
15 com.badlogic.gdx.O00000o0.O000000o.O0000oO0(FileHandle.java:224)
16 com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:146)
17 com.badlogic.gdx.graphics.glutils.O00000o.O00000Oo(FileTextureData.java:62)
18 com.badlogic.gdx.graphics.Texture.O000000o(Texture.java:134)
19 com.badlogic.gdx.graphics.Texture.O00000o0(Texture.java:150)
20 com.badlogic.gdx.graphics.Texture.O00000Oo(Texture.java:222)
21 com.badlogic.gdx.backends.android.O000O0OO.onSurfaceCreated(AndroidGraphics.java:328)
22 android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1543)
23 android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1271)
`
platforms:
 Android

 Thanks for your support.

**Comment by EtK2000** [comment]
Please supply the particle files you're trying to load, as well as a minimal code sample.

**Comment by intrigus** [comment]
This seems to not be a libgdx issue.

**4 Caused by:
5 android.system.ErrnoException:read failed: EINVAL (Invalid argument)
6 libcore.io.Linux.readBytes(Native Method)
7 libcore.io.Linux.read(Linux.java:184)**

**Comment by Darkyenus** [comment]
`libcore.io.Linux.readBytes` internally uses `read` syscall ([at least on unmodified Android](https://android-review.googlesource.com/admin/repos/platform/libcore)). [`read` manpage](https://linux.die.net/man/2/read) says, that `EINVAL` can happen under following circumstances:
> fd is attached to an object which is unsuitable for reading; or the file was opened with the O_DIRECT flag, and either the address specified in buf, the value specified in count, or the current file offset is not suitably aligned.

Since it is unlikely that `O_DIRECT` would be used (or used incorrectly), it seems that the file is "unsuitable for reading". I am not really sure what that means, since the opening of the file already succeeded. Perhaps the directory was unmounted or permissions changed? (Not sure if that would manifest retroactively, probably not.)

In any case, this does not seem like a libGDX issue.

**Comment by Tom-Ski** [comment]
Nothing we can do here
