### ISSUE TITLE
LongMap is buggy

### ISSUE THREAD

**Issue by playmyskay** [libgdx/libgdx#5930]
#### Description
The current implementation of LongMap definitely has a bug. 
After switching back to commit e8fd323c485db7a292c848ad11d6f4c92a386ca7 the problem does not occur anymore. Unfortunately I have a relatively complex construct in my project, which I can't convert into a simple example at the moment.

I add entries and delete them relatively often. After a while an entry is not found anymore, although it is still visible in the debugger in the variable "keyTable".

In any case, I can see that in the following routine the condition "`if(other == 0)`" causes subsequent entries in keyTable to be ignored (called by containsKey):

```java
	private int locateKey (long key) {
		long[] keyTable = this.keyTable;
		for (int i = place(key);; i = i + 1 & mask) {
			long other = keyTable[i];
			if (other == 0) return -(i + 1); // Empty space is available.
			if (other == key) return i; // Same key was found.
		}
	}
```

#### Version of LibGDX
1.9.11-SNAPSHOT

#### Please select the affected platforms
propably all?

- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

**Comment by tommyettinger** [comment]
I'll look into it. If you can provide any kind of info on what kind of keys are in use when this bug happens, that would help; it would also really help to know what size the LongMap has, or (if you have the debugger going) how big the key array is, since that might narrow down the sizes I would need to check to reproduce. The code you pasted in locateKey() is probably not the issue; IIRC the zero key is handled differently from other keys, so the presence of a 0 key at the slot that place() found (or just after, if it needs to loop through identically-placed keys) means that the key is not in the table. That method, locateKey(), just finds the location of one key (as a non-negative int) or the location of the first empty slot in the array where a key could be placed (as a negative int, which gets flipped back to non-negative if used).

**Comment by tommyettinger** [comment]
I was able to reproduce with a few thousand sub-random keys and mixed put() and remove() calls. I have a fix, it's just not ready until I can figure out what other classes with similar code are affected. [Here's the fix commit in a different repo](https://github.com/tommyettinger/merry-ds/commit/695508b6bc8c721aadd54e46ad1384cbba8bc114); it isn't a lot of code and should actually improve performance in benchmarks because it will keep sizes accurate instead of larger.
