### ISSUE TITLE
LWJGL backend parent file path not correctly resolving

### ISSUE THREAD

**Issue by Crunkle** [libgdx/libgdx#5936]
I am unsure if this is the intended design, but I have found that relative path parents do not behave as I would expect them to on the LWJGL backends. See [here](https://github.com/libgdx/libgdx/blob/a3610535f4dcd9b3ae90f790c9fd17bbb3dddf61/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3FileHandle.java#L47) plus the matching sibling class for LWJGL 2.

Now imagine the following snippet and directory structure:

```java
new Lwjgl3FileHandle("tilemap.tmx", FileType.Internal).parent().parent()
```

```
- A
-> tileset.png
-> B (working dir)
--> tilemap.tmx
--> my-game.jar
```

I would expect this to return the `A` directory which is two parents above `tilemap.tmx`. In reality, it does not resolve the absolute path and stops at `B` as an effectively empty path. Is there any rationale I am missing for not using `file.getAbsoluteFile().getParentFile()` inside of `parent`?

**Comment by tommyettinger** [comment]
Internal files are inside the JAR on desktop releases and inside the APK on Android. On GWT, the `A` folder doesn't exist at all. If you want to look outside the JAR or APK, use `FileType.Local` or `FileType.External`, with the last one needing extra permissions on Android but it's probably what you would need.

**Comment by NathanSweet** [comment]
Note on desktop `Internal` prefers a file in the working directory, else it looks in the classpath. Be careful it doesn't pick the wrong file if you wanted it from the classpath!

I think it makes sense for all FileHandles that are `Absolute` to use File `getAbsoluteFile` for their `file` field. After all, it has absolute in the name. Changing it _probably_ doesn't affect existing code negatively, as absolute is already seldom used.

On desktop it seems like both `Local` and `External` could be absolute, but it's not clear how badly this might break existing code. Due to that, I would suggest not changing them. `Internal` can't be absolute, because it resolves to either the filesystem or the classpath as late as possible.

On other platforms I am not sure when it makes sense for the path to be absolute. Someone who makes more use of those platforms could say, otherwise I would leave them as is.

**Comment by Crunkle** [comment]
I am going to close this. It would be nice to have references to files in parent directories, but it is easily avoidable. Upon testing I have found that there is no quick fix without harming existing code.
