### ISSUE TITLE
Trouble launching gdx-setup.jar

### ISSUE THREAD

**Issue by OliPerraul** [libgdx/libgdx#5963]
Please ensure you have given all the following requested information in your report.

#### Issue details
Trouble with gdx-setup

#### Reproduction steps/code

Launching the jar either from command line or by double clicking produces no result
![image](https://user-images.githubusercontent.com/24371247/77251721-55aa4280-6c26-11ea-8e92-352320922187.png)

#### Version of LibGDX and/or relevant dependencies
latest release

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [x] Windows

**Comment by SimonIT** [comment]
@Tom-Ski It seems, that the automatic builded gdx setup is broken because of this split. The reason is that ant is used for building.
We have two options to fix this:
1. Use the gradle script I created in a recent PR to create the gdx-setup.jar (IMO preferred)
2. Fix the ant scripts (I got no clue about ant)

**Comment by OliPerraul** [comment]
I don't know what your fix is? This issue should be fixed ASAP as the main download link dosent work. Ideally the main download from the website should not be tied to a nightly build but rather a stable version.

**Comment by Tom-Ski** [comment]
https://github.com/libgdx/libgdx/pull/5966
