### ISSUE TITLE
Silent crash on Windows with lwjgl3 backend and opengl 3.2+

### ISSUE THREAD

**Issue by langurmonkey** [libgdx/libgdx#6048]
#### Issue details
Libgdx program throws GLFW errors on Windows 10 using the lwjgl3 backend when setting `config.useOpenGL3(true, 3, 2)`. Does not seem to depend on graphics card (tested with intel UHD 620, Geforce MX150 and Quadro K2000M). It works fine on Linux.
The stack trace comes directly from lwjgl (see below).
**Edit:** The program does not crash, but prints lots of `GLFW_PLATFORM_ERROR` to std err.

#### Reproduction steps/code
1. Create empty default project using `gdx-setup.jar`. 
2. Choose only desktop sub-project, no extensions. 
3. Change backend to lwjgl3 in dependencies of main `build.gradle` file. 
4. Add `config.useOpenGL3(true, 3, 2);` to main desktop launcher class. Trying to use OpenGL 4.1 causes even more errors.
5. Run. Minimize/maximize window, until GLFW crash is printed to error output.

#### Version of LibGDX and/or relevant dependencies
Libgdx 1.9.10, with lwjgl3 backend. Desktop only. 

#### Stacktrace
```java
[LWJGL] GLFW_PLATFORM_ERROR error
	Description : WGL: Failed to make context current: The handle is invalid. 
	Stacktrace  :
		org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:4492)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.makeCurrent(Lwjgl3Window.java:442)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:134)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
		test.app.desktop.DesktopLauncher.main(DesktopLauncher.java:11)
[LWJGL] GLFW_PLATFORM_ERROR error
	Description : WGL: Failed to make context current: The requested transformation operation is not supported. 
	Stacktrace  :
		org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:4492)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.makeCurrent(Lwjgl3Window.java:442)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:134)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
		test.app.desktop.DesktopLauncher.main(DesktopLauncher.java:11)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by crykn** [comment]
Hey @langurmonkey, 
after some research I found a very similar issue in another open source project: [intel-isl/Open3D#1550](https://github.com/intel-isl/Open3D/issues/1550), which refers to [intel-isl/Open3D#1598](https://github.com/intel-isl/Open3D/issues/1598). 

The problem seems to be the integrated gpu (the second issue even mentions one similar to yours, Intel UHD 630). If an integrated gpu is used, the application crashes, if another gpu is used, it works. I know that you mentioned that you had tested this issue with different graphics cards, but if all of those were plugged into the same pc, which had the integrated graphics card, can you be sure which gpu was used? 

[intel-isl/Open3D#1598](https://github.com/intel-isl/Open3D/issues/1598#issue-579235134) provides a workaround for this: explicitly setting the used graphics card. As they are using python, I don't whether this solution is going to work in your case as well, but it might be worth a shot.

**Comment by langurmonkey** [comment]
Hi @crykn, thanks for the info! I'll have a look at the related issue in Open3D and see if it helps. Since I don't use Windows, testing this will probably take a while, unfortunately.

**Comment by crykn** [comment]
This issue seems to be out of libGDX' control. Closing it for now.
