### ISSUE TITLE
[Question] How to import libGDX into an existing project?

### ISSUE THREAD

**Issue by seccpur** [libgdx/libgdx#6055]
#### Questions

1) I have  a working C++ native template Android Studio generated working NDK project, how do I import libGDX into this project seamlessly, so that graphics can be handled ?

2) libGDX auto generated build gradle mention of apply `plugin: "eclipse"`, but it still works for Android Studio. How do to change  Android Studio?

#### IDE
- Android Studio 3.5.3

#### Platform
- Android

**Comment by Darkyenus** [comment]
Since this is not an issue with libGDX, please close this and [take your question to Discord/IRC](https://github.com/libgdx/libgdx/wiki/Getting-Help), which is better suited for these questions and folks there will be happy to help you.

That said, you will have to somehow merge both projects. How to do this depends on your needs and more info will be needed (but not here).

Regarding the second point - yes, the eclipse plugin is needed only when you use the Eclipse IDE.
