### ISSUE TITLE
float value fnt file

### ISSUE THREAD

**Issue by DragonKing91-jych** [libgdx/libgdx#6065]
Recently I used BMFont Generator tool, but I didn't get .fnt file with float values form this tool.
So, I want to get fnt generator surpporting float value.
How can I get that tools?
Please help me.

**Comment by tommyettinger** [comment]
I'm pretty sure libGDX doesn't store the values in a .fnt as floats when it loads them, because [BMFont's official file format documentation](https://www.angelcode.com/products/bmfont/doc/file_format.html) says all numeric fields have the type int or uint. So it sounds like you're asking for libGDX to implement a non-standard extension to the .fnt format as well as change the Hiero generator to support this non-standard extension. Do you have some really good reason that you want to give us?

**Comment by NathanSweet** [comment]
We probably shouldn't go against the spec. You can modify the tools as you need.
