### ISSUE TITLE
Android device camera working example 

### ISSUE THREAD

**Issue by patolax** [libgdx/libgdx#6072]
I tried the source code in the wiki, in order to just show Camara preview on android real device. 
[wiki/Integrating-libgdx-and-the-device-camera](https://github.com/libgdx/libgdx/wiki/Integrating-libgdx-and-the-device-camera)

That implementation is outdated. I tried fixing 100s of errors but ended up getting a black screen. 
Not sure anymore about how to fix it. Any working example would be highly appreciated. 

Steps
1) Use gdx-setup.jar and create a new project.
2) Copy code from the wiki, under android and core folders.
3) Fix errors and run

**Comment by MrStahlfelge** [comment]
Hi, the wiki is publicly editable and the example was brought in by another libgdx user. Things change, and I would recommend you not to take the picture yourself but let the camera app things and get the picture back.

This is nothing libgdx related, but a task many Android apps do. To see how you can [work with Android specific code in libgdx there is a wiki article.](https://github.com/libgdx/libgdx/wiki/Interfacing-with-platform-specific-code). This should get you in the right direction.

I am closing this issue now because it is not an issue, but a help request. To find help I recommend you to visit our Discord server. It is full of helpful people.
