### ISSUE TITLE
Replace @Null with an existing library for automatic Kotlin conversion

### ISSUE THREAD

**Issue by cypherdare** [libgdx/libgdx#6077]
I see that in #5812, a custom `@Null` annotation was added. It would be helpful for Kotlin users if one of the annotation libraries listed [here](https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations) were used, because then Kotlin would automatically treat these types as nullable.

In #5615, there was some discussion about whether the Jetbrains library for the annotation should be used. The last opinions on the matter were "I recommend..." and "I could go either way", but ultimately they were not used.

@maltaisn, how are you actually utilizing the annotation to check code? 

This isn't a critical issue. It would just be nice to have since there's an `@Null` annotation anyway now.

**Comment by maltaisn** [comment]
I tried to push the Jetbrains annotations but introducing a new dependency wasn't very welcome, even though it's a source only dependency. I can partly agree to that, i.e. not wanting to tie libGDX to Jetbrains or any other company (Eclipse, Google and others have their own annotations too). 

[This StackOverflow answer](https://stackoverflow.com/a/42695253) makes a pretty detailed analysis of each nullability annotations artifacts, and explains how there's no "official" nullability annotation artifact. `javax.annotation` would probably have been the best, but it's dead apparently. So I think that's how libGDX ended up with it's own `@Null` annotation (which is quite badly named in my opinion).

I also think that some resistance came from the fact handling @​Nullable from Java is a real pain sometimes. Consider this example:
```
object.getFoo().getBar().getBaz();
```
What if the return value of all 3 getters is marked as nullable, but you *know* they're not null? You get a warning on the whole chain, and that's ugly. You have a few choices:
1. Assert each as not null
    ```
    Foo foo = object.getFoo();
    assert foo != null;
    Bar foo = bar.getFoo();
    assert bar != null;
    Baz foo = baz.getFoo();
    assert baz != null;
    ```
    This is so long and verbose that I've never actually seen it done.

2. Remove the warning locally.
    ```
    //noinspection ConstantConditions
    object.getFoo().getBar().getBaz();
    ```

3. Disable the inspection, and we're back to square one.

Compare that to Kotlin's `object.foo?.bar?.baz ?: ...` and you understand why nullability annotations make a lot more sense when using Java from Kotlin than when using Java from Java. But I'm not sure how interested the maintainers are with better Kotlin compatibility...

> how are you actually utilizing the annotation to check code?

I'm not. I made a game last year but I'm not making any currently, and the PR was only merged recently. 

I just checked if IntelliJ IDEA supports a third party annotation for Kotlin and well... it doesn't. It only has support for Java. (Inspections > Java > Probable bugs > Nullability problems > @​NotNull/@​Nullable problems) The Kotlin compiler does seem to have a way to add custom nullability annotations (see [JSR-305 support](https://kotlinlang.org/docs/reference/java-interop.html#jsr-305-support)), but it requires the annotation to be itself annotated with some `javax.annotation` annotations so that kind of misses the point of avoiding the dependency.

I consider that adding the annotations to the framework for improving Kotlin interop is kind of a dead end. Plus, the use of @​NotNull was dismissed entirely when it's as important as @​Nullable, if not more. I never actually got around adding the nullability annotations to the rest of the framework, and I'm not sure if I intend to.

What seems more promising however are IntelliJ's [external annotations](https://www.jetbrains.com/help/idea/external-annotations.html), I have known about them for a while but never considered using them to solve the Kotlin compatibility problem. They're frequently used to add annotations to code you don't have access to, or when annotations take too much space in the source (like @​NotNull here). It seems perfect for this use case. They can also be [distributed as maven artifacts](https://www.jetbrains.com/help/idea/external-annotations.html#external-annotations-maven) which is great. I'll see if I can make this work and distribute it. Maybe @libktx would even be interested to include them?

**Comment by cypherdare** [comment]
Hmm, I wonder if external annotations can use the existing `@Null` to apply Jetbrains' `@Nullable`. I'll look into that. Sounds like it could be a helpful tool for KTX.

I don't think there's much incentive (at least from Kotlin) to have another annotation for non-nullables. Kotlin already lets you treat unspecified variables as non-nullable.

**Comment by cypherdare** [comment]
Looks like workarounds are possible externally.

**Comment by maltaisn** [comment]
Actually I've been enquiring on that and IntelliJ doesn't really let you include external annotations dependencies yet. See [this issue](https://youtrack.jetbrains.com/issue/IDEA-201991) on YouTrack. Also the Kotlin compiler can't see them yet either. I'm hoping this will become possible for the next IntelliJ release.

In the meantime I've started externally annotating the libGDX source code, I'll make a repo when I've made enough progress.
