### ISSUE TITLE
GDX_Bullet with Maven

### ISSUE THREAD

**Issue by CesarChodun** [libgdx/libgdx#6097]
Hi, I'm having trouble with importing the gdx-bullet dependency to my project.
I suspect that the problem is just missing natives. But I don't really know how to get them with maven.

I'm using Windows 10 64-bit.

My pom.xml ([...] replaces some unimportant information):

<code>
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>[...]</artifactId>
        <groupId>com.[...]</groupId>
        <version>0.2.1-SNAPSHOT</version>
        <relativePath>../[...]/pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>[...]</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <repositories>
        <repository>
            <id>mvn-repo</id>
            <url>https://mvnrepository.com</url>
        </repository>
        <repository>
            <id>jcenter</id>
            <url>https://jcenter.bintray.com/</url>
        </repository>
    </repositories>

    <dependencies>
        [...]

        <dependency>
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx-bullet</artifactId>
            <version>1.9.10</version>
        </dependency>
    </dependencies>

    <properties>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.source>1.8</maven.compiler.source>
    </properties>

</project>
</code>

The error message:

<code>com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx-bullet64.dll' for target: Windows 10, 64-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:125)
	at com.badlogic.gdx.physics.bullet.Bullet.init(Bullet.java:63)
	at com.badlogic.gdx.physics.bullet.Bullet.init(Bullet.java:52)
	at com.badlogic.gdx.physics.bullet.Bullet.init(Bullet.java:44)
	at rendering.PhysicsEngineTest.run(PhysicsEngineTest.java:21)[<- this is my class]
	at com.sfengine.components.engines.OscillatoryEngineExecutor.run(OscillatoryEngineExecutor.java:49)
	at com.sfengine.components.engines.DefaultEngine.run(DefaultEngine.java:58)
	at Main.main(Main.java:37)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: gdx-bullet64.dll
	at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:133)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:289)
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:121)
	... 7 more</code>

**Comment by tommyettinger** [comment]
You probably need the platform jar in addition to the pure-Java dependency you already have; the platform jar contains the Windows dll as well as Linux and MacOS libraries, at least for the desktop platform. There's different versions for some other targets, and you can choose one with a Maven classifier; Android needs several classifiers because there's several architectures in use for Android. For desktop, including Windows, Linux, and MacOS:

```xml
<dependency>
  <groupId>com.badlogicgames.gdx</groupId>
  <artifactId>gdx-bullet-platform</artifactId>
  <version>1.9.10</version>
  <classifier>desktop</classifier>
</dependency
```

I hope this helps. There isn't much overlap between Maven users and libGDX users, so some of these questions are slow to find answers; almost everyone uses Gradle because Android development strongly favors it. Gradle's pretty bad though... where the question with Maven is "What obscure configuration do I need to make this work?" the question with Gradle is "Why doesn't this work in the IDE, it worked yesterday, and it halfway works from the command-line, and where did my entire day go...?"

**Comment by crykn** [comment]
Closing this, since the solution provided by @tommyettinger should work.
