### ISSUE TITLE
Mixed types in gdx collections

### ISSUE THREAD

**Issue by augustozanellato** [libgdx/libgdx#6119]
Please ensure you have given all the following requested information in your report.

#### Issue details
In collections there are some occurences of wrong parameter types
`IntFloatMap.findKey(int, int)` should be `(float, int)`
`IntFloatMap.containsValue(int)` should be `(float value, float epsilon)`

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.11

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by crykn** [comment]
Hey @augustozanellato, as far as I can see, you're right. The value parameter should be a float and not an int.
This bug was introduced by @tommyettinger with #5900 , however, I don't think this was intentional. This was probably just a copy & paste mistake.

Would you be willing to submit a PR for that?

**Comment by augustozanellato** [comment]
Sure, I'll be able to do that in a couple days!

**Comment by NathanSweet** [comment]
Thanks!

**Comment by tommyettinger** [comment]
Thanks for fixing my bug, and adding epsilon (back)! The mixed-type maps were quite confusing to port, since I also had ObjectFloatMap (I haven't checked if it has the same float typo or if it could use an epsilon-comparison overload), ObjectIntMap, IntIntMap, IntMap, etc. I think the float-value maps were sometimes copied from an int-value map, which would omit extra methods dealing with epsilon.

**Comment by NathanSweet** [comment]
No worries, can't have you hogging all the bugs! :) Looks like ObjectFloatMap also needed the methods (added now).
