### ISSUE TITLE
1.9.12-SNAPHOT: Exception with newline labeltext.

### ISSUE THREAD

**Issue by Trurl101** [libgdx/libgdx#6159]
Please ensure you have given all the following requested information in your report.

#### Issue details
Setting a label with "\n" only results in Exception.

#### Reproduction steps/code
Displaying a new Label created with "\n" only as text.

#### Version of LibGDX and/or relevant dependencies
1.9.12-SNAPHOT

#### Stacktrace
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:294)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.layout(Label.java:196)
	at com.badlogic.gdx.scenes.scene2d.ui.Widget.validate(Widget.java:88)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.draw(Label.java:229)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:129)
	at xxx.ScreenAbstract.render(ScreenAbstract.java:113)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at xxx.GameAbstract.render(GameAbstract.java:187)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)

**Comment by rdamiano** [comment]
Nice quick fix @NathanSweet 
Oof @ still no snapshot for it tho so my app is still exploding with NPE due to user-input
Coding in a workaround rn but just curious what is the snapshot schedule? I thought it was nightly but-

**Comment by NathanSweet** [comment]
Can see the libgdx build here:
https://libgdx.badlogicgames.com/jenkins/
The job console output shows:
> Waiting for the completion of libgdx-mac
There's two macs, just need one to come online. @Tom-Ski maybe you can boot one?

**Comment by rdamiano** [comment]
Hm so, not to be completely annoying here but there still hasn't been a snapshot in 11 days and if I'm reading that page right, a build began 23 hours ago but never finished? Lol @Tom-Ski

**Comment by Tom-Ski** [comment]
The previous builds were blocked as there were merges that just broke the build. Im having some power issues were the node is, so its occasionally causing the mac to not come back online. Ill check it again now

**Comment by RUSshy** [comment]
can we enforce PRs so every code is reviewed instead of randomly commit to master?

many people depend on this library, let's be professional

**Comment by Tom-Ski** [comment]
Things aren't just randomly committed to master, and in this case, it was reviewed by many people, and passed all tests. Snapshots are there to be bleeding edge, there is no guarantee about stability if you are on snapshots.

**Comment by crykn** [comment]
Hey @RUSshy, I have to agree with Tom-Ski. Nothing is "randomly being committed to master" and there will always be  issues that PR reviews and testing just can't prevent, see for example the recent problems due to differences between Travis CI (used to check whether the PRs compile) and Jenkins (used to actually build the snapshots). 

Also, snapshots are not there to replace official and stable releases. Relying on them is and always will be at your own risk! We recognize that due to the large time between releases, in the past, users may have been inclined to use these snapshots more often, but we are working on shorter release cycles exactly to remedy such problems. For more information on our release policy going forward, please also take a look at the official [libGDX blog](https://libgdx.com/news/2020/09/devlog_2_release_schedule).

**Comment by RUSshy** [comment]
it's not about stability it's about reviewing code by more people than the just commit author himself

this is a community project, not a solo one anymore

**Comment by RUSshy** [comment]
you can't review commits, if mistakes you have to pollute the git tree with revert commits etc etc

**Comment by Tom-Ski** [comment]
It's up to the discretion of all core contributors whether they make their changes with PR or not.  Not everything needs to be PR'd, and increasing bureaucracy for trusted contributors who know the framework inside out is going to make them less likely to want to commit in the first place, for very little gain if any at all.

Its been a very long time since it was ever a solo project, our approach has always been this way, and it's not something that is likely to change now.

Take this discussion elsewhere please, this is on an unrelated issue. Discord would be more appropriate if you wanted to have a discussion or open up an issue if you'd like to discuss it in broader sense with the rest of the core contributors.

**Comment by RUSshy** [comment]
Sorry for the noise created!
