### ISSUE TITLE
File resolution without extension

### ISSUE THREAD

**Issue by deedywu** [libgdx/libgdx#6161]
#### Issue details
When I generate cached MP3 files from other game resource files, I don't want the extension on purpose, but I need extension when I play it

#### Reproduction steps/code
```

package com.badlogic.gdx.files;

public class FileHandle{

...

    protected String extension;

    /**
     * Add an attribute and a method to find a suitable parser for the no extension file.
     * Call the last line of all constructor methods  ex: setExtension(null);
     * @param extension suffix
     */
    public void setExtension(String extension) {
        if (extension == null) {
            String name = this.file.getName();
            int dotIndex = name.lastIndexOf(46);
            this.extension = dotIndex == -1 ? "" : name.substring(dotIndex + 1);
        } else {
            this.extension = extension;
        }
    }

   ...

    /** Returns the file extension */
    public String extension () {
        return extension;
    }

}

```

**Comment by MrStahlfelge** [comment]
Sorry, it is not clear what you want to achieve and what is the problem here. Please state  what you are doing and what is not working.

**Comment by deedywu** [comment]
Sometimes the extension is needed to parse the file, so I can set the extension myself. Can you add the above code to the next version.
![image](https://user-images.githubusercontent.com/29275153/92221736-7adaf680-eed0-11ea-9c36-06be808f972d.png)

**Comment by MrStahlfelge** [comment]
Why don't you generate the files with the correct extension?

**Comment by mgsx-dev** [comment]
Extension is part of the path, changing extension would mean changing the path which mean it's not the same file handle.
Faking things like this would totally change what a FileHandle is and make it inconsistent.
That's not a valid use case IMO.

**Comment by NathanSweet** [comment]
I agree it would be odd to set an extension on a FileHandle, as the extension comes from the path.

Seems OP's issue is that Audio `newSound`/`newMusic` uses the extension to decide how to parse the file. We'd need to add a new Audio method to allow choosing how the file is parsed without using the extension. A workaround may be to subclass FileHandle and return a hardcoded value for the FileHandle `extension` method. On the desktop with an absolute path you can just subclass FileHandle rather than a backend specific class.
