### ISSUE TITLE
Wiki should be adapted to the new branding rules

### ISSUE THREAD

**Issue by payne911** [libgdx/libgdx#6162]
Considering the [new branding rules](https://libgdx.com/brand/):

> The name “libGDX” always starts with a lower-case ``l``, even at the beginning of a sentence. ``GDX`` is always written in upper-case letters.

Someone should figure out a way to automatically run a simple change throughout the entirety of our Wiki: swap all the instances of ``LibGDX`` for ``libGDX`` to be compliant with this rule.

**Comment by crykn** [comment]
I cloned the wiki and replaced most of the mentions of libGDX. There are most certainly still some missing due to "libgdx" also being part of some URLs and find/replace being kinda difficult to use in that context. But those remaining instances can be replaced manually, whenever someones stumbles upon them.
