### ISSUE TITLE
Horizontal ScrollPanes done borked

### ISSUE THREAD

**Issue by rdamiano** [libgdx/libgdx#6189]
Line 438 in recent Snapshot of ScrollPane:

`hScrollBounds.set(x, y, widgetArea.width, scrollbarWidth);`

Should be `scrollbarHeight`, tested it with a duplicated class and fixed the problem. Right now the bounds height is 0 so no visual bar / not clickable.

PS It'd be neat if LibGDX (scene2D) classes didn't have so many package-protected members to make simple modifications through anonymous inner classes easier :/

**Comment by MrStahlfelge** [comment]
> PS It'd be neat if LibGDX (scene2D) classes didn't have so many package-protected members to make simple modifications through anonymous inner classes easier :/

I second this.

About your fix, can you open a PR?

**Comment by tommyettinger** [comment]
I could open a PR if no one else wants to. Thanks for finding the bug! I won't mess with @NathanSweet 's scene2d code beyond this fix because I hope there's some reason why he made most of the fields package-private...

**Comment by NathanSweet** [comment]
Thanks for pointing out the fix!

Making everything in a Java library public API means _any_ change will break users. The boon and bane is that users can access/override everything. It's been discussed a whole lot, here and elsewhere. For scene2d widgets, most are relatively isolated and could be copy/pasted -- ie roll your own so you get exactly what you need rather using the default widgets held together with string.

**Comment by MrStahlfelge** [comment]
@NathanSweet Suggestion is to make fields and methods protected, not public. This way, subclasses can access or override. 
It is asked regularly.

**Comment by NathanSweet** [comment]
Protected access is public API just as much as public access, both expose the implementation details.

**Comment by MrStahlfelge** [comment]
If a slider is vertical is an implementation detail?

**Comment by NathanSweet** [comment]
Is this trolling?

**Comment by MrStahlfelge** [comment]
For sure not, and I don't understand why you suppose that. 

I just pointed out a single example where a Scene2d Actor hides important properties to it's subclasses, clearly not an implementation detail.

**Comment by MobiDevelop** [comment]
Well, Slider does extend ProgressBar, which exposes an isVertical accessor....

**Comment by obigu** [comment]
> @NathanSweet Suggestion is to make fields and methods protected, not public. This way, subclasses can access or override.
> It is asked regularly.

I guess @MrStahlfelge you meant `private` instead of `public` hence the misunderstanding. 

In my personal experience I've found some limitations when trying to create my own widgets by extending Scene2D classes, not that much because of `private` modifiers but because of `default`/`package` modifiers. Within the `com.badlogic.gdx.scenes.scene2d.ui` there's quite some room for extensibility but it gets more limited outside it. To overcome this limitations I've had to create a `com.badlogic.gdx.scenes.scene2d.ui` package in some of my apps just to be able to extend some widgets without copying the whole thing (`ScrollPane` is an example).

**Comment by NathanSweet** [comment]
> For sure not, and I don't understand why you suppose that.

@MrStahlfelge No worries, just that you asked a question when it seemed you know the answer already. Whether a slider is vertical is a property of the slider, not an implementation detail. Slider has a public isVertical getter. An implementation detail would be something like making `calculatePositionAndValue` public API  (protected or public access). That is used internally and doesn't need to be public API. Making it so exposes class internals, increasing the public API surface and making it more difficult to change the class if needed. It can make sense to expose things in the public API, but it should be done carefully and purposefully, not just by making all the fields public/protected access.

> I've found some limitations when trying to create my own widgets by extending Scene2D classes, not that much because of private modifiers but because of default/package modifiers.

Default access is not public API, so can be used within a library without exposing internals, just like private. Using the same package in app code is a workaround, though it comes with an increased risk of breakage since you can access things that were not intended to be used outside the library.

While I understand the need to muck around in a library's internals to get something done, I contend it would not be an improvement to expose all or most fields throughout libgdx as public API (public or protected access). If someone wants full access to everything in scene2d.ui widgets, copying the whole thing into app code is reasonable. In other areas of libgdx that is not possible (or would otherwise mean forking the entire library). In those situations the use cases should be considered individually and APIs exposed only as needed.

**Comment by MrStahlfelge** [comment]
> Well, Slider does extend ProgressBar, which exposes an isVertical accessor

I was not aware that it was added because of #4680, I used it as an example because this was one of my biggest surprise moments in the past. The existance of the issue and the change just proves the point that there are a lot of package-private or private fields and methods that should be protected or public.

I think the cause is that we have very different views on what is considered "public use". Me, I don't see anything being`protected` as `public`. I don't think that changing protected stuff is API breakage. Using protected fields and overriding protected methods is done with the knowledge that this might be subject to change in the future. I am not a Kotlin fanboy, but I think they were right about removing package-private access completely for that language.

I can follow your reasoning that it is possible to copy the code of widgets, it looks like we are just have different views on this, too. I see Scene2d.ui more like an extendable framework, and a very good one - if just there was less unaccessible stuff. :-) And I really don't like to copy code, especially given the fact that some Scene2d widgets are really complex.

For me it is okay to end the discussion on this, as it seems more a matter of taste.

**Comment by NathanSweet** [comment]
> The existance of the issue and the change just proves the point that there are a lot of package-private or private fields and methods that should be protected or public.

The issue is that a getter was missing, not that everything should be public.

> I don't see anything beingprotected as public. I don't think that changing protected stuff is API breakage.

Protected members appear in the public API, users are free to use them at will and without expecting breakage. FWIW see Effective Java by Joshua Bloch or his talks on API design. Not that it's a bible, just that I'm not inventing things.

This scenario isn't specific to scene2d, every library faces this.
