### ISSUE TITLE
[Enhancement] Decal.update()

### ISSUE THREAD

**Issue by MichalLebeda** [libgdx/libgdx#6213]
Hi,
I have found out that sometimes it is useful to get Decal vertices for game logic, The problem is that update() method is protected. We get zero values when calling ```Decal.getVertices()``` on non updated Decal (before first draw call).
Solution:
A) make ```Decal.update()``` public as it contains logic avoiding recalculating vertices anyway
B) call ```Decal.update()``` inside ```Decal.getVertices()```

**Comment by cypherdare** [comment]
I vote for B since it makes sense that you'd expect the vertices to be there when getting them, and then we aren't polluting code completion with a method you should never need to directly call. It's technically a breaking change as it's theoretically possible someone uses `getVertices()` to see the state of the vertices before they are updated. But I think the likelihood that anyone is doing that is extremely low.

Do you want to submit a PR?

**Comment by MichalLebeda** [comment]
Yes I will submit PR. In my opinion returning non updated vertices is not ok so I vote for B.
