### ISSUE TITLE
[CHANGE REQUEST] Dae is the new standard

### ISSUE THREAD

**Issue by Duna** [libgdx/libgdx#6288]
Why are you making custom formats like G3DB since iOS/Unity is using DAE?

All developers are complaining about DAE to G3DB converters. They are not working! 

Please get rig of this stupid custom format

Seriously? Why iOS are using them, doesn't ring the bell? Make a good converter then. G3db resulting file from maya->fbx>fbx-convert>g3db is always crashing my app at loading time with some exception, inside the lib. I'll post the error later, when I reach the mac

The blender 2.8 and 2.9 plugin import export libgdx g3db adon is not working.

Why are making custom formats and do not keep up with the new software? (Maya, 3dmax or at least Blender)

**Comment by Duna** [comment]
https://github.com/mgsx-dev/gdx-gltf

**Comment by mgsx-dev** [comment]
please don't open new issues for the same question as #6287

and please keep cool in your communication, thank you.

**Comment by Duna** [comment]
https://www.donmccurdy.com/2017/06/27/exporting-gltf-2-0-from-maya-lt-2/ all converters are or in alpha/beta or experimental, so a big NO

**Comment by crykn** [comment]
I'm just going to reply here and not on your other issue. Saying that DAE is the "new standard" is kinda dishonest. Just take a look at [this blog post](https://godotengine.org/article/we-should-all-use-gltf-20-export-3d-assets-game-engines) of the team behind the Godot Engine: there are _a lot_ of issues with Collada/DAE and the adoption rate of FBX is probably higher. Also, Apple nowadays seems to lean towards using their own USDZ format. 

If you don't want to use G3DB, the better format to use here is GLTF, which as @mgsx-dev pointed out can easily be used in libGDX via [gdx-gltf](https://github.com/mgsx-dev/gdx-gltf). It is unfortunate that Autodesk is not supporting GLTF after all those years (and I guess that is intentional on their part), but that is more of an issue with Maya and not libGDX.

> G3db resulting file from maya->fbx>fbx-convert>g3db is always crashing my app at loading time with some exception, inside the lib. I'll post the error later, when I reach the mac 

This seems to be your real issue. If you need help figuring out, what is causing the crash, it would have probably been easier to just ask in the 3D channel on our Discord instead of going off on your rant here.
