### ISSUE TITLE
[Scene2D] Scaled Font with markup wrapping issue on 1.9.12

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#6294]
I've noticed an issue with Label wrapping when upgrading one of my projects to from 1.9.11 to 1.9.12. The issue seems to happen on Labels that use a scaled font with markup enabled and wrapping enabled as well. In some cases the Label wraps an extra line and doesn't update it's own size causing layouts that are dynamic depending on the size of the Label not to adapt correctly. This issue was not occuring on 1.9.11.

To reproduce the issue you can use the following code:
https://paste.ofcode.org/zBZzt6cxS74MnbjkSDhLzK

![fontissue](https://user-images.githubusercontent.com/1794492/100490980-8715cf00-3120-11eb-8518-b9cf1184e433.png)

@NathanSweet I've noticed recent changes on GlyphLayout related to markup and wrapping, this may be related.

**Comment by tommyettinger** [comment]
I tried to navigate through the GlyphLayout code and its commit history to try to glean some kind of helpful info, and I came up empty. There's been several commits to GlyphLayout since 1.9.11, they all seem to require pretty substantial knowledge of GlyphLayout internals to understand, and any one or several of these commits could be the culprit(s). Help us, @NathanSweet , you're (probably) our only hope!

**Comment by NathanSweet** [comment]
Oh boy, GlyphLayout fun! I can take a look as soon as I'm untangled from other things, likely Monday.

**Comment by obigu** [comment]
I've also tried trying to understand the changes but the fact that there's no PR for them with some description on the issue they try to solve, reproduction steps and some more detail that explains the new code it's really hard. @NathanSweet Thanks for looking into this when you have time. I have a modest suggestion to make. I understand you have a very deep knowledge of libGDX and you feel confident pushing changes directly to master withouth review but it would be great, for the rest of us and the health of the project itself, if you could make them through more formal PRs (even if you merge them immediately) for doumentation purposes and to allow other contributors to test or fix any possible issue, otherwise the knowledge gets lost. It may be even proof useful to you in the future to remember stuff that you changed in the past, GlyphLayout for example is a beast, no human mind can keep track of that complexity!

**Comment by NathanSweet** [comment]
> it would be great, for the rest of us and the health of the project itself, if you could make them through more formal PRs (even if you merge them immediately) for doumentation purposes and to allow other contributors to test or fix any possible issue, otherwise the knowledge gets lost.

I would do that if it helped, but I don't see a difference between a commit message and a PR that is merged without review, except that the PR takes slightly more of my time. Such PRs would have the text from the [commit messages](https://github.com/libgdx/libgdx/commits/master/gdx/src/com/badlogic/gdx/graphics/g2d/GlyphLayout.java). A PR does make sense when changes need review or to group multiple commits.

FWIW, when GlyphLayout was added it was [via a PR](https://github.com/libgdx/libgdx/pull/2955). Even with more elaborate commit messages or PRs, it's still going to take quite some effort to find, read, and make sense of them all, and after that GlyphLayout is still going to be pretty complex.

> GlyphLayout for example is a beast, no human mind can keep track of that complexity!

Nah, it would just take a bit of effort for others to work on it. It's all right there, in the code! Look at all those nice comments! ;)

It is certainly easy to break, as there are so many edge cases. To really improve the situation it would need a lot of tests and others would still need to want to put in the effort needed to help maintain it. That may not be worthwhile, given it's a reasonably mature class and pretty widely used.

The recent changes fixed things that needed fixing, so even if they broke something with scaled fonts, it's likely better to debug the scaled fonts problem directly rather than find the change responsible. I'll check it out today.

**Comment by NathanSweet** [comment]
@obigu The link to the repro code doesn't work, the server never returns a response. Maybe you can post it here or somewhere more reliable, eg gist?

**Comment by obigu** [comment]
@NathanSweet Blast, can you try this https://pastebin.com/tMZu7gbu?

**Comment by NathanSweet** [comment]
Yep that works, thanks. Fix incoming!

**Comment by obigu** [comment]
It worked, thanks!
