### ISSUE TITLE
[Feature Request] Adjust foreground fps at runtime

### ISSUE THREAD

**Issue by Hangman** [libgdx/libgdx#6298]
It would be nice to have an option like Gdx.graphics.setForegroundFps() / Gdx.app.setForegroundFps() to adjust the foregroundFPS at runtime.

#### Motivation
Due to how asset loading with the AssetManager works, staying at 60fps for example dramatically increases loading times
if you got many load tasks that do their work asynchronously and finish faster than 1/60s. There's always a few milliseconds the app will just sleep. That's of course also the case for larger files that need more than 1/60s and just don't finish right before the next frame is called. Before 1.9.12 I copied the lwjgl2 Sync class to use it with lwjgl3 like many others did as well. Now I could get rid of it if this gets implemented.

#### Benchmark
These times were taken by loading a wide variety of assets, including:
- sound files (as Music and Sound)
- images
- image atlas
- g3db models
- gltf models
- bunch of textfiles pushed through custom loaders
- json files

Loading with fps capped at 60: took 13884ms
Loading with fps capped at 500: took 7782ms
Loading with fps capped at 1000: took 7531ms

#### Version of LibGDX and/or relevant dependencies
1.9.12

#### Please select the affected platforms
- [?] Android
- [?] iOS
- [?] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

#### PS
Should be a 5min thing to implement and therefore I want to apologize for not opening a pull request. I just don't have the time to setup a working libgdx environment for every platform at the moment.

**Comment by MrStahlfelge** [comment]
You are right with the problem about AssetManager. However, I think a better approach would be to get AssetManager to work without waiting, for example by adding a callback method that could be called instead of waiting. But this will be highly controversial. :)

**Comment by Hangman** [comment]
Indeed that'd be even better but I think having the option to adjust the foreground fps at runtime would also be a good thing regardless of the AssetManager problem. Different scenes may need different fps caps (menu vs fast paced first person shooter gameplay).

**Comment by crykn** [comment]
I think both suggestions make sense. There may be other use cases, where changing the targeted fps rate is required (e.g., many games differentiate between menus and in-game screens). And since the asset manager changes appear to be more complex, `Gdx.app.setForegroundFps()` could be used as a work-around for the time being.

**Comment by NathanSweet** [comment]
I don't think using a callback with AssetManager would help. AssetManager goes through tasks one by one and needs to do work on a separate thread (the "async" part of the task) and on the game thread (the "sync" part of the task). If the async part is finished, further progress is blocked until the sync part is done. If you are calling AssetManager `update()` once per frame, the work it does is either 1) it hasn't finished the async part and does nothing, or 2) it finishes the sync part and starts working on the next task. There's nothing wrong with that, but it's likely not the best way to use AssetManager and increasing the target FPS is not the best way to fix it.

Instead of calling `update()` each frame, you can call `update(int millis)`. This uses a busy-wait and gives AssetManager more time to service sync tasks. Likely it can complete more than one per frame. If you want to prioritize loading speed and don't mind your loading screen running at 30fps, you could use `update(1000 / 30f)` (maybe test if you need a little less than this to hit 30fps, depending on the kind of devices you are targeting).

AssetManager aside, in some of my apps I vary the target framerate depending on app state by using the backend specific methods to do so. Having a standard way to do it would be a little more convenient.

**Comment by mgsx-dev** [comment]
We had a discussion on Discord about it and I agree with @NathanSweet. However there is no way right now to change foregroundFPS with LWJGL3 backend. I think it's legit to have at least a setForegroundFPS method for LWJGL3 backend for some use case (eg. ingame user setting). I'm not against having this method across all backends even if only desktop implements it (we already have a setVsync method).

Regarding assetManager loading performance, there are some better ways for improvement though : 
* more than one background thread (require deep changes in asset manager), improvement would be high.
* PBO for async texture loading : i have a working POC for this but it'd need big changes in AssetManager as well.

**Comment by MrStahlfelge** [comment]
Another outcome of the discussion was that the information that was also given by @NathanSweet here should be stated on the wiki, so that new gdx developers don't fall into the trap with an increased loading time.

Probably no one will vote against a new interface method, and it will make sense for other platforms in the future as well. Desktop devs step forward. :)

**Comment by PokeMMO** [comment]
>However there is no way right now to change foregroundFPS with LWJGL3 backend. I think it's legit to have at least a setForegroundFPS method for LWJGL3 backend for some use case (eg. ingame user setting). I'm not against having this method across all backends even if only desktop implements it (we already have a setVsync method).

Unless something has changed, I've been doing this by keeping a reference to `Lwjgl3ApplicationConfiguration` and updating that.

**Comment by Hangman** [comment]
The configuration is copied on startup so updating the reference wouldn't work.

**Comment by PokeMMO** [comment]
Ah I see, that was leftover from lwjgl2? and my internal Sync class was doing it. Thanks.
