### ISSUE TITLE
Paste function in TextField setText() calls acceptChar before setting previously validated characters, failing some regex. 

### ISSUE THREAD

**Issue by FlorianLangeder** [libgdx/libgdx#6333]
#### Issue details
When using the setText function on a TextField with a TextFilter, the acceptChar function gets called for each single character of that string before setting the whole text in the TextField.
When working with Regex to validate an incoming character in acceptChar problems can occur, if the text validated before was not already set. For example if the Regex won't allow spaces at the beginning of the string.
Up until now I just got the text from the TextInput and inserted the char at the current cursor position. But using setText() will call the acceptChar() with the TextInput always being empty.

#### Reproduction steps/code
Create instance of TextField and use setTextFieldFilter() to set a filter implementing the acceptChar() function.
```
@Override
public boolean acceptChar(TextField textField, char c) {
    String updatedText = textField.getText().substring(0, textField.getCursorPosition()) + c +
            textField.getText().substring(textField.getCursorPosition());
    if (!(updatedText).matches("^[a-zA-Z0-9]+[\sa-zA-Z0-9]*$")) {
        return false;
    }
    return true;
}
```

#### Workaround
My current workaround is to call setText once for the first character of the string and then call appendText for each of the characters, to ensure that the text will be set before acceptChar gets called again.
```
for (int i = 0; i < text.length(); i++) {
    if (i == 0) {
        textField.setText(String.valueOf(text.charAt(i)));
    } else {
        textField.appendText(String.valueOf(text.charAt(i)));
    }
}
```

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._
1.9.10

**Comment by NathanSweet** [comment]
`acceptChar` is for checking the validity of each character. As you found, the text is only set once with a string containing only valid characters. I don't think it would be great to set the text for every character, which would trigger many change events. Instead you can use a change event:
```
textfield.addListener(new ChangeListener() {
	public void changed (ChangeEvent event, Actor actor) {
		if (textfield.getText().contains("a")) event.cancel();
	}
});
```
This rejects any text containing `a`. When typing, that will be one character. When pasting or setting programmatically, this will reject the whole string, eg pasting `fubar` would paste nothing because it contains `a`. If you don't like that, you can instead get the text and change it:
```
textfield.addListener(new ChangeListener() {
	public void changed (ChangeEvent event, Actor actor) {
		textfield.setText(textfield.getText().replace("a", ""));
	}
});
```
This can be problematic because the cursor position is lost when setting the text. You could restore it:
```
int cursor = textfield.getCursorPosition();
textfield.setText(textfield.getText().replace("a", ""));
textfield.setCursorPosition(cursor);
```
This works, but the cursor still moves forward for the removed `a` characters. You'd need to adjust the cursor position if you care to prevent that. It may be easier to not use regex and process character by character in `acceptChar`.

**Comment by MrStahlfelge** [comment]
@FlorianLangeder Does the information Nate gave help you?
