### ISSUE TITLE
AndroidFiles initialization does disk I/O on UI thread (Android)

### ISSUE THREAD

**Issue by cthomis** [libgdx/libgdx#6345]
#### Issue details
Initializing the AndroidFiles object (for example, from com.badlogic.gdx.backends.android.AndroidFragmentApplication#initializeForView) will cause a disk read on the UI thread. 
As of 1.9.12, there is also a potential write to disk from the UI thread at com.badlogic.gdx.backends.android.AndroidFiles#<init> -- since https://github.com/libgdx/libgdx/pull/6126 causes the AndroidFiles external path to be eagerly initialized, this can cause the application to try and create those directories on the UI thread if they haven't yet been initialized. 

#### Reproduction steps/code
Enable StrictMode on an Android application (https://developer.android.com/reference/android/os/StrictMode), disallow disk reads and writes, and observe errors on application startup when initializing AndroidFiles.

#### Version of LibGDX and/or relevant dependencies
Disk read seems to have been an issue for a while, disk write issue introduced as of 1.9.12.

#### Please select the affected platforms
- [x ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MrStahlfelge** [comment]
Initializing asynchronously might lead to problems when applications access the file system at startup. We already have similar issues when playing sounds on application startup on Android. 

To keep backwards compatiblity and the ability to access the file system on startup, but to avoid access when not necessary, we could add a new configuration option externalFileAccess: Disabled, Enabled, EnabledOnStartup or make the AndroidFiles class initialization overridable like we do with input and graphics.

**Comment by obigu** [comment]
IMO I don't think it's a big deal the fact that an empty file is created on Android's external path executing on the main thread the first time an app runs by `contextWrapper.getExternalFilesDir(null);`. Except from the general rule of not being a good practice to do disk or network stuff on the main thread I don't think it's worth the hassle and complexity of making it asynchronous.

@cthomis Have you come across any issue due to this or can tell us more about the risks you see or you just found out when enabling Strict mode?

@MrStahlfelge Independently from this issue, I think that initializing `Files` the same way we do with `Audio` or `Input` to improve extensibility would be a good change.

**Comment by MrStahlfelge** [comment]
@cthomis Please check the linked PR. It gives you the possibility to use `NoExternalAndroidFiles` to disable external file access completely, or to use your own async implementation to access files.

**Comment by MrStahlfelge** [comment]
Please check with 1.9.14-SNAPSHOT and the information given in https://github.com/libgdx/libgdx/wiki/File-handling
