### ISSUE TITLE
Desaturated Colors on iOS 

### ISSUE THREAD

**Issue by tarslangil** [libgdx/libgdx#6361]
All colors looks desaturated on iOS.Looks like there is a color profile issue.

#### Issue details
I tested on iPhone 12, iPhone 11 and iPad 5th generation.All looks like the screenshot below.Left is desktop and right one is iOS.

<img width="1600" alt="Screen Shot 2020-12-20 at 14 27 41" src="https://user-images.githubusercontent.com/4326680/104649843-5c7ad800-56c6-11eb-83a5-d0e4c1c16215.png">

#### Version of LibGDX and/or relevant dependencies
Libgdx version => 1.9.13 and forward
Robovm version => 2.3.12

#### Please select the affected platforms
- [ ] Android
- [x] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment]
First we would need to confirm this is libGDX specific or expected behaviour due to hardware/platform differences. From my experience, even by opening the same JPG image on your desktop and on iOS, taking a screenshot and comparing both screenshots they will probably look different. 

Have you confirmed other non libGDX apps don't show that color differences on the devices you are using to test?

If you do believe it's a libGDX bug please provide an executable example that shows the problem (https://github.com/libgdx/libgdx/wiki/Getting-help).
