### ISSUE TITLE
Camera unproject methods use global height and width instead of viewport

### ISSUE THREAD

**Issue by calvertdw** [libgdx/libgdx#6376]
#### Issue details
There are calls to `Gdx.graphics.getHeight()` and `Gdx.graphics.getWidth()` in Camera's unproject methods which return the values of the main window viewport. This means that when rendering to a camera that is not the main camera, these values are for the wrong viewport.

For some context, I have a 3D scene with a 3rd person view main window. I am using another ModelBatch, Viewport, and Camera to render a vitrual camera in the scene. When this camera's height and width are not the same as my main 3rd person window, the uproject methods are broken.

https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/Camera.java#L197

#### Version of LibGDX and/or relevant dependencies
1.9.12

#### Please select the affected platforms
- [X] Android
- [X] iOS
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by Tom-Ski** [comment]
If you want to convert from some other space (rather than screenspace), then use the other unproject methods, or unproject via your virtual Viewport. 

If you think there is an issue, please provide all relevant information including code that reproduces your issue as the template suggests. https://github.com/libgdx/libgdx/wiki/Getting-help
