### ISSUE TITLE
How can I use gradle based build app with libgdx 0.9.8

### ISSUE THREAD

**Issue by vinhvugearinc** [libgdx/libgdx#6378]
#### Issue details
How can I use gradle based build app with libgdx 0.9.8, when I change the gradle file it says cannot resolve libgdx 0.9.8.pom

**Comment by tommyettinger** [comment]
Wow, that's quite an old version. I don't know if 0.9.8 used any form of dependency management (Gradle or Maven), but I know 0.9.8 isn't available at all on Maven Central (the main place Gradle and Maven get their dependencies). [The oldest version available there is 0.9.9](https://search.maven.org/artifact/com.badlogicgames.gdx/gdx). You will probably need to manually download the 0.9.8 files [at this link on GitHub](https://github.com/libgdx/libgdx/releases/tag/0.9.8) if you're set on using 0.9.8. There does appear to be a setup UI there; I don't know if it uses Gradle. There have been 9460 commits since 0.9.8 was released, so it's extremely out of date. I would expect anything Android-related to be so old it would be unusable.

I strongly encourage getting the current [gdx-setup](https://libgdx.com/dev/project_generation/) or [gdx-liftoff](https://github.com/tommyettinger/gdx-liftoff) and using that to generate a new project skeleton, then copying over code from the 8-year-old other project.

I'm closing this because supporting a version that's **over nine thousand** commits behind current should not be a goal for this project. If you have questions regarding the upgrade process, [ask on Discord](https://discord.gg/8TC7H2v) rather than creating a new issue, since it might need some interaction to figure out what is needed.

**Comment by vinhvugearinc** [comment]
I tried with 0.9.9 and it says

Execution failed for task ':android:copyAndroidNatives'.
> Could not resolve all files for configuration ':android:nativesCopy'.
   > Could not find gdx-platform-0.9.9-natives-arm64-v8a.jar (com.badlogicgames.gdx:gdx-platform:0.9.9).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/badlogicgames/gdx/gdx-platform/0.9.9/gdx-platform-0.9.9-natives-arm64-v8a.jar
   > Could not find gdx-platform-0.9.9-natives-x86_64.jar (com.badlogicgames.gdx:gdx-platform:0.9.9).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/badlogicgames/gdx/gdx-platform/0.9.9/gdx-platform-0.9.9-natives-x86_64.jar

**Comment by vinhvugearinc** [comment]
How can I get it to work with 0.9.9 ?

**Comment by vinhvugearinc** [comment]
nvm I got it built but it shows error on start

`
E/com.mygdx.game: No implementation found for void com.badlogic.gdx.backends.android.AndroidGL20.init() (tried Java_com_badlogic_gdx_backends_android_AndroidGL20_init and Java_com_badlogic_gdx_backends_android_AndroidGL20_init__)
E/AndroidRuntime: FATAL EXCEPTION: GLThread 710
    Process: com.mygdx.game, PID: 10119
    java.lang.UnsatisfiedLinkError: No implementation found for void com.badlogic.gdx.backends.android.AndroidGL20.init() (tried Java_com_badlogic_gdx_backends_android_AndroidGL20_init and Java_com_badlogic_gdx_backends_android_AndroidGL20_init__)
        at com.badlogic.gdx.backends.android.AndroidGL20.init(Native Method)
        at com.badlogic.gdx.backends.android.AndroidGL20.<clinit>(AndroidGL20.java:28)
        at com.badlogic.gdx.backends.android.AndroidGraphics.setupGL(AndroidGraphics.java:298)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceCreated(AndroidGraphics.java:346)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1541)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)`

**Comment by tommyettinger** [comment]
> I would expect anything Android-related to be so old it would be unusable.

> I strongly encourage getting the current gdx-setup or gdx-liftoff and using that to generate a new project skeleton, then copying over code from the 8-year-old other project.
