### ISSUE TITLE
Does `FreeTypeFontGenerator#generateFont` need returned `BitmapFont` to caching?

### ISSUE THREAD

**Issue by MairwunNx** [libgdx/libgdx#6381]
#### Issue details
Does it need to caching `BitmapFont` from `FreeTypeFontGenerator#generateFont` for best performance and best memory usage?, in cases when I have different text fields with different font size but with the same font.

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by crykn** [comment]
If you are asking, whether you should save the result of `FreeTypeFontGenerator#generateFont(...)` instead of calling it over and over, then the answer is yes, you should cache it. If you have multiptle font sizes and want to minimise the number of textures, take a look at [`FreeTypeAtlasTest`](https://github.com/libgdx/libgdx/blob/3bcf11ed27648ecdd096d2611f03295cd295b6e2/tests/gdx-tests/src/com/badlogic/gdx/tests/extensions/FreeTypeAtlasTest.java#L142-L183) and [`FreeTypePackTest`](https://github.com/libgdx/libgdx/blob/3bcf11ed27648ecdd096d2611f03295cd295b6e2/tests/gdx-tests/src/com/badlogic/gdx/tests/extensions/FreeTypePackTest.java#L144-L218).

On another note: for general questions like this our [Discord](https://libgdx.com/community/discord/) server may be a better place to ask.

**Comment by MairwunNx** [comment]
@crykn thanks for asking on my question. Thanks for letting me know about discord server.
