### ISSUE TITLE
Common collection interfaces

### ISSUE THREAD

**Issue by Quillraven** [libgdx/libgdx#6406]
This is not an issue but more a discussion. I know this topic was already raised a couple of times but things change over the years and I am wondering if it is possible to introduce common libgdx collection interfaces like `GdxMap` which is then shared by all map implementations.

I am one of the contributors to LibKTX and writing Kotlin extensions for LibGDX collections is very tidious because they don't use the common java interfaces and they also do not have a common LibGDX interface. Therefore, when defining extensions you have to do that for every single implementation of the collection which in case of map is quite a lot.

I understand that the main reason for those collections is to reduce garbage collection (and autoboxing?) but is it still possible to introduce common interfaces that they all share?

Also, are there any benchmarks that compare LibGDX collections against standard java collections? Maybe things have changed over the years and some collections might not even be necessary anymore?

One use case why I raise this discussion is that I wanted to use the typical `getOrPut` / `computeIfAbsent` / ... methods but they are not existing in LibGDX. I can then of course write a simple Kotlin extension function but I don't like that I have to write this extension function X-times because there are so many map implementations in LibGDX without a common parent.

Again, just a question/discussion. If this is not on the roadmap or if there are good reasons against that then fine for me. I would just like to understand the reasoning with nowadays GC implementations / hardware.

**Comment by tommyettinger** [comment]
I've been working on this externally, with the hope of introducing it as a PR whenever libGDX is able to depend on Java 8. [Here it is, jdkgdxds](https://github.com/tommyettinger/jdkgdxds): JDK interfaces for GDX Data Structures. Java 8 is a prerequisite, kind-of, because it has a standard PrimitiveIterator that the int- and long-based classes use, and some lambdas are also used by more exotic collections. There's also the almost-done [jdkgdxds-interop](https://github.com/tommyettinger/jdkgdxds_interop) for converting between GDX collections and the jdkgdxds ones, as well as registering libGDX's Json with serializers for jdkgdxds types. This isn't much help, though, until libGDX shares some kind of interface with other libraries.

**Comment by Quillraven** [comment]
Isn't LibGDX already on Java 8? At least when I use gdx-liftoff setup with android and desktop backend it creates Java8 gradle files and I also have a few android games with Java 8 which did not face any problems so far.

Is it related to a different backend? If yes, what is holding it back to switch to Java 8?

**Comment by MrStahlfelge** [comment]
#5487

**Comment by Quillraven** [comment]
Thanks for the link. To be fair it is from 2019 but the reasons mentioned still apply. Personally I find that a little bit sad to read because I don't think it is a good idea to have a collection API that is not consistent with modern Java standards but I understand that the effort seems to be not worth it.

Again, thank you guys for the update! At least now I know the current as-is status ;)
