### ISSUE TITLE
Support Graal native-image

### ISSUE THREAD

**Issue by lzw-723** [libgdx/libgdx#6436]
[![6Sd8IS.png](https://s3.ax1x.com/2021/02/27/6Sd8IS.png)](https://imgtu.com/i/6Sd8IS)
**Graal** is a project of Oracle Corporation that supports compiling Java programs to native code. For example, the jar file can be compiled into a pure exe file on the Windows platform. It can make Java programs faster and save memory. I think if **libgdx** can support _native-image_ ,it will be more powerful.

**Comment by tommyettinger** [comment]
People have tried. I have tried. You can use Google to survey the carnage of previous attempts to get native-image in particular to work with libGDX and/or LWJGL2 and/or LWJGL3. You may find an entertaining comment by this very @tommyettinger as my mind was eclipsed by a vile force of abject madness deriving its form, insubstantial yet terrible, from the scope of half-forgotten nightmares. It may have become easier since I attempted to compile Graal on Windows before Windows was even supported. I somehow doubt that it is actually easier, if it is even possible. Arc, a fork of libGDX by Anuken, may be able to use native-image, but only by using a completely different backend based on SDL instead of LWJGL. Even then, I don't know if it worked out, or if it actually achieved the claimed performance benefits if it was able to build and run.

PRs welcome! Just be aware that I am not going anywhere near GraalVM's native-image unless someone shows me that it is not so incredibly awful anymore. I'm leaving this open until someone can confirm that getting native-image working is not a good use of our time.

**Comment by Anuken** [comment]
To elaborate on the comment above, Native Image:
- has [lower peak performance](https://github.com/oracle/graal/issues/1069) than standard Java in most cases
- requires extensive JNI and reflection configuration for the simplest games, which ends up being more work than even GWT reflection
- [doesn't support cross-compilation](https://github.com/oracle/graal/issues/407)
- isn't much smaller than packaging a minified/jlink-ed JRE with your application
- will likely never work with LWJGL3 due to its extensive use of `sun.misc.Unsafe` and other performance "hacks"
- doesn't support many Java features

On the other hand:
- you get a single executable instead of a folder - *but this isn't really a big deal*
- startup times might be slightly lower (~1 sec in my experience) - *but for games, this doesn't really matter*

I *did* get native-image working with my Arc fork + the SDL backend + a simple game, but in the end it really wasn't worth it. Packaging a JRE with your game is the superior option.

**Comment by tommyettinger** [comment]
OK, we have our superior option(s): [Packr](https://github.com/libgdx/packr), made by the libGDX organization and which allows packaging a JRE with your game to make an executable for any supported desktop OS, or [JPackage (using some form of tool to handle it)](https://badass-runtime-plugin.beryx.org/releases/latest/), which is part of Java 14 and newer (but the linked tool is a Gradle plugin) and allows packaging a JRE with your game to make an executable for the OS used for the build only. I'm closing this now, thank you Anuken.

**Comment by ByerN** [comment]
I did it for LibGDX on Windows10. Also tried it on my own game with more complex dependencies and it worked aswell.

Please check my video for more details:
https://www.youtube.com/watch?v=9eevmylv0fU&ab_channel=ByerNiX

and repository with sample:
https://github.com/ByerN/libgdx-graalvm-example

**Comment by anyicomplex** [comment]
I've made a library to help build native-image, here's my repo: https://github.com/anyicomplex/gdx-graalhelper

**Comment by tommyettinger** [comment]
Graal support has improved a lot since early 2021, believe it or not. Surprisingly, people are still linking back here, so an update is in order.

There's GraalVM, which as I understand it is an alternative JVM and nothing more (in my benchmarks, GraalVM 20 can do some really good things on small methods). Then there's Graal Native Image, which is entirely different and will AOT-compile your whole game, including assets, into one native executable (such as a Windows x64 exe). There have been no compatibility issues I've encountered with the former (it's just a larger file to bundle with Packr or the like, but maybe a bit faster), so I'll focus on the latter.

Native Image starts up faster, which is why it's become strongly preferred for [command-line tools using the JVM](https://picocli.info/). It doesn't just obfuscate your sources, like ProGuard does; it actually will compile them into native code, so where you aren't using reflection, it's very hard to pull stuff from the .exe without your permission. The smallest single .exe Graal Native Image can produce is **drastically smaller** than the smallest possible bundled JVM solutions; for a command-line app with no assets, this means a [Graal exe](https://github.com/tommyettinger/noisegen) is about 40% of the size (zipped) as a jpackageimage exe (zipped) with the same code. This advantage remains about 11MB better for Graal for larger apps, but I'm not sure of specifics.

![File sizes](https://i.imgur.com/d6qDQWV.png)

With the current library support from anyicomplex (above) carried on by @Berstanio ([here](https://github.com/Berstanio/gdx-graalhelper)), it isn't really hard at all to get LWJGL3 working with Graal Native Image, [see my repo testing it](https://github.com/yellowstonegames/DetritusScion). I haven't noticed framerate dips at all in the game; it isn't doing anything too strenuous, but I'll follow up with some benchmarks to see if the peak performance is significantly different.  Graal has improved reflection support a lot since 2021, and I'm not sure what other features it was missing back then, but pretty much everything works or can be made to work.
