### ISSUE TITLE
gdx-setup_latest does not produce a correct iOS project

### ISSUE THREAD

**Issue by JojoIce** [libgdx/libgdx#6454]
#### Issue details
If the latest gdx-setup_latest is downloaded from here: [project-generation](https://libgdx.com/dev/project-generation/) and then is used to create an iOS project, it will have several problems that likely will be of big problems for most people that page is intended for. 

First of all the version of libGdx that the gdx-setup specifies will make the iOS project crash when packaging it. Seems to be a know problem, but for people going to that page it most likely isn't know. 

Secondly, if you manage to figure that out and reduce the gdx version to 1.9.12 for example it will still have problems. The project generated apparently does not follow whatever changes that has been made for iOS since 1.9.12. The app will only display on the lower quarter of iOS devices.

#### Reproduction steps/code
Download gdx-setup_latest from here: [project-generation](https://libgdx.com/dev/project-generation/) and attempt to build and it will fail. That problem is known, but it would probably be a good idea to not have a newbie tool available that produce faulty projects. 

Secondly, if the gdx version is changed to 1.9.12 and the image is moved to 200,200 in the Game class specified in the gdx-setup gui.

change
`		batch.draw(img, 0, 0);
`
to
`		batch.draw(img, 200, 200);
`
or any suitable position so that it would reach over the middle of any iOS device to test on.

Then build and deploy in device and the image will be clipped to the lower left quarter of the device

It would probably be good to try to make sure that the project generator really creates projects that can work, so changing the gdx version back to 1.9.11 could be good and document why.

Introducing a change (in what typically would be though of as a bug release) that seems to be breaking many if not most games on iOS does not seem like a very good idea. It is also not clear how to migrate to the new version so that iOS games still render normally. At least it would be good to update the template that is generated from the gdx-setup to work so that the whole screen renders.

#### Version of LibGDX and/or relevant dependencies
1.9.12+
But the issue is really regarding gdx-setup and documentation of breaking changes.

#### Stacktrace
No crash but unexpected behaviour. See how right part of image is gone, since right half of screen is not rendering. Also top half is not rendering either.
![Screenshot 2021-03-14 at 02 35 07](https://user-images.githubusercontent.com/3921475/111054631-6f175080-846e-11eb-8700-fcf293226cae.png)

If app is started in landscape, then top part cuts the image given the location of it, but same here, both top and right part of screen is not rendering leaving only lower left quarter of screen rendering:
![IMG_3406](https://user-images.githubusercontent.com/3921475/111054635-750d3180-846e-11eb-9660-a03c287aa01f.PNG)

#### Please select the affected platforms
- [ ] Android
- [x] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment]
Thanks for the report. The issue is on `SpriteBatch` that sets its default projection matrix size to the screen logical pixels instead of setting it to the physical pixels. 

`projectionMatrix.setToOrtho2D(0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());`.

Because the setup basic project template uses `SpriteBatch` directly without changing the default projection matrix (which now is logical pixels) and draws a texture using the texture size (physical pixels) there's a mismatch.

I'll create a PR with the change and will also update tests that don't look good on iOS due to this same issue.

**Comment by obigu** [comment]
**The information on my previous comment was not correct, I've decided to delete it not to cause any confusion.**

https://github.com/libgdx/libgdx/pull/6455 fixes this issue.

Because of the change to support HDPI modes and make logical pixels default, the basic Gdx Setup template doesn't look the same on an Android device than on an iOS device both sharing the same resolution. On iOS or Lwjgl3 (backends that support HDPI modes), the badlogic image will look similar in size independently of the device screen resolution, on the other hand, on Android it will be smaller the higher the resolution on the device.

The same applies to libGDX tests, most of which don't use `Viewport` and scale differently depending on the backend. Most libGDX tests look tiny on Android high DPI screens and that is something worth having a look.

We can have a separate discussion on this topic if we want. The important thing is that the bug is fixed and behaviour is now the expected.
