### ISSUE TITLE
Libgdx not working on my computer

### ISSUE THREAD

**Issue by harshetmaruff** [libgdx/libgdx#6461]
Please ensure you have given all the following requested information in your report.

#### Issue details
Libgdx not working

#### Reproduction steps/code
i cant run a build(desktop) in my computer the files are the template files generated by libgdx generator 

#### Stacktrace
harshet@harshet-desktop:~/Desktop/a/LibGDX/Drop$ ./gradlew desktop:run
Starting a Gradle Daemon, 5 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :desktop:run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/harshet/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

BUILD SUCCESSFUL in 2m 21s
5 actionable tasks: 5 executed
harshet@harshet-desktop:~/Desktop/a/LibGDX/Drop$ 

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ #] Linux
- [ ] MacOS

**Comment by crykn** [comment]
This is most certainly caused by LWJGL 2. Just switch to the LWJGL 3 backend as described [here](https://gist.github.com/crykn/eb37cb4f7a03d006b3a0ecad27292a2d). Also see #6426.

**Comment by tommyettinger** [comment]
You can also switch your JDK to [AdoptOpenJDK](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot); 8 is best-supported by libGDX, but 11 also works (**Java 16 does not work currently** because Gradle hasn't updated to support it yet). Just get the JDK (not the smaller JRE) for your architecture, which is almost certainly x64. AdoptOpenJDK, for whatever reason, works with LWJGL2 and LWJGL3 on all platforms you can install AdoptOpenJDK, while the default JDKs for most Linux distros only work with LWJGL3 out-of-the-box. If you use IntelliJ IDEA or Android Studio, you can also download an AdoptOpenJDK JDK from the IDE (File -> Project Structure -> SDKs -> Plus at the top -> Choose what JDK you want; though I don't remember the last steps that well, I think they are straightforward).

**Comment by harshetmaruff** [comment]
thank you for your help tommyettinger crykn btw is there is any discord community for libgdx

**Comment by tommyettinger** [comment]
Yep, it's very active. https://discord.gg/nVT3Xgh
