### ISSUE TITLE
TmxMapLoader throws NullPointerException when using HeadlessApplication

### ISSUE THREAD

**Issue by Celsiusss** [libgdx/libgdx#6470]
#### Issue details
TmxMapLoader throws NullPointerException when using HeadlessApplication

#### Reproduction steps/code
Create a Headless application:
```java
final HeadlessApplicationConfiguration config = new HeadlessApplicationConfiguration();
new HeadlessApplication(new RoboRallyApp(), config);
```
Then load a tmx map:
```java
new TmxMapLoader().load("Maps/map.tmx");
```

#### Version of LibGDX and/or relevant dependencies
1.9.14 for all libgdx dependencies.

#### Stacktrace
```java
java.lang.NullPointerException
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:142)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:122)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:118)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:76)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:59)
	at RoboRally.Game.Board.BoardTest.createBoard(BoardTest.java:32)	<-- loads the tmx map
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by crykn** [comment]
`TmxMapLoader` tries to load the tile map's textures internally. That fails, because the headless backend doesn't offer a (Mock)OpenGL implementation. The simplest way to fix this is to just mock `Gdx.gl` yourself with [Mockito](https://site.mockito.org) or something similar. See [here](https://github.com/eskalon/pancake/blob/8817f3800391a89d15c4b657d565df22bd68b119/core/src/test/java/de/eskalon/commons/LibgdxUnitTest.java#L26-L29) for an example.
