### ISSUE TITLE
Vector2#hashCode() is bugged

### ISSUE THREAD

**Issue by Glusk** [libgdx/libgdx#6488]
#### Issue details

Every a hash function is expected to have collisions. That said, I believe there's a bug in libGDX's implementation of `Vector2#hashCode()` (and potentially in other classes that use the same code to hash its members).

This is how `Vector2#hashCode()` is currently implemented:

https://github.com/libgdx/libgdx/blob/305be140b7fd6087b92b6ded24564454a1c11f68/gdx/src/com/badlogic/gdx/math/Vector2.java#L473-L479

 `prime * result` can overflow and that's when an error occurs. 

#### Reproduction steps/code

``` java
System.out.println(new Vector2(2f, 0f).hashCode());  //prints -1073740863
System.out.println(new Vector2(0f, -2f).hashCode()); //prints -1073740863
```

#### Proposed solution

One could declare `result` as long and then return modulo `Integer.MAX_VALUE`:

``` java
public int hashCode() {
    final int prime = 31;
    long result = 1;
    result = prime * result + NumberUtils.floatToIntBits(x);
    result = prime * result + NumberUtils.floatToIntBits(y);
    return (int) (result % Integer.MAX_VALUE);
}
```

This **seems** like a fix but I haven't tested it extensively. Anyway, the purpose of opening this issue was to demonstrate the problem.

**Comment by tommyettinger** [comment]
Yes, we are aware that Vector2.hashCode() is not a good hashCode(), and because we don't expect users to do any better on their own types, all of the hash-using collections in libGDX can handle bad hashCode() implementations just fine. Back in 1.9.10, there was an issue with ObjectMap and ObjectSet when hashing Vector2 keys (or any other keys where all hashCode() results are the same in the low bit range), and over a few months I fixed it and the improved code has been in libGDX since 1.9.11. One of the tests I used to confirm the initial problem, and to confirm that the fix works, involved testing a small set of 4-character Strings, such as `21oo 0oq1 0opP 0ooo 0pPo 21pP 21q1 1Poo 1Pq1 1PpP`; for all of those 10 "words", each has a hash of 1540191. That means for those 10 strings, there are 9 collisions. Obviously, we aren't submitting a bug report to Oracle about `String.hashCode()`; the correct response is to make the code that uses the hashCode()s robust against collisions, as HashMap and ObjectMap do.

The proposed solution doesn't really change anything other than making some common Vector2 values not collide; it actually decreases the possible space of hash results by 3 hashes, so over the full space of Vector2 values it actually increases the number of Vector2 pairs that collide. Modulus is also the slowest arithmetic operation, it can still produce negative integers, and there are plenty of ways to hash a Vector2 to reduce collisions. The problem is that we don't need to improve Vector2's collision rate because the classes that rely on hashCode()s have to be able to accept even really atrocious implementations, all the way down to `return 0;`.

If you really want a unique number for every Vector2 (meaning no collisions are possible), you have to use a `long`:
```java
public static long identify(Vector2 v) {
  return (long)NumberUtils.floatToIntBits(v.x) << 32 | (NumberUtils.floatToIntBits(v.y) & 0xFFFFFFFFL);
}
```
