### ISSUE TITLE
Scene2D debug lines are inverted on screen

### ISSUE THREAD

**Issue by madmenyo** [libgdx/libgdx#6491]
#### Issue details
Some Scene2D debug lines are vertically inverted. Luckely not the green hitboxes but the red and blue lines so the Stage is still working. However, it gets really frustrating to debug something on a crowded screen.

#### Reproduction steps/code
Just the barebone example with table.top(); as a change.
https://pastebin.com/ScNigqMF

#### Version of LibGDX and/or relevant dependencies
1.9.14

#### Please select the affected platforms
all

**Comment by obigu** [comment]
Please try 1.9.15-SNAPSHOT. There were some changes here https://github.com/libgdx/libgdx/issues/6363.

**Comment by madmenyo** [comment]
That fixes most of the debug lines, except for the blue lines. But the issue is similar to #6363

**Comment by madmenyo** [comment]
The following is what I get with the 1.9.15-SNAPSHOT, the blue box in the bottom of the left collom should be on top. Not sure what the blue debug lines exactly represent.
![image](https://user-images.githubusercontent.com/6862943/114228945-78b1ac80-9977-11eb-93ca-ccf00838c577.png)

**Comment by tommyettinger** [comment]
Wow, I think the debug lines are cursed code. I attempted to make sense of them early in 1.9.15-SNAPSHOT, I could not do so, and I lit the beacon for aid from @NathanSweet .  He changed something that mostly seems to work, but I guess doesn't here. Before that, there was a different bug in 1.9.13, with a different type of debug line. I hope this current blue-line fix is an easy fix for Nate, because I think it's becoming clear that this code is more complex than anyone expected.

**Comment by madmenyo** [comment]
No it's not some added empty cell. Here is another example. On top there are two tables representing two columns. At the bottom there is this blue box with the exact width and height of these two combined. It's just weird, but at least it is workable now with the latest snapshot.

![image](https://user-images.githubusercontent.com/6862943/114272817-f4fbcc80-9a17-11eb-95c8-25f17ed6fa3a.png)

**Comment by tommyettinger** [comment]
Definitely a bug then. I'm glad it's manageable, but I'm still hoping it's a simple fix.

**Comment by NathanSweet** [comment]
Hopefully this game of whack-a-mole is complete!

There are two blue rectangles. One is the table actor's bounds and the other is the logical table bounds:
https://github.com/libgdx/libgdx/wiki/Table#logical-table

**Comment by tommyettinger** [comment]
Sweet! Thanks Nathan Sweet! Now it looks like every permutation of debug table bug has been exhausted. That should make the next release the first since 1.9.12 or maybe earlier with correct table debug lines. The flipped lines have always been possible, if difficult, to figure out where they should actually be, so there might not have been issues reported if people were working around it on their own. Even though this last one seems to be the least critical to Table building, since people seem not to be actively using both blue rectangles, I'm glad it's all working now.
