### ISSUE TITLE
Use Camera in MapRender interface

### ISSUE THREAD

**Issue by fabiitch** [libgdx/libgdx#6497]
Hi !
In my game i use Perspective camera for render models, or sprites.

I use also a tiled map. All TiledMap renders class need an orthographics camera.
An perspective camera can also do this jobs.

If i modify the MapRenderer interface, the only problems in on zoom properties on orthographics camera. used in setView

```
@Override
	public void setView (OrthographicCamera camera) {
		batch.setProjectionMatrix(camera.combined);
		float width = camera.viewportWidth * camera.zoom;
		float height = camera.viewportHeight * camera.zoom;
		float w = width * Math.abs(camera.up.y) + height * Math.abs(camera.up.x);
		float h = height * Math.abs(camera.up.y) + width * Math.abs(camera.up.x);
		viewBounds.set(camera.position.x - w / 2, camera.position.y - h / 2, w, h);
	}
```

In this case of perspective camera the zoom properties can be the z position.

Do you think its possible to modify MapRenderer interface for use Camera instead of orthographic ?

Im aware that's two differents properties.
I don't open this issues for validate my 'solution'. Just for discuss about this.

I also think  to check camera type in MapRender implementations with instanceof and use zoom or z properties.
like 
```
@Override
public void setView (Camera camera) {
		float zoom = 1;
		if(camera instanceof OrthographicCamera){
			zoom = camera.zoom;
		}else{
			zoom = camera.position.z;
		}
		batch.setProjectionMatrix(camera.combined);
		float width = camera.viewportWidth * zoom;
		float height = camera.viewportHeight * zoom;
		float w = width * Math.abs(camera.up.y) + height * Math.abs(camera.up.x);
		float h = height * Math.abs(camera.up.y) + width * Math.abs(camera.up.x);
		viewBounds.set(camera.position.x - w / 2, camera.position.y - h / 2, w, h);
	}
```
But i think a zoom properties can be correct on PerspectiveCamera too.

I try some changes on my fork. (not  finish and bad)
https://github.com/fabiitch/libgdx/commit/4ded175f5198f510e10889bcfa05a8b59ac329ee

Thanks for reading.

**Comment by mgsx-dev** [comment]
you should use `setView (Matrix4 projectionMatrix, float viewboundsX, float viewboundsY, float viewboundsWidth, float viewboundsHeight)` method in this case. I used this to render tilemaps with perspective camera, it works well.

Orthographic zoom is not the same as perspective Z position, there is no general solution for perspective, that's why there is the other `setView` alternative. `setView (OrthographicCamera camera)` is basically a shorthand and cover most of use cases.

For questions and discussions, please use Discord instead.
