### ISSUE TITLE
Is there a way to set font familes in freetype lib?

### ISSUE THREAD

**Issue by liangchenhe55** [libgdx/libgdx#6499]
#### Issue details

Now the freetype extension lib is very easy to use, thanks. However, there is still a common use case that has not been considerde. If some characters in a string are not in the specified font file, they cannot be displayed correctly. 

Many apps already support setting `font families` which means if some characters are not supported, the next font will be uesd to get the glyph and so on...

I've tried to add this feature, but I don't know freetype well and the code seems complicated. It seems to me that the whole framework is not designed in this way, so it needs to be modified a lot, isn't it? I would appreciate it if anyone could give me some clear ideas (such as which classes need to be extended).

#### Version of LibGDX and/or relevant dependencies

`gdx-freetype` -> 1.9.14

**Comment by tommyettinger** [comment]
Disclaimer: I don't use Freetype currently.

The way fonts work in libGDX always involves rendering a specific part of a Texture when a specific `char` or codepoint is requested. This part of a Texture is always a predefined size, though it can be stretched or shrunk by viewports, scaling the font, or something similar. That Texture and region sizing is handled by a BitmapFont, which Freetype can produce for a given size of font. What you seem to be requesting here would have Freetype take multiple fonts, with one as primary and others as fallbacks, and it would put a fallback font's rendering of a glyph into the BitmapFont if the primary font doesn't support that glyph. I think this makes more sense with incremental mode, where rare glyphs would only be added if needed by game text (instead of adding the whole fallback font). There's some potential problems with matching the size of glyphs in different fonts.

I think this is possible to add to libGDX, but could be complex with how Freetype currently works. There may be some relatively-easy tools out there that can combine .TTF fonts, which would be a good way to handle this now. I'm looking at https://en.fontke.com/tool/mergefonts/ , which seems like it might work for smaller font file sizes. There's also FontForge, which can combine two or more fonts fairly easily if you're on Linux.

I'm sorry I can't be of much help here. I'm working on [a different kind of font rendering solution](https://github.com/tommyettinger/textramode) that doesn't involve Freetype, but can handle bold/italic/underline/etc.

**Comment by liangchenhe55** [comment]
@tommyettinger Thanks for reply. Because the font file is provided dynamically by the user, merging is not an option. 

My idea is based on incremental generation. When the incremental generation starts, but the corresponding glyph is not found in the first ttf file, go to the next file to look for it. Yes, there's some potential problems with matching the size of glyphs in different fonts.
