### ISSUE TITLE
[Scene2D] Scaled Font with markup wrapping issue on 1.10.0

### ISSUE THREAD

**Issue by lucas-kakele** [libgdx/libgdx#6552]
#### Issue details
Hi all. 

This is a related issue of https://github.com/libgdx/libgdx/issues/6294

When I have markup enabled, sometimes labels are wrapped incorrectly.

Example:

![image](https://user-images.githubusercontent.com/56004737/120535159-0a0e2f80-c3b9-11eb-8f1a-c308b3b4d256.png)

Note that I tried to increase the `epslon` added by the fix in the related issue above (I tried values up to `10f`), but the wrapping issue still happens.

(I changed the `epslon` using reflection.)

#### Reproduction steps/code

Please check the example code here:

[label-wrap-test.zip](https://github.com/libgdx/libgdx/files/6586718/label-wrap-test.zip)

#### Version of LibGDX and/or relevant dependencies

I'm using libGDX 1.10.0.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [X] Linux
- [ ] MacOS

Let me know if you need more information, thanks!

**Comment by tommyettinger** [comment]
I'm working on this now; I can absolutely reproduce the issue. The exact conditions for when the wrapping bug occurs are... strange. It shows up when it uses the specific scaling factor you had, `14 / font.getCapHeight()`, or `0.5185185f`, but not `0.5f` or `0.625f`.

0.625f:

![0.625f](https://i.imgur.com/aIsdx0C.png)

0.5185185f:

![0.5185185f](https://i.imgur.com/0PKTJ7k.png)

0.5f:

![0.5f](https://i.imgur.com/M03SXY5.png)

I have a tentative fix, but I don't know if it breaks anything else yet. It simply changes, in GlyphLayout.java and its `setText()` method:
```java
						Glyph glyph = run.glyphs.get(i - 1);
						float glyphWidth = (glyph.width + glyph.xoffset) * fontData.scaleX - fontData.padRight;
```
to
```java
						float glyphWidth = xAdvances[i-1];
```

**Comment by tommyettinger** [comment]
Also, I have been testing this by editing the libGDX source, but I don't think I can include the font Mikadan because it is commercial (currently sold for $9.95 at various font sites). Trying other fonts, it is very hard to find a particular combination of characters that can have this issue happen. Maybe try BMFont or Hiero if you made the font with the other of the two, and see if you continue to encounter the issue?

**Comment by lucas-kakele** [comment]
Thanks @tommyettinger! I used Hiero to generate the bitmap font. Do you need the original OTF file to do more testing?

**Comment by NathanSweet** [comment]
```
float glyphWidth = (glyph.width + glyph.xoffset) * fontData.scaleX - fontData.padRight;
```
This code is taking the glyph width and x drawing offset to find the right edge of the glyph. It scales that and then subtracts any padding on the right edge. The idea is to find the exact right edge of the glyph based on the glyph texture region.

```
float glyphWidth = xAdvances[i-1];
```
This code uses the x-advance, but that's not the same as the right edge of the glyph texture region. It may be too much (causing the bounds to not fit tightly around the text) or too little (causing the text to exceed the bounds).

I'll try to investigate the problem soon. It's strange that it wraps when the text can easily fit. If you guys want to keep looking at it, the place to look is why the code doesn't go through the `// Glyph fits.` block.

**Comment by NathanSweet** [comment]
```
if (x + glyphWidth - epsilon <= targetWidth) {
```
In that code, the `x + glyphWidth` is `403.40753` and `targetWidth` is `403.40738`. The `epsilon` is `0.0001f` so not enough to allow evaluation to true. `0.001f` is enough, though it'd be nice to find a better way.

The label calculates the text width so it can align the wrapped text within the label. It then uses that width to layout the aligned text. A lot of problems are caused by the second layout using the exact width from the first layout. Some of those problems are legit bugs and it has been good to fix them. Some problems have been float rounding though.

**Comment by NathanSweet** [comment]
That was fun to figure out!

**Comment by NathanSweet** [comment]
We calculate the run widths twice, once as we determine wrapping/truncation, then again afterward. We used to try to keep the calculations done the first time, but when wrapping we shuffle glyphs around, then we have to adjust the calculations to match. That got complex so we threw it out and just calculate the final widths at the end.

The problem was the float accumulation differed very slightly, and only sometimes, when the variable holds the x position (first time) rather than just the width (second time).

**Comment by tommyettinger** [comment]
Glad you got it fixed! The GlyphLayout code is pretty labyrinthine, so this kind of bug is to be expected once in a while. The odd thing was how few fonts produced the wrapping bug, which might have been a clue to it being float-related.

**Comment by lucas-kakele** [comment]
Thank you both for working on the fix!
