### ISSUE TITLE
Double precision

### ISSUE THREAD

**Issue by siauderman** [libgdx/libgdx#6556]
Hi, doubles are faster nowadays with AMD64. Any plans to use doubles instead of floats (or to overload the functions to have a double version)?

**Comment by tommyettinger** [comment]
> doubles are faster nowadays with AMD64.
`[citation needed]`

...Seriously, cite your sources that show doubles are faster than floats, especially regarding OpenGL. Show some benchmarks, preferably. Yes, doubles are faster than doing math on Strings that store numbers as their digits, or math on `BigDecimal` objects, and they're faster than they used to be on 32-bit hardware, but I strongly doubt that OpenGL, which almost exclusively uses floats internally, is going to show double-precision math as faster than single-precision.

> Any plans to use doubles instead of floats (or to overload the functions to have a double version)?
This seems very unlikely. If you have a concrete use case for where doubles are all-around better, and this use case requires changes to libGDX code, you can consider submitting a PR, but it would be an uphill battle. Remember that OpenGL represents a lot of its internals as floats and approximately none as doubles.

I'm leaving this open in case you have some information that shows no performance penalty for using double in place of float, but if that doesn't exist, then we can close this.

**Comment by yuripourre** [comment]
@siauderman do you have any references? Double operations are slower than float operations. Also, GPUs would handle only half of the operations, since it would need to process data with the double of the size. All the shaders would have to be updated as well.

Do you have a specific use case in mind?

**Comment by siauderman** [comment]
Hi, I happened to chance across this article which basically says double is faster (on modern machines), besides being loads more accurate, than float: https://articles.emptycrate.com/2012/02/11/double_vs_float_which_is_better.html
(Yes I know the language is different)
However, I forgot that we are using GPU where float is still faster. So sorry.

**Comment by yuripourre** [comment]
@siauderman right, I just read the post. Take a look at the comments, double doesn't outperformes float in every operation even in CPU, there are cases that you cannot use all registers. I think for older devices and mobile using double can be even worse.

I appreciate the suggestion but the current technology doesn't allow us to use double instead of float with the same performance.

**Comment by tommyettinger** [comment]
I read the article too. That author has me irked. They seems to ignore the fact that in his C++ benchmark, `long double` was marginally faster than `double` and yet he still says double is faster. His metric that the float summation is off by two orders of magnitude is clearly because he intentionally added two billion floats and 2 billion doubles -- float is only precise to about 16 million, which this guy should probably know if he's writing an article on it, so he appears to have chosen a value that's maximally problematic for floats. That isn't something that float has a monopoly on, though. There's a maximum value for double that's absolutely possible to encounter; 2.999999999 to the 1000th power is just over 1322070378790606851543921017198051706303375129661758299769912085909199119864413344764285169025641536337332931700615149404686685242411058503281160642976640176292246169653649340512754341341330239489381445053290672355522489873963229251660505589583282972347557180175419192596767257167553584746459762573824788894106281631312554874992983100305208666082972553939913174565568977430937087464890380579596393870804702756703285998709722000321723510580410680322842385155058438052533897486170, but if you multiply the double 2.999999999 by itself 1000 times, you get `Infinity`, and all math stops working on it in a meaningful way. All numeric types have some kind of limit, and exploiting them without informing the reader is poor form. That article needs a `[questionable source]`... 

In all cases, differences reported there are extremely small, and of course, libGDX isn't primarily using C++. It doesn't apply at all to several libGDX platforms, such as 32-bit ARM used on some phones, 64-bit ARM which wasn't benchmarked, and HTML where double and float are probably equivalently poor-performing because of how JS works. I use double personally when I need better precision, but that isn't especially often. Sometimes I need to convert a 32-bit int to a floating-point number without precision loss; that's a good case for a double. If I need to convert a 64-bit long to a floating-point number without precision loss, it isn't going to work for float or double. Some specific math operations I use double for, and `java.util.Math` handles most of those, while `MathUtils` handles float cases more quickly. I have some benchmarks I can run myself using BumbleBench, which may give a better idea of how CPUs handle double and float, but any differences tend to be very small... except for where memory is a factor. Phones and consoles tend to have rather low amounts of memory available, and libGDX tries pretty hard to be efficient on memory. Since float uses half the memory of a double, and that also has important effects when transferring floats over the network or to the GPU, that does certainly matter. It's important to point out that there are currently standardization debates going on over different formats of half-precision floats, because machine learning applications sometimes use so many float-like values that a regular float is too bulky.

Honestly, I'd like to be able to use doubles, just because they're more precise and they are represented more cleanly on GWT. But currently they're better used only as-needed, rather than as the default. This will probably change in some low number of years, as double-precision floats become more common on GPUs and Vulkan et al take off. It's really an open question if libGDX would even want to port APIs to Vulkan, because even basic code to use Vulkan to draw one triangle is ridiculously larger than the equivalent OpenGL code. I don't see OpenGL ever emphasizing a change to higher-precision. Sorry for the rant, but that article just seems so deceptive!

**Comment by siauderman** [comment]
Yes, I guess it is a bad article. I find it odd that long double would be faster than double when I read that for C++ compilers that support a true 80-bit long double on AMD64, x87 is used instead of SSE2 - and SSE2 is supposed to be faster. But I guess all of that is irrelevant on phones too (and the differences are miniscule anyway, especially compared to the much slower speed of double vis a vis float on GPUs). I'm so sorry for the trouble and please feel free to close this issue.
