### ISSUE TITLE
[Feature Request] make SelectBox inheiritable/overrideable

### ISSUE THREAD

**Issue by terefang** [libgdx/libgdx#6598]
chat from Discord channel

```
[7:04 PM] Winter: Ended up getting the SelectBox + icon working
[7:05 PM] Winter: My trick was simply to change the drawItem function in SelectBox

public GlyphLayout drawListItem(Batch batch, BitmapFont font, int index, T item, float x, float y, float width)
{
...
}
[7:05 PM] Winter: It's kinda dirty because I had to copy paste the whole SelectBox code (not heritable because of it's hidden inner class) but at least it wasn't much work
```

**Comment by WinterAlexander** [comment]
Hi, I did not intend to have this opened but let me describe the issue:

SelectBox's inner class SelectBoxList is package-private making it very difficult to 

- Extend the functionalities of SelectBox. For instance I had to add icons to the SelectBox's UI. To do this I had to copy and paste the entire code of SelectBox, because the `drawItem` function of SelectBoxList cannot be overwritten. The amount of copy-pasted code would be highly reduced if SelectBoxList was public
- Detect if an actor is a SelectBoxList. Currently the best way to check if it's one is to compare the String class name which is unefficient and ugly. Checking if the clicked actor is a SelectBoxList is very useful when detecting clicks outside an actor and it's children, as the SelectBoxList itself is not a children of SelectBox, creating a need to handle its click events separately.

A possible solution for both issues would be to make the inner class SelectBoxList public. A solution for the first point only would be to delegate the `drawItem` function entirely to the SelectBox, allowing to change the way items are drawn by overriding the SelectBox.

**Comment by NathanSweet** [comment]
SelectBox has a SelectBoxList which has a List. Making SelectBoxList public doesn't help to override List `drawItem`.

Note SelectBoxList is actually a ScrollPane. Good thing it's private so we can rename it. ;) Though I'm not sure what a good name would be: SelectBoxScrollPane, SelectBoxScroll, ListScrollPane, ListScroll, none of these are great. `SelectBoxScroll` I guess. If it's private the name doesn't matter, but calling it a list adds to the confusion.

The List is exposed via SelectBox `getList` but the SelectBoxList is not. I'm not sure exposing SelectBoxList would help in any situation. We could have SelectBox `getScrollPane` which returns ScrollPane. Currently you can do that with the ugly `(ScrollPane)select.getList().getParent()`.

As for a select box with icons left of each item, I've also needed that and I copy/pasted SelectBox. Eg:
![](http://n4te.com/x/2163-pLz7.png)

Another time I needed to customize the list differently, so again copy/paste SelectBox:
![](http://n4te.com/x/2164-Ep2u.png)

Once I needed a SelectBox with different fonts for some items, guess what? Copy/paste:
![](http://n4te.com/x/2165-JTtV.png)

Delegating List `drawItem` to SelectBox could help, as it already does `toString(item)`. It's not a great pattern though and can lead to a monstrosity, like the way LwjglFrame has many methods for its LwjglCanvas.

Maybe it would handle some use cases to have a protected SelectBox `newList`, allowing a subclass to swap out the list.

**Comment by WinterAlexander** [comment]
> Delegating List drawItem to SelectBox could help, as it already does toString(item). It's not a great pattern though and can lead to a monstrosity, like the way LwjglFrame has many methods for its LwjglCanvas.
> 
> Maybe it would handle some use cases to have a protected SelectBox newList, allowing a subclass to swap out the list.

Another option could be to have an interface `SelectBoxDrawer` with a default value set into the class which could be changed by the user. The SelectBox and it's sub components would then simply call SelectBoxDrawer#render(Batch, BitMapFont, int, T, float, float, float)` for its rendering. This would allow all form of rendering.

 In terms of pattern though, I would tend to prefer simple protected methods inside SelectBox instead. This option is quite clean for an outside user of SelectBox, the fact the protected methods are being used by an inner class doesn't appear or manifests in any sort of way when using the class. Maybe it's bad for the maintainers of `SelectBox`? In my opinion the inconsistent way in which items are draw (two different `drawItem` functions, one in SelectBox and one in `List`) is much worse.

On top of that there is nothing worse in term of pattern than to have to dupplicate an entire class to do something. This creates a lot of unnecessary code and is a source of bugs if the class changes but not the dupplicated versions.

While it's true that making SelectBoxList public doesn't make it easy to extend the drawing functionality it has the advantage of making it possible to detect the class when checking if an actor is a descendant of a SelectBox. Smaller problem but still a problem.

**Comment by terefang** [comment]
> On top of that there is nothing worse in term of pattern than to have to dupplicate an entire class to do something. This creates a lot of unnecessary code and is a source of bugs if the class changes but not the dupplicated versions.

at least we can agree that copy/pasting a whole class is an anti-pattern to be avoided.

let me again play "Advocatus Diaboli" here.

@WinterAlexander maybe you should propose an implementation, on the lessons you have learn so far, from your current overriding.

@NathanSweet since you seam to have had the same experience, maybe your expertise can be merged into the proposal.

**Comment by NathanSweet** [comment]
> In my opinion the inconsistent way in which items are draw (two different drawItem functions, one in SelectBox and one in List) is much worse.

I wouldn't call it inconsistent. One is drawing the item in the select box, the other is drawing items in the list. The select box and the list are not the same.

This problem occurs any time you build a UI control (Widget in scene2d.ui, as much as I dislike that word, couldn't find a better one) using multiple components.

I don't think it's a great design to pull the details of all those components into the UI control. It bloats the API. It limits customization to only what is exposed. That leads to exposing more, which bloats the API more. Better to keep the components doing what they do separately and also customize them separately.

We can expose creation of the components so they can be customized. It makes customization a bit verbose, but otherwise it's pretty OK.

Knowing if an actor is a descendant of a select box scroll pane (not a descendant of the select box itself) is a separate problem. We can expose the class in SelectBox since we'll need to do so to allow customization of the scroll pane.
