### ISSUE TITLE
opengl call to glDrawElements() ignores numIndices parameter on PC, but works on Android

### ISSUE THREAD

**Issue by megalithic3** [libgdx/libgdx#6618]
#### Issue details
Using opengl graphics library directly ...
    import com.badlogic.gdx.graphics.GL20;
    private static GL20 GLES20;
    GLES20 = Gdx.gl20;
 
 Everything works perfectly when launching to Android devices. I have an entire scene with thousands of triangles rendered just fine, but when running on PC there are extraneous triangles being drawn all over the scene. I tracked the problem down to  glDrawElements(). On PC desktop launch, glDrawElements() draws incorrect number of indices, ignoring the numIndices second parameter completely.

    GLES20.glDrawElements(GL20.GL_TRIANGLES, numIndices, GL20.GL_UNSIGNED_SHORT, mIndices);

For example, changing the numIndices to 3 should render only one triangle. 

    GLES20.glDrawElements(GL20.GL_TRIANGLES, 3, GL20.GL_UNSIGNED_SHORT, mIndices);

Here is the expected correct result on Android.

  ![imageandroid](https://user-images.githubusercontent.com/84444721/128443889-55266ff4-225d-4592-ae60-3d9efed30094.jpg)

But the desktop launch show all triangles, ignoring numIndices completely.

![imagepc](https://user-images.githubusercontent.com/84444721/128443905-28a6fca4-5045-4184-bb1f-f9108b1ec938.png)
#### Reproduction steps/code
An SSCCE can be found at
https://gist.github.com/arashbi/5659096

NOTE: There is one bug. The mColorData needs to be changed to floating points or the shader will crash.

#### Version of libGDX and/or relevant dependencies
1.10.0

#### Stacktrace
NA

#### Please select the affected platforms
- [ ] Windows 10

**Comment by mgsx-dev** [comment]
indeed, both desktop backends are impacted : 
https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGL20.java#L279
https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3GL20.java#L278

unfortunately lwjgl doesn't provide methods for that and i don't know if we could temporarily limit the buffers.

**Comment by mgsx-dev** [comment]
Actually this is what we do in Mesh code, see https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/Mesh.java#L617

so maybe we should move part of this code (limit) to desktop backends code?

@Tom-Ski do you know what we did that and if the fix proposal looks good to you?

**Comment by Tom-Ski** [comment]
Seems good to me.

As to why that caching and restoring is done, (if that is your question), I believe its so that the state of the index buffer isn't altered if someone is doing manipulation using the buffer itself.

**Comment by mgsx-dev** [comment]
@Tom-Ski my question was why we limit the buffer in Mesh class since we call a method that should do this job : glDrawElements (int mode, **int count**, int type, Buffer indices);
I was wondering if we did that because of some known backends bugs.

Anyway i have a working test case right now, i'll do the PR, thx. :-)

**Comment by Tom-Ski** [comment]
Ah. Yeah I think this is due to the discrepancies of glDrawElements on the different platforms. We've had a few quirky issues here over time for the same reason as everyone is doing their own thing slightly differently with respect to the glDrawElements with Buffer param method.

**Comment by megalithic3** [comment]
Much appreciated folks. I'm very to to gethub and such, so pretty much a noog question. When the pull request is merged, I guess I need to get the entire libGDX project on to my machine and build it? Sounds daunting. Or do I wait for a release?

**Comment by tommyettinger** [comment]
You can use a snapshot version, see https://github.com/libgdx/libgdx/wiki/Updating-LibGDX -- snapshots are builds of libGDX from between stable releases, usually built nightly (I'm not sure of the current schedule). The current snapshot version is `1.10.1-SNAPSHOT`, so you would change the version `1.10.0` (wherever it is, most likely in the root build.gradle and/or gradle.properties) to `1.10.1-SNAPSHOT`, sync the project in your IDE (or just run any Gradle task), and then the latest snapshot will be downloaded. Be aware that snapshots are built automatically without being completely checked out by a person, so sometimes bugs get into snapshots and are fixed by the next snapshot build (hopefully). You also need to change the snapshot version from `1.10.1-SNAPSHOT` to `1.10.1` when the stable `1.10.1` release comes out, since the snapshot won't last very long after a release is complete.
