### ISSUE TITLE
Missing Javadoc

### ISSUE THREAD

**Issue by CoolKangaroo2022** [libgdx/libgdx#6632]
Hello! I find in your [Developer Guidelines](https://libgdx.com/dev/contributing/) that 
> If you create a new class, please add documentation that explains the usage and scope of the class. You don’t have to add javadocs for methods that are self explanatory.

However, I witness some public classes without Javadocs, e.g.,
* extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/org/jbox2d/pooling/arrays/GeneratorArray.javaclient/src/main/java/org/odpi/openmetadata/accessservices/subjectarea/client/AbstractSubjectArea.java
* extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/org/jbox2d/particle/ParticleSystem.java
* backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglCursor.java
* gdx/src/com/badlogic/gdx/scenes/scene2d/utils/UIUtils.java
......

Would you like to add Javadoc for these classes, or they are just not that important?
If there is anything I can help with?

**Comment by tommyettinger** [comment]
Anything in gwt emu folders is not exactly public-facing. Those are what are known as "super-sourced", a GWT feature that replaces an existing (generally, documented) file with a different implementation when run on the HTML backend. The different implementation is essentially internal, since the emu/ folder is excluded from builds. LwjglCursor inherits its docs from Cursor, and I don't think anything about it is usually exposed to the user in the core/ folder.

However...

UIUtils should probably be documented. It's kind of an odd class, in where it's placed in the packages as well as what it does. There have been various proposals to replace it with something else, but nothing seemed to solidify. Its usage is somewhat straightforward from the names only, but I had to double-check what left(int) and ctrl(int) did with their argument, along with the other left/right/middle methods (which I didn't initially realize were mouse buttons) and other key modifiers. I'm not volunteering to write these docs, but thankfully changing the docs doesn't require actually building libGDX, so the contribution is substantially easier for anyone to make.

**Comment by Frosty-J** [comment]
Mildly off-topic, but what's your motive here? I see you recently joined GitHub to start opening lots of similar issues. Doesn't look like the issues themselves are written by a bot, but I suspect classes missing Javadocs have been detected by one. I'm sceptical you're familiar with these projects. I don't want to dissuade you from contributing, and there's certainly lots of stuff that can be done without a deep understanding of libGDX (half my pull requests are just changing capitalisation and stuff, haha).

These examples of missing Javadocs haven't won me over. It may make more sense to improve existing Javadocs. For example, "The current upper limit for decoded audio is 1 MB" is only true on Android and `AndroidLiveWallpaperService` has very messy commenting, some of which is even just commented-out code.

**Comment by tommyettinger** [comment]
I agree with Frosty that showing up 8 days ago, posting 18 issues in 17 different repos, and having no commits in that time is rather atypical behavior for a human. We are aware of bots that seek approval for automated tests to run during a PR, which they use as an exploit against GitHub Actions (usually to mine cryptocurrency). We obviously don't want to enable bots. *Please show you are a human being* in whatever way you choose. This could be a picture of your keyboard and monitor with this conversation on the screen, for instance. If you are unable or unwilling to do something along those lines, please close this issue.

**Comment by mgsx-dev** [comment]
closing because of spam

**Comment by NathanSweet** [comment]
I'd close any issue or PR made by a bot on principal, even if it would be useful!
