### ISSUE TITLE
Ogg files load way more slowly than wav files

### ISSUE THREAD

**Issue by hasen6** [libgdx/libgdx#6635]
#### Issue details
The only change I make is to switch my sound effect folder all to .ogg rather than .wav and the load time difference is:

All wav sounds:
assets 229
screen 441

All ogg sounds:
assets 1548
screen 1749

The difference in loading time is somewhat noticeable anyway, but I've provided the actual times for clarity.

#### Reproduction steps/code
Load sound effects as ordinary `Sound` files as wav and then all as ogg and test the loading time of each.

#### Version of libGDX and/or relevant dependencies
1.10.0

#### Please select the affected platforms
- [x] MacOS

**Comment by tommyettinger** [comment]
Is that measured in milliseconds? If so, taking 1.5 seconds to load a small amount of .ogg files seems like a lot, but not for a large amount of .ogg files. I'm not at all familiar with audio in libGDX, but IIRC .wav is an uncompressed audio format, while .ogg compresses sounds to reduce filesize. Decompressing an .ogg then has to take some time; it's just unfortunately more than would be optimal here. This is mostly just the difference between the file types, though maybe whatever dependency we use to decode .ogg could be updated or something...

I think this is likely to be closed because we can't make .ogg into an uncompressed format; the file size improvement isn't free. I'll leave it open in case there could be something to update.

**Comment by hasen6** [comment]
> Is that measured in milliseconds? If so, taking 1.5 seconds to load a small amount of .ogg files seems like a lot, but not for a large amount of .ogg files.

Yes it's in milliseconds. The issue is it takes that long to load the SAME amount of audio files with the only difference being ogg and wav format. I realise ogg is compressed but after searching it seems it's the most common format for sounds and music but if it's gonna take 3-5 times as long as loading wavs I don't see how it can be practical.

>I think this is likely to be closed because we can't make .ogg into an uncompressed format; the file size improvement isn't free. I'll leave it open in case there could be something to update.

If it's an issue with ogg itself then it probably wouldn't be the most common audio format? I noticed mp3 loads equally slow.

**Comment by tommyettinger** [comment]
There are numerous possible reasons for slow loading, in particular hard disk drives being slower to read from in general than flash media (like solid state drives or phone storage), or some file systems slowing down in folders with many files. You haven't said how many files you're loading, or the file sizes of the .wav and .ogg files; that might help us understand what's going on. I have to emphasize I have not done much of anything with libGDX audio, or audio in other platforms, but if .ogg is like other similar file formats, there are probably levels of compression you can use with the files, as well as maybe degrees of lossiness. Audio has bitrate as a configuration option, and whatever tool you used to convert the .wav to .ogg may have used a very high bitrate when you might only need a lower one. Since .wav is a very high-quality, high-file-size format, converting may have had the tool attempt to preserve that high quality, leading to larger amounts of data that needs to be processed during loading. There may be some better choices when converting offered by other tools; I've used Audacity a little, and it always worked fine.

I hope someone else can chime in who uses audio more heavily.

**Comment by hasen6** [comment]
I think if it was a hard drive issue it wouldn't effect only ogg and not wav, it's certainly an importing issue. There are 49 sound files but as I say, I don't think it makes a difference since I'm comparing the _same_ amount of files with wav. The files are all 10 - 100k each in ogg format with most under 50k.

I couldn't find much about people talking about slow loading times of ogg or mp3 sounds in game dev. I'm guessing it can't be that much of an issue otherwise there would be more people talking about it. It's increasing my TOTAL load time, including loading all textures etc by FIVE times. The times I gave above are total game load time.

>Since .wav is a very high-quality, high-file-size format, converting may have had the tool attempt to preserve that high quality, leading to larger amounts of data that needs to be processed during loading.

Yes I'm sure the slowdown is due to conversion of the compressed ogg and mp3 formats.

>I hope someone else can chime in who uses audio more heavily.

Yes me too but thanks for your insight. In my own use of LibGDX audio I noticed it is probably the weakest part of the framework so it is possible there is a problem.

**Comment by tommyettinger** [comment]
Yeah, audio does seem to be a very weak point of libGDX, in part because of the restrictions of cross-platform audio code. Loading less than 5 MB (probably about 2.5MB) of almost anything should be very quick... If any of the sound files are freely-licensed (or maybe you could follow the same steps for a free .wav file with comparable properties, like one from opengameart), you could post one here so people could see if there are any unusual qualities of the files. I'm sure GitHub won't mind 50 kilobytes being hosted on their server, heh.

**Comment by hasen6** [comment]
>Yeah, audio does seem to be a very weak point of libGDX, in part because of the restrictions of cross-platform audio code.

Yes and also there are no simple but vital functions like checking if a sound is finished, is playing, or even getting the length of the sound.

Unfortunately I couldn't provide the oggs here for demonstration. They were converted from wav with MediaHuman Audio Converter for Mac to 192k 44100 Ogg. I'd be happy to test any other oggs though.

**Comment by Frosty-J** [comment]
I think it's inevitable compressed formats will potentially take longer to load. Really depends on CPU speed versus storage speed.

Since your WAVs can almost be copied directly into memory (there's a small header to parse, but no conversion is necessary) whereas the OGGs must be decoded. [Even AAA games have chosen uncompressed over compressed for this reason.](https://www.eurogamer.net/articles/2014-03-11-why-the-pc-version-of-titanfall-is-a-48gb-install)

I think ADPCM could be a nice middle ground between size and decode time, but to my knowledge it's completely unsupported in libGDX.

Is it really necessary to load all your sounds in one go - could some be loaded on the fly?

**Comment by Frosty-J** [comment]
I wanted to see if there's anything more behind this issue, and I kind of lost track of what direction I was going in with this comment.

## Tests

This isn't super scientific, but I've tested the decode times of various codecs on my computer with ffmpeg. While blatantly ignoring the fact sound effects will be lots of small files (which will be slower than loading one large file) it gives us an idea for what kind of difference is realistic.

The source file used was the 2010 remaster of Supertramp's _Breakfast in America_ album, ripped from CD - 46m19s in length, and unsurprisingly 16-bit 44.1kHz.

All test files are 128kbps (±1kbps) with the exception of HE-AAC (64kbps) and of course (AD)PCM and FLAC. Three tests for each.

### ffmpeg: libGDX-supported codecs

Format|1|2|3|Avg.
-|-|-|-|-
WAV 16-bit PCM|750|755|750|752
MP3|3289|3189|3195|3224
OGG Vorbis|3533|3443|3504|3493

### libGDX: libGDX-supported codecs

Format|1|2|3|Avg.
-|-|-|-|-
WAV 16-bit PCM|785|776|777|779
MP3|12194|12270|12124|12196
OGG Vorbis|9838|9728|9669|9745

Tested on libGDX 1.10.0 with Java 11 and LWJGL3.

### ffmpeg: Other codecs

Format|1|2|3|Avg.
-|-|-|-|-
WAV 8-bit PCM|555|563|575|564
FLAC (multithreaded)|903|923|911|912
IMA ADPCM|1288|1250|1274|1270
AAC-LC|2332|2312|2323|2322
MP2|3307|3319|3278|3301
FLAC (single)|3658|3640|3661|3653
HE-AAC|4387|4399|4394|4393
OGG Opus|7728|7706|7702|7712

Some of the above codecs can be used on mobile and web, and I hope will be supported on desktop one day. But the table's partly a digression.

## Conclusion

While I'm not surprised the compressed formats take longer, being ~3× slower suggests something suboptimal is going on here in libGDX land.

If I were in charge, I'd have been likely to close this issue with the reasoning of "of course OGGs load more slowly than WAVs", but this does raise the point that libGDX's desktop audio decoding speed could be improved upon, so it could be worth leaving open for that alone.

**Comment by hasen6** [comment]
> I think it's inevitable compressed formats will potentially take longer to load. Really depends on CPU speed versus storage speed.

Yes that does seem to be the case, I was just very surprised by how much longer it took. I mean really, 30% longer for sounds alone would be significant, especially with many files, so I was not prepared for increasing the the _total_ load time by 400%.

> Even AAA games have chosen uncompressed over compressed for this reason.

Not sure why you say 'even' here, AAA games tend to be huge anyway so people don't mind the large size for such huge budget games or even waiting longer to load. It's the smaller Indie games with less budget to spend on advertising, celebrity voice acting etc etc that need to be concerned more with things like game size or indeed load time. What I noticed in the gamedev world after searching was that ogg is the format of choice, and that would mostly be the indie world.

>If I were in charge, I'd have been likely to close this issue with the reasoning of "of course OGGs load more slowly than WAVs", but now I'm thinking this raises the point that libGDX's desktop audio decoding speed could be improved upon, so it could be worth leaving open for that alone.

Thanks for your open mind. It does seem that I wasn't entirely paranoid and that it is a bit slower than it should be. Thanks for going to the trouble with those tests.

**Comment by hasen6** [comment]
Hmm this is REALLY weird. If you load the same ogg files as `Music` rather than `Sound` there is no such slow down at all...! I loaded all the sound effects in wav format AND all the same files in ogg format but in `Music` format at the same time and the total load time was:

assets 412
screen 697

??
This was literally the time taken to load the sounds TWICE...

Something seems seriously wrong here. Even beyond your tests..

**Comment by Frosty-J** [comment]
`Music`: Streams the file from disk.
`Sound`: Decodes the entire audio file into memory at once. So it'll take longer to load but can be played immediately - the obvious choice for sound effects such as attack sounds.

**Comment by hasen6** [comment]
Ok that makes sense and explains why I saw performance issues with using `Music` with sound files. Someone on stackoverflow gave an answer that was to just use the `Music` format for sound to get around the problem where sounds can't detect length, when they're finished etc.

So we return back your findings then. So it's three times slower than it should be, that's somewhat huge and basically what I was seeing with 3-5 times the load time. It's definitely an issue with LibGDX, and thus explains how ogg can be the format of choice for Indie games since with other engines they most likely won't be seeing this problem.

**Comment by Frosty-J** [comment]
I feel like I've been to Hell and back, figuring out Unity. Think I've managed to conjure up an equivalent test - loading an `AudioClip` from outside the project (libGDX test was also external). I think it might be possible to shave off ~50ms from this, but you get the picture. Here's the current score on the three:

Format|libGDX|ffmpeg|Unity
-|-|-|-
16-bit WAV PCM|779|752|764
MP3|12196|3224|5717
OGG Vorbis|9745|3493|5593

libGDX is still the loser, but you need to be loading in an awful lot of audio in one go on desktop for it to really matter.

**Comment by NathanSweet** [comment]
Haha, you actually did a Unity test, you mad man! Cool to see the numbers.

libgdx uses OggInputStream by Kevin Glass which was used in an old Java game toolkit called Slick (ah the memories). It uses the JOrbis library. I vaguely remember hacking on OggInputStream long ago to make it a little more efficient. If it's JOrbis that is slow, it's a bigger issue.

MP3 uses javazoom. I'm not surprised that is slow. MP3 decoding in general seems like quite a mess. I would avoid it if possible and use OGG.

**Comment by hasen6** [comment]
> I feel like I've been to Hell and back, figuring out Unity.

Yeah I would never touch it, LibGDX for me every time. Your tests are very helpful indeed though.

> I would avoid it if possible and use OGG.

On LibGDX as it is I think the only viable option is to use neither, unless it's only for a very small number of short files - like 1-3 or something. I really hope they can address this issue and generally improve the audio side of LibGDX.

**Comment by mgsx-dev** [comment]
I tested with my game and i can load 351 ogg files (total 3MB on SSD) in 1500ms which is totally OK for me considering that : 
* i only use one thread to load them (that could be an improvement for your case)
* most of my other assets are way much heavy (3D models, textures, etc..).
* i loaded them all at once (in real life, you typically only load needed assets before a level)

So i would say that OGG (or any other compressed formats) is totally fine for most use cases. If loading time is much more important to you than storage (i can understand that), then WAV format is better.

**Comment by hasen6** [comment]
> I tested with my game and i can load 351 ogg files (total 3MB on SSD) in 1500ms which is totally OK for me.

You can only ever _**compare**_ it with how long it takes with other engines and with how long WAV takes to load on LibGDX, which you strangely didn't even mention. Saying it's ok for you on a fast desktop with SSD is pretty useless information since there's different desktop systems and even mobile systems where file size will be more important and it will be even slower..

Frosty-J's tests were infinitely more useful. You could at least add the time for loading them in wav format and the size of the oggs since I loaded only 49 in about the same time. I also use an SSD so we can expect slower times on a normal hard drive.

**Comment by Frosty-J** [comment]
Mobile isn't applicable. On Android, `Sound` just uses Android's `SoundPool` (and its 1MB limit) and `Music` its `MediaPlayer`. While I'm unfamiliar with iOS, it's similar in that the OS deals with things. And for web it's up to the browser. Desktop should be the only platform where there's JOrbis and JavaZoom going on.

While a comparison would be nice, it might be a bit much to expect mgsx to convert all his sounds just for this.

**Comment by hasen6** [comment]
>Mobile isn't applicable. On Android, Sound just uses Android's SoundPool (and its 1MB limit) and Music its MediaPlayer.

Ok so it's down to the Android OS to convert it, I didn't know that, I've never developed for Android.

> While a comparison could be nice, it might be a bit much to expect mgsx to convert all his sounds just for this.

It took me literally 5 seconds to drag and drop batch convert all 49 of my sounds. But yeah of course he doesn't need to do that.

>We already know WAV is faster, 

We also already know ogg is slower and HOW slow so equally as pointless to give how long it takes to load oggs.

>and by roughly how much between our two tests, so I'm not sure what him testing with that would prove.

It would prove as much as only showing the time for oggs - ie nothing at all. Especially since the file size was not given since his test was seemingly faster than mine. He also didn't mention the OS used or how many different OS he tested. Checking that a game works fine only on your own system is a common mistake developers make though.

We've established it is somewhat slower than FFMPEG and significantly slower than Unity and most probably other engines too. Not really much more to say than that.

**Comment by tommyettinger** [comment]
> or how many different OS he tested. Checking that a game works fine only on your own system is a common mistake developers make though.

Speaking of which, have you tested on more than one system? You also haven't provided any kind of stats about the machine you tested on. Benchmarks without hardware info aren't as useful. This might help narrow down where bottlenecks are in the loading process; if some processing is done in RAM, which it probably is, then slower RAM (DDR3, for instance) might explain a lot. Some OSes or antivirus may slow down processing if they are concerned about something an app is doing, which could easily include calling a native library (even an innocuous one for audio, if it hasn't been somehow approved by the OS/antivirus).

There's a high possibility that the slowdown is due to either non-perfect code in a third-party library, or just due to JNI overhead, probably in a third-party binding for an audio library. If it's the latter, then nothing we do can really make a difference, because unless we can find and use a pure-Java .ogg reader (that isn't slower on its own), any Java code that calls native code has to go through JNI. I believe JNI performs differently on Java 8 vs. the latest Java, and I don't know which has the advantage (I'd hope Java 16 is faster, but it isn't always).

**Comment by hasen6** [comment]
> Speaking of which, have you tested on more than one system?

You test on more than one system to find if _any_ of them have issues, not if _all_ of them don't. My test was valid because I compared WAV vs Ogg on the same machine and the speed difference was too large. I also stated I was using Mac OS. mgsx-dev's test wasn't useful because he not only did not provide stats for his system, or indicate the OS used, but he also did not compare ogg with wav.

>Benchmarks without hardware info aren't as useful.

Not _as_ useful, but unless the system is ancient then they are still useful since we want games to run on a wide range of systems.

>There's a high possibility that the slowdown is due to either non-perfect code in a third-party library, or just due to JNI overhead, probably in a third-party binding for an audio library.

Well I don't know what can be done, I'm just saying this issue exists. All we have is mine and Frosty-J's tests which show a great difference between ogg and wav and a great difference compared with other frameworks like Unity. All we can say is there is a problem.

Try not to be so pessimistic anyway, there may well be a way to fix it.

**Comment by tommyettinger** [comment]
You *still* haven't provided any basic info on your hardware (such as "year built" or "Intel processor" or "a new M1 Mac") other than "MacOS". I feel like asking repeatedly is a waste of my time. I would rather not waste my time! The AARCH64 vs. x86-64 difference is actually quite significant, and you could quite reasonably be running either in 2021. It's entirely possible that this issue doesn't appear on M1 Macs, but does on Intel, or vice versa; it's even more likely that the magnitude of severity is different on different architectures, OSes, eras of production, etc.

Please remember, you are using tools built by volunteers in their spare time, and @mgsx-dev is such a volunteer. He has helped this project immensely over several years, and our 3D code basically depends on him. He's earned our respect. @Frosty-J has recently contributed some really in-depth reporting on various issues that would have otherwise stagnated, and he's shown a keen eye for detail. He's also earned our respect.

**Comment by hasen6** [comment]
> You _still_ haven't provided any basic info on your hardware (such as "year built" or "Intel processor" or "a new M1 Mac") other than "MacOS". I feel like asking repeatedly is a waste of my time.

Strangely you're yet to ask mgsx-dev _at all_, despite the fact he didn't even provide the OS used, never mind anything else. It would certainly be useful if he did. I'm using an intel mac. I don't think a game that only works on M1 macs would be particularly useful so not sure what this would prove? Also my test shows the _difference_ between wav and ogg is too great. That conclusion could be reached on _any_ hardware. If mgsx-dev also provided the speed for wavs we'd probably see the same problem. Frosty-J doesn't appear to have provided the system or hardware used either but I feel the information he gave is valid since it's a comparison.

>Please remember, you are using tools built by volunteers in their spare time, and @mgsx-dev is such a volunteer. He has helped this project immensely over several years, and our 3D code basically depends on him. He's earned our respect.

I'm sure, I was just remarking that his comment here was not useful in any way. Especially his conclusion that "it's fine". I think it's better to just concentrate on the facts rather than making this all personal. Yes Frosty-J's comparison test with Unity vs LibGDX and wav vs ogg was very helpful here and it shows there is a problem without even needing to look at anything I've or mgsx-dev has said.

**Comment by Frosty-J** [comment]
> I don't think a game that only works on M1 macs would be particularly useful so not sure what this would prove?

He didn't say anything about a game only working on one or the other. libGDX games can run on both Intel and M1 on macOS (albeit more prone to technical issues on M1 until we no longer need Rosetta) so we wouldn't be able to figure out which you're using on our own.

> Frosty-J doesn't appear to have provided the system or hardware used either but I feel the information he gave is valid since it's a comparison.

So that this argument has one fewer direction to head in, my relevant specs are:

&nbsp;|&nbsp;
-|-
**CPU**|Intel i7-4770
**RAM**|Dual channel DDR3 1600MHz, mixed brands
**Storage**|An SSD that's bottlenecked by being connected over SATA
**OS**|Ubuntu 20.04

I could easily enough change any of the above, but I don't see what for. I expect WAV to always be faster, and typically by a similar percentage, except in the case of slow storage such as loading from floppy disk.

**Comment by Frosty-J** [comment]
Can we close this? #7140 makes Ogg faster, and if it's still not fast enough there's still PCM WAV or https://github.com/Hangman/TuningFork?tab=readme-ov-file#supported-formats (desktop only).
