### ISSUE TITLE
AIDE Project generator

### ISSUE THREAD

**Issue by chiaravalle** [libgdx/libgdx#6668]
#### Issue details
Create a project generator which outputs an AIDE project 

#### Version of libGDX and/or relevant dependencies
Latest

#### Please select the affected platforms
- [X] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

AIDE (https://play.google.com/store/apps/details?id=com.aide.ui) is an Android IDE for building Android Apps and games. It (badly)  supports LibGDX, and making a project is possible, but hard.
My idea is to generate a project from Project generator, but from device, for device

**Comment by tommyettinger** [comment]
If AIDE doesn't support Gradle projects, I don't see how that's an issue with libGDX... The gdx-setup app is a desktop app in the first place (it uses Swing). You're probably better off making a **project template** that has whatever format AIDE can load. In general, any support for AIDE needs to come from the AIDE developer(s); we see no proceeds from the sales of AIDE products (such as its debugger), and I see only misery as a result of supporting it here. If it were compatible with the standards that libGDX uses (Gradle for projects), we would naturally try to have gdx-setup's projects support those standards, but that won't make gdx-setup able to run on Android.

You can probably find a number of open-source libGDX demos out there (a game jam just finished, https://itch.io/jam/libgdx-jam-18/entries ), and you might be able to open one in AIDE, depending on whether it has non-Gradle project files for Eclipse or Android Studio included. If you have an existing project that works, you can use it as a template, stripping out anything specific to the original game.

I'm closing this because we are on an issue tracker for libGDX and this is an issue with AIDE, namely that it doesn't support Gradle projects like every other current development tool that makes Android projects requires. We cannot fix problems with AIDE.

**Comment by chiaravalle** [comment]
I see, thanks anyhow. For the records, yes, a template project already exists in the web, but requires you to perform tricks to get it working, and a simple Android App generating AIDE projects would have boosted and improved project generation. I'm not sure, but I guess AIDE supports Gradle (it's not specified in the description, but Android Studio project's support is mentioned).
By the way, thanks for taking time to read me =) cheers

**Comment by tommyettinger** [comment]
Confusingly, there are two Android Studio project types (at least): a `.iml` file stores an IDEA or AS project in a file that's specific to the JetBrains IDEs, and AS also supports a recent Gradle version. There's also a cousin of .iml that stores the same information in a folder, which I think is `.idea/`. Since Gradle isn't specific to AS, IDEA, or Eclipse (it's used by AS, but can also be used with Eclipse, NetBeans, or without any IDE), and they mention AS project files, they probably mean one of the JetBrains IDE-specific formats; this could be .iml, the .idea folder, or an Android Studio variant on these. From what I recall on the Discord attempting to help people who used AIDE, it didn't support Gradle at the time, and had really limited ability to import from the web (such as from GitHub).

**Comment by chiaravalle** [comment]
Uhm, what a big mess =)

**Comment by MobiDevelop** [comment]
It's not terribly difficult to get a libgdx project set up for AIDE, the main problem is that its use of Gradle is pretty much exclusively for dependencies, it doesn't really run Gradle tasks so can't copy the natives automatically.

If you do that manually, it works fine.
