### ISSUE TITLE
Very bad perfomance when using LWJGL3 on Mac OS X

### ISSUE THREAD

**Issue by funkyfourier** [libgdx/libgdx#6690]
#### Issue details
When running my app with LWJGL3 on OS X, as opposed to LWJGL2, I am getting very bad performance. The app makes heavy use of scene2d.ui. When running the app on Android the performance is quite good, and running the desktop version with LWJGL3 on a Raspberry Pi 4 also runs very well.

So when running on LWJGL2 on the mac I am getting a steady 60fps, and when on LWJGL3 it is more like 20. It is run with `-XstartOnFirstThread` and `-Djava.awt.headless=true`.

The Mac is a 2014 MacBook Pro running Big Sur. Had this issue also on Catalina.

Could this have something to do with PR #6673?

The app in question is [Sputter Music Sequencer](https://play.google.com/store/apps/details?id=info.casualcomputing.sputter) for Android. If anyone wants to check it out for whatever reason, let me know and I can give you a promotion code to download it for free.

#### Reproduction steps/code
I have not been able to find exact steps to reproduce it. For the default project generated by gdx-setup I am not able to measure any difference between LWJGL3 and LWJGL2 on my MacBook Pro.

#### Version of libGDX and/or relevant dependencies
1.10.0

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] macOS

**Comment by tommyettinger** [comment]
OK, so this is an Android app and you're trying a desktop (MacOS) version for debug, I'm guessing? Well, first, what we know it isn't:

 - #6673 hasn't been merged, so it won't affect your application.
 - We know this isn't an M1-related MacOS issue, so that possibility can be ruled out.
 - There have been intermittent reports of total crashing failures with LWJGL2 on recent MacOS versions, typically Catalina -- all of the logs contain this:
```
# Problematic frame:
# C  [AppKit+0x3e5abc]  -[NSOpenGLContext setView:]+0xe5
```
It's something to note that you're able to run with LWJGL2 at full speed on Catalina; this doesn't help resolve this bug, but it may for other people's bugs.

The default project probably doesn't have enough happening in it to lower FPS below the monitor refresh rate of 60FPS. You might want to just loop *n* times and create a large grid of *n* small buttons, to see about at what *n* performance starts to dip. If a tightly packed grid of buttons doesn't dip FPS, it probably isn't scene2d.ui related (still might be...). I'd try profiling with [VisualVM](https://visualvm.github.io/), which is free, to see where the most time is being spent. The majority of the time in most games and applications (that aren't already very close to going below 60 FPS) should be in render() or methods called by render(). Multithreaded usage may change what to expect from profiling. The main thing to look for, I think, would be if a particular method (especially part of LWJGL) is taking a substantially larger percentage of time when the only factor that changes is LWJGL2 vs. LWJGL3. I wouldn't be surprised if there's some uncommon issue with framerate being limited more than once, but this hasn't been reported by anyone else, to my knowledge.

To make sure this isn't caused by the frame limit, you can change the settings in your Lwjgl3Launcher (or DesktopLauncher, if you didn't use gdx-liftoff to generate the project):
```
                // Try with both true and false.
		configuration.useVsync(true);
                // Try with 0 (unlimited), the refresh rate and maybe also twice the refresh rate. Maybe half as well.
		configuration.setForegroundFPS(Lwjgl3ApplicationConfiguration.getDisplayMode().refreshRate);
                // Be careful with your computer's temperature if you have VSync set to false and FPS is high.
```

If VSync is on, the FPS should be no higher than the monitor's refresh rate. If it is off, the only limit is what is set on the next line, with setForegroundFPS(). You can try absolute numbers or multiples of the refresh rate, depending on what you know about your monitor's settings. If setting VSync to false (without the second line) lets the LWJGL3 app run at a higher speed, that narrows down the possibilities a lot. The same is true if VSync is false and foreground FPS is 0 or very high.

I don't have a Mac, so there's very little I can do to reproduce this. I think a few members of the team use Macs regularly, or can access one from about the same era as yours. Without seeing any code, there's not a ton we can do... That's why I gave all these options so you can try to track it down on your side.

**Comment by PokeMMO** [comment]
Are you using 3d and ModelBatch? If so, check if #5893 is the culprit.

**Comment by funkyfourier** [comment]
Thanks  @tommyettinger for your quite elaborate answer and also to you @PokeMMO for your suggestion.

I tried VisualVM. Thanks for the suggestion, it seems like it can be a very useful tool. However, when I run my app and try to click on it in Visual VM nothing happens. Occasionally I could get the usual screens to show up, but everything seemed frozen and unresponsive. This was both when using LWJGL3 and 2. I got it to work with the default gdx-setup project, so I am not sure what is going on. 

I also tried your exact vsync and fps configurations, they had no effect.

Probably I will have to live with this issue for now. Actually the goal is to have the app running on a Raspberry Pi, while developing it on a Mac. So if it works well on the RPi that will have to suffice for now. 

I'd be happy to try any other suggestions. @PokeMMO Is there anything specific I could try in the issue you pointed to? I am not not sure if I am using ModelBatch. At least not on purpose... But it could be that Scene2D.ui does?

**Comment by tommyettinger** [comment]
> I am not not sure if I am using ModelBatch. At least not on purpose... But it could be that Scene2D.ui does?

ModelBatch renders 3D models, so you're pretty much certainly not using it unless you specifically have 3D models in your project assets.

> However, when I run my app and try to click on it in Visual VM nothing happens. Occasionally I could get the usual screens to show up, but everything seemed frozen and unresponsive. This was both when using LWJGL3 and 2. I got it to work with the default gdx-setup project, so I am not sure what is going on.

Now this seems strange. Is it your game that is freezing, or VisualVM? I use the Startup Profiler extension (which can be installed from inside VisualVM, Tools -> Plugins -> Available Plugins) so I can delay the game's startup until profiling is running. With that, I had startup issues that got resolved by following some of VisualVM's suggestions (I had to use the current agent option, and make sure the JVM I was using had been calibrated before running). I think you must have calibrated already, but if you haven't, calibration is sort of a hidden option: Tools -> Options -> Profiling -> Manage (at the bottom). If you got it working with gdx-setup, there might be something different about your application that makes VisualVM have problems...

This is definitely an uncommon problem; we don't have a lot of people targeting the RPi, but it does work there using LWJGL3 from what I understand. You have to use LWJGL3 to target the RPi, but in most cases it's fine to have both an LWJGL2 and LWJGL3 module that function essentially the same. As long as all changes are in core, or less commonly, duplicated in LWJGL2 and LWJGL3, you could develop with LWJGL2 on your Mac and run with LWJGL3 on your RPi. This was an anticipated use case for having LWJGL2 and LWJGL3 both allowed in the same project in [gdx-liftoff](https://github.com/tommyettinger/gdx-liftoff). Note that gdx-setup has never supported having both LWJGL2 and LWJGL3 projects, though you can modify one of its projects quite a lot to get it to do that.

**Comment by Frosty-J** [comment]
> Note that gdx-setup has never supported having both LWJGL2 and LWJGL3 projects

This isn't strictly true. If you run it from the command line, `desktop` and `legacy_desktop` modules will both be created, unless you `--excludeModules` one of them of course. I could add support for this to the GUI if there's interest, but personally I'm hoping LWJGL2 completely dies out.

**Comment by tommyettinger** [comment]
> personally I'm hoping LWJGL2 completely dies out.
For that to happen, we'd need to resolve this mysterious slowdown issue. Thank you for volunteering, your sacrifice shall not be in vain.

**Comment by funkyfourier** [comment]
Alright! Seems like I have found something. I installed the Startup Profiler as you @tommyettinger suggested, and now I can get it to work. Using it, I tracked the issue down to `Gdx.graphics.getDensity()` which was called every frame. This has been done to calculate correct sizes etc with regards to different screen densities. When I instead just return 1, the application runs 100% fine as expected on my 2014 Macbook Pro.

I do not know if `Gdx.graphics.getDensity()` is expected to run fast enough that it can be called on each frame. There is appearently some stuff going on in `Lwjgl3Graphics.getPpcX()`, and I guess some of that stuff is ultimately calling OS functions.

Let me know if there is something more I can test/do to debug this issue.

Just to be clear: It has been running fine using LWJGL3 on the RPi4 all along, and still does. Even with the `Gdx.graphics.getDensity()` call.

**Comment by funkyfourier** [comment]
> I'm not totally sure this is something those projects would call a bug, since in (almost?) all cases you don't need to call getDensity() every frame. It seems like you have a solution that works on your hardware, and definitely works on the RPi target hardware, but maybe the solution here would just be to update the documentation and say that getDensity() should be stored, rather than called every frame.

That seems reasonable. The underlying code for determining screen density will likely be platform dependent in any case, and there is no way to be certain of the cost of it. At least I will update my code to not call it on every frame. 

As far as having two screen with different densities I actually have that here, Retina screen on the MacBook and an extra screen on the side which is probably 160dpi. Not sure how to properly tackle that. It seems like "normal" apps adjusts to it when I move them from one screen to another. For now it will work 100% well enough, but I'll try to deal with it some day and will report back then.

Also I wanna thank you again for pointing me to and helping me out with VisualVM. I have been looking for a good open source profiler to use on desktop. Gold!

**Comment by funkyfourier** [comment]
I tried with and without running `Gdx.graphics.getDensity()` on each fram on a RPi 4. Without it running I get a steady 60fps, and when running it on each frame it drops to about 30. I have not noticed any issues like this on Android, but it could be that determining the DPI on the screen of a phone is a known constant, while on desktop machines some costly calculation has to be run. At least it does seem so.

In any case, as you @tommyettinger suggest it would make sense to update the documentation to warn about this. I have proposed such an update in the PR.

Thanks again for all your help!
