### ISSUE TITLE
Missing characters in Hiero fnt

### ISSUE THREAD

**Issue by yangbo1024** [libgdx/libgdx#6699]
use hiero to export bitmap font;
characters (SampleText):

 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~؋،؍؎؏ؐؑؒؓؔؕ؛؞؟ءآأؤإئابةتثجحخدذرزسشصضطظعغـفقكلمنهوىيًٌٍَُِّْٕٖٜٓٔٗ٘ٙٚٛٝٞ٠١٢٣٤٥٦٧٨٩٪٫٬٭ٮٯٰٱٲٳٴٵٶٷٸٹٺٻټٽپٿڀځڂڃڄڅچڇڈډڊڋڌڍڎڏڐڑڒړڔڕږڗژڙښڛڜڝڞڟڠڡڢڣڤڥڦڧڨکڪګڬڭڮگڰڱڲڳڴڵڶڷڸڹںڻڼڽھڿۀہۂۃۄۅۆۇۈۉۊۋیۍێۏېۑےۓ۔ەۖۗۘۙۚۛۜ۞ۣ۟۠ۡۢۤۥۦۧۨ۩۪ۭ۫۬ۮۯ۰۱۲۳۴۵۶۷۸۹ۺۻۼ۽۾‎—‘’“”…、。《》【】ﭐﭑﭒﭓﭔﭕﭖﭗﭘﭙﭚﭛﭜﭝﭞﭟﭠﭡﭢﭣﭤﭥﭦﭧﭨﭩﭪﭫﭬﭭﭮﭯﭰﭱﭲﭳﭴﭵﭶﭷﭸﭹﭺﭻﭼﭽﭾﭿﮀﮁﮂﮃﮄﮅﮆﮇﮈﮉﮊﮋﮌﮍﮎﮏﮐﮑﮒﮓﮔﮕﮖﮗﮘﮙﮚﮛﮜﮝﮞﮟﮠﮡﮢﮣﮤﮥﮦﮧﮨﮩﮪﮫﮬﮭﮮﮯﮰﮱﯓﯔﯕﯖﯗﯘﯙﯚﯛﯜﯝﯞﯟﯠﯡﯢﯣﯤﯥﯦﯧﯨﯩﯼﯽﯾﯿﱞﱟﱠﱡﱢ﴾﴿ﷲ﷼ﺀﺁﺂﺃﺄﺅﺆﺇﺈﺉﺊﺋﺌﺍﺎﺏﺐﺑﺒﺓﺔﺕﺖﺗﺘﺙﺚﺛﺜﺝﺞﺟﺠﺡﺢﺣﺤﺥﺦﺧﺨﺩﺪﺫﺬﺭﺮﺯﺰﺱﺲﺳﺴﺵﺶﺷﺸﺹﺺﺻﺼﺽﺾﺿﻀﻁﻂﻃﻄﻅﻆﻇﻈﻉﻊﻋﻌﻍﻎﻏﻐﻑﻒﻓﻔﻕﻖﻗﻘﻙﻚﻛﻜﻝﻞﻟﻠﻡﻢﻣﻤﻥﻦﻧﻨﻩﻪﻫﻬﻭﻮﻯﻰﻱﻲﻳﻴﻵﻶﻷﻸﻹﻺﻻﻼ！（），：；？￥️

There's 603 characters, but only 489 in exported .fnt file.

Version:  Hiero v5, Version 1.0 (1.8.0_301); 
OS: Windows 10 & OSX

**Comment by tommyettinger** [comment]
BitmapFont doesn't display right-to-left text anyway, so that Arabic script is not going to display correctly at all. I think the chars that aren't exported are the combining diacritical marks, which you can see stacking on top of various chars in what you posted. BitmapFont also doesn't handle stacking multiple combining marks on the same char. It also doesn't support the extremely complex joining/ligature rules that Arabic characters have (I don't think it even handles the fi ligature in the Latin script). I haven't checked, but if any characters are at code points greater than 65535, or '\uFFFF', then I doubt Hiero can handle those (and they're hard to handle in Java already).

The only way to properly support Arabic and other scripts would be to somehow incorporate a library like HarfBuzz, which handles complex text shaping, and doing that would be a major effort because of GWT limitations and iOS/Android differences. The characters after 65535 are even harder (if that's an issue here at all), since a char in Java only goes that high.

This is a legitimate limitation of BitmapFont, but I don't think it's one that we have the workforce to address. This could change in the distant future. For now, if you need to support complex scripts you need to look elsewhere, primarily at game engine companies with multi-million dollar budgets for features (Unity or Unreal, probably). Godot may have some progress made on this, but it's a pretty tough problem...
