### ISSUE TITLE
This repository is over 1 GiB - can we prune it down a little?

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx#6704]
Obviously it's good to preserve history, but holy moly is it slow when I forget shallow clones exist.

Here's the worst offenders discovered with [the first script I found](https://stackoverflow.com/a/14329983) - 15 files over 20MB (I pondered for a long time how much to include, but it would've been a whopping 748 rows if I included everything over 1MB):

Bytes|Filepath
-:|:-
46,784,255|backends/gdx-backend-android/libs/android-9.0.jar
40,002,291|backends/gdx-backends-gwt/libs/gwt-dev.jar
35,291,301|demos/superjumper/superjumper-html/gwt-unitCache/gwt-unitCache-0000013915ACE9EF
34,734,577|demos/dev-guide/my-gdx-game-html/gwt-unitCache/gwt-unitCache-00000136B5AEA243
34,622,170|backends/gdx-backend-android/libs/android-7.1.jar
33,235,402|backends/gdx-backends-gwt/libs/gwt-dev.jar
33,018,022|backends/gdx-backends-gwt/gwt-unitCache/gwt-unitCache-00000134CCFCD7DD
32,757,583|backends/gdx-backends-gwt/gwt-unitCache/gwt-unitCache-00000133E4DA458E
32,565,585|backends/gdx-backends-gwt/gwt-unitCache/gwt-unitCache-00000133E4E6BFF7
29,045,358|backends/gdx-backends-gwt/libs/gwt-user.jar
28,661,546|backends/gdx-backends-gwt/libs/gwt-user.jar
28,313,631|backends/gdx-backends-gwt/libs/gwt-dev.jar
21,792,859|backends/gdx-backend-android/libs/android-4.4.jar
21,500,314|backends/gdx-backend-android/libs/android-30.jar
21,371,904|extensions/awesomium/gdx-awesomium/src/com/badlogic/gdx/awesomium/natives/Awesomium.dll

With some more scrolling, it gets less interesting - just duplicate filenames, such as 70(!) versions of `gdx-backend-jogl.jar`. Fortunately, most of the weight seems to be old stuff, so I don't see it getting all that much bigger anytime soon.

Some of this will no doubt be important, but we can get rid of some of it... right? Or move it somewhere. I don't know what the repercussions would be. The repository just feels unnecessarily bloated.

**Comment by tommyettinger** [comment]
Well deleting it from the repo wouldn't do anything, since it would still be in .git's history. You'd need to delete it, commit, and then scrub with a tool like bfg.jar ... which rewrites the history of the repo to remove those files. And when you use bfg.jar, everyone with their own fork needs to re-clone the repo. It's a huge hassle, and if anyone forgets, the old file history is back. I believe this process also does stuff to open PRs (probably it closes them to avoid mix-ups). If anyone has a better way, I'd love to hear it, since I just today was dealing with a 4GB repo that I got to about 1GB.

**Comment by Frosty-J** [comment]
Oh, that's unfortunate. Was hoping they'd just disappear on the next pull. But that makes sense.
