### ISSUE TITLE
test fail: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by suoyi123wang** [libgdx/libgdx#6709]
the unit test case we generate failed:
![image](https://user-images.githubusercontent.com/44200574/143803961-cdaa9ced-3204-456c-9810-eb924bdf740f.png)

![image](https://user-images.githubusercontent.com/44200574/143804016-640b30b1-71da-4669-8c95-da6a12f84268.png)

before calling `out[index + 2]`, you should compare the length of out with index + 2

#### Version of libGDX 
1.10.0

#### Please select the affected platforms
- Linux

**Comment by tommyettinger** [comment]
You should be more clear that this is a test you wrote/generated, not one already in libGDX. It's also rather clear that this is generated code, since a reasonable human wouldn't make the mistake your test has. If I want to fill a float array with the color channels of a gradient's start and end, it's pretty easy to see that an array with length 2 won't be sufficient, since there are red, green, and blue channels in a color (plus sometimes alpha) -- 3 is more than 2! The docs could be more clear that this uses the 3 channels of a color, but we're an open source framework, and anyone can just open up the GradientColorValue file and look at it.

Because libGDX code style does not typically use excessive checks for array length before access (and because those checks have a speed cost that is better addressed by fixing your code), I'm closing.
