### ISSUE TITLE
Rotate a bitmap font

### ISSUE THREAD

**Issue by badlogic** [libgdx/libgdx#671]
_From [tobias.w...@gmail.com](https://code.google.com/u/113866277779216050036/) on December 18, 2010 14:31:15_

If I have an object which holds a sprite and a corresponding text, I can rotate the sprite, but not the text.

Maybe I could do that with a seperate spriteBatch, but:
"A SpriteBatch is a pretty heavy object so you should only ever have one in your program."

So I think there are two options:
- BitmapFont.setRotation(float)
- or allow to make a Sprite from a BitmapFont (possible?)

_Original issue: http://code.google.com/p/libgdx/issues/detail?id=83_

**Comment by samueljohnston96** [comment]
Hi, I am unable to use this solution since I would like to compile this to html and run it on the web as well as run it on the desktop.  When attempting to place this on the web the application crashes with the error "GwtApplication: exception: (TypeError) : Cannot read property '1' of undefined
(TypeError) : Cannot read property '1' of undefined", but when I remove the spriteBatch and use the batch given on draw it works fine.  How would I be able to get rotated BitmapFonts working on both html and the desktop?

**Comment by NathanSweet** [comment]
@samueljohnston96 The solution above will work for web. However, you posted to a 5+ year old issue:
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
