### ISSUE TITLE
Box2d rotation/angular velocity slows down on pause and resize.

### ISSUE THREAD

**Issue by maxkcy** [libgdx/libgdx#6735]
Please ensure you have given all the following requested information in your report.

#### Issue details
In my game "butt hole slime", box2d rotation slows down and makes the game unplayable when it is paused.

#### Reproduction steps/code
create a few spinning KINEMATIC bodies with a few rectangle shape fixtures and set angular velocity. watch it slow down on pause and resize.

#### Version of libGDX and/or relevant dependencies
It is in my "ButtHoleSlime" repo

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android (not tested)
- [ ] iOS (not tested)
- [X] HTML/GWT
- [X] Windows
- [ ] Linux (not tested)
- [ ] macOS (not tested)

**Comment by Frosty-J** [comment]
https://github.com/maxkcy/ButtHoleSlime/blob/e95f03e4807cc47065831f690af4faf6c2c73c5a/core/src/main/java/com/max/buttholeslime/Screens/TheOnlyLvl.java#L127-L130

You should probably have some kind of accumulator approach as seen at https://github.com/libgdx/libgdx/wiki/Box2d#stepping-the-simulation.

Shame you got banned from the Discord server and removed from two separate libGDX jam pages, as this issue will probably get closed due to being more help-oriented.

**Comment by Tom-Ski** [comment]
> 

what for?

**Comment by Frosty-J** [comment]
> what for?

I'd rather not dig stuff up. If @raeleus or anyone in authority wants to, they can _if they choose to do so_. So long as your volume is turned down, you can find his itch.io page (maxkcyfun.itch.io) to get some insight into the mind of Max.
