### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [libgdx/libgdx#6763]
Hey there!

I belong to an open source security research community, and a member (@haxatron) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by tommyettinger** [comment]
Hello, thanks for the notice!

You (well, Haxatron) already disclosed it, even if you haven't yet realized it. Thankfully, the "security issue" in question only applies to a tool run offline, on files that are essentially never downloaded from the internet. In practice, there should be no security concerns with the tool in question, unless you have other concerns that aren't publicly visible. We appreciate your vigilance and will internally discuss how best to handle security-related contacts in the future. For what it's worth, my email is on my GitHub profile, and while I show no respect to repo scrapers who cold-call me trying to sell something, I absolutely take security concerns seriously, and if I got a security-related email I would discuss it with the team. (I just don't check my emails that often...)

If you are, by any chance, looking for places that should have security as a priority, EsotericSoftware's Kryo project could maybe benefit from a careful look-over, especially since it's used in various other large projects. I don't think Kryo itself is exactly insecure, but the ecosystem around it may have fallen behind the times, such as third-party bindings to Kryo for other JVM languages. And of course, Kryo is a serialization library, so I'm sure you know how many security issues in the coding world are related to serialization.

In the future I would recommend making forks private, if possible, before disclosure. If I had a malicious intent, right now I would be going through public repos associated with your research community and checking for open/exploitable bugs that had not yet been patched. This isn't an attempt to shame your practices; I just think as security researchers you understand the position you are in arms you with knowledge that isn't widely available, and if a bad actor wanted that knowledge, you would want to safeguard your findings.

**Comment by Haxatron** [comment]
Hi, thank you for the reply.

Currently, huntr needs to be able to read a branch containing a patch from
a fork if a researcher wants to submit a fix. I will ask Jamie if there are
any plans for researchers to submit a fix more discretely.

Regarding the issue at hand, thanks for the clarification that the tool in
question (I'm  presuming you mean that the TiledMapPacker) will never be
used on any malicious .tmx files downloaded from the internet. Will proceed
to mark the report as invalid.

**Comment by tommyettinger** [comment]
Indeed, TiledMapPacker is the one. I actually don't know where I could find any .tmx file, malicious or not, to test on. The only way I can think of would be to make one myself.

As for ways to hide undisclosed findings, making your researcher team members of an organization, and the huntr tool also part of that organization (with permissions to see private repos in there), may be a part of a solution. This also serves in a way to provide support for resolving complex security issues that need multiple researchers to collaborate on a fix or fixes, while keeping their work away from prying eyes.

It looks like you've done plenty of good work already, so I hope you're able to keep cleaning up lots of vulnerabilities in the open source world.

I'm not closing this because the team still needs to discuss a security notification protocol; I think we'll probably follow GitHub's guidelines as closely as we can.

**Comment by JamieSlome** [comment]
@tommyettinger - we appreciate your feedback, very in-depth!

We do have plans to really iterate on our fix process in the future and will look to address this in our roadmap.

If you have specific feature requests that you would like us to address immediately, we do have a public roadmap where you can create an issue or request:

https://github.com/418sec/huntr/issues/new

**Comment by badlogic** [comment]
Hello, jumping in here. If you have identified a security issue you want to disclose privately, you can send me an email at mario@badlogicgames.com. If you have a fix for a security issue, send a PR. Other than that, we generally do not do anything on top of that.

If you are using automated tooling to identify security issue, and keep sending a lot of emails, we'll likely not reply after a while.

Closing this out now.
