### ISSUE TITLE
Integrating into an existing Android Studio project

### ISSUE THREAD

**Issue by reymalahay** [libgdx/libgdx#6781]
Hi there,

Is there any documentation available on how to integrate `libgdx` into an existing `Android Studio` project?

please advise.

thanks in advance,
rey malahay

**Comment by tommyettinger** [comment]
If it is not a Gradle project, it is not officially supported. This is also not the appropriate venue; use the Discord ( https://libgdx.com/community/discord/ ) for help. The issue tracker is used only to report bugs or other problems with libGDX itself, and potentially feature requests for libGDX. I'm closing this because you ignored the issue template. You can ask on the Discord, but people will almost certainly need more detail than you have given here.

**Comment by reymalahay** [comment]
@tommyettinger thanks, will do.
