### ISSUE TITLE
Is libgdx affected by spring's 0day rce vulnerability

### ISSUE THREAD

**Issue by kinkwok117** [libgdx/libgdx#6839]
Please ensure you have given all the following requested information in your report.

#### Issue details
_Please provide the details of your issue_

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue. This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://libgdx.com/wiki/articles/getting-help)_

#### Version of libGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] macOS

**Comment by Frosty-J** [comment]
I don't think so, no. Unaware of any part of it that uses Spring.

**Comment by tommyettinger** [comment]
There's no dependency on spring-core in libGDX or any of its subprojects in this repo. The only code from Spring is a simple String matcher added in 2011 (no reflection or Serializable code to worry about): https://github.com/libgdx/libgdx/commit/86d174264b9360a40eff776bef71a8ea90b2625f . What's more, the SpringShell vulnerability appears to be limited to Java 9 and higher, and libGDX's internals (for completely unrelated reasons) won't currently build on Java 9 or higher due to a JavaDoc issue with the GWT backend. Parts of libGDX will build (if you ignore the docs, you can build with Java 8-15), but the Java version GH Actions uses should be 8. User projects can still depend on Spring on their own, but that's not related to libGDX.
