### ISSUE TITLE
gdx-setup.jar can't download

### ISSUE THREAD

**Issue by yuangu** [libgdx/libgdx#6907]
I download gdx-setup.jar  from https://libgdx.com/wiki/start/project-generation
but download from  https://libgdx-nightlies.s3.eu-central-1.amazonaws.com/libgdx-runnables/gdx-setup.jar  failed.  Network is  unreachable.

**Comment by yuangu** [comment]
Will it be because I am in China? GWF ban? I can't  download it also on my Alicloud。
![image](https://user-images.githubusercontent.com/1897438/175088566-d0d9aa9e-2901-4c94-9e1a-9cda8af3bd9d.png)

**Comment by yuangu** [comment]
here is my local pc.

![image](https://user-images.githubusercontent.com/1897438/175089668-6205024b-d9b2-4695-81c8-05dccbc613c9.png)

**Comment by yuangu** [comment]
I can't create a  discord account. because the discord server  unable to send sms memssage to my phone  (china phone No.) .

**Comment by crykn** [comment]
You could give [JavaCakeGames/gdx-setup-archive](https://github.com/JavaCakeGames/gdx-setup-archive) a try. It contains archived versions of the setup tool.

**Comment by tommyettinger** [comment]
There's also https://github.com/tommyettinger/gdx-liftoff as an alternative. There are some differences between gdx-setup and gdx-liftoff in the generated folders, but not that many. Getting started with libGDX without any access to the libGDX Discord sounds challenging.

**Comment by Frosty-J** [comment]
I suggest we reopen this issue and rename it, as that's like a billion people who can't download gdx-setup. `libgdx-nightlies.s3.eu-central-1.amazonaws.com` is blocked, according to [this tester](http://www.greatfirewallofchina.net/), but so is `github.com`? It's probably not 100% accurate, but it's the best I can do. `libgdx.com` and `github.io` seem to be in the clear. Updating `libgdx.com/assets/downloads/legacy_setup/gdx-setup_latest.jar` (this is very outdated despite its filename!) from 1.10.0 to 1.11.0 would probably be good enough for now, though even 1.11.0 stable is broken out the box for Android projects.

For a while, I was playing Asphalt 9. There seemed to be a lot of Chinese players in that community. I figured most of them illegally used a <strong>\\/</strong>ery PersonaI Ñame (read between the lines - I'd rather not get this issue excluded from regional search results) to access Discord, though I never asked. The libGDX Discord server isn't configured to require a phone number (Discord doesn't like my number either) but I'm all too aware that Discord itself sometimes wants to send a verification text. I don't know how they determine when to do this, but a possible factor is many accounts being created from the same IP address.

In the meantime, I've reuploaded the AWS contents to **https://api.javacakegames.com/libgdx-nightlies-mirror/**, including `gdx-setup.jar` of course. Fortunately, the wall of fire operates on a blacklist basis instead of a whitelist.

I'm not too sure what the actual answer is here. Do you think it would be feasible to have the nightlies uploaded to `libgdx.com` ([libgdx/libgdx.github.io](https://github.com/libgdx/libgdx.github.io/)) instead, @crykn? Or even a `downloads.libgdx.com` which points somewhere other than GitHub Pages? From what I've read, ESNI-enabled TLS 1.3 connections are blocked in China, so maybe also keep an eye on https://www.esnicheck.com/.

**Comment by tommyettinger** [comment]
It doesn't seem like `github.com` is blocked if someone could create an issue here. At some point we just have to accept that some organizations are not in favor of individual productivity, and that people who belong to those organizations (willing or not) pay that price. It isn't the responsibility of the libgdx organization to provide loopholes through any firewall, regardless of size. It would be nice to have a larger user-base, maybe, but support for the Chinese script is still rather poor in libGDX... It might make more sense for users constrained by GFW to use some other framework, like Cocos-2DX, that is more targeted at the China market.

**Comment by Frosty-J** [comment]
Thing is, libGDX doesn't violate the restrictions - we're not exactly comparing presidents to bears here. If the website itself works, we just need to have a non-AWS download available for gdx-setup, and preferably also Hiero etc. Of course, I don't know how well Gradle will fare beyond that point.

Yes, support for non-Latin scripts is poor, but that's not reason enough to not care about entire countries. There are Chinese books on libGDX (dated from when I think it was hosted on libgdx.badlogicgames.com), so clearly this hasn't stopped them.

**Comment by crykn** [comment]
Maybe we could add the gdx-setup.jar files to the [releases](https://github.com/libgdx/libgdx/releases). AFAIK we should also be able to automate this with GitHub Actions.

**Comment by Frosty-J** [comment]
Can you try https://github.com/libgdx/libgdx.github.io/pull/124 and see if that makes any difference?
