### ISSUE TITLE
Intersector.intersectPolygons issue with overlap polygon: polygons must contain at least 3 points.

### ISSUE THREAD

**Issue by rubybrowncoat** [libgdx/libgdx#6986]
#### Issue details
`Intersector.intersectPolygons` gives an unexpected error `polygons must contain at least 3 points.` when it is trying to generate the overlap polygon.

#### Reproduction steps/code
```java
import com.badlogic.gdx.*;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.math.Intersector;
import com.badlogic.gdx.math.Polygon;

public class Barebones extends ApplicationAdapter {
    public void create () {
        Polygon p1 = new Polygon(new float[]{3018.6086f, 304.13184f, 2983.5085f, 263.56183f, 2903.8853f, 253.33517f, 2857.1885f, 283.38184f, 2863.5386f, 328.83517f, 2913.5886f, 357.0285f, 2981.1785f, 353.03516f});
        Polygon p2 = new Polygon(new float[]{2996.0f, 277.0f, 2996.0f, 278.0f, 2997.0f, 278.0f, 2997.0f, 277.0f});

        Polygon intersectionPolygon = new Polygon();
        if (Intersector.intersectPolygons(p1, p2, intersectionPolygon)) {
            System.out.println("Intersected!?");
        }
    }

    public void render () {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        // your code here
    }

    public static void main (String[] args) throws Exception {
        new LwjglApplication(new Barebones());
    }
}
```

#### Version of libGDX and/or relevant dependencies
1.11.0

**Comment by Frosty-J** [comment]
`new Polygon()` creates a polygon with zero vertices, hence the error. According to the javadocs, `intersectionPolygon` can be `null` if it's not needed.

**Comment by rubybrowncoat** [comment]
That's not it, the issue in that example was that my polygons weren't clockwise. Now I have a new example (below) with both polygons verified clockwise (with GeometryUtils.isClockwise) and I'm getting the same issue:

```java
import com.badlogic.gdx.*;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.math.Intersector;
import com.badlogic.gdx.math.Polygon;

public class Barebones extends ApplicationAdapter {
    public void create () {
        Polygon polygonOne = new Polygon(new float[]{3200.1453f, 88.00839f, 3233.9087f, 190.34174f, 3266.2905f, 0.0f});
	Polygon polygonTwo = new Polygon(new float[]{3213.0f, 131.0f, 3214.0f, 131.0f, 3214.0f, 130.0f, 3213.0f, 130.0f});

	Polygon intersectionPolygon = new Polygon();
	if (Intersector.intersectPolygons(polygonOne, polygonTwo, intersectionPolygon)) {
	    System.out.println("Intersected!?");
	}
    }

    public void render () {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        // your code here
    }

    public static void main (String[] args) throws Exception {
        new LwjglApplication(new Barebones());
    }
}
```

**Comment by obigu** [comment]
This is a rounding issue due to floating-point arithmetic (as most `Intersector` related issues). In this case, the intersection area is extremely small.

What happens here can be boiled down to the line `Intersector.intersectLines(s, e, ep1, ep2, ip)` that for the values `s=(3200.1453,88.00839) , e=(3214.0,130.00032) , ep1=(3214.0,130.0) , ep2=(3213.0,130.0)` returns the following intersection point `ip=(3214.0,130.0)` which is one of the points on the line due to float precision. When then it checks this condition later `if (floatArray.size < 2 || floatArray.get(floatArray.size - 2) != ip.x	|| floatArray.get(floatArray.size - 1) != ip.y)` it returns `false` not adding one of the points.

I think we can consider this special case  to be equivalent to 2 polygons with just one single point in common (just touching on one point) which is not considered an intersection. The fix would just require to check before returning if the intersection `Polygon` has at least 3 vertex and, if it does not, return `false` and a null intersection polygon.
