### ISSUE TITLE
Desktop apps crash on Mac when window is moved around

### ISSUE THREAD

**Issue by Trurl101** [libgdx/libgdx#6987]
#### Issue details
Desktop apps crash Mac OS when the window is moved around.

Sometimes it shows the following error: 
`A command encoder is already encoding to this command buffer `

#### Reproduction steps/code
Start a Desktop app on Mac OS and move the window around, after a few seconds the app crashes.

#### Workaround
Remove from build.file: 
`implementation "com.badlogicgames.gdx:gdx-lwjgl3-glfw-awt-macos:$gdxVersion"`
And use -XstartOnFirstThread as VM option

#### Version of libGDX and/or relevant dependencies
1.11.1-SNAPSHOT
Mac OS 12.6/M1 Mac
I could not test it on Intel Mac but found a similar issue here and that happens only on M1:
https://github.com/opentk/opentk/issues/1457

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] macOS

**Comment by tommyettinger** [comment]
I'm just using this code now, for what it's worth. It goes in the DesktopLauncher or Lwjgl3Launcher, before any GLFW calls are made. I'm not using gdx-lwjgl3-glfw-awt-macos at all, since this acts similarly. The glfw_async feature is relatively new in LWJGL3, so requires libGDX 1.11.0 or newer.
```java
		if (SharedLibraryLoader.isMac && Gdx.app == null) {
			org.lwjgl.system.Configuration.GLFW_LIBRARY_NAME.set("glfw_async");
		}
```

**Comment by tommyettinger** [comment]
> I'm just using this code now, for what it's worth. It goes in the DesktopLauncher or Lwjgl3Launcher, before any GLFW calls are made. I'm not using gdx-lwjgl3-glfw-awt-macos at all, since this acts similarly. The glfw_async feature is relatively new in LWJGL3, so requires libGDX 1.11.0 or newer.
> 
> ```java
> 		if (SharedLibraryLoader.isMac && Gdx.app == null) {
> 			org.lwjgl.system.Configuration.GLFW_LIBRARY_NAME.set("glfw_async");
> 		}
> ```

So this approach turns out to still have issues with resizing. I've been recommending using [some form of this gist](https://gist.github.com/tommyettinger/27f622c2b3f3fa90fc03a4613b46a082) for a little while now, and gdx-liftoff includes that gist's code in LWJGL3 modules. On macOS, it automatically adds `-XstartOnFirstThread` so users don't need to mess with that, and doesn't need any extra dependencies or the glfw_async thing. That's all @crykn 's code from Guacamole. The part I added affects Windows, and allows users with non-ASCII usernames (and so non-ASCII paths for their default temp directory) to still run an LWJGL3 game, in at least most cases. Without something like this, a user with Turkish-specific letters in their username wouldn't be able to launch the game at all, and the same is true for some other languages.
