### ISSUE TITLE
Array not shifting element if it's present in array in one-way

### ISSUE THREAD

**Issue by fxgaming** [libgdx/libgdx#6997]
Please ensure you have given all the following requested information in your report.

#### Issue details
Ordered `Array#insert()` not shifting element if it's present in array and specified index is lower than element index

#### Reproduction steps/code
```java
Array<Object> array; //Array filled with random elements
array.insert(0, array.get(array.size - 1)); //moving last element to the end
```
However, `array.insert(array.size - 1, array.get(0));` will work because object have smaller index than we specified in insert

#### Version of libGDX and/or relevant dependencies
1.11.0

#### Please select the affected platforms
- [Not tested] Android
- [Not tested] iOS
- [Not tested] HTML/GWT
- [+] Windows
- [+] Linux
- [Not tested] macOS

**Comment by tommyettinger** [comment]
It seems like you expect insert() to do something different from what it actually does. This isn't that unreasonable, because Array.insert() is totally undocumented, but normally people are familiar with this kind of method from some other code... What insert() does is add an element at a chosen position (index) that can be anywhere inside the Array, as opposed to add() which only adds an element at the end (where index is equal to size). It doesn't move an item that is already inside the Array to another position, other than shifting the later items towards the end of the array.

I ran this code and got the output at the bottom; everything is what I expect.

```java
import com.badlogic.gdx.utils.Array;

public class ArrayInsertTest {
    public static void main(String[] args) {
        Array<String> array;
        array = Array.with("A", "B", "C", "D", "E", "F", "G", "H", "I", "J");
        System.out.println("Original array, A through J:");
        System.out.println(array);
        array.insert(0, array.get(array.size - 1));
        System.out.println("Inserting the last item at the start:");
        System.out.println(array);
        array = Array.with("A", "B", "C", "D", "E", "F", "G", "H", "I", "J");
        array.insert(array.size, array.get(0));
        System.out.println("Inserting the first item at the end:");
        System.out.println(array);
        array = Array.with("A", "B", "C", "D", "E", "F", "G", "H", "I", "J");
        array.insert(0, array.removeIndex(array.size - 1));
        System.out.println("Moving the last item to the start:");
        System.out.println(array);
        array = Array.with("A", "B", "C", "D", "E", "F", "G", "H", "I", "J");
        array.insert(array.size - 1, array.removeIndex(0)); // note that the removeIndex call changes the size!
        System.out.println("Moving the first item to the end:");
        System.out.println(array);
    }
    /*
Original array, A through J:
[A, B, C, D, E, F, G, H, I, J]
Inserting the last item at the start:
[J, A, B, C, D, E, F, G, H, I, J]
Inserting the first item at the end:
[A, B, C, D, E, F, G, H, I, J, A]
Moving the last item to the start:
[J, A, B, C, D, E, F, G, H, I]
Moving the last item to the start:
[B, C, D, E, F, G, H, I, J, A]
     */
}
```

I'm going to close this; you can try again for help on Discord, but I didn't really understand what was wrong last time. The code works as it should, though, so there isn't a bug here.

**Comment by fxgaming** [comment]
understood, sorry
