### ISSUE TITLE
not colliding

### ISSUE THREAD

**Issue by BoodyZedan** [libgdx/libgdx#7022]
so i'm making a pong game but when i try to check if the ball and the paddle collided it says that they did not collide,can any one help?

[this is my code](https://github.com/libgdx/libgdx/files/9938418/message.txt)

**Comment by obigu** [comment]
This is an issue tracker. I can see you've asked on Discord, if you've followed https://libgdx.com/wiki/articles/getting-help there's a high chance you get help there.

**Comment by BoodyZedan** [comment]
i can't find something like my scenario perhaps you have a solution

**Comment by Frosty-J** [comment]
Without any information about `player`, I think it's impossible to say why the collision isn't registering. Probably not an issue with libGDX itself, so not a good fit for GitHub. But while I'm here...

* `RightOrLeft`, `UpOrDown`, `goingLeft`, `goingUp`, `goingDown` and `goingRight` seem redundant as all of their states could be determined by `ballDirection`.
* Instead of direction, you may want to consider storing the velocity, perhaps as a `Vector2` - this would eliminate the need for separating it into `moveBallTopRight()`, `moveBallDownRight()`, `moveBallDownLeft()` and `moveBallDownRight()`. Alternatively, enums are pretty cool.
* Instead of having a `randomDirection` global variable, `direction` could be set to a random direction.
* Consider giving each method a single job to do. e.g. `colidingPlayer1()`<sup>[sic]</sup> should just return whether it is colliding or not instead of controlling ball movement.
* Some parts of this code could be optimised into `switch` statements or `if...else` chains.
* `&` is a bitwise AND operator - if you want a logical AND, it should be `&&`.
* Nice use of `extends`.

I have followed your thread on Discord, so let's continue there.
