### ISSUE TITLE
您好，渲染文本需要用BitmapFont，有个疑惑假假如显示的文本是动态的，那岂不是要制作一个包含所有中文的纹理图片？

### ISSUE THREAD

**Issue by lewic1987** [libgdx/libgdx#7029]
您好，渲染文本需要用BitmapFont，有个疑惑假假如显示的文本是动态的，那岂不是要制作一个包含所有中文的纹理图片？如果还涉及多语言的话，岂不是又要包含所有国家的字符纹理图片？这样实现的话不太现实呢

**Comment by tommyettinger** [comment]
Here is a font you could use that supports a large amount of Chinese characters.

https://github.com/tommyettinger/textratypist/blob/main/knownFonts/Hanazono-standard.png
https://github.com/tommyettinger/textratypist/blob/main/knownFonts/Hanazono-standard.fnt
https://github.com/tommyettinger/textratypist/blob/main/knownFonts/Hanazono-License.txt

Chinese characters can be supported in font files, but usually need the characters to be somewhat small in size, and the texture needs to be fairly large.

Some other scripts are much harder, like Arabic and some Indic scripts, because each character can change its appearance depending on what characters are before and after it. Arabic is probably the least likely language to be supported by libGDX, except by using an image for each phrase you have in a game (probably with all of them in a TextureAtlas).

**Comment by lewic1987** [comment]
非常感谢您的回复，如果按照你说的这样集成的话，那么资源太大了，不太合适，请问没有其他好的支持中文的方式了吗？看网上有说使用FreeType扩展库的，libgdx只能显示英文，如果需要适配其他语言，比如中文，则可以使用freetype，请问FreeType是可以解决中文问题吗？

**Comment by lewic1987** [comment]
我使用了FreeType方式，但是依旧无法显示中文，代码如下图片，使用的字体文件是方正黑体，是支持中文的，但是中文依旧没有显示出来。
<img width="1303" alt="截屏2022-11-16 15 52 06" src="https://user-images.githubusercontent.com/27275977/202119869-6f8b5b2f-32db-44f4-9e7e-f64e02ed7fc2.png">

**Comment by Frosty-J** [comment]
You need to define `parameter.characters` as by default it only includes Latin. Obviously, this isn't very practical, and will require increasing the page size from the default of 1024 (`FreeTypeFontGenerator.setMaxTextureSize()`).

**Comment by lewic1987** [comment]
OK, it’s ok, thank you very much, when do you need to set FreeTypeFontGenerator.setMaxTextureSize()? Is it related to the length of the displayed text content?
In addition, what is the font.getData().breakChars property used for? There is no problem in displaying Chinese without setting it.

<img width="1309" alt="截屏2022-11-16 16 42 24" src="https://user-images.githubusercontent.com/27275977/202131319-238fda88-ffe6-4019-836e-61e50e29d967.png">

**Comment by lewic1987** [comment]
@Frosty-J Got it, thank you very much for your answer

**Comment by shumaosi** [comment]
@lewic1987 你好，渲染图片模糊有锯齿，你有遇到这个问题吗

**Comment by mgsx-dev** [comment]
@shumaosi please stop spamming and move to the libgdx server, thank you.
