### ISSUE TITLE
isKeyJustPressed & isButtonJustPressed does not trigger consistently at '1.11.0' with gdx-lwjgl3-glfw-awt-macos

### ISSUE THREAD

**Issue by damn** [libgdx/libgdx#7059]
Not using the gdx-lwjgl3-glfw-awt library and using JVM opts "-XstartOnFirstThread" fixes the issue.
- [ X] macOS

**Comment by tommyettinger** [comment]
It seems like -XstartOnFirstThread is the only really reliable way to have LWJGL3 work on MacOS. The [StartOnFirstThreadHelper](https://github.com/crykn/guacamole/blob/master/gdx-desktop/src/main/java/de/damios/guacamole/gdx/StartOnFirstThreadHelper.java) class from Guacamole may make distributing executable JARs easier -- just start your main() method with `if (StartOnFirstThreadHelper.startNewJvmIfRequired()) return;` and that file takes care of restarting with the necessary argument if it isn't already there. Distributing with Packr or jpackage means users don't need a JDK installed (which can be tricky on MacOS, because of x64 and ARM64 both being used), and both of those can specify -XstartOnFirstThread as an argument when launched via the .app . The need for -XstartOnFirstThread is mostly an issue during development, when JARs are being sent around but not yet packaged with JREs for distribution. Hopefully the class from Guacamole (which really just needs that file, not the library) can help.

**Comment by damn** [comment]
I am planning to create a debug UI/editor UI as a second window on top / besides my libgdx app. 

So I would be interested to fix these issues also. Where would I have to look ?

**Comment by crykn** [comment]
I don't think this is as easy to fix as you'd like it to be, but the best place to start looking is the original PR that introduced the extension (https://github.com/libgdx/libgdx/pull/6772). 

Apart from that, you could try removing the `gdx-lwjgl3-glfw-awt-macos` extension and doing this at the beginning of your `DesktopLauncher` instead:
```java
if (SharedLibraryLoader.isMac && Gdx.app == null) {
    org.lwjgl.system.Configuration.GLFW_LIBRARY_NAME.set("glfw_async");
}
```

This should have the same effect as our extension, but is offered by LWJGL 3 itself. So they might be able to help you figure out what is causing this.
