### ISSUE TITLE
UI with HTML/CSS/JS (Chromium? WebKit?)

### ISSUE THREAD

**Issue by Osiris-Team** [libgdx/libgdx#7088]
I want to create and render my GUI with HTML on top of my game.
I thought the JCEF (Java Chromium Embedded Framework) would be the right choice for this,
the problem however is its [issues with offscreen rendering](https://bitbucket.org/chromiumembedded/java-cef/issues/434/load-events-not-getting-triggered-in).

**Comment by prineside** [comment]
I've tried to use Chromium as a game's UI once (not LibGDX - directly tied into game's C++ codebase) and this approach simply does not work. It is too heavy, too overcomplicated and will result in lots of lags / delays each time your game will try to communicate with Chromium (because it usually runs on a separate thread and synchronization is expensive). You'll probably have to write JS scripts for it to behave properly or reduce lags, which is error prone and, honestly, is an overkill.

Don't go with Chromium for your UI. You can still try to use it as an in-game browser but it may be better to simply use Gdx.net.openURI().

If you want to use something like HTML for your UI, take a look at [gdx-lml](https://github.com/czyzby/gdx-lml)

**Comment by Osiris-Team** [comment]
@prineside What if the application was based on chromium instead.
So that my app is rendered inside the orginal chromium thread and render function.
This way there wouldnt be a performance bottleneck.

**Comment by prineside** [comment]
@Osiris-Team in this case, why would you use LibGDX? :) There are some frameworls / game engines that use HTML/JS for that and allow to create a "native" games for a different platforms (they basically make a wrapper for an embedded engine like Chromium or use platform's default WebView)

**Comment by Osiris-Team** [comment]
Yeah you are right.

**Comment by Osiris-Team** [comment]
@prineside The problem is that I can't find any java based engine for that.

**Comment by Osiris-Team** [comment]
So for anyone interested I fixed this by developing a Deskop/Mobile Java Framework using JS/HTML/CSS technologies,
including the FlexBox, which makes it pretty easy to create simple and complex layouts within seconds.
https://github.com/Osiris-Team/Desku
