### ISSUE TITLE
IntelliJ IDEA cannot find gdx-platform-1.11.0-natives-desktop.jar

### ISSUE THREAD

**Issue by rayin19** [libgdx/libgdx#7151]
#### Issue details
I created a new program with libGDX installer (fresh download from the website) on Windows 11 and when I open the project in IntelliJ IDEA I get the following error:

```
Could not find gdx-platform-1.11.0-natives-desktop.jar (com.badlogicgames.gdx:gdx-platform:1.11.0).
Searched in the following locations:
    file:/C:/Users/Asus/.m2/repository/com/badlogicgames/gdx/gdx-platform/1.11.0/gdx-platform-1.11.0-natives-desktop.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

#### Reproduction steps/code
 - I'm using windows 11
 - Downloaded the libGDX executable from [Project Generation](https://libgdx.com/wiki/start/project-generation) 
 - Created a new project, with the only changes to Title of the project and Location of the project to be saved.
 - Tried to open the project in IntelliJ IDEA and got the error.

#### Version of libGDX and/or relevant dependencies
Version 1.11.0 . Also I tried making gxdVersion = '1.9.13' and it works!

#### Stacktrace
```java
Could not find gdx-platform-1.11.0-natives-desktop.jar (com.badlogicgames.gdx:gdx-platform:1.11.0).
Searched in the following locations:
    file:/C:/Users/Asus/.m2/repository/com/badlogicgames/gdx/gdx-platform/1.11.0/gdx-platform-1.11.0-natives-desktop.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
This happens to me all the time. It is some Gradle bug where if it found some "part of a dependency" in mavenLocal (which is that .m2 folder in your home directory), but doesn't find another part requested elsewhere, it just dies and doesn't try to locate the rest of the dependency.

The simplest solution is to delete the line `mavenLocal()` from your build.gradle file(s), and to update the project by refresh/reimport/reload/sync/whatever IDEA calls it (it should be a popup in the upper right that suggests to do this). There are a few places `mavenLocal()` can occur, and it is safe to comment out or delete all of them in most cases. You only actually need `mavenLocal()` at all if you are building and installing customized versions of libraries; even then, many libraries use [JitPack](https://jitpack.io/) and don't need mavenLocal() then either.

The other solution is to just delete part or all of the `.m2/repository` directory, such as `C:/Users/Asus/.m2/repository/com/badlogicgames/gdx/gdx-platform/1.11.0/`, and reload/sync/reimport/whatever your project that wasn't building. That will make Gradle download all required gdx-platform dependencies with version 1.11.0 again. I don't like this approach as much because it only downloads the dependencies your current project needs, not necessarily what other projects might need... and then other projects could have the same issue in the first place. Still, if you have self-installed libraries, like modified versions of libGDX, this might work best.

**Comment by rayin19** [comment]
That worked. Thanks!!
