### ISSUE TITLE
TextureAtlas loader and encoding of .atlas files

### ISSUE THREAD

**Issue by SomeTroglodyte** [libgdx/libgdx#7155]
#### Issue details
The loader for .atlas files does not specify a Charset or otherwise control encoding. A modder for Unciv managed to trip this - [#9468](https://github.com/yairm210/Unciv/issues/9468) - he's got an UTF-8 encoded atlas file using many codepoints outside iso-8859, and on one user's desktop it misunderstands the encoding - meaning that JVM isn't defaulting to UTF-8. In that issue the system re-interprets an em-dash as chinese characters before going back to disk for the texture png. On _my_ Linux it works as is.

The critical point is here: https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/TextureAtlas.java#L362

I'd suggest adding a `Charset.forName("UTF-8")` there or maybe a `StandardCharsets.UTF_8`, as atlas files are supposed to be cross- individual os- compatible, so enforcing a common encoding independent of the JVM settings makes sense.

The luxury variant would add overloads allowing to explicitly specify the encoding, which would include the ability to revert to `Charset.defaultCharset()`...

The minimal variant would be to ensure documentation clearly states that atlas files using path names outside ascii are not supported for cross-platform transportability, and inform tool authors about it (I admit I'm lazy, https://libgdx.com/wiki/tools/texture-packer doesn't contain the words "encoding", "UTF" or "ascii", so I assume that isn't already so).

As always, this is meant as food for thought and by no means as urgent call to action :smile_cat: 

#### Reproduction steps/code
sorry, see linked issue above, it's admittedly quite outlandish

#### Version of libGDX and/or relevant dependencies
1.11.0

#### Stacktrace
see Unciv issue

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
This bit me as well when loading an atlas with emoji in its names! For an immediate fix, you can copy [this block of code from TextraTypist](https://github.com/tommyettinger/textratypist/blob/main/src/main/java/com/github/tommyettinger/textra/KnownFonts.java#L1639C8-L1878), which is just a barely-modified atlas loader from libGDX. I think the existing code should work without needing any changes if you run on Java 19 or higher, which defaults to UTF-8. That said, most users probably aren't on 19, and shouldn't use 20 at the moment.

**Comment by NathanSweet** [comment]
TextureAtlas could at least use FileHandler `reader` so outside code can work around it. If you control the Java invocation, you could probably add CLI parameters to specify UTF-8 as the default.

I'm fine with defaulting to UTF-8 rather than the system charset. We should probably also take a charset as an optional argument.

**Comment by HydrolienF** [comment]
> This bit me as well when loading an atlas with emoji in its names! For an immediate fix, you can copy [this block of code from TextraTypist](https://github.com/tommyettinger/textratypist/blob/main/src/main/java/com/github/tommyettinger/textra/KnownFonts.java#L1639C8-L1878), which is just a barely-modified atlas loader from libGDX. I think the existing code should work without needing any changes if you run on Java 19 or higher, which defaults to UTF-8. That said, most users probably aren't on 19, and shouldn't use 20 at the moment.

Java 18 use utf-8 as default to.

**Comment by HydrolienF** [comment]
With Java 17 or less you can launch with `java -Dfile.encoding=UTF-8 … com.x.Main` as NathanSweet sugest.

**Comment by NathanSweet** [comment]
@SomeTroglodyte Extend FileHandle (or FileHandleStream, which is intended for this kind of thing) and override `reader` to use UTF-8 instead of the platform charset.

**Comment by tommyettinger** [comment]
Yeah... I'm going to keep using my only-slightly-less-cumbersome custom atlas data reader in TextraTypist... Extending FileHandle to do this is not a good approach IMO. Especially since much of the rest of libGDX implicitly discourages inheriting from libGDX classes through the use of package-private variables.

**Comment by tommyettinger** [comment]
> For anybody happening on this - in kotlin you can do:
> 
> ```kotlin
>     // Old, uses system charset - could be microcarp-1252 (or worse - GBK or other corpses never meant to live) ruining things
>     val myAtlas = TextureAtlas(fileHandle)
> 
>     // New, uses reliable charset
>     val myAtlas = TextureAtlas(object : FileHandle(fileHandle.file(), fileHandle.type()) {
>         override fun reader(bufferSize: Int): BufferedReader? {
>             return super.reader(bufferSize, "UTF-8")
>         }
>     })
> ```
> 
> ... you must override **_this specific overload_** of `reader`, the other three can be ignored.

Note that this will only work if file() works for the fileHandle you pass. If this was ported to Java, a different approach would have to be used when targeting GWT (since it doesn't have FileHandle.file() ), and I have no idea how GWT handles platform encoding. I updated [my alternative way of loading an atlas in TextraTypist](https://github.com/tommyettinger/textratypist/blob/c32288596d943755491dd94c259ff071204f4def/src/main/java/com/github/tommyettinger/textra/KnownFonts.java#L1740-L1979), which still only makes one significant change (it specifies an encoding where it calls `FileHandle.reader()`. Reading this issue thread made me realize `loadUnicodeAtlas()` is still needed on libGDX 1.12.1. If the player of a game specifies any file encoding other than UTF-8 (such as by using `-Dfile.encoding=ISO-8859-1`), then unless FileHandle is modified, TextureAtlas won't correctly load an atlas that uses Unicode for the names of images. This is true at least when running with Java 17, and I think is still true for higher versions. Using `loadUnicodeAtlas()` works even when the file encoding is specified to something unusual, on any version.

**Comment by Frosty-J** [comment]
All he did was mention it. Some people like an interactive web, and the efficiency we have in Chromium-based browsers isn't as bad compared to Java as you might expect, even if improvements could be made by moving away from JS. See the libGDX jams as evidence of this. MS Office doesn't use a huge amount of RAM (with typical documents) - maybe you're thinking of something else.
