### ISSUE TITLE
Bullet classes starting with lowercase do not autocomplete.

### ISSUE THREAD

**Issue by madmenyo** [libgdx/libgdx#7186]
#### Issue details
Bullet Classes that start with lowercase like btCollisionShape and btRigidBody do not autocomplete. The ones that start with a capital do autocomplete. So a probable fix is to change them to start with a capital letter.

#### Reproduction steps/code
Just add bullet to the core dependacy or tick it using the setup tool or lift-off.

I'm using IntelliJ IDEA, not sure about other IDE's.

#### Version of libGDX and/or relevant dependencies
1.11.0

#### Please select the affected platforms
- [x] Core

**Comment by JamesTKhan** [comment]
I don't think changing the names of all those classes is the right solution. That would break every single project using Bullet. From what I understand the class names were preserved from the C++ Bullet code.

I do have the same behavior in IntelliJ. What I am not sure of, is if this is an issue in IntelliJ or something else. I don't think this is a libGDX problem because I created a custom class called `testClass` and IntelliJ code completion does not pick that up either when I start typing the class name in. I can't find any IntelliJ setting I can change to fix it. I wonder if this is a bug in IntelliJ or something else.

**Comment by madmenyo** [comment]
> I don't think changing the names of all those classes is the right solution. That would break every single project using Bullet. From what I understand the class names were preserved from the C++ Bullet code.

Oh yeah right :).

I found something this morning on my phone about the auto complete settings in InelliJ, it has a option "Case Sensitive Completion". I couldn't test since I was on phone and now at office. But this could be it I think. It still is weird since it does autocomplete classes I create myself starting with lowercase.

**Comment by obigu** [comment]
This is not libGDX related, it should be possible to fix it within the IDE.
