### ISSUE TITLE
Project generator times out trying to download Gradle and generates broken project

### ISSUE THREAD

**Issue by AirborneDetergent** [libgdx/libgdx#7208]
#### Issue details
When I tried to make a project supporting desktop with the Tools, Box2d, and Box2dlights extensions, it gave me an error upon generation. If I try to open the project in IntelliJ anyway, it downloads gradle-7.5.1-bin.zip, then gives me an error that just says "Read timed out."
![image](https://github.com/libgdx/libgdx/assets/78456403/48fb7741-b4c0-48cb-96a7-e7d7e3bff149)
The project also appears to be mostly empty.
![image](https://github.com/libgdx/libgdx/assets/78456403/0ee4d4e2-ea0d-4783-b247-f2318dc43140)

#### Reproduction steps/code
No SSCCE because I can't actually get to that point. Simply configure the generator as shown in the screenshot and try to generate a project.
![image](https://github.com/libgdx/libgdx/assets/78456403/4b889ad7-9e1d-4d1c-aa92-3d79610b0268)

#### Version of libGDX and/or relevant dependencies
1.12.0

#### Stacktrace
```java
Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-7.5.1-bin.zip failed: timeout
	at org.gradle.wrapper.Download.downloadInternal(Download.java:122)
	at org.gradle.wrapper.Download.download(Download.java:80)
	at org.gradle.wrapper.Install$1.call(Install.java:83)
	at org.gradle.wrapper.Install$1.call(Install.java:63)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:63)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:461)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1509)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1476)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1065)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3525)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3518)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:106)
	... 7 more
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
Might be a temporary network outage. I just tried downloading gdx-setup and making a new project with the same extensions (I also had all the platforms checked), and it a) initially saw that I had Gradle 7.5.1 and didn't download anything, so b) I deleted my local Gradle 7.5.1 wrapper dist and installation for that version, then c) I ran gdx-setup again and it did download 7.5.1, a bit slowly but it finished.

You can, of course, always try [gdx-liftoff](https://github.com/tommyettinger/gdx-liftoff), which doesn't run any Gradle tasks during setup, and uses the current Gradle release (8.2.1 at the time of writing).

**Comment by AirborneDetergent** [comment]
@tommyettinger The project your utility generated was not empty like the other one, but I still got the same "Read timed out" error after it downloaded gradle 8.2.1. Deleting the contents of my `dists` folder and restarting IntelliJ had no effect.

**Comment by tommyettinger** [comment]
It doesn't seem to be on gradle.org's end: https://status.gradle.com/ Could there be antivirus blocking the Gradle wrapper from downloading the Gradle distribution? The likely files that could be quarantined or otherwise prevented from downloading would be `gradlew.bat` (for Windows), `gradlew` (for non-Windows), and `gradle/wrapper/gradle-wrapper.jar`.

**Comment by AirborneDetergent** [comment]
My Windows Security protection history shows no relevant logs. I'm able to download the file pretty much instantly by copying the URL into my browser. Even though I wasn't having this problem until I tried to use LibGDX, it seems to have spread to IntelliJ as a whole. Upon creating a new Gradle project through IntelliJ (without LibGDX), I see this error:
![image](https://github.com/libgdx/libgdx/assets/78456403/d0d7e5e6-9fad-4638-8bf5-64e63b17b5f4)

**Comment by tommyettinger** [comment]
I've never seen this before and I hope it won't happen to me...

... OK, I just saw your latest message. Weirdly, `curl -v https://downloads.gradle.org/distributions/gradle-7.5.1-bin.zip --output gradle-7.5.1-bin.zip` successfully downloads the file, but the services.gradle.org link fails with curl. I'm wondering if Gradle might be rolling out a change to their URLs...?

**Comment by AirborneDetergent** [comment]
@tommyettinger I tried changing the URL in `gradle-wrapper.properties` and invalidating all caches to no avail. Is Gradle just.... bad?

**Comment by tommyettinger** [comment]
It seems like maybe something, somewhere in the parts of Gradle that are cached, something became damaged or corrupted. No idea what. My suggestion at this point would be to first restart the computer and see if it works after the restart, since some environment variables are a pain to change without a restart. If it doesn't work as it should, either a) kill all Java processes that are open, such as the Gradle daemon process, or b) restart again. Once all Java processes are killed or haven't started yet, you can more-freely fiddle with Gradle. There's a lot of files that are stored in (in your case) `C:\Users\miner\.gradle\` ; I think you should *rename that folder* or move it somewhere else. I don't think you should delete it just yet, but if something's badly corrupted and affects non-libGDX projects, the problem is probably there. Then, you can try launching a Gradle build from the command line, to rule out IDEA problems: from the project folder (the outermost folder still in your project; it should have a file in it called `gradlew.bat`), the gdx-setup project uses `gradlew desktop:run`, and the gdx-liftoff one uses `gradlew lwjgl3:run` . If it works, it will download Gradle into a completely fresh `.gradle` folder (may take a minute), build the sample project, and run it once it's built. For gdx-setup, you'll see a red screen with a yellow smiley face; for gdx-liftoff, it depends on which template you picked, if any (I think the default shows the libGDX logo).

**Comment by AirborneDetergent** [comment]
@tommyettinger That doesn't appear to have had any effect. I still get the same error. It did create another gradle folder with two files in `gradle/wrapper/dists/gradle-8.2.1-bin/at9gpsch2ri3eon3x9pgos16j` named `gradle-8.2.1-bin.zip.lck` and `gradle-8.2.1-bin.zip.part`

**Comment by tommyettinger** [comment]
This is just crazy... you can (maybe) manually install Gradle and avoid using the wrappers until this situation gets figured out. I'd go with 8.2.1 and the Liftoff project, because it's a complete project and should be runnable if you have Gradle installed. I haven't needed to manually install any Gradle in years; I always use the wrapper, but here the wrapper seems to be not downloadable at all for some reason, while the manual download seems to just work. The main difference between using the wrapper and using a manual installation is `gradlew` vs. `gradle` . If the wrappers are causing all this headache, you can rename `gradlew.bat` to something like `migraine.bat` and then IDEA shouldn't try to use the wrappers (in theory. It might need the wrappers deleted or moved out of the folder). You might need to give IDEA some location info about your manual/global Gradle installation so it uses it.

**Comment by AirborneDetergent** [comment]
Nope, still tries to download it, even with the gradlew files deleted. I'm honestly about ready to give up. The only thing I can think of trying at this point is nuking my entire java and intellij installation and restarting everything from scratch, but I'm not entirely sure how to do that correctly. I'm going to take a break and then try that and will leave a final update here as to whether or not I was able solve it. If not, I guess I just can't use Java anymore lol.

**Comment by tommyettinger** [comment]
There's Maven as an alternative to Gradle, if you aren't targeting Android. I'm pinging @terefang in the hopes that he'll notice, since he uses Maven regularly for libGDX projects. I have some Maven projects, but they're all libraries at this point... Maybe I have one or two desktop apps? I'll edit this with links as I find them.

**Comment by AirborneDetergent** [comment]
I may target Android in the future, so that's not really a solution for me. Right now, I'm just trying to learn how to use LibGDX in the first place by making a simple Desktop game. Amazingly, uninstalling and reinstalling Java and IntelliJ had no effect whatsoever. I'm going to open an issue on the Gradle repository and close this one because the issue is clearly not with LibGDX and the people over there may have a better idea of what's going on.

**Comment by AirborneDetergent** [comment]
@tommyettinger Thank you for your kindness, patience, and generosity with your time. I appreciate all of the help you have provided. The issue has been moved here: https://github.com/gradle/gradle/issues/26094
