### ISSUE TITLE
addMesh not working properly

### ISSUE THREAD

**Issue by Diljeet** [libgdx/libgdx#7216]
Please ensure you have given all the following requested information in your report.

#### Issue details
ModelBatch.addMesh (float[] vertices, short[] indices) is not working properly
its not drawing the vertices
i found the solution and used addMesh (float[] vertices, short[] indices, int indexOffset, int numIndices)
the issue happened when i updated from 1.11.0 to 1.12.0

#### Reproduction steps/code
just use the method addMesh (float[] vertices, short[] indices) in old version and then in new version

#### Please select the affected platforms
- [ ] Android, currently i can only confirm this on Android as my app is android only

**Comment by tommyettinger** [comment]
I can absolutely see the error, there's an order-of-operations/bitwise mistake in the two-argument addMesh that isn't present in the four-argument: https://github.com/libgdx/libgdx/blob/ed811688c42a3eeb32427e56b47988e7ac4a6539/gdx/src/com/badlogic/gdx/graphics/g3d/utils/MeshBuilder.java#L798

I think all it needs is some parentheses around the `indices[i] & 0xFFFF`, since without that, the addition applies to 0xFFFF, and makes it an invalid mask.

**Comment by Diljeet** [comment]
Thanks for fixing it, i will check it on the next released version
