### ISSUE TITLE
2.5D

### ISSUE THREAD

**Issue by deft663** [libgdx/libgdx#7221]
hello there
  i don't know how much support  is currently available for 2.5D,as instroduced here  https://en.m.wikipedia.org/wiki/2.5D

**Comment by tommyettinger** [comment]
It's just fine. Look at [the showcase](https://libgdx.com/showcase/) on the main site. [Space Haven](https://store.steampowered.com/app/979110/Space_Haven/) uses libGDX, it is 2.5D. So do I think several others on that page. Not on that page is [Crawl Tactics](https://store.steampowered.com/app/1290750/Crawl_Tactics/), which is a good example of 2.5D. A common thread between 2.5D implementations is that devs realize they can implement the underlying physics logic in 3D and only display it to look like 2D; at least some of the linked games did use 3D positions for lighting and collisions.

For future questions, there's the [Discord](https://libgdx.com/community/discord/), since this page on GitHub is for tracking bugs and issues with libGDX.

**Comment by deft663** [comment]
thank you for your answer
