### ISSUE TITLE
Timer does not respect pause when using repeat

### ISSUE THREAD

**Issue by dkoding** [libgdx/libgdx#7281]
#### Issue details
When pausing a Timer, it still unexpectedly retriggers, not respecting the paused Timer.

#### Reproduction steps/code
I have code like this:

```
Timer.schedule(new Timer.Task() {
                @Override
                public void run() {
                    ...
                }
            }, 0f, .1f, 10);
```

In my main loop:

```
elapsedPauseMillis += (long) (deltaTime * 1000d);
        elapsedPauseMillisRemain += deltaTime * 1000000 % 1000;
        if (elapsedPauseMillisRemain > 1000) {
            elapsedPauseMillis += 1;
            elapsedPauseMillisRemain -= 1000;
            Timer.instance().delay(1);
        }

```

Even when the Timer.instance() is delayed, it does not prevent the timer task to repeat.

#### Version of libGDX and/or relevant dependencies
LibGDX 1.11.0

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by crykn** [comment]
`Timer#stop` does indeed not work as I'd expect it to. While it blocks the current task from completing (and thus from repeating as well), the time passed still counts toward its delay. To test this, just start the example below, immediately press `S` to stop the timer, count to 5 and then press `S` again to start the timer. 

Expectation: the task is executed 10 seconds later.
Reality: the timer is executed 5 seconds later, because the 5 seconds while the timer was stopped were still applied towards the task's delay.

However, pausing via `Timer#delay` works fine. To test this, start the example, press `P` to pause, count to 5 and then unpause via `P` again. As expected, the task is executed 10 seconds later.

```java
public class Issue7281Test extends ApplicationAdapter {
	private int i = 0;
	private boolean timerStopped = false;
	private boolean timerPaused = false;
	private float timePassed;

	public static void main (String[] argv) {
		Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
		config.setWindowedMode(1024, 720);
		new Lwjgl3Application(new Issue7281Test(), config);
	}

	@Override
	public void create () {
		Timer.schedule(new Timer.Task() {
			@Override
			public void run () {
				Gdx.app.log(String.valueOf(timePassed), "Task " + ++i + " completed!");
			}
		}, 10F, 10F, 9);
	}

	@Override
	public void render () {
		ScreenUtils.clear(timerPaused ? Color.GRAY : (timerStopped ? Color.RED : Color.GREEN));
		timePassed += Gdx.graphics.getDeltaTime();

		if(timerPaused)
			Timer.instance().delay(Math.round(Gdx.graphics.getDeltaTime() * 1000));

		if(Gdx.input.isKeyJustPressed(Input.Keys.S)) { // Start/stop
			if(timerStopped)
				Timer.instance().start();
			 else
				Timer.instance().stop();
			timerStopped = !timerStopped;
		} else if (Gdx.input.isKeyJustPressed(Input.Keys.P)) { // Pause
			timerPaused = !timerPaused;
		} else if (Gdx.input.isKeyJustPressed(Input.Keys.D)) { // Delay
			Timer.instance().delay(2000);
		}
	}
}
```

**Comment by NathanSweet** [comment]
@dkoding mentions pausing a timer (which only has start/stop, not pause) and gives unexecutable code (which doesn't call start/stop), so there's nothing to be done there.

@crykn thanks for the executable repro! I'll make a PR.
