### ISSUE TITLE
Latest Gdx-setup enables proguard minify which breaks skin files 

### ISSUE THREAD

**Issue by b3nk4n** [libgdx/libgdx#7331]
#### Issue details
After publishing my game from 1.9.11 to 1.12.1, I noticed that the app crashed at startup after installing the Android app from the Google Play Store. However, no such crash happened when launching the app via Android Studio.
After some digging into the problem, it turned out it was because I also took the changes from the latest `gdx-setup` tool, which now enables minification by default:
https://github.com/libgdx/libgdx/blob/7d1a149305cc65cfa2a93b1077a1b4e2af30b3e0/extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/android/build.gradle#L29-L30

However, with the current setup of the generated `proguard-rules.pro` file, this is breaking my `skin.json` skin files at runtime. As it generates this file:
```
-verbose

-dontwarn com.badlogic.gdx.backends.android.AndroidFragmentApplication

# Required if using Gdx-Controllers extension
-keep class com.badlogic.gdx.controllers.android.AndroidControllers

# Required if using Box2D extension
-keepclassmembers class com.badlogic.gdx.physics.box2d.World {
   boolean contactFilter(long, long);
   void    beginContact(long);
   void    endContact(long);
   void    preSolve(long, long);
   void    postSolve(long, long);
   boolean reportFixture(long);
   float   reportRayFixture(long, float, float, float, float, float);
}
```
Which causes that package/class names are now minified, and the `skin.json` files are invalid when using `release` mode.
And because this minification is not applied in debug mode, it is easy to miss while development. And e.g. requires the use of `bundletool` to install the apk/aab file manually, to see this problem before publishing it.

#### Reproduction steps/code
1. Generate a new Android project using the `gdx-setup` tool.
2. Load e.g. the following skin file:

```json
{
  "com.badlogic.gdx.graphics.Color": {
    "white": {
      "a": 1,
      "b": 1,
      "g": 1,
      "r": 1
    },
    "black": {
      "a": 1,
      "b": 0,
      "g": 0,
      "r": 0
    }
  }
}
```

3. Create a signed AAB file.
4. Install the app to your phone with minifacation enabled (e.g. using `bundletool` of the actual `.aab`/`.apk` file to upload), or the app built in `release` mode.
5. See the `ClassNotFoundException for com.badlogic.gdx.graphics.Color`, which is because it got minified.

#### Version of libGDX and/or relevant dependencies
_1.12.1_

#### Stacktrace
```java
com.badlogic.gdx.utils.ax: Error reading file: jsonSkin.json
...
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.graphics.g2d.BitmapFont
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

## Possible Solution:

As described [here](https://stackoverflow.com/questions/35366302/libgdx-fatal-exception-loading-a-skin-json-file), what works is to disable minification for libgdx classes:

```
-keep class com.badlogic.**{
   **[] $VALUES;
    *;
}
```
(or multiple similar less general rules for `com.badlogic.gdx.graphics.*`, `com.badlogic.gdx.scenes.scene2d.ui.*`, ...)

Or list classes individually that can be used in skin.json files:
```
- keep class com.badlogic.gdx.graphics.Color
- keep class com.badlogic.gdx.graphics.g2d.BitmapFont
- keep class com.badlogic.gdx.scenes.scene2d.ui.TextButton
...
```

Or at least update the [Skin docs](https://libgdx.com/wiki/graphics/2d/scene2d/skin) that the `proguard-rules.pro` needs to be touched if `minifyEnabled true` is used. 🙂 But I leave that fully up to you what is the best solution here.

**Comment by tommyettinger** [comment]
Minimization should generally be enabled when doing an Android release, unless you actually want larger APK/AAB sizes and effortlessly-dissected apps. ProGuard/R8 is invariably going to require some configuration when doing that; that's part of Android app development. There's a way to include R8 configuration in a library so apps use that configuration when depending on the library, but that config only works for R8 at the moment, not desktop ProGuard. This R8 configuration, which goes in the `META-INF/proguard` directory, could be added to libGDX or the Android backend part of it.

I would also be remiss if I didn't mention that [gdx-liftoff](https://github.com/tommyettinger/gdx-liftoff) has partly solved this already, and includes these lines in Android's `proguard-rules.pro`:

```
# You will need the next three lines if you use scene2d for UI or gameplay
# If you don't use scene2d at all, you can remove or comment out the next line
-keep public class com.badlogic.gdx.scenes.scene2d.** { *; }
# You will need the next two lines if you use BitmapFont or any scene2d.ui text
-keep public class com.badlogic.gdx.graphics.g2d.BitmapFont { *; }
# You will probably need this line in most cases
-keep public class com.badlogic.gdx.graphics.Color { *; }
```

Any libraries you depend on may have their own needs for reflection and may need more classes to be kept as-is. It is really hard, if not outright impossible, to make a general-purpose ProGuard or R8 file that works at the project setup stage, since libraries can be (and often are) added after that stage. If more libraries start using the R8 META-INF configuration, that might help the problem, but I believe this feature was added last year and wasn't usable for much of that year (because Gradle 8 had so many incompatibilities that needed resolving, such as with AGP).

I'd advise against disabling R8 for all of libGDX, but you could do that, I guess. It wouldn't help with any other dependencies.

**Comment by mgsx-dev** [comment]
I think that minify/obfuscate by default is a bad idea : 
* some third party libs requires introspection / JSON serialisation and such.
* Third party libs being open source there is no reason to obfuscate them anyway.
* Even some game specific packages shouldn't be obfuscated (game state that you want to load/save)

So i think the best solution would be to provide a proguard template (commented by default) that users could enabled if they think it's good for their game. This template could illustrate how to do it properly : 
* only obfuscate game specific root package
* and an example of exclusion of a game specific sub package (eg. com.my.gdxgame.state)

**Comment by tommyettinger** [comment]
The setup app(s) could include some simple configuration for Android to use in the generated project, and it could match what mgsx-dev suggested about obfuscating the game code by default but not obfuscating things we know need reflection to work, like scene2d.ui Skin code. Commented and documented sections that show what it would look like to make R8 keep your reflection-dependent code the same, that would be great. I'm not sure that a large library like libGDX should have minimization skipped for all of it; certainly we want dead code elimination to run on libGDX when it is a dependency, and I'm not sure what stage of R8 that falls under. Any extra steps of obfuscation can certainly be skipped for open source libraries... Minimization might still cause trouble, but for large libraries it could really help the output size.

**Comment by b3nk4n** [comment]
Thanks for your answers above already. I appreciate it!

> I agree we can add some more commented blocks for Scene2D to avoid issues with Skins (or have them enabled by default and add a comment that they can be commented out if Skins not used).

I would be fine with that. And maybe a note in the [Skin docs](https://libgdx.com/wiki/graphics/2d/scene2d/skin) would not harm. My concern is mainly **"first user experience"**. A beginner programmer might not really know about ProGuard. And honestly very likely also not care too much about an as small as possible. And I'm sure especially many beginner developers will only dev/test their apps in DEBUG mode, and then release it to the store. And in that scenario (which also happened to my yesterday because of laziness 😇 ) it might be frustrating to see the app crash in production. While it worked perfectly fine during development.

But anyways, I think you guys can judge that better.

**Comment by Frosty-J** [comment]
Classes commonly accessed via reflection in skins could do with being excluded in the ProGuard rules. This issue comes up relatively frequently in the Android channel on Discord.

At least now you've experienced the importance of testing with the release version. If your app has a large userbase, you may wish to utilise Google Play's test tracks, and release updates to production as a staged rollout to reduce the number of users who may experience a bad update before you catch it.
