### ISSUE TITLE
Can't use Lambda in newly created libgdx project (Jdk ver. set to 1_8/17) in Android Studio

### ISSUE THREAD

**Issue by its-yuu** [libgdx/libgdx#7333]
Libgdx version 1.12.1
im using gradle ver.8 , liberika nik jdk 17..
im using AndroidStudio version Hedgehog

#### Issue details
i've run a test and create new project in android studio itself and it works fine with lambda but when i try to use newly created project in libgdx i cant use lambda even if i set the the java version to 1_8 and 17.

i tried to put 
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8     (and tried 17)
        targetCompatibility JavaVersion.VERSION_1_8
    }
and tried to edit in module settings but didnt success.
any help will much appreciated thanks.

affected platforms
- [ ] Android

**Comment by tommyettinger** [comment]
This is an issue tracker for bugs with libGDX, and this doesn't look like a bug with libGDX. This seems like a configuration issue with how you're using Android Studio. For help using libGDX and related tools we have the Discord community server: https://libgdx.com/community/discord/

This is probably something quick you can change in the module settings, but it makes much more sense to do this kind of debugging with immediate feedback (such as on Discord) than in stops-and-starts over GitHub Issues. Screenshots would also really help.

The initial projects created by gdx-setup use Java 7 as their language level, which doesn't support lambdas, but if you set source and target compatibility in all places where they are set currently (which could be in other build.gradle files), everything should work if they are all set to VERSION_1_8 as you have it. You may need to change the Project Structure to use a JDK 8 or newer, if somehow it started off using a JDK 7 installation. Project Structure also is where the current language level is stored; it should pick this up from Gradle, but it can be changed temporarily in Project Structure. As always, after changing any Gradle settings you need to sync the project, which the IDE may do automatically for you, or may prompt asking you to sync.

I'm closing this because it isn't a bug. I hope you can get support on the Discord!

**Comment by Frosty-J** [comment]
> The initial projects created by gdx-setup use Java 7 as their language level, which doesn't support lambdas

This is no longer true as of #7311. I can't think of why lambdas would work in Android projects but not libGDX ones - they're both configured for Java 8 (wouldn't surprise me if Google's Groovy/Java template is no longer getting updated) out of the box, in my experience.
