### ISSUE TITLE
LibGDX + KMP (Kotlin Multiplatform﻿)

### ISSUE THREAD

**Issue by omkar-tenkale** [libgdx/libgdx#7385]
#### Issue details
I've built a KMP app which targets android and iOS, I wish to run a simple game powered by libGDX in one of the screens built with Compose multiplatform
Is it possible?

**Comment by tommyettinger** [comment]
It sure looks like the answer will be "no", since a) libGDX isn't written in Kotlin, b) [all of the libs that are listed as compatible with KMP](https://libs.kmp.icerock.dev) are written in Kotlin, and c) libGDX has been doing its own (different) multiplatform way for longer than Kotlin has existed. If this is possible, it would be a ghastly mess, since I don't think anyone's even considered KMP with libGDX before, RoboVM does its own native AOT compilation, Android is using the JVM that is part of that mobile OS, and so on... You should probably look into what pure-Kotlin gamedev libraries are out there, since I don't think KMP can do anything with Java. Pure-Kotlin gamedev libraries are not our area of expertise around here, nor should they be; you should look around and maybe ask in some Kotlin-centric venues. Good luck! I'm closing this.
