### ISSUE TITLE
Intersector.intersectPolygons bug

### ISSUE THREAD

**Issue by streamsoftdev** [libgdx/libgdx#7407]
The following code from line 200 in `Intersector.java` (version 1.12.1) appears to contain a bug. The condition on `floatArray2.size` is simply that it must be not zero, i.e. greater than zero. However the `overlap.setVertices` method will throw an illegal argument exception in cases when the `floatArray2` size is less than 6, since a polygon must have at least 3 vertices. 
```
if (floatArray2.size != 0) {
	if (overlap != null) {
		if (overlap.getVertices().length == floatArray2.size)
			System.arraycopy(floatArray2.items, 0, overlap.getVertices(), 0, floatArray2.size);
		else
			overlap.setVertices(floatArray2.toArray());
	}
	return true;
}
```
The expected behavior would be to return a line segment or a point, when the overlap is not a polygon. This can be fixed by returning a 1, 2 or 3, to indicate polygon, line segment or point, and providing `overlapPoly`, `overlapLineSegment` and `overlapPoint` in the method signature, to handle the cases.

The workaround is to catch the exception and treat this as no overlap.

**Comment by tommyettinger** [comment]
It looks like it has already been fixed; a fix is in the current revision and has been in place since February (after 1.12.1 was released). https://github.com/libgdx/libgdx/commit/7bed7d3666d3b343aebeb1c3f733eae63380dd10 . I'm not sure if the fix is complete enough for what you're suggesting, but the behavior currently seems to be predictable and valid. If two polygons only share an edge or a point, but no overlapping area, then the method returns false. The overlap Polygon it assigns to wouldn't make sense to store only a segment or point. I'd like to hear what @obigu thinks about the alternative fixes suggested; maybe there is some better solution.

**Comment by obigu** [comment]
Yes, we define overlapping in 2D to be positive only when there's an area shared by two shapes, that should be consistent across geometry related methods in `Rectangle`, `Circle` or `Polygon`. I think the fix is good as it is.

**Comment by tommyettinger** [comment]
I agree, consistent is ideal. I think I'll close this.

**Comment by streamsoftdev** [comment]
Yes, indeed, it's my mistake. My polygon points were in CW order in the XZ plane, which is effectively with the Y flipped when Z is taken as Y. I need translate the polygons first.
