### ISSUE TITLE
Could not find the required files

### ISSUE THREAD

**Issue by aoldude123** [libgdx/libgdx#7409]
I've been trying to set up a libGDX project but i keep getting the same errors. 
I tried googling but found nothing close to this. I tried reinstalling gradle, java (17,21,22), downloading the missing files (they seem to no longer be named as below) but nothing works.
I'm using 1.11.0 libGDX and if you dont already have the files in your maven repository then it probably wont work for you either.
This is the output when I try running the gradle desktop-other-run command on vscode.

>3 actionable tasks: 1 executed, 2 up-to-date
><-------------> 0% WAITING
> IDLE
>
>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Execution failed for task ':desktop:compileJava'.
> Could not resolve all files for configuration ':desktop:compileClasspath'.
   > Could not find lwjgl-glfw-3.3.3-natives-linux.jar (org.lwjgl:lwjgl-glfw:3.3.3).
     Searched in the following locations:
         file:/C:/Users/USER/.m2/repository/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-linux.jar
   > Could not find lwjgl-glfw-3.3.3-natives-linux-arm32.jar (org.lwjgl:lwjgl-glfw:3.3.3).
     Searched in the following locations:
         file:/C:/Users/USER/.m2/repository/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-linux-arm32.jar
   > Could not find lwjgl-glfw-3.3.3-natives-linux-arm64.jar (org.lwjgl:lwjgl-glfw:3.3.3).
     Searched in the following locations:
         file:/C:/Users/USER/.m2/repository/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-linux-arm64.jar
 (etc...)

.
.
.
I also recently got this error:
 
 <-------------> 0% WAITING
> IDLE
C:\Users\USER\Desktop\Coding\Extensions\test\core\src\com\mygdx\game\MyGdxGame.java:3: error: package com.badlogic.gdx does not exist
import com.badlogic.gdx.ApplicationAdapter;
                       ^
(etc...)
13 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileJava'.

**Comment by tommyettinger** [comment]
So, gdx-setup is still (for now) linked in the documentation. But what was its competitor, gdx-liftoff, is now part of the libgdx organization. Hooray, I can officially recommend gdx-liftoff as the better option! I'm very close to releasing a new stable version, but for now there's a preview release of the new UI (and newest Gradle version) here: https://github.com/tommyettinger/gdx-liftoff-ui-redesign/releases/tag/v1.12.1.10-PREVIEW-A . This is for libGDX version 1.12.1; I don't know why you want the older 1.11.0 or if you do at all. If the issue is what I think it is, you will be able to generate a project just fine with Liftoff and may already be generating a project with gdx-setup, but the initial sync may fail on either or both. Steps to fix:

You should **remove the lines in build.gradle** that consist entirely of `mavenLocal()` (in `repositories` blocks). It is not at all rare for one failed download to the local Maven cache in `C:\Users\USER\.m2` to stop the whole Gradle build. Avoiding the local Maven cache is one option (it will put libGDX in the Gradle cache instead, which doesn't have this problem). The other option is to remove the problem files from .m2, such as any files inside .m2/repository/com/badlogicgames/ , and let Gradle try to download them again.

If you use IDEA or Android Studio, after you remove either the mavenLocal() lines or the files from .m2, you should re-import the Gradle project, or whatever the term JetBrains uses today for "try to open the Gradle project again." The button is on the Gradle taskbar (to get the taskbar open, either click Gradle on the right edge of the window, or use View -> Tool Windows -> Gradle), and it looks like two circling arrows. It is usually at the top left of the Gradle tool window. This may start the download of all dependencies, potentially from nothing if you deleted files from .m2 . Once it completes, DesktopLauncher or Lwjgl3Launcher should have no red lines. You can launch the app using the Gradle task `gradlew desktop:run` (which you can launch in the Gradle tool window, potentially requiring some Settings wrangling to get it to show Gradle tasks, or you can launch the task by typing it in to Execute Gradle Task, or you can enter it at the command line). You can also launch using the green triangle next to main() in the code's margin, but I don't recommend this because it needs you to make a Run Configuration that has the right working directory (`assets/`).

I hope this helps!

**Comment by aoldude123** [comment]
YOU ARE AMAZING!!!!! Thank you so much for your help! 
The problem seemed to be a mixture of my firewall settings and the maven repository, so I deleted the .m2 repository folder and it redownloaded everything! Also doing this in vscode was a bad idea and switching to IDEA made it work almost instantly.
.
.
I also tried the liftoff version but I was getting the same error that it couldnt find a package, specifically com.badlogicgames.gdx:gdx:17. The error gave some links to repos where it would download, and I tried to do it manually but all of the links (like https://jitpack.io/com/badlogicgames/gdx/gdx/17/gdx-17.pom) didnt work. But its no matter since the original version works beautifully! 

I appreciate your help so very much! Thank you again!
![ITWORKS](https://github.com/libgdx/libgdx/assets/6424217/406ce1af-1e44-4bcb-a3b3-51837b913b6a)

**Comment by Frosty-J** [comment]
Yeah, the latest version of gdx-liftoff won't work (see https://github.com/libgdx/gdx-liftoff/issues/163) but you can use an older version of it or just stick to gdx-setup as you've done.

**Comment by tommyettinger** [comment]
> Yeah, the latest version of gdx-liftoff won't work (see [libgdx/gdx-liftoff#163](https://github.com/libgdx/gdx-liftoff/issues/163)) but you can use an older version of it or just stick to gdx-setup as you've done.

I'd appreciate if you'd try the latest version of gdx-liftoff, since I can't reproduce the issue with versions getting mixed up.

**Comment by Frosty-J** [comment]
Looks like you've got it fixed now in https://github.com/libgdx/gdx-liftoff/commit/c2f2f99ce77c7bcada8fd4b1c7b855e718044d45

**Comment by tommyettinger** [comment]
Huh??? Who did that? Me???

...Yes, there were some stripe-y copy-paste-y types of errors.
