### ISSUE TITLE
No suitable manifest in .jar package

### ISSUE THREAD

**Issue by Ir3nicuz** [libgdx/libgdx#7417]
#### Issue details
For a first build and deploy test I started gdx-setup.jar on windows. I didn't change the name and class settings from default. I selected the desktop platform only. I selected all official extensions and clicked "generate". After generating I opened the project with Netbeans and build the desktop project.

Within the IDE the project launches and runs fine.
But without the IDE the project .jar does not run. Not on Windows and not on Linux.

Assuming that "...\desktop\build\libs\desktop-1.0.jar" is the correct .jar package to launch I double clicked it on windows and nothing happend. Running this package on linux with "sudo java -jar desktop-1.0.jar" gives the error "no main manifest attribute".

In the attached .zip package is the generated project. In the "desktop/build.gradle" file is the "dist" task present but the manifest file in the "...\desktop\build\libs\desktop-1.0.jar" package seems to have no content.

Do I miss something?

#### Reproduction steps/code
[test.zip](https://github.com/user-attachments/files/16198875/test.zip)

#### Version of libGDX and/or relevant dependencies
libGDX Project Generator 1.12.1
Netbeans 18

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [ ] macOS

**Comment by Frosty-J** [comment]
Your JAR is missing, well, just about everything. All it has is `DesktopLauncher` and `badlogic.jpg`. There should also be your core module's classes, libGDX's classes, and various native libraries. Check how you're generating it - I don't use NetBeans nor do I know anyone who still does, but the `desktop:dist` Gradle task should produce a valid JAR without any extra work.

**Comment by tommyettinger** [comment]
However you ran the `gradlew desktop:dist` task, it didn't run correctly. I just ran these steps in cmd.exe, so no IDE involvement:

```
C:\Users\tommy\Downloads\test\test
λ gradlew desktop:dist

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 6s
5 actionable tasks: 5 executed
C:\Users\tommy\Downloads\test\test
λ java -jar desktop\build\libs\desktop-1.0.jar
```

And from then on a window appeared as normal, showing badlogic.jpg . I did this with your project, though I of course deleted the build directories first for safety reasons. This could be a NetBeans issue, and since no one uses NetBeans anymore you would need to fix any configuration there yourself.

Good luck! Make sure you're launching the `desktop:dist` task you mean to be, and NetBeans isn't doing something mid-way through. This isn't an issue with libGDX or even the setup tool, so I guess I'll close this.

Please consider [other IDES](https://www.jetbrains.com/toolbox-app/) that people are much more likely to be able to help with. Even [Eclipse](https://www.eclipse.org/downloads/) has drastically more users than NetBeans.
