### ISSUE TITLE
 No matching variant of com.android.tools.build:gradle:8.1.2 was found.

### ISSUE THREAD

**Issue by hojat72elect** [libgdx/libgdx#7476]
#### Issue details

After forking the project and building it with Android Studio, whenever I run the `./gradlew fetchNative` command in the root directory, I receive this error. 

#### Reproduction steps/code
1- fork the snapshot version of the app on a windows machine.
2- open the repo with Android Studio or IntelliJ IDEA.
3- Run `./gradlew` command in the root directory. 

#### Version of libGDX and/or relevant dependencies
<i>1.12.2-SNAPSHOT</i>

#### Stacktrace
```java
* What went wrong:
A problem occurred configuring project ':backends:gdx-backend-android'.
> Could not resolve all files for configuration ':backends:gdx-backend-android:classpath'.
   > Could not resolve com.android.tools.build:gradle:8.1.2.
     Required by:
         project :backends:gdx-backend-android
      > No matching variant of com.android.tools.build:gradle:8.1.2 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.4' but:
          - Variant 'apiElements' capability com.android.tools.build:gradle:8.1.2 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'javadocElements' capability com.android.tools.build:gradle:8.1.2 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'runtimeElements' capability com.android.tools.build:gradle:8.1.2 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'sourcesElements' capability com.android.tools.build:gradle:8.1.2 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
> Value is null
```
![Screenshot 2024-10-10 040254](https://github.com/user-attachments/assets/b244e04b-d98d-4352-88bf-febb6ba93823)

**I will be thankful if you help me with this issue or let me know if I have gone wrong somewhere; Thanks ❤️**

**Comment by tommyettinger** [comment]
You're running with Java 8. That won't work with current Android. You really should be running with a JDK 17, maybe 11 is OK. Android just keeps updating to be not just compatible with, but requiring, newer JDK versions.

**Comment by hojat72elect** [comment]
OK, looks like the problem was that when we run `./gradlew fetchNatives`, the gradle wrapper automatically, chooses a java version and in my case, that version was always below 17 and that's why I was facing that error. 

I fixed it by adding this line to gradle.properties : 
`org.gradle.java.home=Path\to\jdk\` and referred it to the path of my own jdk with version 17.

I understand this issue is about gradle and doesn't concern LibGDX; but I suggest that docs be updated to address this. It might save some time from people.

Thanks.

**Comment by tommyettinger** [comment]
I'm just rephrasing what the error actually says:

>               - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8

This means something is compiling in a way that needs everything to be compile-able with JDK 8, but something needs Java 11 features or APIs. When you're running with `./gradlew`, that doesn't see any of the configuration you apply to File -> Settings options in IDEA or Android Studio. Only the Gradle files and any environment variables matter. The JAVA_HOME environment variable may be set to a Java 8 JDK somewhere, and that would make Gradle try to build with Java 8 when building via command line. There can be settings in your user Gradle file, which I think is in ~/.gradle/ inside your user home folder, and these can sometimes tell Gradle to use a specific JDK instead of what it would normally use. I don't know all the various environmental things that can affect how Gradle runs, but! You can just open the Gradle tool window in your IDE and run the task there. It's the elephant icon on the right side. Android Studio defaults to not showing the tasks you can run by default, but you can click the second icon at the top of the Gradle window, "Execute Gradle Task", and just type in the command as normal. `gradlew` is already part of it. You don't actually need to even open the Gradle tool window, if that's your preference; you can hit shift twice, click Actions, find "Execute Gradle Task" and make it run `gradlew fetchNatives` there. If you run Gradle tasks using the IDE, then IDE configuration generally applies to Gradle in that situation. That means running `gradlew fetchNatives`
 in the IDE's menus should use your JetBrains Runtime 17 JDK.

OK, I see you have your own fix, I think I can close this now.
