### ISSUE TITLE
Adding support for embedded collisions on Tilesets

### ISSUE THREAD

**Issue by danielesca** [libgdx/libgdx#7550]
Tiled Tilesets support embedding objects into the tiles themselves (embedded collisions) but as of now, **libgdx does nothing to those embedded collisions**.
I think we should add support for this type of objects; so that they can be easily accessed, like the Objects from object MapLayers are.

This issue aims to **gather feedback** regarding this topic.

As of now, the current behavior does not make the embedded objects accessible, and it only creates one instance of them if its "parent" tile is present. Placing multiple times the same tile with embedded collisions does not result in multiple collisions being placed, just one. Also, those objects don't match their parent's positions (nor any other property) but rather appear at 0,0.

Reproduction steps/code:
This is a [basic project](https://github.com/daniesmar0/embedded-collisions-libgdx) that displays a Tiled map and renders the outlines of any Actors that the map has. Note that there are no Actors displayed, since libgdx is not detecting embedded collisions as objects and thus, the Stage has no Actors. You can toggle the boolean "_processEmbeddedTileCollisions_" inside "_core/src/main/java/com/danielem/eot/FirstScreen.java_" to see an approximation of how I believe libgdx should handle embedded collisions.

#### Version of libGDX and/or relevant dependencies
All up to current version (1.13.0)

Affected platforms:
- [X] Android
- [X] iOS
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] macOS

**Comment by BoBIsHere86** [comment]
I'm just popping in to ping some other Tiled Users who have been active recently.
@Quillraven, @silas-hw, @lyze237, Please feel free to chime in with any thoughts on this issue. (If you have any, no pressure)
As I mentioned in the discord when this was brought up. I've never used Tiled's Tileset Collision Editor. So I can't shape an opinion on this. My only concern going forward is that IF we were to modify how this works by default we should be careful as it could be quite the "Breaking Change" for those who have been using this for years. That being said I've always been a fan of giving the users an "option" to make their lives easier. So I'm all for any change in that direction.
Cheers!

**Comment by Quillraven** [comment]
Can you elaborate some more what exactly embedded collision is?

I personally use the collision editor and parse those objects to create static box2d bodies for collision in my game. That works well. A tile in LibGDX can have MapObjects which represent the collision objects of the collision editor in Tiled.

What exactly is this about? Didn't have time yet to check the link/video. Only read the opening post.

**Comment by Quillraven** [comment]
Hm then I think this is unnecessary and works already as intended?

As mentioned, you already get the collision objects of a tile in LibGDX. The position 0,0 makes sense because a tile has no position itself. It depends on where it is used on the map. So you need to add its real position of the map where it is used.

Anyway, for me this was working as intended and made sense. If we change something then most likely my projects will break.

I can share some code tomorrow and check your code as well.

I have btw two scenarios. One scenario where I use map objects that refer to a tile. The second scenario is simply for static collision body creation of the map itself.

In both scenarios I use Box2d to create bodies/fixtures.

**Comment by Quillraven** [comment]
I read through all posts now again and I will share now my approach so far to this topic. Maybe I am missunderstanding something but at least to me the current approach makes sense in LibGDX.

Let's first talk about the normal tilemap collision. I use Box2D for that so everything I write is related to it. 
We have a map with a tileset.
On the tileset we can make collision objects to a tile. Those objects' positions are relativ to 0,0 since a tile in a tileset has no position. Imo this makes sense because one tile can appear multiple times on a tilemap and therefore a single tile must not have a position. The position is coming from the cell, where the tile is placed.

My approach is very simple by simply iterating over all cells of the tilemap in all relevant layers and create static physic bodies out of it. Code is in Kotlin but should be readable also for Java folks:

```Kotlin
    // forEachCell is a Kotlin extension function for a TiledMap. I post it below this function as a reference
    // basically, every cell that is not null will perform the given lambda by passing the cell, the x and y index of the layer of the cell.
    // x and y are the position of the cell
    private fun loadGroundCollision(tiledMap: TiledMap, world: World) {
        tiledMap.forEachCell { cell, cellX, cellY ->
            if (cell.tile.objects.isEmpty()) {
                // no collision objects -> nothing to do
                return@forEachCell
            }

            val body = cell.tile.toBody(world, cellX.toFloat(), cellY.toFloat(), BodyType.StaticBody)
            staticCollisionBodies += body
        }
    }

    private inline fun TiledMap.forEachCell(action: (cell: Cell, cellX: Int, cellY: Int) -> Unit) {
        layers.filterIsInstance<TiledMapTileLayer>()
            .forEach { layer ->
                for (x in 0 until layer.width) {
                    for (y in 0 until layer.height) {
                        layer.getCell(x, y)?.let { action(it, x, y) }
                    }
                }
            }
    }
```

We now iterate over all cells and can create Box2D bodies out of it. This happens in the `toBody` method from above. The cell's x/y coordinate are the position of the body (Of course that depends on how you map your physic units to your game units but in my case I have e.g. 16x16 tiles and 1 physic unit (=meter) is then 16 pixels. Therefore, I have a 1:1 mapping between cell x/y and game world positions.

```Kotlin
fun TiledMapTile.toBody(
    world: World,
    x: Float,
    y: Float,
    bodyType: BodyType,
    data: Any? = null
): Body {
    if (objects.isEmpty()) {
        gdxError("Trying to create a physic body without fixtures for tile ${this.id}")
    }

    val physicWorld = world.inject<PhysicWorld>()
    return physicWorld.body(bodyType) {
        // !!! here we are using the cell's x/y. No crazy calculations or conversions necessary
        position.set(x, y)
        fixedRotation = true
        userData = data
        fixtureDefinitions.addAll(toFixtureDefs())
    }
}

// toFixtureDefs is now iterating over the objects of a `TiledMapTile`. Those objects are the collision objects in Tiled.
fun TiledMapTile.toFixtureDefs(): GdxArray<FixtureDefinition> {
    val result = GdxArray<FixtureDefinition>()
    objects.forEach { mapObject ->
        result.add(mapObject.toFixtureDef())
    }
    return result
}

fun MapObject.toFixtureDef(): FixtureDefinition {
    return when (this) {
        is RectangleMapObject -> rectangleFixtureDef(this)
        is EllipseMapObject -> ellipseFixtureDef(this)
        is PolygonMapObject -> polygonFixtureDef(this, this.polygon.vertices)
        is PolylineMapObject -> polygonFixtureDef(this, this.polyline.vertices)
        else -> gdxError("Unsupported MapObject $this")
    }
}

// and here as an example the rectangle fixture creation which is a box in Box2D
// UNIT_SCALE is the physic world/game world conversion factor that I mentioned before. In the example 
// described above it is 1 / 16f to make 16pixels one unit in the physic world.
private fun rectangleFixtureDef(mapObject: RectangleMapObject): FixtureDefinition {
    val (rectX, rectY, rectW, rectH) = mapObject.rectangle
    val boxX = rectX * UNIT_SCALE
    val boxY = rectY * UNIT_SCALE

    val boxW = rectW * UNIT_SCALE * 0.5f
    val boxH = rectH * UNIT_SCALE * 0.5f
    return FixtureDefinition().apply {
        shape = PolygonShape().apply {
            setAsBox(boxW, boxH, vec2(boxX + boxW, boxY + boxH), 0f)
        }
        friction = mapObject.friction
        restitution = mapObject.restitution
        density = mapObject.density
        isSensor = mapObject.isSensor
        userData = mapObject.userData
    }
}
```

The approach for objects and dynamic bodies is very similar in my case. Therefore, I don't really see the problem or any missing functionality. To summarize:
- you have access to a cell and its tile and its position
- you have access to a tile's objects (=collision objects)


Finally, I just want to point out that I am speaking only for myself. If this functionality is confusing or if there are missing things for others then please feel free to change whatever you want to change. I will be able to adapt my projects if necessary and just convert everything back to what I described above ;) Not a huge issue.

**Comment by MobiDevelop** [comment]
That's sort of along the lines I was thinking...

Reusing the single tile object instance throughout the map is following a flyweight pattern in an effort to minimize extra memory use where the tile's placement doesn't change its properties.

You could, of course, create a utility to a) swap in new Tile instances with embedded objects having knowledge of their placement, or b) accept the tile along with its placement and return the objects accounting for the placement, or c) take an object along with the placement rect and do "something" with it. Which route depends on what is more important in the particular use-case (memory vs compute).

None of these strategies strictly require changes to libgdx itself, but could be added as a utility if enough found it useful - it sort of feels like an application specific thing.

**Comment by Quillraven** [comment]
I personally am not a big fan of util classes. I would add it to TiledMapLayer.

**Comment by silas-hw** [comment]
Embedded objects are accessible through a tile, and if you're getting that from a layer you already know the cells position right?

This seems like far more of a user dependent thing to me, and if youre already iterating over layers and objects it's a few lines of code on top.

IMHO this is unneeded as a feature of LibGDX

**Comment by AndrewMatzureff** [comment]
The current solution seems incomplete (or perhaps the use that I have for accessing embedded collision boundaries out of the box in the way that is proposed is unreasonable... I am still new to Tiled so folks can let me know if this makes sense). In this thread all I've seen so far is justifications for accessing embedded collision boundaries of tiles which are _physically_ associated with a tile layer _cell_. The use that I would have for accessing the ECB, on the other hand, would be something akin to the following:

1) Select an existing graphic tile or create a new tile within my tileset which will ultimately represent some "prop" placement location or entity "spawn" point or some other dynamic object whose position is not necessarily locked to the tile grid.
2) Insert an ECB into my newly created tile via the tile collision editor.
3) Insert an instance of my newly created tile object into one of my existing object layers.
4) Create a template consisting of my new collision tile object.
5) Easily insert, precisely place and transform my template instances anywhere I want in my object layer.
6) Upon loading the relevant object layer, I identify an ECB-containing `MapObject`, call `MapObject::getTile` to gain access to the tile object which owns the ECB, then I call TiledMapTile::getObjects so that I can create a transformed copy (based off of the geometry properties of the "root" `MapObject` obtained from the object layer) and finally initialize my domain collision boundary objects with the proper transformations applied.

Ultimately my goal is to be able to define the collision boundaries of my _dynamic_ entities conveniently within Tiled while still being able to maintain sub-cell precision and visual clarity (since they are graphic tile objects and not just shape objects) when placing them on the map.

**Comment by AndrewMatzureff** [comment]
> The current solution seems incomplete (or perhaps the use that I have for accessing embedded collision boundaries out of the box in the way that is proposed is unreasonable... I am still new to Tiled so folks can let me know if this makes sense). In this thread all I've seen so far is justifications for accessing embedded collision boundaries of tiles which are _physically_ associated with a tile layer _cell_. The use that I would have for accessing the ECB, on the other hand, would be something akin to the following:
> 
> 1. Select an existing graphic tile or create a new tile within my tileset which will ultimately represent some "prop" placement location or entity "spawn" point or some other dynamic object whose position is not necessarily locked to the tile grid.
> 2. Insert an ECB into my newly created tile via the tile collision editor.
> 3. Insert an instance of my newly created tile object into one of my existing object layers.
> 4. Create a template consisting of my new collision tile object.
> 5. Easily insert, precisely place and transform my template instances anywhere I want in my object layer.
> 6. Upon loading the relevant object layer, I identify an ECB-containing `MapObject`, call `MapObject::getTile` to gain access to the tile object which owns the ECB, then I call TiledMapTile::getObjects so that I can create a transformed copy (based off of the geometry properties of the "root" `MapObject` obtained from the object layer) and finally initialize my domain collision boundary objects with the proper transformations applied.
> 
> Ultimately my goal is to be able to define the collision boundaries of my _dynamic_ entities conveniently within Tiled while still being able to maintain sub-cell precision and visual clarity (since they are graphic tile objects and not just shape objects) when placing them on the map.

I've since realized that the workflow I'm describing is indeed already possible. For some reason unbeknownst to me, Tiled must've been using some stale data in between saves that resulted in the value returned by `MapObject::getTile::getObjects` not having been populated in the file... After closing tiled completely, my template shape changes now seem to be working.
