### ISSUE TITLE
[Input] Swype Dictionary not showing

### ISSUE THREAD

**Issue by LooSik** [libgdx/libgdx#783]
Swype keyboard does not function correctly. Whenever i focus on textfield swype dictionary bar is not showing up, it doesn't type any letters ( note numbers are fine ) in field unless I press space or enter.

However if i switch to any app, for example google search, i open up my swype keyboard there then swap to the libgdx app I can get it show just one time, however input is still not reflected in textfield.

Phone: Samsung Galaxy S2

**Comment by Emperorlou** [comment]
This is an absolutely unacceptable answer and completely invalidates libgdx as a serious game engine option.
@badlogic

**Comment by badlogic** [comment]
You resurrect an 8 year old issue and tag me to inform me of your entitlement. Good job, @Emperorlou! I'm sure people love working with you.

**Comment by tommyettinger** [comment]
> This is an absolutely unacceptable answer and completely invalidates libgdx as a serious game engine option.

Says the guy who's using Mozilla Rhino 1.7.8 and Gradle 3.5.1 in production, but not libGDX 🤣 . No no, we really value your opinion, tell us more about how much you use Swype in 2021! How absolutely vital Swype support is for a game engine, haha.

**Comment by Emperorlou** [comment]
The decision to ignore this issue is why it still exists 8 years later, and
it is delegitimizing libgdx on the mobile platform. A lot of people have
invested a lot of time and effort into this engine and this attitude is
exactly why it can't be taken seriously. Why wouldn't you care enough about
libgdx to give it proper Android input support? Why close this issue when
someone else could have taken it on? I get that you might not have the time
to do it yourself, but by closing the issue you're shutting down a fix for
it. Even worse, you specifically say that it's not going to happen?

In fact people HAVE taken it on and if you do enough Google searching you
can see people have hacked a way through this problem before. The
leadership here is ignoring a glaring issue like this by simply saying "no"
to fixing it. So now every game that uses a keyboard has to be sub par, or
the game dev needs to fix a broken engine - without support from the
leadership of the engine. Of course I should be mad about this. At the very
least keeping the issue up allows the conversation to continue, and not
saying "this is not going to happen" - discouraging people from trying to
submit fixes themselves.

**Comment by Emperorlou** [comment]
My LibGDX project isn't on Github.

And not just Swype that's important, but EVERY modern keyboard feature.

**Comment by badlogic** [comment]
By all means, submit a fix for this issue via a pull request. But you do
not get to dictate how things are run around here. Nor does anyone working
on this owe you a single thing.

As can be seen by you necromancing this issue after 8 years, it was easily
discoverable via a simple search for your specific problem. You could have
decided to ask for re-opening as you'd like to take on the issue since you
have an immediate need for a fix. You could have shown work arounds you
found that could be implemented and discuss the best approach to implement
the fix with maintainers before heading off and sending a PR.

Instead you come here with pompous entitlement, ignoring any and all
reasons why this issue may have been closed
8 fucking years ago, and also being entirely oblivious about how things
work around these parts. Because YOU have a booboo in your super important
project! Because YOUR issue is the most important issue in the world and it
is an afront that someone didn't anticipate YOUR need 8 years ago. How dare
those OSS maintainers!

You must not interact often with people, if you think they way you
introduced yourself here will yield a positive outcome.

People like you are the reason why OSS is ultimately a fools errand. Your
entitlement and disrespect is inversely proportional to your contributions
to this community. And sadly, there are more people like you than people
who actually take their time to get to know and participate in the
community surrounding an OSS project. Ultimately, this kind of shit
examplified here by you is why one loses any interest in doing this kind of
work (for free).

So, good luck getting more favorable responses from poor customer support
folks working on "legitimate engines" that can be "taken seriously" when
you send them an angry email about a "Won't fix" issue from 8 years ago for
a piexe of third party software that has been discontinued 5 fucking years
ago.

**Comment by badlogic** [comment]
Can I file an issue on your repos to not copy our code and strip the
license header? Surely, such behaviour would mean your project simply can
not be taken seriously. Nobody would want that, right?

https://bitbucket.org/universeprojects/voidspacegraphics/src/master/src/main/java/com/universeprojects/packer/texturepacker/TexturePacker.java

Also, closing an issue written by a man in distress, because he "CAN ONLY
EAT ONE FOOD" by saying "Works as intended" is also not very good form.
That's why nobody can take Initium seriously. I'm also sure there's a
lesson burried in there. Something about teaching a man to become a fish or
something.

https://github.com/Emperorlou/Initium-ODP/issues/846

And by the way, JEP is GPL 2. Initium links to it. Surely, if I post an
issue on your Initium-ODP tracker asking for the closed sources of your
project that you link with this GPL code, I'll get those closed sources, as
the GPL requires, right? Anything else would be unacceptable and lead
people to not take your project (and you) seriously.

https://github.com/Emperorlou/Initium-ODP/blob/master/Initium-Odp/src/org/cheffo/jeplite/JEP.java

**Comment by tommyettinger** [comment]
Yeah, I'd actually like to see those sources, as the GPL 2 requires. Or you can remove the GPL code from your project entirely, your call, but you still would need to disclose the older version.

**Comment by NathanSweet** [comment]
🍿 Who gives a shit about being taken serious? MISSION ACCOMPLISHED

**Comment by julienvillegas** [comment]
I was going to watch something on Netflix and changed my mind when I found this thread.
Go Mario!
