### ISSUE TITLE
Controller extension needs to re-register after losing window handle

### ISSUE THREAD

**Issue by badlogic** [libgdx/libgdx#910]
See https://code.google.com/p/libgdx/issues/detail?id=1219

**Comment by SolarLune** [comment]
Hey, there! I seem to be having the same problem now, with LibGDX version 1.7.2 - when I change the display mode or go full-screen, the gamepad stops working. A key held during the change will keep being reported as being held, but pressing it again fixes the issue, and the keyboard itself can still be used after the change. 

Was this fixed in the latest version?

**Comment by xoppa** [comment]
@SolarLune this issue was closed almost two years ago and the last comment was "this is now fixed". So indeed, this was fixed.

Asking questions by commenting on an old and closed issue is usually not going to give you much response. If you found a new issue then please consider opening a new issue (and link to this one if you think it is related). If you have a question then consider posting on the forum or irc instead.

Either way, you can easily try the latest version (and lwjgl3 in this case) if you want to test whether your problem still occurs in the latest version.
https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md

**Comment by SolarLune** [comment]
OK. Thanks for responding. I assumed that if an issue that was confirmed and reported as being fixed got a comment that it's broken again, the issue would be reopened and looked into. 

I've made a new issue and linked it to this one.
