### ISSUE TITLE
InputProcessor not giving the correct mouse coordinates when Gdx.input.setCursorCatched(true)

### ISSUE THREAD

**Issue by badlogic** [libgdx/libgdx#924]
See https://code.google.com/p/libgdx/issues/detail?id=1596

**Comment by FuzzyCat444** [comment]
When calling `setCursorCatched(true)` in `touchDown()`, the next call to `touchDragged()` occasionally supplies logical mouse coordinates that aren't the same as where the cursor touched down (the usual and expected behavior being that they _are_ the same). The logical mouse coordinates sometimes end up far outside the window, causing a spike in mouse delta when the mouse delta should be 0. It happens more when clicking and dragging in the same stroke as opposed to clicking, waiting a moment, and then dragging.
